### ISSUE TITLE
refine edit interface for extensions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1034]
![propose changes to odering here](https://cloud.githubusercontent.com/assets/7359272/11338124/29358658-91ea-11e5-9a75-fd1689860d69.jpg)

**Comment by ValWood** [comment]
I think this could be 'streamlined' a bit 
Suggestion:
---
Extension added so far: (make this singular, because it ends up as a single annotation extension)
has_input cdc2 Delete ...

These extension types are allowed for GO:0016485 (but convert to term name)
happens during (e.g. cell cycle phase or stage) ...
processes
If these occur together,  use more than one type  to create a "compound" annotation extension
(Or, "duplicate" and "edit" to create a new independent extension) 


(Its a lot shorter and would also work, regardless of whether there are existing annotations or not. I don't think we need to be so explicit here as they will most likely have made some extensions, or at least seen the verbose version earlier).

We *might* need to clarify that to edit an existing annotation you need to delete the existing ones so that the options reappear.  I'm not sure that this will be immediately obvious....lets see....

**Comment by kimrutherford** [comment]
Just to be clear, we should have a shorter text only when they edit an existing extension?

Does this need to be in the text when they first make an extension or just for editing?:

    If these occur together, use more than one type to create a "compound" annotation extension

**Comment by ValWood** [comment]
I think just for editing....

**Comment by mah11** [comment]
my take:

Leave the wording as is (except perhaps * below) for adding an extension in the first place. The sentence about making a compound annotation is actually more important at that point than at the editing stage, because it could be the first time the user sees it.

It would make sense to use slightly different wording for "edit extension" than for adding one in the first place -- if they make it as far as having an extension to edit, they certainly don't need to see the "Can you extend ..." bit again, and the compound extension idea should look familiar.

So, text suggestion for the editing interface:

"You have annotated $gene to $term ($ID), with this extension: 

[extension details]

These extension types are allowed for $ID:

[allowable extension types]

To change the extension, you can delete one (or more) of the details you've entered, and/or add new details. You can use more than one of the allowed extension types at once, to create a "compound" extension in which all of the parts occur together."


*I also don't love the "occur together" wording but I haven't figured out what I'd like better. I'll comment again if 'n when I do think of something, in a new ticket if the rest of this is done by then.

**Comment by ValWood** [comment]
sounds better.

I wonder if we really need 
"To change the extension, you can delete one (or more) of the details you've entered, and/or add new details."
it should be really obvious....but put it anyway, lets see....

**Comment by mah11** [comment]
This is one of at least six tickets that would be superfluous if it were all that obvious ;)

**Comment by ValWood** [comment]
which? I'm lost. I think it there is an edit button with a "X" you don't need text saying you can delete this?
but lets go with the wordy version.....(Maybe I'm just being too swayed by my smartphone. It doesn't have any instructions for anything, and its the first thing I have ever been able to use....no text good).

**Comment by ValWood** [comment]
After chat with Kim

Leave editing part the same for now so that the  extension teypes and added extesnions appear in the same order.

Only changes
1. Omit 
Can you extend this annotation by providing additional details based on the experiments in this paper?
From the editing text if extensions are already added.

2. Include
To change the extension, you can delete one (or more) of the details you've entered, and/or add new details. You can use more than one of the allowed extension types at once, to create a "compound" extension in which all of the parts occur together."
in the editing box.

Does that work for now?
We could do some user testing to refine further...

**Comment by ValWood** [comment]
Actually  after further discussion with  KIm scrub
2. Include
To change the extension, you can delete one (or more) of the details you've entered, and/or add new details. 

If this isn't  obvious  how to do this edit we need to think about the interface.....

**Comment by kimrutherford** [comment]
> 1. Omit
> ...

I've done that.  I'll close this and we can open new issues for specific other changes.
