### ISSUE TITLE
refine text box for comments

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1035]
Currently:
Please provide any additional details you have for this annotation that do not fit into the available evidence, extension options, etc. The curators will record this additional information in PomBase.

I think we should ditch
 The curators will record this additional information in PomBase.
because, it isn't really true. The forst part is enough. Obviously if we can, we will.

It could say:
Please provide any additional details you have for this annotation that do not fit into the available evidence, extension options, etc. To expediate checking it is useful to add the figure legend or table number here.

(this would be much more useful to us...)

**Comment by mah11** [comment]
"expediate" isn't a cromulent word. did you mean "expedite"?

And do we need a second sentence at all anyway? We do. not. need anyone to copy & paste a figure legend, so at least ditch that bit. If you insist on a second sentence, it could be "Please include the relevant figure or table number."

**Comment by ValWood** [comment]
OK "Please include the relevant figure or table number." works fine (I meant fig No obvis)

**Comment by kimrutherford** [comment]
So this text?:

    Please provide any additional details you have for this annotation that do not fit into the available
    evidence, extension options, etc. Please include the relevant figure or table number.

**Comment by ValWood** [comment]
Hmm, what do others think...maybe we don't want to force it...
But how about

Optional additional details, figure or table numbers etc. 

personally, I'd prefer more figure and table numbers and less of anything else....
I don't think we need to say "which do not fit the available evidence options etc", kinda obvious...

**Comment by mah11** [comment]
I agree we should restore "optional"; overlooked that earlier.

For the rest, what are we trying to accomplish by offering this text box? The live Canto text emphasizes extensions, because the box was the only place non-admin users could put that information.

If we want people to tell us anything they couldn't fit into the annotation (including evidence and extensions), we will have to say so. The full description could be hidden behind a "more..." link or a mouseover.

If you only want to ask for figure/table numbers, then the text doesn't need to ask for anything else.

So ...

"Additional information (optional): you can supply figure or table numbers, or provide any details you have for this annotation that do not fit into the available evidence, extension options, etc."
[stuff after ":" can be hidden if you want]

OR

"Figure or table number (optional)"

**Comment by ValWood** [comment]
Lets  go with 
"Additional information (optional): you can supply figure or table numbers, or provide any details you have for this annotation that do not fit into the available evidence, extension options, etc."
[stuff after ":" can be hidden if you want]

**Comment by kimrutherford** [comment]
I've updated the text on the code.  I can't update Canto until oliver0 is back online.

**Comment by kimrutherford** [comment]
oliver0 is updated now.  Please re-open this if the text needs more tweaking.
