### ISSUE TITLE
Canto slow since server upgrade

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1054]
Ever since the server upgrade (2016-01-08), Canto has been very slow to finish annotations. It doesn't seem to matter:
- what type of annotation (GO, FYPO, interaction, etc)
- whether I use the step-by-step interface or "quick add" or duplicate
- how many genes or annotations are already in the session (!)

It's always the last step that takes ages. It used to be fast.

Unlike Antonia, I don't have network connection as an obvious variable; this is all from the office. (I also didn't ever have a big difference between office and home.) The timing w.r.t. the server upgrade is suspicious.

**Comment by kimrutherford** [comment]
I've found one problem at least, the upgrade installed a really slow version of the Perl database adapter library.  I've installed the latest version and it has helped a lot.  For me the finish step now takes ~1.5 seconds instead of 6.  The database access was slow for everything so hopefully this fix will improve the speed of the whole interface.

Please give it a go and let me know if it's better for you now.

**Comment by ValWood** [comment]
Would it be useful to put this info in the install docs (troubleshooting)  (that Perl database adapter library may affect speed), or will this be obvious to most people?

**Comment by kimrutherford** [comment]
> Would it be useful to put this info in the install docs

I've changed the installation script to force the good version to be installed, which should be enough.

**Comment by Antonialock** [comment]
canto is working fine for me now (yay!)

**Comment by kimrutherford** [comment]
> canto is working fine for me now (yay!)

Excellent!

**Comment by mah11** [comment]
Much better for me too (finally got a chance to try). Yay!

**Comment by kimrutherford** [comment]
Glad it's working better now.  I'll close this but please open tickets about any other slowness.
