### ISSUE TITLE
expressivity pop-up

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1060]
looks like this:

![expressivity suggestions](https://cloud.githubusercontent.com/assets/7359272/12558894/02b582fe-c38a-11e5-99e9-46d4fbca1ad5.jpg)

**Comment by ValWood** [comment]
1. what is complete expressivity? I thought this only applied to penetrance (i.e all population afffected)?
Do we have examples of "complete' expressivity? presumably only applies to a subset of phenotypes (li

2. Should FYPO extension not be here?

3. On the  AE page do we need somthing to clarfy the meaning of 'expressity'? a lot of people don't appear to know what it refers to

4. slight tangent but should we have isoforms as an admin only option? since you would need the isoform IDs (currently gives an error....)

**Comment by mah11** [comment]
1. Complete expressivity is pretty meaningless. "Complete" appears in that pop-up because it just shows the entire FYPO extension ontology (including, oddly, the root - see (2)). Not sure how to get it hidden ... tomorrow I'll have a think about whether there's a graceful way to add more structure to FYPO_EXT. Otherwise it'd have to be subsets ...

2.  It's the root of the ontology, and indeed it shouldn't appear in the pop-up.

3. Maybe we should use "severity" in the interface (with "expressivity" in parentheses just so it won't scare anyone when it appears when the annotation is finished)? might even be worth changing all Canto and gene page displays ...

4. They are admin-only in the config file. If you see that option, you must be logged in ;) #1011 has been closed for a while, so any error message is presumably bug-report-worthy.

**Comment by ValWood** [comment]
Re 3.  >  I think  we should change to 'severity' globally. Much more understandable.

Re 4. > OK!  will open a separate bug report

**Comment by ValWood** [comment]
Number 4 is solved

**Comment by ValWood** [comment]
Kim, we need you to recommend what we need to do for point 1.

Complete only applies to "expressivity"
One option would be to specify which  specific IDs can be used with which extension, or you may have other suggestions.

**Comment by mah11** [comment]
Fix for now: M to adjust FYPO_EXT ontology to add grouping terms for "penetrance level" and "expressivity level", and assert links as appropriate.

**Comment by mah11** [comment]
also add do_not_annotate subset for root - that will eventually help with #1075

**Comment by mah11** [comment]
also adjust fypo ext config to list allowable FYPO_EXT IDs individually

(that could eventually be superseded when "do not annotate" is fully supported but will work as long as it has to in the meantime)

**Comment by mah11** [comment]
FYPO_EXT and config edits done. We'll test to make sure they have the desired effect before closing this.

**Comment by kimrutherford** [comment]
I think the expressivity options are right now.  Could someone check and then close this issue if it's OK?

**Comment by mah11** [comment]
That does look fine now. Yay!

That said, I've changed the config again to test #1075 and #1080, so I'll do some more testing. I can put the config back if something goes wrong, and report any problems on the other tickets (or new ones).
