### ISSUE TITLE
Allow pipe separated domain ID in extension config

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1071]
Implement the idea from @airvine from https://github.com/pombase/canto/issues/1007#issuecomment-174472906

eg.

    FYPO:0003452|FYPO:0004083    is_a    assayed_using   PR:000000001   ...

**Comment by mah11** [comment]
So, is the idea that we should change from this situation:

    FYPO:0002274    is_a    assayed_using   ProteinID       assayed protein 0,1     user
    FYPO:0002333    is_a    assayed_using   ProteinID       assayed protein 0,1     user

to this:

    FYPO:0002274|FYPO:0002333     is_a    assayed_using   ProteinID       assayed protein 0,1     user

?

And we leave things like this unchanged:

    FYPO:0000653    is_a    assayed_using   SO:0000110      assayed region  0,1     user
    FYPO:0000653    is_a    assayed_using   ProteinID       assayed protein 0,1     user

If so, that should be OK. I don't think it would work to allow piped values in more than one column of any row, because that's what would lead to which-goes-with-which clashes.

**Comment by airvine** [comment]
Your example:

```
FYPO:0000653    is_a    assayed_using   SO:0000110      assayed region  0,1     user
FYPO:0000653    is_a    assayed_using   ProteinID       assayed protein 0,1     user
```

could still be configured on a single line, since the same FYPO ID is used:

`FYPO:0000653    is_a    assayed_using   SO:0000110|ProteinID      assayed region  0,1     user`

... but if the domain IDs were different

```
FYPO:0000653    is_a    assayed_using   SO:0000110      assayed region  0,1     user
FYPO:0000675    is_a    assayed_using   ProteinID       assayed protein 0,1     user
```

Essentially what we are saying above is that we are using the same relation for the two Domain ID terms & their descendants, but the range of values that is applicable to the terms is different. In that case, you would still need to maintain two separate lines, so that we know which value range applies to which set of terms.

However, there should not be a problem dealing with multiple ranges, if they were the same for both  Domain IDs, such that:

```
FYPO:0000653    is_a    assayed_using   SO:0000110|ProteinID      assayed protein  0,1     user
FYPO:0000675    is_a    assayed_using   SO:0000110|ProteinID      assayed protein  0,1     user
```

could become:

`FYPO:0000653|FYPO:0000675    is_a    assayed_using   SO:0000110|ProteinID      assayed protein  0,1     user`

Here we are simply saying that different domain IDs refer to the same set of values, i.e. the same combination of relation / range / display text / cardinality / user are the same for both domain IDs. If any one of these values were different, then the domain IDs would need to be kept separate.

**Comment by mah11** [comment]
Hi Alistair,

I'm afraid I find your comment kind of confusing, but in my first example the two lines can't be combined into one. If the desired display text were the same for both range IDs, one line would work, but they're not (and the reason for that is that SO IDs do not represent proteins).

As long as there are multiple values in only one column, they can be combined on a single configuration line, with the multiple options pipe-separated. As soon as ANY two columns would have multiple entries, that should be separated into two (or more) lines. I guess that's what you mean by your final paragraph, but your "FYPO:0000653|FYPO:0000675 is_a assayed_using SO:0000110|ProteinID assayed protein" is very misleading because it would be an incorrect configuration.

m

**Comment by airvine** [comment]
Oh yes, sorry my mistake with the first example - if you display text needs to be different, then you couldn't have them on the same lines.

With the last example, the assumption would be that you are not choosing one range or another to be applicable to a specific domain ID, but rather that all ranges are applicable to all domain IDs.

My example is probably quite confusing because in reality these ranges would not actually go together, I was just trying to explain the principle.

**Comment by ValWood** [comment]
Is this covered by other changes already? we'll open a new ticket for further changes
