### ISSUE TITLE
expressivity cannot be added to abnormal cell length phenotype?

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1080]
I don't have the option to add an expressivity extension to
FYPO:0000648 	viable small vegetative cell or
FYPO:0001492 	viable elongated vegetative cell 

but it shouldn't be restricted for these terms (you could be reeeeeally long, or just a bit longer)?

**Comment by mah11** [comment]
Drat. I think the problem here is that Canto must only be following is_a links to figure out which extensions to offer for which terms. That's mostly a good thing, because we don't want it following every link type in every ontology, but for FYPO expressivity and penetrance life will be a lot easier if it also considers has_part. Not only would it be a pain to manually assert is_a links, I might end up putting some back that I took out a while ago (and that made things a lot better for reasoning).

Kim: Can the extension .. um, stuff (don't know the jargon) handle following has_part for FYPO? Do I add it to the config file in column 2? Can I put pipe-separated entries in that column?

**Comment by mah11** [comment]
p.s. I know I thought we would only need is_a, but apparently I was wrong. Sigh.

**Comment by kimrutherford** [comment]
> Can the extension .. um, stuff (don't know the jargon) handle following has_part for FYPO?

Yes, but ...

> Do I add it to the config file in column 2? Can I put pipe-separated entries in that column?

It doesn't support pipes so we'll need some code changes.  It looks relatively quick.  When you get a chance, could you add an example (just one would be fine) of this case to the config file and let me know?

**Comment by mah11** [comment]
OK, I've changed the has_expressivity entry to this:

    FYPO:0001985    is_a    has_expressivity|has_part       FYPO_EXT:1000001        expressivity    0,1     user

Shout when it's ready for testing and I'll see what it does.

**Comment by kimrutherford** [comment]
>      FYPO:0001985    is_a    has_expressivity|has_part       FYPO_EXT:1000001

Should that be?:

    FYPO:0001985    is_a|has_part    has_expressivity       FYPO_EXT:1000001

**Comment by mah11** [comment]
oops, yes; fixed now

**Comment by kimrutherford** [comment]
I've made this change.  Could you check that I have it right?  I checked FYPO:0000648 and expressivity is an option now.

**Comment by mah11** [comment]
Mostly working, except that it looks like it hasn't updated to reflect that I fixed the config file to remove "has_expressivity|has_part" (so that's what shows up in the completed extension).

**Comment by kimrutherford** [comment]
> it hasn't updated to reflect that I fixed the config file to remove "has_expressivity|has_part"

That's fixed now.
