### ISSUE TITLE
adding sequence details to an 'unknown' allele

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1091]
I had an allele I was using in a session which had been added in a previous session.

I tried to add the new allele details because the new paper sequenced the mutant. This isn't possible if you try to add a correct description and the select an existing "unknown" name, it just reverts to 'unknown'. I thought that I used to be able to do this. 

I did eventually figure out that I could edit it here:
![can only override unknown here](https://cloud.githubusercontent.com/assets/7359272/13465835/2e108d1e-e08f-11e5-8724-e654624ebfab.jpg)

but I don't think this is intuitive.
We might need a way to make this clearer (or change it slightly, I'm not sure)

**Comment by mah11** [comment]
The description above has some confusing bits, but the question is how to supply the description for an allele where the name already exists, but the description has been "unknown" up 'til now.

The interface is kind of unintuitive, because if you select the existing name in the autocomplete, "unknown" is automatically and irrevocably filled in. We haven't come up with a good way to improve that, so for now we'll just document what to do, and close this ticket.

To add a description: Type the allele name. _Ignore_ the autocomplete offerings and finish typing. Then the usual popup for allele type and description will appear. Use 'em.
