### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1092]
I just had a look in Jose Aytes session and there are a lot of errors. I don't know if it is because the session is paused (I/m looking at it in /ro )
https://curation.pombase.org/pombe/curs/4e4a8605a4b1fccb
![screen shot 2016-03-02 at 23 56 58](https://cloud.githubusercontent.com/assets/12727506/13479970/9b604506-e0d2-11e5-8879-edfd42016971.png)

**Comment by kimrutherford** [comment]
>  I don't know if it is because the session is paused

Thanks for that hint.  I think that might be the problem.  I'll have a look today.

**Comment by kimrutherford** [comment]
This is fixed in the code, but not released yet.  I'm holding back releasing for now because we (well Midori) have updated the documentation for the new extension interface.  If we update the main Canto, the public docs will be updated too, but then won't match.  Hopefully we can release the extension interface very soon so this won't be a problem.
