### ISSUE TITLE
root nodes still show in penetrance and expressivity drop doens

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1097]
e.g.
FYPO expressivity extension

**Comment by kimrutherford** [comment]
> FYPO expressivity extension

That's not a root node, so it gets shown in the list.  The root in that ontology is FYPO_EXT:1000000 - "FYPO extension".

"FYPO expressivity extension" and "FYPO penetrance extension" are in the "qc_do_not_annotate" subset but Canto stopping using "qc_do_not_annotate" when showing extensions when I implemented:
  https://github.com/pombase/canto/issues/1084

To fix issue #1084 I changed things so that only root terms got ignored when showing terms in the extension interface.  Probably we would have the desired behavior if we ignored terms in the qc_do_not_annotate subset for extensions, but continued to allow terms in the gocheck_do_not_annotate and gocheck_do_not_manually_annotate subsets.

That's just a configuration change (thanks to #1084) so I've just updated the test Canto.  It seems OK.  Please give it a test.  If it's not right we can tweak it quite easily.

**Comment by ValWood** [comment]
perfect (can't sleep!)

**Comment by kimrutherford** [comment]
> perfect

Great!  Thanks for checking.

> (can't sleep!)

Oh dear.

**Comment by ValWood** [comment]
Its OK, half an hour of git hub will do the trick....
