### ISSUE TITLE
column17 annotations in Artemis do not display in Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1111]
Like
GO="aspect=F; term=protein binding; column_17=PR:000027705; annotation_extension=happens_during(GO:0000092); GOid=GO:0005515; evidence=IPI; db_xref=PMID:19686686; with=PomBase:SPAPB1A10.09; date=20090820"

**Comment by ValWood** [comment]
Admin only option so no huge hurry

**Comment by kimrutherford** [comment]
Related: #1117

**Comment by kimrutherford** [comment]
I've added the col 17 value as an extra column.  The column is only visible in a table if needed.  The column is temporarily called "Gene product form id" because that's what GO call it.  Please let me know what you'd like to rename it to.

Here's an example session:

https://curation.pombase.org/pombe/curs/a309fa2c0e0a8d62/ro

**Comment by ValWood** [comment]
"Gene product form ID"
