### ISSUE TITLE
possible bug or user error on www

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1129]
I managed to create  what looks like an identical duplicate genotype.

![help](https://cloud.githubusercontent.com/assets/7359272/14993135/5ac9b81e-1161-11e6-89b1-edcdebc61091.jpg)

**Comment by ValWood** [comment]
in curs/9ef4b740616f8870

I left it in the session for now while you have a look. I need to delete  the one with no annotations

**Comment by kimrutherford** [comment]
I've checked and the two annotations are identical.  The only way I know of for that to happen is if you change a genotype and it becomes identical to another.  I thought there was an issue about that but I couldn't find it.  I've made one: #1130

If you have a duplicate that wasn't caused by editing, that must be a separate bug.

**Comment by ValWood** [comment]
yep its possible I started as a deletion and changed to a disruption. I'll delete this  from the session now...
