### ISSUE TITLE
Always show the extension edit button if there are existing extensions

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1136]
Midori found a case where a term does allow any extensions but has an extension because it was allowed in a previous config.  The extension edit button is hidden since there is no current matching config so the incorrect extension can't be deleted.

See: genotype 1 in 9ef4b740616f8870

**Comment by ValWood** [comment]
Thats caused by me duplicating an editing and then forgetting about the extension.....

**Comment by kimrutherford** [comment]
> Thats caused by me duplicating an editing and then forgetting about the extension.....

I'll make a separate issue about that bug.

I've changed the edit dialog so that if there is an extension you can always edit.

You should be able to fix 9ef4b740616f8870 now.

**Comment by mah11** [comment]
Unfortunately, I don't think all is well. I went and tried to fix 9ef4b740616f8870, but any annotation in that session that has an extension shows the "add" button instead of the "edit" button. If I do hit "add" the popup doesn't show the existing extension.

I have a different session where that doesn't happen, but there are two variables - my "ok" session (4b35693cfa0373c0) is curation_in_progress, whereas 9ef4b740616f8870 is in approval. I haven't tried any other sessions in approval, but let me know if it'll help if I do.

**Comment by kimrutherford** [comment]
Sorry about that.  I spotted that problem too, then fixed it, then re-released the test Canto instead of the main one.  It should be OK now.

**Comment by mah11** [comment]
Thanks - it's much better now. The fix is done, and the behavior is exactly right (allows us to delete a dodgy extension but not add a new one).
