### ISSUE TITLE
better text for the genotype management drop down

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1143]
moved from
https://github.com/pombase/canto/issues/1133#issuecomment-219400256

So, now do we still need better text for the drop down?
Annotations for this genotype -> view annotations?
Edit details -> edit genotype details?
Duplicate -> Copy and Edit?

Suggestions?

**Comment by ValWood** [comment]
Midori to approve any suggestions

**Comment by mah11** [comment]
I suggest 'Annotations for this genotype' -> 'view phenotype annotations' (makes it a little clearer what 'annotations' refers to).

Otherwise, I don't have any strong preferences, and I don't actually think changing these is really that high a priority (I liked "duplicate" better than "copy and edit" globally but I know I'm in the minority, and I'll get used to the new text in a while).

**Comment by kimrutherford** [comment]
> 'Annotations for this genotype' -> 'view phenotype annotations'

I've made that change.

I also took the executive decision to change "Duplicate" to "Copy and edit" for consistency with the annotation tables.  It's easy to change back though.

Please close this if you're happy.  The changes are now in the main Canto.

**Comment by ValWood** [comment]
It was 3:1 ;)
Better suggestions welcome. I think copy edit is *much* clearer tho'
