### ISSUE TITLE
don't we normally put "Description- Expression"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1151]

**Comment by ValWood** [comment]
Or something?

I'm worried people won't remember what "not assayed" means


![no_expression](https://cloud.githubusercontent.com/assets/7359272/15761994/44de2764-2913-11e6-8144-f530bdffa867.jpg)

**Comment by kimrutherford** [comment]
Are there some words missing from the title?

**Comment by mah11** [comment]
I'm not sure I completely understand the question, but I don't think it would make sense to put "Expression" in the table header because "description" means the description of the whole genotype.

We could add a help thing (mouseover or icon, pick one, I don't mind which) to provide the bit about "allele descriptions and expression levels".

**Comment by ValWood** [comment]
Sorry, I wasn't paying full attention.
I think it should be the same as the webpages
http://www.pombase.org/spombe/result/SPBC11B10.09#fission_yeast_phenotype-single_allele-cell_phenotype

allele [expression]

otherwise its confusing for people who only see a session in review where it often says [not assayed], and it isn't really obvious what isn't assayed unless you created the annotation.

**Comment by mah11** [comment]
Do you mean you want a sub-table for each multi-allele genotype, with a column for description and expression of each allele? It's not displayed as 'allele [expression]' on pombase web pages anyway, it's table columns.

**Comment by ValWood** [comment]
No.
I wanted the table header to say

Allele[Expression]  which matched what is displayed, rather than 'description'

(I though it used to be like this?)

**Comment by ValWood** [comment]
More similar to this (although whatever we use both should be the same?)

![other](https://cloud.githubusercontent.com/assets/7359272/15855040/20c565b4-2ca5-11e6-93d5-4feedcb47924.jpg)

**Comment by mah11** [comment]
That's not so bad, although it'll have to allow for plurals to accommodate multi-allele phenotypes. At first I thought you wanted just to add the word "expression" to the header, which wouldn't work for more than one alleles.

If there's room, the header could say "Description: allele name(s), description(s) and expression level(s)"; if not, some could be behind a mouseover.

**Comment by ValWood** [comment]
Genotype  name(description)[expression] ?

**Comment by mah11** [comment]
> Genotype name(description)[expression] ?

would work fine for a single allele. What would a multi-allele genotype look like?

**Comment by ValWood** [comment]
I thought it could just be the same, since they are arranged one per line like so:

Genotype name(description)[expression] 
Genotype name(description)[expression] 
Genotype name(description)[expression]

**Comment by ValWood** [comment]
Another option would be to omit [not assayed] form the display if there is no information?

**Comment by mah11** [comment]
> I thought it could just be the same, since they are arranged one per line like so:
> 
> Genotype name(description)[expression]
> Genotype name(description)[expression] 

Not exactly - we put the allele name, not the genotype name, in the description lines (there often isn't a genotype name anyway)

**Comment by ValWood** [comment]
OK Genotype was a separate label ,refering to  entire column, not to the string 
syntax 
name(description)[expression]

I guess this isn't clear though.....

Any other suggestions anyone?

**Comment by Antonialock** [comment]
we could make it match
![screen shot 2016-06-09 at 14 44 36](https://cloud.githubusercontent.com/assets/12727506/15931705/bf0ad7ca-2e50-11e6-801c-8d9bac9ccd8e.png)

"unknown product level"

**Comment by ValWood** [comment]
That works!

**Comment by kimrutherford** [comment]
I'm confused about what needs changing here.  Could someone summarise?

**Comment by ValWood** [comment]
Lets talk about this on call....

**Comment by ValWood** [comment]
![still need to deal with this](https://cloud.githubusercontent.com/assets/7359272/16484209/efb4de06-3eaf-11e6-90de-3857fb428306.jpg)

**Comment by ValWood** [comment]
solution,  in this list, unknown product level

**Comment by kimrutherford** [comment]
Make it look like the gene pages.
![screenshot 2016-06-30 22 08 43](https://cloud.githubusercontent.com/assets/90474/16484813/77270a08-3f0f-11e6-9a67-e6eb14ea5823.png)

**Comment by kimrutherford** [comment]
The genotype management table currently looks this on my laptop.  Anyone have any comments?  The gene pages have some horizontal lines instead of alternating white and grey backgrounds for the rows.  Alternating colours don't look so good when the rows are different heights.  Should Canto use lines?

Also I've only changed the genotype management page for now.  The genotypes appear in the annotation tables for phenotype annotations on the front page and gene pages.  Should we format those the same way?

![screenshot 2016-08-22 20 12 17](https://cloud.githubusercontent.com/assets/90474/17847929/d594387c-68a4-11e6-95a5-b4b143862247.png)

**Comment by mah11** [comment]
> Alternating colours don't look so good when the rows are different heights.

That actually doesn't bother me in the slightest - I find the alternation helpful whether row height stays the same or not.

Lines and alternating colours aren't mutually exclusive anyway. Test and live Canto currently have both, which does make it easy to see what's in which row and column. I vote to keep it that way.

In the screenshot, the lack of vertical lines is a slight problem, especially combined with the bigger problem of too little horizontal cell padding - there are a few places where text in one column crashes into text from the next column, and that won't do no matter what else we do with borders or background colours.

> Should we format [annotation tables for phenotype annotations on the front page and gene pages] the same way?

Hmm, good question. I don't think it's essential to use the same format for the annotation tables, because they serve a different purpose from the table of genotypes on the genotype management page. It also might be awkward to cram all the genotype columns into the annotation tables along with all the other info that doesn't have to fit in the genotype details table. But if V&A want to see what it looks like, it shouldn't hurt to try it as long as it's easy to revert if it doesn't work.

**Comment by ValWood** [comment]
I don't think it is essential to use the same format for annotation and genotypes
I'm unsure about the lack of vertical lines here...I think its a bit confounded by the spacing issue

**Comment by kimrutherford** [comment]
Thanks.  I'll try it with the border lines in and release it in the test Canto.

**Comment by kimrutherford** [comment]
> I'll try it with the border lines in and release it in the test Canto.

It's in the main and test Canto now.  Could you have a look and let me know any changes you'd like?

**Comment by mah11** [comment]
I think it would be easier to read and understand if it had horizontal lines only between genotypes (i.e. not between separate genes within one genotype, and not dividing a colour block).

The vertical lines do help.

**Comment by ValWood** [comment]
I was going to submit exactly the same.......no horizontal lines within a colour block...

**Comment by kimrutherford** [comment]
> not between separate genes within one genotype

I've made that change.

**Comment by kimrutherford** [comment]
I'll close this.  Please open a new issue for problems.
