### ISSUE TITLE
allele appearing as sys ID

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1157]
Do you know why fzr2 allele is appearing like this-
![fzr2](https://cloud.githubusercontent.com/assets/7359272/16051409/98d0fb06-3257-11e6-953c-ca009d534dcd.jpg)

curs/2e22c541f5e9e87c

**Comment by kimrutherford** [comment]
That is the name of the allele in the Canto database: SPAC13G6.08delta

That could happen if someone explicitly typed in that as the deletion allele name, which is unlikely.  Or if the gene didn't have a name when the allele was added in Canto.  Otherwise it's a Canto bug.

It won't appear like that on the web pages because there is a Chado post-process after loading that fixes the delta alleles name that use a systematic ID (if there is a gene name).

**Comment by ValWood** [comment]
OK, maybe the name was added later,
