### ISSUE TITLE
new term suggestions

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1169]
If a user can't find a phenotype term, then they often get stuck. 

Currently you need to select an existing term in order to suggest a more specific one. I think some users struggle to locate terms because they don't search on synonyms, or search on something really specific. maybe we should offer the option of suggesting a new child term straight from the search page to avoid potentially frustrating users?

**Comment by ValWood** [comment]
Yes we need to improve this.

1.
Start typing a phenotype in the search box. If you do not find the term you are looking for with your initial search, begin with a broad term (cell phenotype,
* when I do type 'cell phenotype'  this term is not in the list
Action: fix this
Action: Should we have alternative high level term suggestions

 2.
Is it possible to check if a user has typed a few phrases without selecting from the pull down?
that some additional pop-up with more instructions pops up ?  (this might be annoying)

3. Refine text. We tell them to search for a broader term, but they may not know what this means.
We might also suggest, try synonyms  (I can see how Simon would search on mobilization and then  not find anything and not think to search on transposition).

hopefully we can get them to at least one term (even if it is really high level), and from there they should be able to request a term.

**Comment by ValWood** [comment]
Should we have a  HowTo/FAQ for the questions about community curation?
We seem to be answering similar questions  a bit. This will also help us to decide where changes are needed.

Although if people use the FAQ and get an answer  and don't mail the helpdesk we wouldn't know (I was thinking recently that it would be nice of you hit a button  "was this FAQ useful?" so we know which ones people were using most.....)

**Comment by mah11** [comment]
> when I do type 'cell phenotype' this term is not in the list
> Action: fix this

This is working as intended: the autocomplete doesn't offer any terms that are in any do_not_annotate subset, and 'cell phenotype' is in FYPO's  (done for #1075, but also see still-open, not-done #461). So the fix is for curators to pick a different example of a broad term.


> Is it possible to check if a user has typed a few phrases without selecting from the pull down?

I don't understand this suggestion, but it does sound annoying to have something pop up after a delay.


> We tell them to search for a broader term, but they may not know what this means.

could say "try a less specific term, or a word or phrase that could be a synonym" ?


> Should we have a HowTo/FAQ for the questions about community curation?

Yeah, it probably would be good for Canto to have a FAQ (but I'm groaning inside because I know I'll end up writing most of it ;) ).


> if people use the FAQ and get an answer and don't mail the helpdesk we wouldn't know

This is a general issue for all FAQs. I'd be surprised if we get much useful information out of adding a "was this useful" button, because the vast majority will probably ignore it (I almost always do - once or twice I've said no; I can't recall ever bothering for 'yes' and occasionally being asked annoys me slightly ... but that might be because I've found an inverse correlation between FAQs being useful and FAQs asking me if they were useful :P).

**Comment by ValWood** [comment]
OK.
1. Replace cell phenotype suggestion....I guess most high level terms are blocked for use? any suggestions?

2. Change text to  "try a less specific term (for example...), or a word or phrase that could be a synonym"

we can begin to open tickets for FAQ.  Kim, where how should this be maintained?

**Comment by ValWood** [comment]
I have removed discuss from this.

We had a little discussion yesterday  and I think we have another way t make this clearer. I'll do a mock up for this later. 
If there is anything useful in this ticket I'll add it to the new ticket.

**Comment by ValWood** [comment]
Midori is dealing with this one now

**Comment by mah11** [comment]
I have stuck my neck out and amended various bit sof text in https://github.com/pombase/canto/edit/master/canto.yaml

Over to Kim:
For V&A to see the edits in context, could you pls deploy this to test Canto? Thanks :)

**Comment by kimrutherford** [comment]
> For V&A to see the edits in context, could you pls deploy this to test Canto?

Done!

**Comment by mah11** [comment]
If they like it, the only thing left is to roll it out to live. Thanks!

**Comment by ValWood** [comment]
Yep....can go to livr

I wonder if this could be  combined?

Gene products may be annotated with multiple phenotype terms.
Alleles may be annotated with multiple phenotype terms, including both normal and abnormal phenotypes for one allele.

->?
Alleles of gene products may be annotated with multiple phenotype terms. including both normal and abnormal phenotypes.

**Comment by mah11** [comment]
That precise edit would be harder, because of which bits are slotted in for every ontology-based annotation type, and which are type-specific (i.e. all ontology annotation types get the "Gene products may be annotated with multiple $ontology terms." line, whereas the "alleles may be annotated ... " line is part of the FYPO-specific text).

I can easily change the sentence that starts with "Alleles may be annotated ..." itself so it repeats less of the preceding sentence. How about "Any allele may be annotated to normal or abnormal phenotype terms (or both)."? (not sure I love it; edits welcome)

Or, open a new ticket to ask Kim if the first sentence can be suppressed just for FYPO. That might be the best approach if it's easy for him, because it's kind of odd to say gene products can be annotated to phenotype terms anyway, because phenotype annotations attach to genotypes, not products.

**Comment by ValWood** [comment]
Is this one done?

**Comment by kimrutherford** [comment]
> Is this one done?

I think so.
