### ISSUE TITLE
duplicated "assayed transcript"

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1179]
Here I am looking at extension options for
FYPO:0001117  decreased RNA level during vegetative growth 

there are two "assayed transcript" options, the first lets me specify a transcript or gene.
here transcript is chosen from a SO term that I can search for (see screenshot). We probably want some help text to say when to choose the transcript option as opposed to the gene option. Eg (for example generic transcripts such as centromere outer repeat transcript or leucyl tRNA OR specific genes such as cdc2 or SPATRNALEU.01)

the second "assayed transcript" lets me choose a SO term from a dropdown list...it looks a bit weird.

![screen shot 2016-07-06 at 12 36 17](https://cloud.githubusercontent.com/assets/12727506/16616752/32c04b06-4377-11e6-98d9-7b0175be98fd.png)
![screen shot 2016-07-06 at 12 35 47](https://cloud.githubusercontent.com/assets/12727506/16616753/32f058e6-4377-11e6-9ec7-8fc20c5a2b9a.png)
![screen shot 2016-07-06 at 12 34 35](https://cloud.githubusercontent.com/assets/12727506/16616754/33026a0e-4377-11e6-9454-75783c2acad4.png)

**Comment by mah11** [comment]
The second "assayed transcript" prompt is admin-only (so at least the weirdness won't scare any community users). The options are in a dropdown because the number of possibilities is low enough; they're LTR transcript types. They're admin-only because at present the extension config uses the SO term for LTR (i.e. the DNA feature, not the actual RNA transcript). That will change when SO finishes the ticket I opened requesting an actual LTR transcript term (https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/341) -- LTR transcripts will be included with all the others.

I'll add some friendly text to the config file for the transcript option all users see.

**Comment by ValWood** [comment]
is this one still current?

**Comment by mah11** [comment]
Well, Canto behavior isn't going to change until (unless?) SO finishes that ticket linked above. Whenever we do get the requested term I can update the config file so that only one "assayed transcript" option appears even for admins for the relevant terms.

**Comment by mah11** [comment]
this should improve soon - I just updated the config
