### ISSUE TITLE
2 numbers for approved sessions in Admin

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1183]
What's the difference between 
Publications with approved sessions (top)
and
Approved sessions (bottom)

The have different numbers 2638 vs 2652

![diff](https://cloud.githubusercontent.com/assets/7359272/16706973/00d320da-45b8-11e6-8d76-e9c70b5c48c9.jpg)

**Comment by kimrutherford** [comment]
The first number is the count of publications that have at least one session.  The second number is the count of approved sessions.

The difference means that some papers have had more than one approved session.

**Comment by ValWood** [comment]
>The difference means that some papers have had more than one approved session.

I don't understand that, because we would just 'reopen' the existing session.

Can you give an example?

**Comment by kimrutherford** [comment]
Sorry, I thought that was the problem but I guessed wrong.  There aren't any publications with more than one session.

Now that I've looked properly, we're getting different numbers because the first number is the publications with approved sessions where the publication has the triage type "Curatable".  The "Approved sessions" count includes all triage types.

Perhaps that first list shouldn't exclude the non-Curatable pubs?

Here are the 14 publications that are in the second list and not the first:
https://curation.pombase.org/pombe/view/object/pub/PMID:22322963?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:21672643?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:18029449?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:10593605?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:1502179?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:1620594?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:2044950?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:2226803?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:23497645?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:23907116?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:25402480?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:25452419?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:25747261?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:26545777?model=track

**Comment by ValWood** [comment]
I agree these don't need to be in the curated total
but maybe just add another link 
"Approved non-curatable publications"

Sometimes it isn't immediately clear if a paper has curatable data, and I send it out. If the author tells us it hasn't , a cursory scan saves us reading it in detail.....

**Comment by ValWood** [comment]
This is out of date because the number is equivalent.

Nice....July 19 2016  2638 approved sessions.  Today 3482!
