### ISSUE TITLE
Facilitating checking sessions in approval

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1184]
We want the tability to "tick off" annotations made by the community curator where we agree with their annotations. When they make a lot of annotations it can get a bit confusing otherwise.

One suggestion:
-highlight all of the annotation (turn it red or something) and then the ability to hit an admin only check box when we  check the annotation off.

**Comment by kimrutherford** [comment]
> highlight all of the annotation (turn it red or something) and then the ability to hit an admin only
> check box when we check the annotation off.

Sounds good.  Just to check: you'd like a button like "Highlight all" and a way to toggle highlighting on and off for each annotation?

I guess the current highlighting needs to be stored so you can come back to a session later?

**Comment by ValWood** [comment]
On 10/07/2016 10:15, Kim Rutherford wrote:
>
>     highlight all of the annotation (turn it red or something) and
>     then the ability to hit an admin only
>     check box when we check the annotation off.
>
> Sounds good. Just to check: you'd like a button like "Highlight all" 
> and a way to toggle highlighting on and off for each annotation?
>
> I guess the current highlighting needs to be stored so you can come 
> back to a session later?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/pombase/canto/issues/1184#issuecomment-231579111>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AHBLKKY1HdWJW2_f75PW8SuSfK9emAvgks5qULg-gaJpZM4JIyrz>.
>

yep thats it....


-- 
Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by Antonialock** [comment]
yep and yep

**Comment by kimrutherford** [comment]
OK, thanks.  Should be no problem.

**Comment by kimrutherford** [comment]
I've had a go at this.  I've added a (badly named) button on each annotation that allows you to toggle the status of the annotation.  The buttons only appear when you're approving a session.

The buttons are labelled "Checked" because (in my head) you click it once you've checked the annotation.  If you click the annotation background changes to a nasty green colour and the button label changes to "Clear" (meaning "clear the 'checked' status").

As well as the badly labelled buttons this isn't the functionality you asked for - there's no "Highlight all" button.  I've run out of time to fix things today but I thought I'd put these changes in so you could try/comment on them.

Here's how is looks in the main Canto:

![screenshot 2016-09-01 16 57 50](https://cloud.githubusercontent.com/assets/90474/18156628/b13f466e-706b-11e6-863b-bc811f305d5e.png)

**Comment by ValWood** [comment]
OK we'll try this and let you know if we have any further suggestions, but looks as though this will be fine to me...
Will try it out shortly....

**Comment by ValWood** [comment]
I just used for this  humungous session, it made it much, much, much easier to check!

https://curation.pombase.org/pombe/curs/26a7509190100074/ro/

However, I think it would be  useful if the session 
a) began coloured, so that you checked them and the shading disappeared rather than appeared.

...because now, here all of the checked annotations are green. I don't really want to need to go through again to  get them back to default shading

b) and/or a "toggle all off" button

**Comment by kimrutherford** [comment]
I can do either.  Which would you prefer?

**Comment by mah11** [comment]
I prefet (b) - "check all" and "clear all" could be more generally useful, and I really, REALLY don't want to look at sessions full of lurid green tables (I suspect I'll use this feature less than V&A do anyway).

**Comment by ValWood** [comment]
OK, in that case b)

**Comment by kimrutherford** [comment]
OK, I'll add a toggle on and toggle off.

> lurid green tables

We could pick a different lurid colour if you like.  :-)

**Comment by kimrutherford** [comment]
I've added the buttons.  Let me know if there are problems.
