### ISSUE TITLE
Remove popup confirming deletion

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1187]
Can we please remove the popup "really delete?" It adds an extra really annoying step :-)
![screen shot 2016-07-13 at 08 03 44](https://cloud.githubusercontent.com/assets/12727506/16794558/71f294c4-48d0-11e6-8ac0-d0bb75c72873.png)

**Comment by ValWood** [comment]
Agreed....
Because we use this such a lot  because of "duplicate and edit". 

I *think* my preference would be for the duplicate and edit NOT to copy the extension, because the likelihood that it would be the same is slim.  That might be odd as it would not be duplicating. 

How about, if it copied the entire annotation,  BUT forced you to keep extensions with a tick, rather than remove with a x....this would save quite a bit of clicking  for removal (2 steps for each extension) AND  stop inadvertent cary over of extensions from duplicated annotations?

**Comment by Antonialock** [comment]
> I think my preference would be for the duplicate and edit NOT to copy the extension, because the likelihood that it would be the same is slim. 

I wouldnt say slim, sometimes several genes are screened against the same "whaever is in the extension"

I think your idea about keeping/discarding with a tick might be good though

**Comment by kimrutherford** [comment]
> Can we please remove the popup "really delete?"

Done.

**Comment by mah11** [comment]
Anything about duplication should be on a separate ticket. Since it's come up, though, I will say I have a _very_ strong preference for it to copy everything, without needing a tick (= another damn click). Not having to add an extension over again is a big part of what makes duplicating useful.

**Comment by Antonialock** [comment]
Lets close this since it's removed (thanks) and we can open a new discuss ticket
