### ISSUE TITLE
column 17

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1193]
I'm pretty sure we used to be able to put for example, column17=PR:000028939
in the extensions field

but this is not allowed any longer

**Comment by kimrutherford** [comment]
Sorry, the column_17 stuff got lost when we started using the new extension editor code.  I've added a dodgy extra configuration in the extension interface to capture col 17 stuff.  Will this work OK?  It's admin only.

![screenshot 2016-07-20 17 33 51](https://cloud.githubusercontent.com/assets/90474/16976084/4b4f564c-4ea0-11e6-9169-e19c56b6ed90.png)

**Comment by Antonialock** [comment]
Hmm...I think it needs tweaking.

The drop down thing for genes has disappeared and it would be neat to have the ability to browse
/pombe-embl/mini-ontologies/pombe_mini_PR.obo

**Comment by kimrutherford** [comment]
> The drop down thing for genes has disappeared

Which drop down thing?  I can change it so that you can select a gene from the session OR type in an identifier.  Is that what you mean?

**Comment by Antonialock** [comment]
>  I can change it so that you can select a gene from the session OR type in an identifier

I would prefer it to be the same as this:

![screen shot 2016-07-20 at 10 28 20](https://cloud.githubusercontent.com/assets/12727506/16981888/c3c5cc96-4e64-11e6-8dd7-e607a14081cd.png)

here the transcript input box is searchable on both term name and ID
![screen shot 2016-07-20 at 10 30 31](https://cloud.githubusercontent.com/assets/12727506/16981960/2a63118e-4e65-11e6-8958-e5647eeb39cc.png)


If you instead choose gene, then the "drop down thing" is this:
![screen shot 2016-07-20 at 10 26 11](https://cloud.githubusercontent.com/assets/12727506/16981894/d0b5eca6-4e64-11e6-9d6e-0f7e3e193d15.png)

It would be neat if you could make it searchable here too: 
![screen shot 2016-07-20 at 10 27 27](https://cloud.githubusercontent.com/assets/12727506/16982011/811f84b2-4e65-11e6-8fd9-7f67d112bf24.png)

does that make sense?

**Comment by Antonialock** [comment]
(assayed protein isoform also uses terms from /pombe-embl/mini-ontologies/pombe_mini_PR.obo )

**Comment by mah11** [comment]
We've decided not to have PRO browsing at all, so we can avoid loading any of it (even the pombe_mini_PR.obo isn't loaded at present). To use assayed protein isoform you have to paste in a PR:nnn ID.

I do agree the interface should behave the same way for things destined for col 16 (extensions) and col 17, but neither has browsing for the protein ontology right now.

For col 17, and for protein isoforms in extensions, there's no need for the gene list dropdown because the gene IDs would never go into col 17 or isoform-specific extensions; both use PR:nnn IDs (and maybe someday specific RNA IDs, but let's not go there until/unless we have to).

**Comment by Antonialock** [comment]
It looks like "gene product" refers to a normal has_substrate extension?

**Comment by ValWood** [comment]
DONE!
