### ISSUE TITLE
multiple "localizes" links

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1203]
I selected the term
protein localization to actomyosin contractile ring involved in mitotic cytokinesis 

and wanted to add an extension.
In the list of extensions there are 3 options to add a "localizes" target, all 3 show the same gene dropdown box when clicked?
![screen shot 2016-07-27 at 16 04 36](https://cloud.githubusercontent.com/assets/12727506/17180373/1c829ba2-5414-11e6-84cd-b3a1db4e6a42.png)

**Comment by mah11** [comment]
This happens because the ontology term GO:1904498 has paths to three different terms (GO:0033365, GO:0072741 and GO:1990778) that all have entries in the config file.

I don't remember why the config file doesn't just use the most generic 'cellular protein localization' (GO:0034613). If it's because of the 'GO:0006886 .. transports' line, i.e. to exclude transport, we can now do a single config line using GO:0034613-GO:0006886.

**Comment by mah11** [comment]
I've updated the config, which I think means it'll be OK tomorrow. (If I've inadvertently trashed something else the changes can be rolled back in svn.)
