### ISSUE TITLE
Visible link to stats page

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1204]
Where should we put a link to this?

We could just have it in admin, 
https://curation.pombase.org/pombe/track
but I think publicly visible would  e better than we can SHOW people

So on the Canto homepage:
https://curation.pombase.org/pombe

We could also add a link here
http://www.pombase.org/community/fission-yeast-community-curation-project
(should probably think about updating this text soon)

**Comment by kimrutherford** [comment]
My only concern is that's it's slow to load so it doesn't look very slick.

Part of the slowness is that Chado doesn't have the publication year for each publication, just the PMID.  So to generate the stats the code has to query Canto and Chado and combine the results.  When pombase/pombase-chado#559 is done everything will be in Chado so I can change the code to do just one(-ish) Chado query per table.  The page should load quickly then.

**Comment by ValWood** [comment]
OK no hurry...

**Comment by kimrutherford** [comment]
> My only concern is that's it's slow to load so it doesn't look very slick.

It's fast enough now.  Where on the front page would you like the link and what text would you like for it?

**Comment by ValWood** [comment]
Maybe above
https://curation.pombase.org/pombe/
More about community curation
Text suggestion:
Header "Canto Statistics" 
Body Text <link Canto Statistics>  :   Curation progress,  source, and changes over time.

Or, if we want to just streamline this page a bit we could reduce to a single link "Canto statistics"

We could probably even dump this section now?
"More about community curation
By curating your papers here, you will make your work more visible to the community. Your data will be available in PomBase and shared with other public databases. Read more about the motivation, background, and progress of the Fission Yeast Community Curation project at the PomBase web site."

Or this could be replaced by a single link to this page
http://www.pombase.org/community/fission-yeast-community-curation-project
"Motivation"

So we could have:
"Motivation"    | "Canto Statistics"     | "Documentation"     | "Contact us"

**Comment by ValWood** [comment]
@mah11 @Antonialock  does this sound OK. @mah11  any other suggestions?

**Comment by Antonialock** [comment]
I like the idea of replacing the text block below ""More about community curation" with:

> So we could have:
"Motivation" | "Canto Statistics" | "Documentation" | "Contact us"

**Comment by mah11** [comment]
Thought 1:
The stats link text should be "Curation statistics", not "Canto statistics". It doesn't add anything to repeat "Canto" on a Canto page, and "curation" is more descriptive.

Furthermore, "Canto statistics" could be taken to mean "statistics about Canto itself", e.g. how many times the code has been downloaded.

**Comment by mah11** [comment]
Thought 2:
I think it's worth keeping a _brief_ note about community curation on this page. It certainly shouldn't be any longer than it is now, and could perhaps be a bit shorter. At the very least we can delete the last sentence, "PomBase community curation uses Canto", because this is on a Canto page that's clearly labeled as such.

Possible more extensive redraft:
header: About community curation
body: Canto curation makes your work visible in PomBase and many other databases. Find out more on the <linky>Fission Yeast Community Curation</linky> page at PomBase.

I don't like labeling a link "Motivation" because (a) that seems a bit too much like clubbing them over the head with it, whereas I prefer to be more subtle ;) , and (b) speaking only for myself, I don't think I would follow a "Motivation" link. If you really don't want anything other than a few links, "About" will do the job better -- not only is it not so heavy-handed, it'll match about a zillion other websites out there. People have learned to click "About" when they want to learn more about a thing.

**Comment by ValWood** [comment]
Thought 1:
The stats link text should be "Curation statistics", not "Canto statistics". It doesn't add anything to repeat "Canto" on a Canto page, and "curation" is more descriptive.

That is true, but these stats are only the data curated in Canto.... we need to make a distinction between this data and the *eventual* totals...we can call it something else though....(it could be a line saying that this is currently only data curated in canto, and curation via other routes will be added to a stats page shortly.... )

About is better....I couldn't think of a word!

**Comment by mah11** [comment]
It would make a lot of sense to add the rest of the curation stats to the existing stats page (whenever), and add placeholder text in the meantime. No point making ourselves or anyone else chase down two or more pages to get all the stats.

And "Canto statistics" still says "statistics _about_ Canto to me.

**Comment by ValWood** [comment]
Yep, the main stats page  on the PomBase website will need to include *everything*. Kim may still want to generate a Canto stats page  (as this could be a feature of Canto itself, for other users)

https://github.com/pombase/pombase-chado/issues/562

I'm not sure the best  way to do it....

**Comment by kimrutherford** [comment]
> as this could be a feature of Canto itself, for other users

A lot of the stats tables come from Chado queries so most of the stats page won't help other Canto users.  The queries were easier that with Chado.

> And "Canto statistics" still says "statistics about Canto to me.

Would "Canto curation statistics" be too long?

I've made the changes as I understand them.  Could you have a look at the test Canto and comment?

https://curation.pombase.org/test/

**Comment by ValWood** [comment]
> A lot of the stats tables come from Chado queries so most of the stats page won't help other Canto users. The queries were easier that with Cha

In that case, I think just "Curation statiistics" for the link, and the header is better.
We can gather all stats here, regardless if they are Canto derived or not, and label the individual graphs accordingly.
Sorry for the misunderstanding.

**Comment by ValWood** [comment]
Remove this line now?
 - [ ] Find out more on the Fission Yeast Community Curation page at PomBase.

**Comment by mah11** [comment]
> Would "Canto curation statistics" be too long?
> 
> I've made the changes as I understand them. Could you have a look at the test Canto and comment?

Looks fine to me.

**Comment by mah11** [comment]
> Remove this line now?
>
> Find out more on the Fission Yeast Community Curation page at PomBase.

Either remove the entire "About community curation" section, or keep that line. Without it there's no point at all to the blurb (I don't have a strong preference whether to keep or chuck the lot; it isn't a problem to have the bottom "About" link go to the same place). I did suggest making "Fission Yeast Community Curation" the hyperlinked text, since it goes to that page.
