### ISSUE TITLE
weird allele name changes

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1210]
In this session
https://curation.pombase.org/pombe/curs/cb6a65f348103325/
the mre11 allele is entered as rad32-1
however the allele is called rad31-1 in the table of existing annotations.

similarly in the phaf for  PMID: 9003295
the allele called prp3-3, gets changed and on the gene pages it is called prp1

also see https://github.com/pombase/curation/issues/954

**Comment by kimrutherford** [comment]
Sorry about that.  I think this is happening because of the changes in pombase/pombase-chado#531 (or the change not being correct at least).

We try to name unnamed alleles in Chado when we see a matching named allele later in the load.  I had the code wrong so it was overwriting the existing name with a new name if the types and descriptions matched.

I've fixed it for the next load.

**Comment by Antonialock** [comment]
good catch @ValWood :-)
