### ISSUE TITLE
Align "publications curated" with "annotations made" in the "curator statistics"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1215]
Is there any way to align "publications curated" with "annotations made" in the "curator statistics" table:
https://curation.pombase.org/pombe/stats/annotation ?

From legend:
Each annotation is individually date-stamped upon creation, whereas the curation date for a publication reflects the date on which the entire curation session was approved for inclusion in PomBase (this accounts for discrepancies such as the annotations, but no publications, attributed to 2011).

We discussed in https://github.com/pombase/canto/issues/1180

Val: How possible is it to convert the annotation made date to the publication approved date, so that the data matches up better?

Kim: We could use the date the session was approved and pretend that the annotations were all made on that date. That's a bit dodgy though.

Antonia: Yeah, we go back and fix things in sessions, so the date that a session is
approved might be much later than when the annotations went into chado.

Val: Is the date that a paper was submitted for approval recorded? That would seem to be the most convenient data to group all of the annotations for a paper, even if they were really made over some weeks.....

**Comment by kimrutherford** [comment]
> We could use the date the session was approved and pretend that the annotations were
> all made on that date.

Yep, that's possible.  Let me know if you'd like me to make that change.

**Comment by ValWood** [comment]
Hmm, is that first approval date, or  does that get changed if a paper is taken out of approval and then reapproved?  (do you record either i) date submitted for approval? or ii) data of first approval?

**Comment by kimrutherford** [comment]
>  does that get changed if a paper is taken out of approval and then reapproved

It's the date of the most recent approval.

>  (do you record either i) date submitted for approval?

That is recorded.

 > date of first approval?

So don't currently do that.  If you take a session out of "approved" back to the "in approval" state it is as if it was never approved.  We could change that for future sessions if you'd like so that we record a "first approval" date.

**Comment by ValWood** [comment]
In that case, I think we should use "date submitted for approval".....does that make sense to everyone?

**Comment by Antonialock** [comment]
yeah. Date submitted for approval would be better.

Date approved is a bit meaningless because we go back and fix things (sometimes I take them out of approval, but that's rare, so it feels like that date should be better)

**Comment by kimrutherford** [comment]
I've changed the loading code so that the date of submission for approval is stored in Chado.  I'm doing a new load.  Once that's done I'll change the stats page code to use that date instead.

**Comment by kimrutherford** [comment]
Fixed!

![screenshot 2016-08-22 21 34 37](https://cloud.githubusercontent.com/assets/90474/17850213/4dce0a42-68b0-11e6-874e-35ec72fecff6.png)

**Comment by ValWood** [comment]
Looks good, which 6 papers were curated in 2012 (425 is a LOT of annotations from 6 papers, but the other figures look good)

**Comment by kimrutherford** [comment]
I realised that the publication counts were based on approved date not submitted date.  I've fixed that so the counts have moved around a bit in the main Canto.  There are now 13 community curated papers from 2012.

There are two papers with lots of annotations that make up most of the 425 community annotations from 2012:

https://curation.pombase.org/pombe/curs/83c8a0868d64f0a1/ro/
https://curation.pombase.org/pombe/curs/2614826033a82ee6/ro/

Both have lots of interactions.  Currently we're counting symmetrical interactions twice because after a discussion a while ago we decided to automatically add the reciprocal interactions to Chado.  I'll filter those extra interactions which will bring the counts down.

The interactions and the inferred reciprocal annotations from those two session make up most of the 425 annotations from 2012.

These are the 13 sessions from 2012:

https://curation.pombase.org/pombe/view/object/pub/PMID:19139265?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:1896017?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:22064477?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:17998401?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:21801748?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:19158663?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:18799612?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:7254352?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:21900489?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:22624651?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:2674650?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:18675827?model=track
https://curation.pombase.org/pombe/view/object/pub/PMID:17353264?model=track

**Comment by ValWood** [comment]
OK, all looking good

**Comment by kimrutherford** [comment]
I've found two more problems with the stats.

First, many annotations have been counted as community when they are actually done by admin.  Lot's of annotations had the email "val@sanger.ac.uk" which wasn't being counted as an admin account because vw253@cam.ac.uk is the admin user.  I've fixed the sessions so everything is consistent in Canto now but Chado will need need to be re-loaded to get the fixes.

Second, I was talking rubbish above - it's not counting interactions at all.  The interactions are stored in a different Chado table and I forgot to include them in the query.  I'm fixing that now.

**Comment by kimrutherford** [comment]
> Chado will need need to be re-loaded to get the fixes

I made a quick fix in Chado while we wait for the next load.

> it's not counting interactions at all

Interactions are included now.

So the "Curator summary" stats in the main Canto should be right now (as far as I know).

**Comment by ValWood** [comment]
can we get rid of val@sanger.ac.uk completely?

**Comment by kimrutherford** [comment]
> can we get rid of val@sanger.ac.uk completely?

Should be gone now - they were old sessions.

**Comment by kimrutherford** [comment]
The annotations counts have gone down slightly now I've fixed #1219.

**Comment by ValWood** [comment]
still healthy...
