### ISSUE TITLE
Users  still making "compound" genotypes for single allel mutants

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1220]
I'm not sure if this user did this before or after the recent changes. I still think it is easy not to 
"complete" a genotype. I think some improvement might still be made just by changing the  page layout slightly. I had an idea about this a while ago, so I'll think about it some more to see if it would work...

![another_eg_17005570](https://cloud.githubusercontent.com/assets/7359272/17859585/12e9eee2-6882-11e6-85d8-9f11fee0462e.jpg)
e

**Comment by ValWood** [comment]
This isn't high priority and we don't need to discuss, but we should try to think of a way to make this clearer.  It would be good if anyone gets an opportunity to watch what a user does here....

**Comment by mah11** [comment]
One idea (the only one I've had on this subject): move the "Finish" button so it's harder to miss. If there are a lot of genes for the paper, you may have to scroll down to see "Finish". Can it go at the bottom of the table of genotype details? If not, it might have to go upper right instead of lower right.

**Comment by ValWood** [comment]
I thought that too.

**Comment by ValWood** [comment]
duplicate of 
https://github.com/pombase/canto/issues/1339
