### ISSUE TITLE
show GO term name in breadcrumb trail

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1224]
Or did we decide not to for some reason?

![show id-name](https://cloud.githubusercontent.com/assets/7359272/17946846/eaaebfea-6a41-11e6-86e5-435d764457ab.jpg)

**Comment by kimrutherford** [comment]
Some of the term names are long so we decided to put the IDs in instead.  Would showing the term name when you did a mouse-over help at all?

**Comment by ValWood** [comment]
yep...

**Comment by kimrutherford** [comment]
In the test Canto I've changed it so that it shows the term ID and then the first 40 characters of the term name.  If you mouse over you see the full name.  Please let me know what you think.

![screenshot 2016-08-31 18 10 01](https://cloud.githubusercontent.com/assets/90474/18118143/261889e8-6fa7-11e6-9422-a1ee7bdef22d.png)

**Comment by ValWood** [comment]
yep!

**Comment by kimrutherford** [comment]
OK, it will be in the main Canto next time I update.

**Comment by kimrutherford** [comment]
> OK, it will be in the main Canto next time I update.

It in the main Canto now.

To get it to work I needed to upgrade the user interface library that Canto uses.  That caused a few knock on problems especially with dialogs which should be fixed now.  I tested everything I could think of in the interface and it all seems OK.  But let me know if you spot any weirdness.
