### ISSUE TITLE
Long genotypes look a bit crazy

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1252]
One option would be to put only the genotype name, but not the genotype description in the title.
So this would become 
cdc25-22 [not assayed] mik1-[not assayed]cdc25-9A[overexpression]
@mah11  @Antonialock  ?

Also do you need to continue the vertical line down further for the full description in genotype details?
(in fact the description here is duplicated?)

![looks a bit busy](https://cloud.githubusercontent.com/assets/7359272/18529799/83aa1570-7ac6-11e6-8972-55a8c6a19c2d.jpg)

**Comment by kimrutherford** [comment]
> put only the genotype name, but not the genotype description

Do you mean the allele name?  That genotype doesn't have a name.

**Comment by ValWood** [comment]
Where it says 
Genotype: 
 I assumed the 'geneotype name' is the allele names strung together?

**Comment by kimrutherford** [comment]
That string is the all the allele details concatenated together.  The allele details are:
  alelle_name(allele_description)[allele_expression]
so it is more than just the allele names.

We could drop the allele descriptions from that genotype string but some alleles don't have names.  Perhaps we should just say "Genotype details" at the top since the genotype name and the allele details are quite prominent on the page?  I originally put that as the title because on the gene pages we put the gene name at the top.  But it doesn't make as much sense for genotypes.

**Comment by ValWood** [comment]
Actually I think we did decide to do that at one point, its likely it didn't make it into a ticket.
So the title would just be "Genotype"?
Sounds good...

**Comment by kimrutherford** [comment]
> So the title would just be "Genotype"?

OK, I'll do that.  It will solve the immediate problem.

**Comment by kimrutherford** [comment]
> So the title would just be "Genotype"?

I've done that but it looks odd.

**Comment by ValWood** [comment]
@mah11 @Antonialock Heeeellllp
Stuck!

**Comment by mah11** [comment]
I agree that at first glance it looks a little odd to see just "Genotype" at the top of a genotype details page; it makes sense for each genotype detail page to have a title specific to the genotype. I don't have a strong preference, but I can easily live with some genotype pages having crazy-long titles, because some genotypes just do have long descriptions. Nothing's gonna change that. 

I also don't want to risk mucking up the [made-up stat alert] 95% of genotypes that have tolerably not-too-long descriptions for the sake of a few.

**Comment by mah11** [comment]
Re some bits from the original summary:

> Also do you need to continue the vertical line down further for the full description in genotype details?

No, the line extends as far as the Name, Background and Description fields, as expected.

> (in fact the description here is duplicated?)

No, the part that's not indented and doesn't have the vertical line is not another copy of the descirption. It's the list of alleles with links to the Canto gene pages, and it's not redundant because it's where we decided it fits to show which gene the allele is an allele of (note to self: think of more graceful way to word this), which is important if the allele name uses a synonym (e.g. cdc19-P1 is a commonly used allele of mcm2).

That list probably doesn't need to show the expression, though, since that's (a) right above, in the description, and (b) not relevant to which gene the allele is for.

**Comment by ValWood** [comment]
OK,
I have (I think) a better suggestion. Would it look better if the line wrapping  was a bit different.
It seems as though it is trying to centralise the header which doesn't really work here. MAaybe a line break at a specific line length would be better? (I think its generally trying to line break at the hyphen which is always present after the  gene name in an allele description. Kim can you over-ride that? it might look better then?

**Comment by kimrutherford** [comment]
> Kim can you over-ride that?

Yep.  We can change things so that it break words to fit a given width.  I'll try it.

**Comment by kimrutherford** [comment]
It looks a bit better now:

https://curation.pombase.org/pombe/curs/a820cd9476653a92/feature/genotype/view/1/ro

**Comment by ValWood** [comment]
much, can close!
