### ISSUE TITLE
Search allele descriptions  and synonyms in addition to names?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1284]
Re:Jacky:
In PMID15177031 they used the tea2 mutation E336A. When I was curating the paper this did not come up in the  drop downlist of tea2 mutations
so I thought the paper hadn't been done. I  then entered it as tea2(aaE336A)(Not assayed) but I see  I see you did it as  Switch II(aaE366A)[Not assayed].

**Comment by ValWood** [comment]
@mah @Antonialock  any thoughts?

**Comment by Antonialock** [comment]
If you make a new point mutant aaE366A, and switch II is the database name for the aaE366A change, then you might not want to select that allele anyway (switch II sounds like a mutant from a screen so could have other changes....) 

Could switch II would be treated as a (narrow) synonym? So that if switch II (aaE366A) is created, then tea2-E366A is also automatically created, that way you can search for either?

**Comment by Antonialock** [comment]
Just suggesting it because I think  we have talked about allele synonyms in the past & that it might be useful?

**Comment by mah11** [comment]
I would NOT bother with scopes for allele synonyms, but including them is already decided, tho not implemented - adding them to the database noted in https://github.com/pombase/pombase-chado/issues/400 and searching them in Canto in #1744.

Automagically adding a standard-syntax synonym for an allele with a user-supplied name sounds clever but is a separate issue from the topic here, worthy of its own ticket (maybe on the chado tracker instead of canto?).

re original question: fine with me to search allele descriptions as well as names (and eventually synonyms)

**Comment by ValWood** [comment]
1. Oddly "SwitchII" does noot seem to. be a synonym of tea2-E366A? (val to fix)
2. How long would it take to make synonyms/ description searchable?  Then I can decide priority level

**Comment by kimrutherford** [comment]
> How long would it take to make synonyms/ description searchable? Then I can decide priority level

Maybe half a day or a day.  It's a bit fiddly to make sure that allele names are prioritised over synonyms in the autocomplete.

**Comment by ValWood** [comment]
OK low priority for now because any errors from inconsistencies should now be  picked up by the logs.
Lots more important things right now to move things forwards.

**Comment by kimrutherford** [comment]
> Maybe half a day or a day.

I think that's a bit optimistic.  I think a day or 2 is more realistic to cover the weird cases.

**Comment by kimrutherford** [comment]
I've started implementing this since pombase/canto#2688 is close to being done.  I need to chat about it before I do too much more though.

**Comment by kimrutherford** [comment]
> Search allele descriptions and synonyms in addition to names?

The synonyms have been included in the search for many years:

![image](https://github.com/pombase/canto/assets/90474/e80d92cd-2a10-49b3-9375-78d2cd4e3fb1)

I'm working on searching using descriptions.

**Comment by kimrutherford** [comment]
I'll work on this after the allele systematic ID and promoter changes are done.

**Comment by ValWood** [comment]
Duplicate of https://github.com/pombase/canto/issues/2841
