### ISSUE TITLE
bug updating e-mail address

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1286]
when I change the e-mail address to current and submit, I get an error

Internal error
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::SQLite::st execute failed: UNIQUE constraint failed: person.orcid [for Statement "UPDATE person SET orcid = ? WHERE ( person_id = ? )"] at lib/Canto/Controller/Edit.pm line 648

person/444?model=track

**Comment by kimrutherford** [comment]
It looks like it was having trouble because the orcid you were adding was already being used by another user in the database.  Which user was it and what was the orcid?

**Comment by kimrutherford** [comment]
I think I've fixed this.  Can you give it a try?

**Comment by mah11** [comment]
Val wasn't adding an ORCID - she was trying to change an email address. I also tried it and got the same error message.

It's for Yannick Gachet, user 444; trying to change from gachet at cict dot fr to yannick dot gachet at univ-tlse3 dot fr; I don't think we know his ORCID.

I just tried the email change again and it worked, so yay and thanks. Since it's working now, I don't mind if you close this, but right now I'll leave it open in case there's anything to look at because it wasn't an ORCID we were trying to change.

**Comment by ValWood** [comment]
Thats all good. I had a little conversation with Kim off list  where I explained which user and what I was trying to do  so that I did not have to put the users e-mail in the ticket. So the final fix takes account of the fact that I wasn't trying to do ORCID.

Thanks for testing.
