### ISSUE TITLE
approver name

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1295]
My approver name is sometimes valerie wood, and sometimes val?

https://curation.pombase.org/pombe/view/list/publications_with_session_needing_approval?model=track

**Comment by kimrutherford** [comment]
It's not a great system at the moment.  The approver name is copied into the session when approval starts.  That's not good and I've been meaning to fix it.

You're in the database with the name "val" but I'm sure you were "Val Wood" until recently.  Probably you confirmed your name as "val" instead of "Val Wood" with you started curating a new session at some point.  Which is also something I need to fix.

So older sessions have "Val Wood" as the approver because that's what your name was in the main "person" table.  I've changed you back to "Val Wood" and changed all the "val"s to "Val Wood".
