### ISSUE TITLE
need a way to see allele type in review mode

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1304]
At present, review mode lets us view the name, description and expression level of each allele in a genotype, but the allele type doesn't appear anywhere.

In an active session (one that has curation in progress or approval in progress), allele types can be seen in the "edit" interfaces (i.e. "Edit details" and "Copy and edit"), but not anywhere else. That's slightly inconvenient, because one has to pretend to edit a genotype to see the allele type(s) but it's not as bad as review mode where there's nothing.

Should we add a read-only version of the "alleles of this genotype" table to the "view" pages ("View details" for review mode; "View phenotype annotations" for active sessions)? Or would you rather have it somewhere else?

**Comment by mah11** [comment]
Kim suggests adding a column to the table on the genotype management page. Curators think that's worth trying and likely to be fine.

**Comment by ValWood** [comment]
This seems quick?

**Comment by kimrutherford** [comment]
It's quite quick but we're still making changes to the genotype table code for PHI-Canto.  I'd like to wait until that settles down before doing this change.

**Comment by kimrutherford** [comment]
Sorry it's been two years since I looked at this.  A column might be too much in cases with lots of obvious allele types (like deletion and wild type).  Maybe a mouse-over would do the job?  Here are three possibilities:

-------------------------

![genotype-table-allele-type-1](https://user-images.githubusercontent.com/90474/107928282-fe9b2200-6fdc-11eb-8081-8689ea8f8b14.png)

----------------------

![genotype-table-allele-type-2](https://user-images.githubusercontent.com/90474/107928294-00fd7c00-6fdd-11eb-994f-4130af506f8f.png)

---------------------------

![genotype-table-allele-type-3](https://user-images.githubusercontent.com/90474/107928305-04910300-6fdd-11eb-9f1a-049861b05054.png)

**Comment by mah11** [comment]
> Sorry it's been two years since I looked at this

LOL, no worries. We've all been busy.

Anyway, I don't really have a strong preference from among those options. A mouseover would be fine. I'll pretty much be happy as long as I don't have to reactivate a session to see the non-obvious allele types.

**Comment by kimrutherford** [comment]
OK, I've added it as a mouse-over because we're always having trouble with tables being too wide.  Let me know if you're like anything changed in the pop-up.  We can also change the delay before it pops up.

**Comment by mah11** [comment]
That's fine; thanks! I'm going to close this so we can pat ourselves on the back and say we polished one off. ;)
