### ISSUE TITLE
extension text for phosphatase activity term

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1308]
I was going to add an extension to the BP "negative regulation of protein tyrosine phosphatase activity "

and the text that was shown was "regulates modification of" 
but it isn't the modified target (cdc2 in this case) that I want to put in the extension, but the phosphatase that is being regulated (cdc25)

so the text should be "regulates activity of" (or howveer specific we want to go)

**Comment by ValWood** [comment]
we are trying not to use these terms....
https://github.com/geneontology/go-ontology/issues/12859

So far I have deleted any which are   redundant with the MF annotation.
There are not so many remaining:
https://curation.pombase.org/dumps/latest_build/logs/log.2017-02-06-23-18-26.excluded_go_terms_softcheck

I think to be LEGO compliant we will need to allow plain has_input on  MF (rather than has_substrate, directly_inhibits and directly_activatates)


So my first question is "is this annotation absolutely required?"

I can't see why this would be required to capture a relationship between cdc25and cdc2
(las week when I asked if you sere using these terms you said "no, don't worry", so I'm guessing I didn't explain properly? ;)

**Comment by Antonialock** [comment]
this is for hsp9 where we don't know exactly how it is regulating cdc25 phosphatase activity.

I could see a use case for when e.g. a phosphatase has both ser/thr and tyrosine phosphatase activity and the regulator only negatively regulates one 'branch' (for example only negatively regulating the tyrosine phosphatase activity). But maybe that's not important.

**Comment by Antonialock** [comment]
(hsp9 has not been shown to be a direct regulator of cdc25 so I can't put it on the MF term)

**Comment by mah11** [comment]
If there turn out to be any "regulation of phosphatase activity" terms that you would want to keep using, and you want to add "regulates activity of" extensions, add a line to the config file. There isn't anything right now, and I thought it might be an oversight because there is an entry for regulation of protein kinase activity (the GO:0045859 line).

**Comment by Antonialock** [comment]
By the way Val, this is not exactly what yopu told me to not do. You asked me not to annotate
e.g.
cdc2
MF - protein kinase activity
_BP - protein phosphorylation_ (don't add this one)

fpr hsp9 you asked me to link it to cdc25 (since this link wasn't in Pombase) since I couldn't add the link on an MF I had to add it on the BP. I can remove it if you don't want the link there, but I can't think of an alternative way of doing it.

**Comment by Antonialock** [comment]
Hmm...I guess
"negative regulation of phosphatase activity" and e.g.
"protein phosphorylation"

are equally useless terms since they describe very specific evenets rather than the broader biology?
I'll remove it for hsp9...

**Comment by ValWood** [comment]
> I could see a use case for when e.g. a phosphatase has both ser/thr and tyrosine phosphatase activity and the regulator only negatively regulates one 'branch' (for example only negatively regulating the tyrosine phosphatase activity). But maybe that's not important.

yeh I'm guessing that if we know that  much detail we can get it on the MF term

**Comment by Antonialock** [comment]
yeah just ignore me..

**Comment by ValWood** [comment]
So in summary
 1. We are trying  not to use "phosphorylation" and "regulation of phosphatase activity" 
term. I wasn't yet sure yet if they we  unavoidable. I have removed any where there is a  corresponding MF term (redundant). The reminder (not so many) need evaluating.

This makes annotation more consistent, and makes annotation more consistent, and LEGO compliant.

2.  Sometimes we will not know if something is regulating a process by direct interaction, but is upstream. Antonia pointed out that it was incorrect to extend with the regulated gene product in these cases.  Here the new qualifier option might be a better stop gap.

In which case
- [ ]  Find out which qualifier is suitable
- [ ]  Get Canto updated to allow this qualifier (is this a config issue or a code change)

OR
3. This means that hsp9 will not link into the network. Its a pity we can't do something on the MF term with "directly or indirectly regulates"? Is this a possibility?

4. Once a decision made, retrofit any remaining "phosphorylation" "regulation of phosphatase" on process

**Comment by ValWood** [comment]
- [ ] 5. Have I put regulation targets on processes which need to be fixed....

**Comment by ValWood** [comment]
Hmm,  solution 2 won't work. Its just a qualifier, not a relation so there is no way to specify the gene acted upon.
We need to think about some way to  do this on the function if possible ( the annotation should look the same as if it were represented in LEGO.

Also, I notice this is on the canto tracker. I'll summarize the issue on the curation tracker. Not sure when.

Here I need to sort the prompt for the extension or something....I'm not completely sure what the problem is but it looks as though something is configured in a way that does not  apply to all descendant terms.
I'll try to look at that today...

**Comment by mah11** [comment]
> Here I need to sort the prompt for the extension or something....I'm not completely sure what the problem is but it looks as though something is configured in a way that does not apply to all descendant terms.

For this part, what term(s) do you expect to offer which extension option(s)?

**Comment by ValWood** [comment]
So in the BP config file for 
GO:0031399	regulation of protein modification process

the expected extension is "regulates modification of"

Antonia says:
but it isn't the modified target (cdc2 in this case) that I want to put in the extension, but the phosphatase that is being regulated (cdc25)

so the text should be "regulates activity of" (or howveer specific we want to go)


Antonia was using "negative regulation of protein tyrosine phosphatase activity"
to annotate hsp9. and  wanted to say it regulated cdc2.

If I was using this term I could only use it to annotate a   the regulation of a phosphatase, and I would put cdc25 (which is closer to hsp9  in the pathway than cdc2) in the extension.
The extension  in the gene product should always apply to  term. We don't need to capture the effect on cdc2 because that is a given if you regulate cdc25, that you are going to regulate cdc2. However, if you did need to capture this you would use "positive regulation  of protein kinase activity" cdc2

So I think this part isn'y an issue. @Antonialock  can you confirm?

**Comment by mah11** [comment]
It is now less clear than before whether you want the extension options in Canto to change!

**Comment by ValWood** [comment]
I think they are correct as it. Summary. I don't know why we would want to add cdc2 as an extension to this term. Its about regulating a phosphatase....

**Comment by mah11** [comment]
Antonia opened this ticket because she couldn't add *cdc25* in an extension.

**Comment by ValWood** [comment]
Yes Antonia is correct. I need to change the text to "regulates activity of" .  Its the wrong prompt.
phew!
Thanks!

**Comment by mah11** [comment]
No, I think you have to add a new line for GO:0043666 (regulation of phosphoprotein phosphatase activity). The configuration that has "regulates modification of" is for GO:0031399 regulation of protein modification process, and if you keep that one it shouldn't change its text prompt.

**Comment by ValWood** [comment]
oh bother.

GO:0031399  is a parent of GO:0043666 
does this term need some extra configuration in a branch?

**Comment by mah11** [comment]
I'll do it.

**Comment by mah11** [comment]
done
