### ISSUE TITLE
was able to add an exact duplicate

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1311]
I though this was barred?

![exact duplicate](https://cloud.githubusercontent.com/assets/7359272/24468197/66e46002-14af-11e7-9850-b79263203823.jpg)

**Comment by kimrutherford** [comment]
As far as I remember Canto allows duplicate annotations, but not duplicate genotypes.

**Comment by ValWood** [comment]
I'm sure that usually when I try to create an exact duplicate annotation (same everything), I am prevented. Maybe this only happens via copy and edit though. I will check next time. 

We can keep this open  in case we want to take any action later....

**Comment by ValWood** [comment]
Is this related, I spotted this last night:

![assayed_transcript](https://cloud.githubusercontent.com/assets/7359272/24488604/de88ead2-150f-11e7-86ad-8b2a8b548c7d.jpg)

(2 assayed transcript)

**Comment by mah11** [comment]
> Is [2 assayed transcript] related ...?

No. That happens because the is_a ancestor for FYPO:0003423 has two entries in the config file, one of which is admin-only. Non-admin users will only see one (and only admins can use LTR).

If & when SO ever finishes this ticket I'll be able to update to a single config entry: https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/341

Any further comment on the "assayed transcript" question should go on a separate ticket.

**Comment by kimrutherford** [comment]
> I'm sure that usually when I try to create an exact duplicate annotation (same everything),
> I am prevented.

I checked the code and there are no checks for duplicate annotations.

> Is this related, I spotted this last night:

I don't think it's related.

**Comment by ValWood** [comment]
no action yet....
