### ISSUE TITLE
extension configuration question

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1312]
![default](https://cloud.githubusercontent.com/assets/7359272/24468234/85a79478-14af-11e7-81d6-5323296441ed.jpg)

what does this mean (I have never seen the red required before...)

**Comment by ValWood** [comment]
I'm wondering about the duplication... will check config

**Comment by ValWood** [comment]
GO:0015197	is_a	has_substrate	ProteinID	transports		0,1	user
GO:0061608	is_a	has_substrate	ProteinID	transports	0,1	user

do we have another list describing "required extensions" somewhere? I can't remember....

**Comment by kimrutherford** [comment]
> I have never seen the red required before...

This looks like a bug.  I'll fix it.

> do we have another list describing "required extensions" somewhere? I can't remember..

Required qualifiers are the ones without * or a 0 in the cardinality column.  There are only two cases configured at the moment:

FYPO_A_E_config:18:FYPO:0000702  is_a  assayed_using  ProteinID  affected proteins (add TWO, i.e. both binding partners)    2  user                                                                              
GO_MF_A_E_config:27:GO:0030674  is_a  has_direct_input  ProteinID  binds proteins (add TWO, i.e. both of the bridge proteins)    2  user

**Comment by kimrutherford** [comment]
The problem was a missing tab character in the config file so Canto was reading "user" as the cardinality.  It was defaulting to treating that extension as required since the cardinality didn't make sense.  Very buggy.  I've fixed it so that it complains it the cardinality is badly formatted.

I've fixed that transport config in GO_MF_A_E_config.  There was also a missing tab in FYPO_A_E_config for:
  FYPO:0000682-FYPO:0004916      is_a    assayed_using   ProteinID       assayed enzyme  0,1     user

that would have caused a similar problem.  I've fixed that too.

**Comment by ValWood** [comment]
I spotted this last night (2 assayed transcript)
Is this related?

![assayed_transcript](https://cloud.githubusercontent.com/assets/7359272/24488627/0accf886-1510-11e7-9791-8fd468465719.jpg)

**Comment by mah11** [comment]
> Is [2 assayed transcript] related ...?

No, it isn't related to the bug. It happens because the is_a ancestor for FYPO:0003423 has two entries in the config file, one of which is admin-only. Non-admin users will only see one (and only admins can use LTR).

If & when SO ever finishes this ticket I'll be able to update to a single config entry: https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/341

Any further comment on the "assayed transcript" question should go on a separate ticket.

**Comment by ValWood** [comment]
OK I remember now...
