### ISSUE TITLE
Is there a way to tell which Chado load Canto is using?

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1315]
It would be nice to know whether to expect new or updated annotations from Artemis, PHAFs, etc. to appear in Canto sessions (e.g. I'm waiting for PMID:25580577 PHAF annotations right now, before I send my approval curation to the community curator for review; would also let us tell what's going on in situations like https://github.com/pombase/pombase-chado/issues/621 or #1300).

Does an update only happen when we ask? Or is it on some schedule?

**Comment by kimrutherford** [comment]
> Does an update only happen when we ask? Or is it on some schedule?

It's manual at the moment.  I update when you prod me but I also try to update once or twice a week without a prod.  I haven't been as consistent for the last few month since I haven't been working on Canto.

It doesn't happen automatically because the overnight load still occasionally goes wrong.  It's much more reliable than it used to be so this is less of as problem these days.

My plan is that we only update Canto and the nightly version of pombase v2 if the checks reported in the chado checks log file all pass.  We don't have that many checks at the moment and perhaps should add more but even with the current checks if something serious goes wrong (like the Canto annotations fail to load), the checks usually catch it.

Perhaps I should do this soon?  It's never quite got to the top of the priority list.

You can see the current Chado version that Canto uses at the top of the stats page.  Or you can look at the "Chado DB properties" which I've just added to the secret Chado interface:
https://curation.pombase.org/pombe/chado

Sorry the current Chado that Canto is pointing at is so old (2017-04-05).  I'll update now.

**Comment by mah11** [comment]
That will do nicely - now that I know there are places where I can look and see if I need to prod, I can bumble along. It'll be nice to have an automatic-if-checks-pass update working, but it's not urgent. It can wait until after the pombe meeting and the website debut there :)

thanks also for the looming update

**Comment by mah11** [comment]
oh yeah, this does what I asked for, so closing
