### ISSUE TITLE
extension options a little confusing

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1316]
![default](https://cloud.githubusercontent.com/assets/7359272/25186646/b30c3468-2518-11e7-9eba-6550084160bc.jpg)

I'm not sure what they all mean or why they are all needed (or indeed if they are all supposed to be there)

**Comment by ValWood** [comment]
I'm definitely finding the reference to RNA confusing!

**Comment by mah11** [comment]
Anything that mentions "complex" in FYPO extensions is admin-only. I think I can take the "RNA or" part out of that particular "assayed substrate" entry, because RNAs are covered by the user part of the config. Apart from that, these are all correct for the term.

There's an idea for improving the admin options in #1068, but it's never been a high priority because it affects so few people (maybe literally only three; I don't know of any other canto instances that have deployed extensions, let alone the whole configuration shebang).

**Comment by mah11** [comment]
RNA is there for phenotypes that affect an enzyme that acts on ... wait for it ... RNA.

**Comment by mah11** [comment]
To configure it so "RNA" doesn't appear for things like "protein kinase activity" would require an ontology grouping terms for catalytic activities that have RNA vs. protein substrates. I don't know of any in GO, and I'm not enormously keen on trying to do it at the FYPO level without GO terms to refer to.

**Comment by ValWood** [comment]
Ah ok, not to worry if its admin only...i was thinking of the users, I could figure it out!
