### ISSUE TITLE
proposal to rename field in canto genotype management

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1321]
![name](https://cloud.githubusercontent.com/assets/7359272/25840634/6a3a488e-3494-11e7-9823-8d28ef7fcda2.jpg)

Why don't we change this field to say "synonym"
This way it can cover any variation (lab strain name, which nobody ever puts in here).
It will also provide us a way to record any alternative names, and consolidate any differences.

The fission yeast community aren't particularly attached to  gene names  as a rule,   so I'm sure it will be OK for us to adopt one name as "primary" name, and at least all variants will be available and could be searchable eventually.

Any 'pet' names which don't conform to our standard naming system for designated ~allele~ genotypes can also go in here.

**Comment by ValWood** [comment]
related to
pombase/curation#1429

**Comment by ValWood** [comment]
my thinking was  is that eventually for  everything which used a "standard description"
we don't need to display 

cdc2-Y15F(Y15F)
we would only display cdc2-Y15F
(much as we do already for  cdc2Δ, we  don't say  cdc2Δ( cdc2Δ)

**Comment by mah11** [comment]
I vote no.

- I don't like using "synonym" by itself, because it leads straight to the question "synonym of what?" It doesn't make sense to have a synonym without a name.

- If nobody puts lab strain names in that box now, they still won't if its label changes to "synonym". Are we happy treating lab strain names and genotype names as the same thing? If so, we can put that in the documentation and pop-up help text.

- I could see perhaps labeling the field "Genotype name" to remove any ambiguity, although it might then also be nice to edit the grey help text, as otherwise it would be redundant.

- The rest of the ticket description and follow-up comments muddle names and synonyms for *genotypes* with names and synonyms for *alleles*. They are not the same, and it will NOT help to try to stuff allele synonyms in the genotype name field. It would make a nasty mess.

- As for the last comment on allele display, that's a good idea but it has nothing whatsoever to do with the label for the genotype name field.

- We probably do want a way to collect allele synonyms via Canto some day, but it looks like they're not even stored in Chado yet (or so I infer from the fact that https://github.com/pombase/pombase-chado/issues/400 is open). That's also separate from the genotype name field label.

**Comment by ValWood** [comment]
The reason I suggested it is because up to no I have only ever seen "allele or genotype synonyms" added to this field.  I noticed Jacky has used the filed this way. I think often people use the names like  cdc2-1 etc as strain names, and these are also allele synonyms. 

Then there is the "other type" of strain name which is a strain ID like JB***, I have never seen this entered into this field. I'm not sure that we want to collet these.

Maybe we should begin with a list of what has actually been entered in this field and work out which "type" they are...

**Comment by mah11** [comment]
Renaming the genotype name field to "synonym" will not address that problem, or any other problem with names of alleles, genotypes, strains, etc.

The field has to apply to genotypes, not to alleles. If someone wants to name a single-allele genotype after the allele of interest, that's not actually inherently terrible. The only potential problem I can see is if people try to re-use a genotype name, whether it happens to be the same as an allele name or not. It's just more likely to happen with genotype names based on allele names - which is a good reason for us not to encourage it - because someone might try to use the same name for genotypes with the allele of interest in different backgrounds. Again, calling the genotype name field "synonym" will not help.

**Comment by ValWood** [comment]
Is the label the problem?

"Alternative genotype name"  

but I still don't see why a single allele synonym isn't a genotype name?

**Comment by mah11** [comment]
> "Alternative genotype name"

What's "alternative" about it?

I suggested "Genotype name" above.


> but I still don't see why a single allele synonym isn't a genotype name?

A single allele can have zero or one names, and zero, one or more synonyms. Any and all are connected with the allele in the database (and in reality). 

Any genotype may have a name, or it may just have the descriptive string formed of constituent allele name(s). The name, if any, is connected with the genotype, not directly to any alleles, in the database.

A genotype with just one allele of interest may be named after that allele,  but not necessarily. Even if the genotype name string does match the name or any synonym of the allele, that does not make them the same thing in the database. The Canto field we're talking about is for a genotype name, and will not alter anything about an allele entry.

**Comment by ValWood** [comment]
Hi @kimrutherford ,

Could you do a query at some point with a list of what has been stored in the "short genotype name" field.
We can take it from there. 

My suggestion is to change this field to  something that we are using it to capture ...
I know it has been used for various "genotype names" (which are often  the same as allele names). 

It will be helpful to look a  the useage.

After P2017...

Val

**Comment by ValWood** [comment]
probably no action required

**Comment by ValWood** [comment]
I still don't know why we call this field"short name" why does it need to be short?
People are putting the short name in here  (i.e pof8∆(deletion)
and then using  the longer name as the standard name pof8Δ::kanMX6

I swapped this around  but I don't see why  we don't let people put any other name in here, and use it as an allele synonym field  so that  we can collect alternative names to the standard name (whether they are shorter of longer)

How do you get a shorter  name than  pof8∆?

**Comment by ValWood** [comment]
We only need a place to store the official genotype name, and  a place for any allele synonyms?

**Comment by mah11** [comment]
> I still don't know why we call this field "short name" ...

"Short name" appears only in the grey help text, and isn't the actual field designation behind the scenes or even in the interface labels (it's just "Name"). It's the genotype name. It's easy to change the grey help text if you don't like having it say "short", and we could also use "genotype name" as the label instead of as part of the help text. I don't have strong feelings about that.

> ... use it as an allele synonym field

We cannot use the field in your screenshot for allele synonyms, because it's the genotype name field. It is NOT HELPING to conflate alleles and genotypes in this ticket.

> We only need a place to store the official genotype name, and a place for any allele synonyms?

The "Name" field in the screenshot is the place to store the genotype name.

At present, Canto doesn't have a place to put allele synonyms. It ought to have one, but that is a new feature request that should go in a separate ticket (and which would require https://github.com/pombase/pombase-chado/issues/400 to be done).

**Comment by kimrutherford** [comment]
> I still don't know why we call this field"short name" why does it need to be short?

Yep, that's not the best label for it.  Probably "name" would be better.  In my head I think of it as a short name and eg. `cdc25-22(C532Y aa) mcs6-13(L238R aa) pwis1(wis1+) wee1-50(G850E aa) Background leu1-32 h-` as the long or full name.

**Comment by ValWood** [comment]
Kim, at some point could you do a query to list what has been entered in this field. I have used it for synonyms for sure. We can call then "genotype names", but for a single allele the genotype is the same as the "allele name" and any alternative name is a synonym.
I'm really struggling to see what the difference is.

To me the "official  genotype name" is the standard description that we display on the gene pages. 

cdc2-Y15F or  cdc2Δ
cdc2Δcdc13Δ
etc.

anything else cdc2Δ::ura4  etc  is a genotype synonym surely?

**Comment by kimrutherford** [comment]
> single allele the genotype is the same as the "allele name"

Not really.  A genotype is a collection of alleles and their expression levels.  One allele can be part of two separate single allele genotypes.  So these are different genotypes:

  -  cdc1-1(aaF124D)  -  Overexpression

  -  cdc1-1(aaF124D)   - Wild type product level

**Comment by kimrutherford** [comment]
> Kim, at some point could you do a query to list what has been entered in this field.

I've put the list in Dropbox:
 Dropbox/pombase/Chado/queries/all_genotype_names-2018-03-01.txt

**Comment by kimrutherford** [comment]
>  A genotype is a collection of alleles and their expression levels.

... and the background.

**Comment by ValWood** [comment]
But the field we are referring to excludes the expression and the background (so it isn't really the genotype!)

**Comment by ValWood** [comment]
Anyway this field isn't used much so maybe we can begin from scratch ....

**Comment by ValWood** [comment]
It's is largely used for heterozygous diploids (which will be addressed by https://github.com/pombase/canto/issues/976)

after that a lot of it looks suspect,

sensitive to potassium chloride?
 cpy missorting?
wild type?

or redundant
mmi1delta?
 fhl1 delta?

we can have a tidy up and then extablsih a "genotype synonym" field

**Comment by kimrutherford** [comment]
For reference, here's the original discussion about genotypes and genotype names: #413

**Comment by mah11** [comment]
Some responses to some bits, not in chronological order:

> To me the "official genotype name" is the standard description that we display on the gene pages.

That is the description, NOT the name. I thought that if a genotype has a name assigned, that would appear on the gene page, and we would only display the description for unnamed genotypes (or in mouseovers). But what's actually happening is that the description always gets displayed.

> But the field we are referring to excludes the expression and the background (so it isn't really the genotype!)

The field we are referring to is the one provided for a genotype name. It allows any text, and so doesn't necessarily include or exclude expression or background.

> I'm really struggling to see what the difference is.

It doesn't help that the genotype name field has been misused, but most of the problem is that you are still confusing allele names (and synonyms) with genotype names. Maybe this will help (it's part of the diagram I did when we were designing the database schema):

![phenotype_erd_snippet](https://user-images.githubusercontent.com/5196259/36898361-7a4b3f36-1e12-11e8-8199-de6ae5c4a964.png)

Note that both alleles and genotypes can have names, descriptions, and optional synonyms. Also check out the [session for PMID:25891897](https://curation.pombase.org/pombe/curs/9f25f26d17f2ec78/genotype_manage/ro), where Jacky has used the genotype name field correctly.

> we can have a tidy up and then establish a "genotype synonym" field

We do need a way to add _allele_ synonyms. That is separate from genotype names.

I still have not seen much need for a genotype synonym field, but if we did add any, they would still not be allele synonyms. The diagram shows where they would go.

**Comment by mah11** [comment]
and for Kim ...

> I've put the list in Dropbox:
> Dropbox/pombase/Chado/queries/all_genotype_names-2018-03-01.txt

Thanks. Could you do a version that includes the PMID or session ID where these are used? It would help us track them down.

**Comment by kimrutherford** [comment]
I've updated the file with the PMID and session ID.

**Comment by ValWood** [comment]
We should update this file once the diploids have been fixed and see what this field contains.

Perhaps we could just change the label to "Note" if it really is a bunch of stuff.
I can't think that I have even used it for genotype synonym, and these are so rare it seems odd to have a field designated for them.

**Comment by kimrutherford** [comment]
> Perhaps we could just change the label to "Note" if it really is a bunch of stuff.

There's also a "comment" field so "note" is probably redundant.

**Comment by ValWood** [comment]
https://github.com/pombase/canto/issues/2071
