### ISSUE TITLE
Sessions with lots of existing annotation are very slow

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1327]
For example:
  https://curation.pombase.org/pombe/curs/5724d1814ea9f342

**Comment by ValWood** [comment]
This session doesn't have existing annotation?

**Comment by mah11** [comment]
Yes, it has 1 BP and 3 FYPO. It no longer has lots because I took them out!

I did >1200 more phenotype annotations in a PHAF, and when they got in, the Canto session seized up. I moved the PHAF out of the load directory so Sophie could use the session for the rest of the paper. If we aren't going to need to look at the session again, I could restore the PHAF.

**Comment by ValWood** [comment]
Ah I see, I think you can restore the PHAF?

**Comment by mah11** [comment]
done (but ticket stays open because the session will clog now)

**Comment by ValWood** [comment]
In this situation it might be nice to have a
"PMID:XXXX has a large amount of  HTP- data  already attached and will be slow to load"
then with a :
do not display HTP data in session [ ]

**Comment by kimrutherford** [comment]
Duplicate of #2702
