### ISSUE TITLE
error loading genetic interactions into Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1328]
This session 
https://curation.pombase.org/pombe/curs/bf037075feb20f28

is giving me the message
Error for genetic_interaction: couldn't read annotations from the server - please try reloading

and it persists after reloading?

**Comment by kimrutherford** [comment]
The session had a mangled annotation.  It was a interaction with no interactors.  I've removed it and now the session loads fine.

That annotation was from 2014 so hopefully it was caused by an old bug that's not there any more.  I've checked the other sessions for similar dodgy annotations and there aren't any.
