### ISSUE TITLE
canto oddity, taxon restricted term unavailable

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1331]
Flagging as a bug, but more likely a GO issue

/curs/a493fe4ede17fe68
has

isp3 | GO:0042244 | [UNKNOWN TERM]
-- | -- | --

This is "spore wall assembly" which is an extant term?

(Note to self I want to replace this by 

GO:0030476 | ascospore wall assembly

but I could not edit the existing term, best to leave anyway until cause known

**Comment by kimrutherford** [comment]
In the OBO file for GO:0042244 it has:
  subset: gosubset_prok

maybe that's it?

> but I could not edit the existing term

Why couldn't you edit it?  What went wrong?

**Comment by ValWood** [comment]
Its OK, I think I won't be able to select the correct term at present because it is now in a taxon restricted branch.

https://github.com/geneontology/go-ontology/issues/13873
will fix

**Comment by mah11** [comment]
gosubset_prok is a subset (same thing as GO uses to flag slim terms), not a taxon restriction, so that shouldn't be the explanation. It just means a term could be applicable to some prokaryote, so it means essentially the same thing as not having a eukaryotes-only restriction. Our stuff should just ignore the gosubset_prok tag.

GO:0042244 doesn't appear to have any taxon restrictions, which makes sense it's parent for ascospore wall assembly (GO:0030476) and a few other terms, some of which can be used for prokaryotic spores.

We probably ought to add GO:0042244 to our GO soft-check file, because we can always use the more specific GO:0030476, but that's off on a tangent and also shouldn't have anything to do with the Canto oddity.

It does look like a Canto oddity rather than a global PomBase oddity too, because the annotation looks just-fine-thank-you on the completely normal-looking, functional ontology term page for GO:0042244.

I put a similar comment on the GO ticket.

**Comment by kimrutherford** [comment]
I checked the GO pombe-only subset we use for Canto and GO:0042244 isn't there.  I've double checked by running OWLTools manually.  It's in the input OWL file but not the output OBO file.

**Comment by ValWood** [comment]
@cmungall  @kltm any ideas of cause of our new problem?

**Comment by ValWood** [comment]
I created an issue for this so that Chris and Seth will see it,
https://github.com/geneontology/go-site/issues/403

But just to be sure the only thing that should prevent a term being included in our subset at present is a taxon restriction right?

**Comment by mah11** [comment]
I put a comment on the go-site ticket that I hope will come closer to explaining our problem. But I think what they'll really need is for Kim to tell them exactly how the Canto term set gets generated.

**Comment by kimrutherford** [comment]
After the hack suggested by Chris M in https://github.com/geneontology/go-ontology/issues/13873 that term (GO:0042244) is back in Canto.

**Comment by ValWood** [comment]
What needs to happen here?

**Comment by kimrutherford** [comment]
I think we can close this.  We've moved on to: #1340
