### ISSUE TITLE
suppress term appearing twice

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1337]
I never noticed this before:

Viewed from FYPO:0000608

![term appears twice from fypo-0000608](https://user-images.githubusercontent.com/7359272/29836498-5190f718-8ced-11e7-8b65-7bf0392de65d.jpg)

(referring to the top term)

**Comment by ValWood** [comment]
A bug but a very minor one. Any idea why this happens?

**Comment by kimrutherford** [comment]
I had quick look and I think it's because "abnormal cell cycle arrest in mitotic M phase with abnormal spindle" is a "is_a" child of "abnormal cell cycle arrest in mitotic M phase" and also a "has_part" child (or maybe parent?  It's has_part so I'm already feeling confused).

So the solution is to remove those sort of duplicates from the list.  I didn't consider the case where a term is a child via two different relationships when I wrote the code.

Note to self, query in Canto DB to get the children:

```sql
select t.name, s.name from cvterm_relationship r
  join cvterm t on r.type_id = t.cvterm_id
  join cvterm s on s.cvterm_id = r.subject_id
  join cvterm o on r.object_id = o.cvterm_id
 where o.name = 'abnormal cell cycle arrest in mitotic M phase';
```
name|name
has_part|inviable elongated mononucleate aseptate vegetative cell with cell cycle arrest in mitotic M phase
has_part|inviable elongated cell with mitotic G2/M transition delay and cell cycle arrest in M phase
has_part|abnormal cell cycle arrest in mitotic M phase with abnormal spindle
is_a|abnormal cell cycle arrest in mitotic anaphase
is_a|abnormal cell cycle arrest in mitotic metaphase
is_a|abnormal cell cycle arrest in mitotic telophase
is_a|abnormal cell cycle arrest in mitotic prophase
is_a|abnormal cell cycle arrest in mitotic M phase without septation
is_a|abnormal cell cycle arrest in mitotic M phase with abnormal spindle

**Comment by mah11** [comment]
>  I think it's because "abnormal cell cycle arrest in mitotic M phase with abnormal spindle" is a "is_a" child of "abnormal cell cycle arrest in mitotic M phase" and also a "has_part" ...

Hmm, that is a bit daft. I'll try to improve it in the ontology.

But I don't think it's a bad idea to have the code remove duplicates, because it looks like it will help with other duplicates, e.g. those in #1367, and it'll be future-proofing against any multi-type ontology links that do make sense.

**Comment by ValWood** [comment]
Action 
 - [ ]  Do not display duplicate term descendants

is this quick?

**Comment by kimrutherford** [comment]
The relations around the example (FYPO:0000608) have changed and the duplicate has gone by itself.

But I think I've fixed the code to not show duplicates for other cases in future.  I'll deploy the fix once oliver1 is back in action.
