### ISSUE TITLE
extensions showing twice

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1367]
I spotted this today when I was demoing to Alayne:

![transporter 2x](https://user-images.githubusercontent.com/7359272/33046520-2819e960-ce49-11e7-837b-e7273c2b38a0.jpg)

"transports" and "involved in biological process" showing twice

@mah11  do you know how to fix? Is it config?

**Comment by kimrutherford** [comment]
Can you give me an example term to check?

I checked a random annotation.  The term was ubiquitinyl hydrolase activity (GO:0101005).  The extensions were:

    involved in biological process ...
    has function during ...
    involved in biological process ...
    deubiquitinates ...

I'll check that one.  Are there others?

**Comment by ValWood** [comment]
ah my other part did not post.

the above e.g.



 was  a protein transporter, "nuclear import receptor activity" I think

I had this e.g too
![serine kinase](https://user-images.githubusercontent.com/7359272/33047554-51d7ade6-ce4e-11e7-8ad9-3c575b3ecfb9.jpg)

serin kinase. Duplicated "phosphorylates"

**Comment by mah11** [comment]
Yes, this looks like a config thing. The file had entries for GO:0061608 and GO:0015197, but didn't need both because GO:0061608 has an is_a path to GO:0015197. And it just had a straight-up exact duplication of the line for GO:0003674.

I have fixed the config, but the fix for #1337 would probably also eliminate this sort of redundant prompt.

**Comment by kimrutherford** [comment]
Thanks for the fix Midori.
