### ISSUE TITLE
term1-term2 config not working for some entries

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1373]
The Canto extension interface seems to be ignoring the "term1-minus-term2" syntax for some term/extension options.

None of the FYPO1-FYPO2 configs is working properly. For these all of the extension options appear, whether there should be a separate prompt for the FYPO2 branch or not.

    FYPO:0000682-FYPO:0004916	is_a	assayed_using	ProteinID	assayed enzyme		0,1	user
    FYPO:0004916	is_a	assayed_enzyme  ProteinID	assayed enzyme		0,1	user
    FYPO:0004916	is_a	assayed_substrate	TranscriptID|ProteinID	assayed substrate (RNA or protein only	       0,1	user

These have two "assayed enzyme" links for descendants of FYPO:0004916, but should only have one ...

    FYPO:0001985-FYPO:0005448&FYPO:0005449	is_a|has_part	has_expressivity	FYPO_EXT:1000001	expressivity		0,1	user

and descendants of FYPO:0005448 or FYPO:0005449 offer "expressivity" when they shouldn't.

    FYPO:0000702	is_a	assayed_using	ProteinID	affected proteins (add TWO, i.e. both binding partners)		2	user
    FYPO:0001092-FYPO:0000702	is_a	assayed_using	ProteinID	assayed protein		0,1	user

For descendants of FYPO:0000702, it's especially nuts. Not only do both the FYPO:0001092-derived "assayed protein" and the FYPO:0000702-derived "affected proteins (add TWO, i.e. both binding partners)" both appear, it greys out the longer message after one addition even though that's the one with cardinality 2. After that, it lets me add oodles of extensions, completely ignoring the cardinality limits:

![screen-capture-4](https://user-images.githubusercontent.com/5196259/34781000-937df03e-f61c-11e7-86d5-eae985ad57e3.png)

I also checked GO BP (GO MF and GO CC don't have any term1-term2 entries), and for that it's inconsistent. This pair of entries looks like it is working as intended:
    
    GO:0006886	is_a	has_input	ProteinID	transports		0,1	user
    GO:0034613-GO:0006886	is_a	has_input	ProteinID	localizes		0,1	user

i.e. for a descendant of GO:0006886 I'm offered only "transports".

But for this pair

    GO:0006355-GO:0051090	is_a	has_regulation_target	TranscriptID	regulates transcription of		0,1	user
    GO:0051090	is_a	regulates_activity_of	ProteinID	regulates activity of	0,1		user

 I get both "regulates activity of" and "regulates transcription of" for a descendant of GO:0051090.

And for this set, I get the sensible "regulates activity of" suggestion for descendants of GO:0043666 or GO:0045859, but I don't see "regulates modification of" for other descendants of GO:0031399:

    GO:0031399-GO:0043666-GO:0045859	is_a	has_regulation_target	ProteinID	regulates modification of              		0,1	user
    GO:0050790	is_a	regulates_activity_of	ProteinID	regulates activity of		0,1	user

(GO MF and GO CC don't have any term1-term2 entries.)

**Comment by kimrutherford** [comment]
> FYPO:0000682-FYPO:0004916

I think I understand what's going on and I think I broke things a long time ago when implementing: #1258

It looks like the "-FYPO:0004916" in the configuration is being ignored because the code is looking for something like: "FYPO:0000682-is_a(FYPO:0004916)".  That was an accident due to the way I implemented things.

In #1258, when I changed the code to pay attention to the relation column in the config file I only half changed it to handle the relation when excluding subsets (the "-FYPO:0004916" bit).  We need to know which relation to use when excluding subsets which is why "-is_a(...)" is needed instead of just "-term".

I changed my local copies of the extension config files to add "is_a()" where appropriate and I think the extension page now shows the correct extensions.  I've checked those changes because it seems to improve things but we should chat about the syntax and ideas for making it clearer.  The update will visible in Canto in an hour or two.

There is one config line I'm not sure about because the relation column is "is_a|has_part":

   FYPO:0001985-is_a(FYPO:0005448)&is_a(FYPO:0005449)      is_a|has_part   has_expressivity        FYPO_EXT:1000001        expressivity            0,1     user

Does the domain in that case need to be this?:
  "FYPO:0001985-is_a(FYPO:0005448)&is_a(FYPO:0005449)&has_part(FYPO:0005448)&has_part(FYPO:0005449)"

We need to revisit this syntax as it's as clear as mud now.

**Comment by kimrutherford** [comment]
> This pair of entries looks like it is working as intended:
> GO:0034613-GO:0006886 ...

I _think_ that's because GO:0006886 is part_of GO:0034613 rather than is_a?  So even though the "-GO:0006886" was been ignored the configuration wasn't being shown for GO:0006886 and children.

The other GO examples seem OK after the fix.

**Comment by kimrutherford** [comment]
> The other GO examples seem OK after the fix.

Forgot to say, the FYPO look OK too now.

**Comment by ValWood** [comment]
Close?

**Comment by kimrutherford** [comment]
We can open new issues for problems.
