### ISSUE TITLE
some annotation extensions still duplicated

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1375]
I thought Midori fixed this recently in the config file.

For this one, the first one has  "gene" and "SO" options, the second one has only SO options (or maybe it was the other way around, anyways they are different).

![twice](https://user-images.githubusercontent.com/7359272/35109167-805b088c-fc6d-11e7-8604-0a7fbff8ff12.jpg)

**Comment by ValWood** [comment]
Assigning to @mah11  first

**Comment by ValWood** [comment]
maybe its not all terms not, this one was

FYPO:0002944 | decreased RNA level during G0

**Comment by kimrutherford** [comment]
Maybe caused by these two lines?:

FYPO:0000824    is_a    assayed_using   TranscriptID|SO:0000673 assayed transcript      For a general transcript type, sech as 'rRNA', 'tRNA', 'centromere outer repeat transcript' type text\
 in the text box. For a specific gene, select the 'Gene' radio button and then choose a gene from the pulldown menu. or    0,1     user

FYPO:0000824-FYPO:0002934       is_a    assayed_using   SO:0000286      assayed transcript              0,1     admin

**Comment by mah11** [comment]
Known issue; previously reported in #1179 and requires https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/341 for improved behavior.

Other extension option anomalies may require #1373, #1068, or both (depending on the specific term/extension combination).

Additional tangentially relevant points in #1316, https://github.com/pombase/canto/issues/1312#issuecomment-290352906, #1294 and maybe others I didn't ferret out.

**Comment by ValWood** [comment]
OK, I lost track!
