### ISSUE TITLE
Write PHI-Canto specific documentation

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1417]
We'll need documentation for pathogen-host mode.

(Replaces https://github.com/PHI-base/canto/issues/8 )

**Comment by jseager7** [comment]
As discussed in #1664, we need some way to add the documentation files to Canto without checking them in. The current PomBase docs are checked in as a mix of MHTML and Markdown in the `/root/docs/` directory.

**Comment by kimrutherford** [comment]
I'm hoping that the bulk of the PHI documentation can be added to the Canto docs directory.  That definitely makes sense for generic pathogen-host mode docs (rather than PHI-base specific stuff).  It also makes sense for PHIPO documentation to be added to the main repository in /root/docs/

We should mostly be able to put PHI-base specific tweaks in canto_deploy.yaml

**Comment by kimrutherford** [comment]
> We should mostly be able to put PHI-base specific tweaks in canto_deploy.yaml

After discussion, that's probably not true.  We'll make a separate phi-canto-docs directory and use the existing docs directory as a starting point.

Job for Kim: allow configuration of the docs directory location.

**Comment by kimrutherford** [comment]
> Job for Kim: allow configuration of the docs directory location.

I've done a first pass at that now.

 - I've added a new config setting `base_docs_path`
   - for PHI-Canto set it to "phi_base_docs" in `canto_deploy.yaml`:
                  `base_docs_path: phi_base_docs`
 - As a starting point, I've copied the existing documentation to `canto/root/phi_base_docs` where it can be edited as needed
 - I've added a directory for PHI-Canto specific images: `canto/root/static/images/phi_base_docs`
 - Some of the doc files in `phi_base_docs` are currently symbolic links / shortcuts to the corresponding PomBase doc file (eg. the GO annotation doc)
    - the phenotype doc file will need to be replaced with a PHI-Canto specific file

James, we should have a chat once you've had a chance to try this.  I'm sure some tweaks will be needed.

**Comment by jseager7** [comment]
Thanks for this. I think our 'Getting started' page is pretty much finished with no remaining comments, so I can look at converting that to MHTML (all our documentation is currently stored as Google Docs, for ease of collaboration).

**Comment by jseager7** [comment]
I found an add-on for Google Docs called [Docs to Markdown](https://gsuite.google.com/u/0/marketplace/app/docs_to_markdown/700168918607?hl=en&pann=docs_addon_widget) that can download a Google Docs file as Markdown. The add-on doesn't include images, but I was able to download them by exporting the Docs file as an HTML page, and I linked the images up with a script afterwards.

There were a few extra hurdles converting Markdown to MHTML – the main thing was replacing the image `src` attributes to use the dynamic path that Catalyst sets, but I was expecting to have to do this anyway, and it's easily automated.

```perl
<%init>
my $config = $c->config();

my $base_docs_path = $config->{base_docs_path};

my $image_path = '/static/images/' . $base_docs_path;
</%init>
```
The other key difference is the markup structure, due to the fact I converted from Markdown. For example, our images are just `<img>` elements wrapped in a paragraph:

```html
<p>
  <img alt="" src="<% $c->uri_for($image_path . '/session_submit_button.png') %>" title="" />
</p>
```

Whereas PomBase has images as links inside dividers styled with Bootstrap classes:

```html
<div class="row-fluid">
  <div class="span6">
    <a href="<% $c->uri_for($image_path . '/gene_list.png') %>"/>
      <img class="screenshot" src="<% $c->uri_for($image_path . '/gene_list_small.png') %>" alt="gene list box"/>
    </a>
  </div>
</div>
```

The lack of the `screenshot` class attribute also means that our images render without the black border that PomBase has. I think all of this should be fixable with some extra templating, though.

Here's how the documentation page currently looks on my local copy:

![phibase_docs](https://user-images.githubusercontent.com/37659591/80716627-c4b16b80-8aef-11ea-9762-90d1dd23fe37.png)

**Comment by jseager7** [comment]
The documentation for 'Getting Started' and 'Creating alleles and genotypes' is now available on the production and demo servers. The next thing to work on is the 'Curating phenotypes' page.

**Comment by jseager7** [comment]
The Curating phenotypes page is on the production and demo servers now.

@kimrutherford Now that we have documentation for our phenotype annotations, the `detailed_help_path` in `canto_deploy.yaml` needs to be updated to match, but I'm not sure if this should have `/docs/` as the directory prefix, or `/phi_base_docs/`. Could you let me know which of the following is correct?

```
detailed_help_path: /docs/phipo_annotation
```
or
```
detailed_help_path: /phi_base_docs/phipo_annotation
```

**Comment by kimrutherford** [comment]
> detailed_help_path: /docs/phipo_annotation

Should be `/docs/`

**Comment by jseager7** [comment]
As requested by @CuzickA, I've added an index page for the PHI-Canto documentation that contains a table of contents linking to other sections of the documentation. 

Note that there could be some other links in the documentation that could benefit from the fact that we can now link to section headings.

Here's how it looks:

![image](https://user-images.githubusercontent.com/37659591/91444318-7b3e1680-e86c-11ea-8837-4a6465691d44.png)

**Comment by jseager7** [comment]
I think this can be closed now, since the most important documentation is done. Also, we now have a dedicated repository for PHI-Canto documentation at [PHI-base/canto-docs](https://github.com/PHI-base/canto-docs), which is a better place for any follow-up issues.
