### ISSUE TITLE
major bug in main tool... cannot activate session

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1428]
I'm logged in  ;)

and for this session (mine)

http://curation.pombase.org/pombe/curs/4d3b0d5a0015df91/ro
Review only - this session can be viewed but not edited?

**Comment by ValWood** [comment]
I just removed /ro/ and I  can continue...

**Comment by kimrutherford** [comment]
> I just removed /ro/ and I can continue...

Yep, that's the solution.

**Comment by mah11** [comment]
you can always click the "finish reviewing" button too

**Comment by ValWood** [comment]
yes, but the button has also disappeared for me:

![no review](https://user-images.githubusercontent.com/7359272/39323747-64457b18-4985-11e8-8a6b-c06392357876.jpg)

?

**Comment by kimrutherford** [comment]
The "Finished reviewing" button only appears for submitted sessions.  We added review mode so that sessions could be viewed read-only after submission.  Do we want a button to go from review/read-only mode to edit mode if curation is in progress?  In that case the review link could just redirect to the normal mode without requiring a button press.

How did you get the review /ro link for a in-progress session?

**Comment by ValWood** [comment]
good  question, I didn't actively go there...I will try to replicate later (it happened every time I left the session and returned to it using the PMID though

**Comment by ValWood** [comment]
Hmm, I'm going to quietly close this. La la la la la.....
