### ISSUE TITLE
old genotype interface from "gene" entry point

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1432]
you still go to:

http://curation.pombase.org/pombe/curs/4d3b0d5a0015df91/genotype_manage#/edit/15

**Comment by kimrutherford** [comment]
Should it go to the main genetype management page?  Would that be confusing?

**Comment by ValWood** [comment]
I don't think so?
It's confusing not because it doesn't work -you can't add alleles from here any more ;)

@mah11 @Antonialock  what should happen here?

**Comment by Antonialock** [comment]
I’m not sure what you mean either Val

**Comment by kimrutherford** [comment]
> well now, from this page, when I click on ...
> single allele phenotype nothing happens.....

Ah, sorry, I was testing the multi-allele link.  I've fixed this now.

> also "quick add" doesn't appear for phenotypes or interactions....

We've never had a quick add for single allele phenotype because the main link is a kind of quick add.

We don't have a quick add link for interactions any more because of #1380 - it would be redundant as the main link now does a quick add.

**Comment by ValWood** [comment]
works as I expected now...
