### ISSUE TITLE
remove redundancy in amino acid descriptions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1433]
rec8-7A(aaS400A,aaS402A,aaS404A,aaS410A,aaS412A,aaT414A,aaS416A)

could be (aaS400A,S402A,S404A,S410A,S412A,T414A,S416A)

**Comment by ValWood** [comment]
consideration:
@Antonialock > What do we do in cases of a ‘mixed’ mutant? Eg say there is an nt change and an aa change?

good point, do we have any? (we would need to curate them as type 'other' anyway so
 we could be explicit in the description?

**Comment by kimrutherford** [comment]
> could be (aaS400A,S402A,...

Should we also change the behaviour for "nucleotide substitution(s)" alleles so that the "nt" isn't repeated?

> What do we do in cases of a ‘mixed’ mutant? Eg say there is an nt change and an aa change?

The code only adds "aa" if the allele type is "amino acid substitution(s)" so I think we can safely change what we do in the "rec8-7A(aaS400A,aaS402A,aaS404A,..." case.

I have the change ready to deploy.

**Comment by ValWood** [comment]
sounds good.
It is possible to have a combined  mutant described as a combined nt and aa modification if there is an AA change and a promoter mutation. We have no examples of this. We can handle it when  we have an example.....

**Comment by kimrutherford** [comment]
OK, I've made that change.  The "aa" and "nt" are now only added at the start.
