### ISSUE TITLE
GO complex as "assayed using" for some phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1461]
Can we add this?

so that I can use the GO term for MBF as "assayed using" for a DNA binding term?

![tmp](https://user-images.githubusercontent.com/7359272/40356106-0b91b056-5db0-11e8-8740-5de95984e4ba.jpg)

**Comment by mah11** [comment]
The line that would do this was commented out in the config file. I suspect that may be because it was causing odd behavior (and on a related note, see #1068), but I've uncommented it so you can try using it.

I'll leave this open until you have a chance to test it, in case it goes awry.

I also updated the GO ID for complex .... hadn't been done since the merge in GO CC.

**Comment by ValWood** [comment]
that all works
