### ISSUE TITLE
Support for multiple phenotype annotation types

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1462]
Currently, the Canto configuration files can only handle one OBO namespace for phenotype annotations:

https://github.com/pombase/canto/blob/8859c754335a40170633b41a5f692ee3c8ae205c/canto.yaml#L1650-L1652

 However, my understanding is that this needs to change for PHI-Canto, since PHIPO currently has three namespaces for phenotypes:

- disease formation phenotype
- host phenotype
- pathogen phenotype

This presumably means that the configuration (specifically something corresponding to the `available_annotation_types` property in `canto.yaml`) will need to be extended to support more than one phenotype annotation type.

Would appreciate thoughts from @kimrutherford on this, since I don't know how simple it will be.

**Comment by kimrutherford** [comment]
It's already possible to configure more than one phenotype annotation type.  The thing that isn't supported in restricting a phenotype type to a specific genotype type.

For example we only want to allow annotation of pathogen genotypes with PHIPO:0000002 "pathogen phenotype" terms (or descendents).

One of the settings for each annotation type in canto.yaml is `feature_type` which can currently be "gene" or "genotype".  We probably need to add a optional `feature_sub_type` that can be set to "pathogen", "host" or "pathogen_host_interaction".  For the "disease formation phenotype" we would configure `feature_sub_type: pathogen_host_interaction`.

**Comment by kimrutherford** [comment]
It's sort-of related to this issue, so I'll mention it here: I've changed the `metagenotype_list_row_links.html` template so that `disease_formation_phenotype` isn't hard coded in the URL.

It now reads the list of annotation types from the configuration and displays links for annotation types that have a `feature_type` of `metagenotype`.  Probably there will only ever be one link because we'll probably only have this one ontology/annotation type for meta-genotypes:

    - name: disease_formation_phenotype
      category: ontology
      namespace: disease_formation_phenotype
      display_name: 'disease formation phenotype'
      feature_type: 'metagenotype'
      ...

**Comment by kimrutherford** [comment]
I think this is fixed.
