### ISSUE TITLE
Do we want to display the uniprot strain in the organism dropdown?

### ISSUE THREAD

**Issue by CuzickA** [pombase/canto#1467]
![big box and uniprot strain](https://user-images.githubusercontent.com/11753634/40422747-29baa848-5e88-11e8-86d0-d071ac0aa7f1.PNG)
Is this confusing with  planned strain dropdown list? could be a conflict in strain name.
This display makes box too big.
UniProt species names dont always match NCBI taxon names eg Gibberella zeae and Fusarium graminearum.

**Comment by kimrutherford** [comment]
Could you let us know which UniProt ID you were using?

**Comment by kimrutherford** [comment]
> Could you post a screen grab. I'm a bit lost where we are up to until I can see the tool.

There's one at the top of the issue.

**Comment by kimrutherford** [comment]
I had a look at Q00909 and looked for other entries for the same protein.  Unfortunately in this case UniProt have annotated/reviewed the protein for a specific strain (Q00909) but none of the entries for the species are reviewed.

There are several un-reviewed entries for Gibberella zeae itself rather than a strain but that doesn't help us.  For example: http://www.uniprot.org/uniprot/Q96W88

We might want to consider changing Canto to look up parent taxons in this case.  If the taxon ID for a protein isn't in the database Canto could use the NCBI taxonomy API to find the parents and then check to see if any of those taxons is in the database.  
eg. https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=taxonomy&id=229533&mode=text

**Comment by ValWood** [comment]
Ah sorry  I missed that fromthe e-mail.

I think this is simple to fix here. Only display the taxon ID from UniProt, not the strain. I made the same note from my brief test last night:

1. text required  when adding genes. 
Note that if  your strain has not been sequenced you can use the reference strain for your species. This step is to disambiguate  genes not species/strains. You will be asked for strain information later.
2.
text not required (strain PH-1 / ATCC MYA-4620 / FGSC 9075 / NRRL 31084)
when displaying organims.

Remember we aren't concerned with the strain here. We are only using UniProt to disambiguate the loci (in case the same name is used in different places etc). The strain is determined  by the user within the tool.

**Comment by kimrutherford** [comment]
> Only display the taxon ID from UniProt, not the strain

The complication is that the taxon ID in this case refers to a strain.  Inside Canto we use the taxon ID as the "primary key" and we won't have the taxon ID for the strain in the database.

**Comment by kimrutherford** [comment]
This should be fixed now.

See https://github.com/pombase/canto/issues/1611#issuecomment-436906309 for details.
