### ISSUE TITLE
unknown term GO:0032876

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1489]
do we know what is causing this?

![unknown term](https://user-images.githubusercontent.com/7359272/41126252-d2f6601a-6a9e-11e8-8779-0c26c6140c03.jpg)

nothing happened to the term as far as I'm aware?
https://www.ebi.ac.uk/QuickGO/term/GO:0032876

**Comment by ValWood** [comment]
Also curs/515169773959f90f

GO:0000145[UNKNOWN TERM]

This is exocyst. This must be a GO problem???
https://www.ebi.ac.uk/QuickGO/term/GO:0000145

**Comment by kimrutherford** [comment]
That term is not in the pombe only GO subset.  I have been trailing the taxon restrictions in the test Canto but accidentally updated the main Canto too.  Sorry for not letting you know.

In this case the problem might be because of this ancestor?  It has "subset: gosubset_prok".  Seems suspicious given that the definition mentions Drosophila:

[Term]
id: GO:0042023
name: DNA endoreduplication
namespace: biological_process
def: "Regulated re-replication of DNA within a single cell cycle, resulting in an increased cell ploidy. An example of this process occurs in the synthesis of Drosophila salivary gland cell
polytene chromosomes." [GOC:jl, GOC:vw]
comment: Note that this term is only to be used in situations were this process occurs normally. Not to be used to describe mutant or diseased states.
subset: gosubset_prok
synonym: "DNA endoreplication" EXACT []
synonym: "DNA re-duplication" EXACT []
is_a: GO:0044786 ! cell cycle DNA replication

**Comment by ValWood** [comment]
Yep looks like a taxon problem. I'll get that fixed....

**Comment by ValWood** [comment]
The  exoxyst term has "only in celllular organisms" which is correct?

**Comment by kimrutherford** [comment]
Exocyst is missing from the pombe-only GO subset too.  It has this relationship:

relationship: capable_of_part_of GO:0097712 ! vesicle targeting, trans-Golgi to periciliary membrane compartment

and GO:0097712 has:

    Never in Taxon 	4890 	Ascomycota

I don't understand "capable_of_part_of" but could that be the problem?

**Comment by ValWood** [comment]
thanks, I think that one needs removing...

**Comment by ValWood** [comment]
The GO issue is fixed 
https://github.com/geneontology/go-ontology/issues/15887#issuecomment-395855265

but this is still  displaying "unknown" I thought that would have filtered through by now?

**Comment by kimrutherford** [comment]
> I thought that would have filtered through by now?

It looks like the change hasn't come through the pipeline yet.

**Comment by ValWood** [comment]
OK now
