### ISSUE TITLE
preventing   users including entire datasets  (i.e contaminants and low confidence) in physical interactions

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1490]
Antonia pointed out instances of  users including all proteins in a pull down, including "common contaminents"

We should probably  change the text  here:

![add text](https://user-images.githubusercontent.com/7359272/41220473-6a08ecae-6d59-11e8-89f9-aa0a5430d036.jpg)

 something to say that the data should be "pre processed" to filter   common false positives.

It's difficult to word because  we can't  use "threshold", many of the contaminants  are  going to be higher than the real interactors .....

ideally they would report any "conservative" dataset that they report in the paper, but if they don't do this, it's difficult to know how to word it.

suggestions?

**Comment by ValWood** [comment]
- [ ]  for this particular dataset, Antonia you should contact the authors  
we need a "boiler plate"  e-mail for future instances which are not caught by the annotation guidance.

Something t say:
We noticed that  you have reported your Mass spec  dataset in it's entirety. We encourage you to remove known/likely contaminants ( translation factors, and ribosomal proteins for example)

could you draft something and circulate?
@mah11  any ideas?

**Comment by mah11** [comment]
> suggestions [for the interaction interface]?

I have added this to the documentation in git:

"We recommend that you only annotate interactions that you think are biologically meaningful. For example, don't include known or suspected contaminants from mass spectrometry results (e.g. ribosomal proteins, translation factors, 'sticky' proteins)."

You could crib some or all of that to put in the curation popup.


> @mah11 any ideas [for email draft]?

One idea: please don't put an apostrophe in the possessive pronoun "its" ("it's" is a contraction of "it is").

Some possible words:

"In your annotations for [paper], it looks like you have included an entire set of mass spectrometry results in the physical interactions section. We believe that interaction annotations are useful when they represent biologically relevant interactions rather than experimental artefacts, so if any of the interacting proteins you have annotated are likely to be contaminants (such as ribosomal proteins or translation factors), we recommend that you remove them from the Canto annotations."

**Comment by ValWood** [comment]
Its a typo

**Comment by mah11** [comment]
now you're just taking the piss ;)

(would it be funnier if i'd typed "your"?)

**Comment by ValWood** [comment]
Yes but you just couldn't do it could you?

**Comment by mah11** [comment]
at least I thought about it!

**Comment by ValWood** [comment]
ACtion, include these suggested words

"In your annotations for [paper], it looks like you have included an entire set of mass spectrometry results in the physical interactions section. We believe that interaction annotations are useful when they represent biologically relevant interactions rather than experimental artefacts, so if any of the interacting proteins you have annotated are likely to be contaminants (such as ribosomal proteins or translation factors), we recommend that you remove them from the Canto annotations."

BUT could we add a tiny bit of text to discourage people from entering likely artifacts to start with?

**Comment by ValWood** [comment]
Maybe the  message  I would like needs to be further forward, before they even add the genes for the session.

here: 

![names](https://user-images.githubusercontent.com/7359272/64261527-93fb4100-cf24-11e9-9d38-13620da654e4.jpg)

**Comment by ValWood** [comment]
Perhaps 
Note that, for large physical interaction datasets we only require high confidence positive interactions (e.g. after common contaminants are removed)
If you have large datasets please consider one of our spreadsheet formats
https://www.pombase.org/submit-data/bulk-annotation. 


@mah11  @Antonialock ?

**Comment by kimrutherford** [comment]
> Implement text change

Done!
