### ISSUE TITLE
phenotype annotate error 

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1509]
Ontology is not loading when attempting to annotate

The server is responding with an http 500 error:

The url it is attempting to reach is:

<http://canto.phi-base.org//ws/lookup/ontology/phenotype/:COUNT:?extension_lookup=0>

The url of the page generating the error is:

<http://canto.phi-base.org/curs/a77ad74e14f4fc35/feature/genotype/annotate/1/start/phenotype>

I have checked that the ontologies loaded correctly without error.

**Comment by kimrutherford** [comment]
The error response says:

     no cv with name: disease formation phenotype

Have you loaded that ontology?

**Comment by jseager7** [comment]
It looks like you're loading a version of the config file that is referencing the PHIPO namespaces. That's probably my fault for sending you incorrect configuration at some point. You might want to change your `canto_deploy.yaml` so that `available annotation types` just has `phenotype` as the only annotation type, and make sure that the `namespace` sub-property is `fission_yeast_phenotype` (which matches FYPO).

You can get a working version of the phenotype annotation type here:

https://github.com/PHI-base/config/blob/master/vagrant.canto_deploy.yaml#L24
