### ISSUE TITLE
Split genotypeManager into angular directives

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1554]
Replace existing genotype_manage.mhtml code with a directive offering two options:

- Genotype management
- Mega Genome

Convert existing genotype_manage.mhtml code into a directive and re-implement the perl parts

**Comment by barnabynorman** [comment]
@kimrutherford should all be working (although a bit rough) - fighting with the caching - not even debug hack would make it stop! I will look again tomorrow and talk it through.

**Comment by kimrutherford** [comment]
Thanks Barnaby.

I've made a change to the Perl controller so that if you go to /genotype_mange you get to the genotype management page.  If you go to /metagenotype_manage you get the metagenotype page.  Both paths use the new template you made (gentoype_switch.mhtml) but a different flag is passed in each case.

I think with that change we'll be able to merge back into the master branch soon and Canto will continue to work OK for pombe.  Then to test the meta-genotype stuff we can go to /metagenotype_manage.  We just won't link to it initially.

**Comment by kimrutherford** [comment]
I've moved these changes onto the metagenotype-dev branch so they're all in one place.

I deleted the branch for this issue "tickets/ticket-1554".
