### ISSUE TITLE
Don't show both Pathogen and Host gene pickers in Genotype Management

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1555]
Now that we've decided to have separate views for Host genotype creation, Pathogen genotype creation, and Meta-genotype creation, we should probably revert the changes that added a second organism and gene picker to the meta-genotype page.

I think the relevant commits are in #1403, but I'm not whether reverting them is the best option; maybe we should just make the changes in new commits.

**Comment by kimrutherford** [comment]
I've just added two new routes /pathogen_genotype_manage and /host_genotype_manage so that the genotype management page will know if it should show host, pathogen or all organism in the organism picker.

The gentoype-manage direction now has a genotypeType parameter which is set to "normal", "pathogen" or "host".  In the "normal" case we should show all organisms in the organism-picker.

**Comment by jseager7** [comment]
Closing this now, since it's been implemented by #1559.
