### ISSUE TITLE
Tracking changes to curation sessions in Admin

### ISSUE THREAD

**Issue by CuzickA** [pombase/canto#1561]
It would be useful to have a copy of the original curation made by the author prior to any corrections made by the PHI-Canto team within the Admin pages.

**Comment by ValWood** [comment]
we usually just add a comment.
e.g

vw:  changed evidence
vw: added  gene targe extensions
etc

If you add completely new annotation they are assigned to you, so easy to distinguish

Also bear in mind authors very rarely get things wrong, they mainly only miss things...

Otherwise, we would need to store none extant data in the database. This  would be a problem (I'm not sure how it could be done easily)

 worst case scenario  I think it would be would be avaiable in archived canto versions

**Comment by CuzickA** [comment]
Great this makes sense thanks.
I'll close the ticket.
