### ISSUE TITLE
PHI canto adding strain

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1567]
I started to have a play around curating

PMID:22712509
Title | Necrosis-inducing proteins of Rhynchosporium commune, effectors in quantitative disease resistance.
Authors | Kirsten S, Navarro-Quezada A, Penselin D, Wenzel C, Matern A, Leitner A, Baum T, Seiffert U, Knogge W

session
http://canto.phi-base.org/curs/2c86043921e7e7a7

 I  really felt that I needed/wanted to add the strain info when I added the allele here, but I can't do this.

![strain](https://user-images.githubusercontent.com/7359272/43193154-2676b88e-8ff7-11e8-9b76-068ffbce208e.jpg)

Is this part still to be implemented? And at which point was it  decided that this would be added/ I can't remember...

Looking good so far though...

**Comment by kimrutherford** [comment]
Strain selection isn't implement yet.  There's a issue it but it's a bit out of date: #1421

**Comment by ValWood** [comment]
Ok, looks good so far...once thats done I'll do this paper....its has quite a few multi gene I think.

@CuzickA  when you get chance could you make a list of a few complicated allele/strain combination papers for testing. We might as well curate real papers when we test. It does not matter if ontology terms are not there yet, we can just add them as term requests.


Val

**Comment by ValWood** [comment]
https://github.com/pombase/canto/issues/1421
sounds good. I remembered there was a brief discussion about adding later, but  I think it should be in genotype, definitely...

**Comment by CuzickA** [comment]
I think we favored either adding the strain at 1) the same time as the gene/organism lists or 2) at the genotype stage ... there is a document of notes on strains https://docs.google.com/document/d/1uoG3ewi_u7kUE0GNUt_P1rA65lRhdqjyvUONGyOnC1Y/edit

**Comment by CuzickA** [comment]
@ValWood I'm currently tidying up 6 months of PHI-base data for the next release. 
I came across this article which may be useful for PHI-Canto testing...
PMID: 28921772 
Title: Interplay of classic Exp and specific Vfm quorum sensing systems on the phenotypic features of Dickeya solani strains exhibiting different virulence levels.
Potrykus M, Hugouvieux-Cotte-Pattat N, Lojkowska E.

It had been poorly curated so I had a go at re-curating it (all the strains for a given gene had been lumped together and annotated with a single phenotype, rather than entered individually and given a phenotype per strain. This was essential as the phenotypes varied per strain). 
It contains several genes, both single and multi-alleles and several strains. I based my phenotype annotations on the current high-level PHI-base terms 'reduced virulence' and 'unaffected pathogenicity' depending on the pathogen's ability to macerate either chicory leaves or potato tubers. There are also motility and PCWDE production phenotypes that could be captured in the future with PHI-canto.

Hope this is useful.
