### ISSUE TITLE
Fix inconsistent dialog buttons and style

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1589]
The delete annotation / delete genotype confirmation dialogs should use the same style and button order as the edit dialogs.

![confirm-delete-1](https://user-images.githubusercontent.com/90474/43562461-c59f7188-9670-11e8-86a0-044fe6946762.png)

![edit-dialog-1](https://user-images.githubusercontent.com/90474/43562463-c896e3ee-9670-11e8-8169-50bbca52f4b1.png)

**Comment by ValWood** [comment]
@kimrutherford Is this something @jseager7  could look into?

**Comment by jseager7** [comment]
@kimrutherford I've had a quick look at this and it seems simple to fix, but there's a slight dilemma about the colour of these buttons: on the Edit dialog you've got the Cancel button styled as a 'warning' button (using Bootstrap classes), meaning it appears orange.

However, if we fixed the order on the Delete modal to have Cancel on the left, then I'm not sure it would make sense to style that as a warning, because in this case it's the OK button that is the 'dangerous' action.

So I think it might be more intuitive if we flipped the colours in this case. I also think labelling the button 'Delete' instead of 'OK' would make it blindingly obvious what's going to happen when either button is pressed. Here's how that would look:

![image](https://user-images.githubusercontent.com/37659591/64245374-b8462600-cf02-11e9-9355-99ac8ad72f1f.png)

Alternatively, we could use the `btn-danger` style to add more visual emphasis, since this action is one of the most destructive things Canto offers (there's no way to undo a deleted annotation):

![image](https://user-images.githubusercontent.com/37659591/64245487-e88dc480-cf02-11e9-96f8-61e497cd4d7e.png)

**Comment by kimrutherford** [comment]
> Alternatively, we could use the btn-danger style

I think it makes sense for the btn-danger style for dangerous actions.

But changing the label might be too much work.  We currently just do this:

```html
   <a title="Delete this annotation"
      confirm="Are you sure you want to delete this annotation?"
      ng-click="deleteAnnotation()">Delete</a>
```

and then the dialog is created by an Angular module: https://github.com/jameskleeh/angular-confirm/tree/1.2.x

In the docs they show how to to it more manually (http://jameskleeh.com/angular-confirm/):

```js
 $scope.delete = function() {
      $confirm({text: 'Are you sure you want to delete?', title: 'Delete it', ok: 'Yes', cancel: 'No'})
        .then(function() {
          ...
        });
  }
```

but that seems like too much effort.  :-)

**Comment by jseager7** [comment]
I didn't realise that the confirm was being generated dynamically. That certainly complicates things.

From my testing, it seems the situation is worse than the docs imply, because even manual configuration only lets you change the labels for the buttons, not their styles (as far as I can tell). You can't change the button order either, so angular-confirm seems to be the root cause of this issue. I think the only fix is to render a modal manually, like what we do with the Edit dialog.

The fix isn't quick, so I'm removing the 'quick' label from this issue. I'd still like to take a look at this when I have time.

**Comment by kimrutherford** [comment]
> think the only fix is to render a modal manually, like what we do with the Edit dialog.

Yep, I agree.

> I'd still like to take a look at this when I have time.

Thanks, that would be great.  Let me know if I can help.
