### ISSUE TITLE
adding isoforms

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1591]
in this session
curs/f30149c5fcc7f553/ro.

I want to capture that the protein binding between 
dma1 and sid4  is between unubiquitinated dma1 PR:000044741 and phosphorylated sid4 PR:000044611.

I don't see the option to add the isoforms.

**Comment by ValWood** [comment]
Actually that is probably because I have already added the protein.

We can use this as an example to discuss

how we want this to work. https://github.com/pombase/website/issues/67
We'll do that on our next call

**Comment by Antonialock** [comment]
I thought we could put
col17=PR:xxx in the extensions field (but I could be wrong, I guess it is an odd place for it)

for the interacting protein, can you put a PR ID in the with field? Or IPI the gene ID + add an extension to specify the PR ID?

**Comment by ValWood** [comment]
Yes but the point is at present it isn't clear whether we do the PR of the interacting protein or the interactor and the display is confusing in this respect.
I can put the info in but we need to address this anyway. we aren't consistent.

**Comment by mah11** [comment]
> I thought we could put
> col17=PR:xxx in the extensions field (but I could be wrong, I guess it is an odd place for it)

Yes, the admin-only extension options include "column 17 (PR:nnn ID for gene product form) ...", which pops up a box where we can paste an ID (no need to type out the col17= bit). It is a bit odd because all other extensions go into GAF column 16, but I guess we've seen no reason to do a whole separate part of the Canto interface just for column 17.

In Val's example this is what to do for the dma1 isoform.

> for the interacting protein, can you put a PR ID in the with field? Or IPI the gene ID + add an extension to specify the PR ID?

No, neither would work with Canto as it's currently configured. For GO evidence, the with field only allows genes from the list you enter for the session (pick from a pulldown). For extensions, we don't have anything configured to allow PR IDs in GO extensions (there are a few FYPO branches configured to allow PR:nnn extensions, admin-only).

I think we could add some PR-ID-in-col16 configuration options easily in principle. The only hard part is coming up with adequate help text to remind us of the col16/col17 distinction. We have plenty of time to work on refining the help text for community users, because none of the existing PR:nnn options are available to them; they're all admin-only.

So right now we don't have a place for Val's sid4 isoform, but we can add one in tho configuration.

**Comment by mah11** [comment]
> Yes but the point is at present it isn't clear whether we do the PR of the interacting protein or the interactor 

To me it is clear that:
- we should the PR:nnn ID for the protein annotated to GO:0005515 in a column 17 entry, and we can do this now; and
- we should put a PR:nnn entry for the bound protein (the one whose gene ID goes in the 'with' field for IPI evidence), but we can't do this yet.

**Comment by ValWood** [comment]
What isn't totally clear to me is what we / or the users expect to see on the pages. Can discuss Thursday, time permitting....

**Comment by mah11** [comment]
What pages?

**Comment by mah11** [comment]
That's not a Canto issue, then.

**Comment by ValWood** [comment]
Wee it is in the first instance because to me it isn't clear  how we curate the based on what we are showing. I'd like to discuss both aspects simultaneously, and I don't have time to figure it out right now.....

**Comment by ValWood** [comment]
IOW I want to begin with what we want to see on the gene page, and work backwards to make sure this is intuitive when we capture in Canto. At the moment it isn't because I don't understand it.

**Comment by ValWood** [comment]
Re 
> we should put a PR:nnn entry for the bound protein (the one whose gene ID goes in the 'with' field for IPI evidence), but we can't do this yet.

I can actually do what I wanted to do here, like this:
![dma1](https://user-images.githubusercontent.com/7359272/43891161-94165eb0-9bc0-11e8-8fdf-0047c402a4d3.jpg)

which is adequate and complete AFAICS?

So maybe nothing needs to happen in Canto at all?
I don't know why I could not make the annotation that I wanted to before......

**Comment by ValWood** [comment]
Midori will update config.
Val will test with above session.

**Comment by mah11** [comment]
I've committed the MF config update.

**Comment by ValWood** [comment]
OK, I *think* I got that right:

![dma1-sid4](https://user-images.githubusercontent.com/7359272/44776749-b53a8c00-ab70-11e8-92d0-144f95b4b495.jpg)
