### ISSUE TITLE
Strain adder should only render once for each organism

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1618]
(Related to #1617)

On the _Gene and host organism list_ page, each gene table currently renders the strain selection dropdown for every row, even if the organism is the same:

![multiple_strain_dropdown](https://user-images.githubusercontent.com/37659591/45683314-1683c880-bb3b-11e8-9b90-d660d4816c5a.PNG)

They share state too, meaning we have redundant displays of strain names:

![strain_dropdown_shared_state](https://user-images.githubusercontent.com/37659591/45683331-2b605c00-bb3b-11e8-9d9b-3e7ef6764656.PNG)

We could solve this by applying a row span to the strain column, so that there is only one strain selector per organism:

![rowspan_strain_selector](https://user-images.githubusercontent.com/37659591/45683363-44690d00-bb3b-11e8-8d71-2171961973a3.PNG)

However this isn't going to work well at the moment, since the gene tables are currently sorted by the systematic identifier (UniProt ID), which means genes for the same organism won't display in adjacent rows in all cases:

![strain_row_split](https://user-images.githubusercontent.com/37659591/45683381-58ad0a00-bb3b-11e8-947d-0246179fbad0.PNG)

So I suggest we solve this with the following two changes:

* Sort the table by organism name / taxon ID, instead of systematic identifier.

* Set a rowspan on adjacent rows in the strain column with the same organism name / taxon ID.

**Comment by barnabynorman** [comment]
I started thinking about whether this problem is the wrong way up as we have organisms that have genes, then I started prototyping a solution that is organism centric:

![image](https://user-images.githubusercontent.com/1710907/46092321-8b46aa80-c1ac-11e8-8ba4-803cc14bc2e6.png)

I was even thinking that the host organisms with no genes could go in with the hosts table and instead of showing the list of genes it would say "No genes for this organism" - simple!

However, I have set myself an impossible task - my first thought was adding rowSpan attributes on the organism columns and just repeating the gene rows / columns, but I can't find a clean logical way of building that as any angularjs repeat (or directive) requires a single enclosing element. This lead me to embedding a second table for the genes, but as you can see above, the columns won't line up and angular appears to be ignoring my width attributes! I may just have to abandon and go back to plan A - @kimrutherford, @jseager7 any thoughts?

**Comment by jseager7** [comment]
Does your markup look roughly like this?

```html
<table>
  <thead>
    <tr>
      <th rowspan="2">Taxon ID</th>
      <th rowspan="2">Organism</th>
      <th rowspan="2">Common Name</th>
      <th rowspan="2">Strain</th>
      <th colspan="4">Genes</th>
    </tr>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Synonyms</th>
      <th>Product</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td rowspan="2">4565</td>
      <td rowspan="2">Triticum aestivum</td>
      <td rowspan="2">Bread wheat</td>
      <td rowspan="2">Strains</td>
      <td>P01083</td>
      <td>IMA1</td>
      <td></td>
      <td>Alpha-amylase inhibitor 0.28</td>
    </tr>
    <tr>
      <td>P11383</td>
      <td>rbcL</td>
      <td></td>
      <td>Ribulose bisphosphate carboxylase large chain</td>
    </tr>
  </tbody>
</table>
```
Because I think you might be able to solve this by using `ng-repeat-start` and `ng-repeat-end` to repeat a series of elements, without the need for a container ([see the docs](https://code.angularjs.org/1.5.11/docs/api/ng/directive/ngRepeat#special-repeat-start-and-end-points)).

So you'd have one repeat for the row that includes the organism information (with its range explicitly controlled with `ng-repeat-start` and `ng-repeat-end`):

```html
    <tr><!-- ng-repeat-start for organism in organisms -->
      <td rowspan="2">4565</td>
      <td rowspan="2">Triticum aestivum</td>
      <td rowspan="2">Bread wheat</td>
      <td rowspan="2">Strains</td>
      <td>P01083</td>
      <td>IMA1</td>
      <td></td>
      <td>Alpha-amylase inhibitor 0.28</td>
    </tr>
```

And then maybe within the range of that `ng-repeat`, you could nest more 'standard' `ng-repeat`s on the `<tr>` elements below, for rows that only include the gene data:

```html
    <tr><!-- ng-repeat for gene in genes, except the first -->
      <td>P11383</td>
      <td>rbcL</td>
      <td></td>
      <td>Ribulose bisphosphate carboxylase large chain</td>
    </tr>
    ...
    <!-- then ng-repeat-end somewhere later -->
```

I guess the nested repeater would have to exclude the first gene from the list, otherwise you'd duplicate the first gene.

The biggest problem here is that it looks like the `ng-repeat-end` has to be on an element as well, but putting it on the last gene row could be difficult because that might be nested in a separate `ng-repeat`.

**Comment by barnabynorman** [comment]
@jseager7 sounds like a plan - I will let you know how I get on.
