### ISSUE TITLE
Add help text for summary page genotype heading

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1658]
Pull request #1649 added a new heading on the summary page to separate the genotype links from the gene links. However this new heading doesn't have any help text associated with it, whereas the gene heading does. Is it worth adding any help text?

**Comment by ValWood** [comment]
Hi @jseager7  can you screenshot which heading this is. then we can write some text (or add to agenda for monday, seems quick)

**Comment by kimrutherford** [comment]
> can you screenshot which heading this is. 

It's the "Annotate genotypes" heading here.  We should add a "?" help link and some text.

![summary_genotype_heading](https://user-images.githubusercontent.com/37659591/47494737-444ee200-d84a-11e8-96a7-12674bc85979.PNG)

**Comment by ValWood** [comment]
This is a good point.

The help for genes says
Once you have selected a gene to annotate you will be presented with a set of annotation options

What should the help link for genotypes day?

Phenotypes annotations are connected to genotypes in Canto.  Required genotypes  can be added upfront, or individually as required for annotation depending on your preferred workflow.

@mah11  edits?

**Comment by ValWood** [comment]
@mah11  we can close this once the text is revised. Does this sound OK? can you improve ?

**Comment by mah11** [comment]
I think this would suffice:

> Add genotypes (including alleles, expression levels, and optional background) to use in annotating phenotypes.

I don't think it's actually necessary to tell people they can add genotypes all at once or bit by bit; they'll figure it out as they use Canto. But if you really want to, so much that it's worth the extra verbiage, also include:

> You can add genotypes individually as you go through the paper, or all at once before you start adding phenotype annotations.

i.e. even with the addition I wouldn't explicitly say "workflow".

**Comment by ValWood** [comment]
yes I agree workflow wouldn't be good.

But  I think it might be useful for users to be aware here that they can add genotypes all at once or bit by bit;
I don't think it's immediately clear that once you have moved forward  through the workflow you can easily come back later

This information would probably be even more useful for the PHI-base users.

I think we should add it. Maybe in future iterations we can tailor the instructions more for novice/first time users to returning users so that people don't need to see comments like this all the time.
We can deal with this when we do some user testing, hopefully some time next year.
