### ISSUE TITLE
Small text changes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1677]
In the Gene tables

- [ ]  1. Change "Organisms" to "Organism" (it's only one per row)
Q Would "Species" be better?

- [ ]  2.  Change "Genes" to "Gene" (ditto above)

- [ ]  3. Change Reference Genome ID  to "UniProt ID" (these aren't the reference genome IDs)

**Comment by jseager7** [comment]
I assume we're talking about the gene table on the 'Confirm genes and organisms' page?

I agree with changing 'Organisms' to 'Organism', but changing 'Genes' to 'Gene' might be problematic, because the gene rows are grouped with the organisms, like this:

![gene_table_grouping](https://user-images.githubusercontent.com/37659591/48484013-e855f880-e80c-11e8-8953-bd95edaafa1f.PNG)

So strictly speaking, there can be more than one gene per (organism) row.

I think the naming of the 'Reference Genome ID' column was something suggested by @CuzickA or @kehammond, so I'll have to defer to them on reasoning for this.

**Comment by ValWood** [comment]
> So strictly speaking, there can be more than one gene per (organism) row.

I don't think that matters, it's still a single gene object (cardinality 1 for the row).  Synonyms could be synonym(s) because there could be one, or more than one per row, but plural is fine here...

>I think the naming of the 'Reference Genome ID' column was something suggested by @CuzickA or @KEHammond, so I'll have to defer to them on reasoning for this.

OK. it isn't the 'Reference Genome ID' though. I can see why this label because this is to indicate that this is the  UniProt sequence for the reference strain. Tricky...

I think, here I would just put "UniProt ID" actually, (more precisely it is the UniProt accession, but we will ignore that issue).

The information about which ID is  needs to be entered should be provided early in the workflow. It needs to be in the help text on the gene upload page
http://canto.phi-base.org/curs/8bf2259e22c37d46/gene_upload/
Once the ID is entered the curator doesn't need to be reminded that its the reference ID, since they now know this because they added it.

- [ ]  PHI-Canto specific text explaining precisely which IDs are required (in addition to   documentation to trouble-shoot when  the entry can't be easily located). MAybr move to a separate ticket

**Comment by jseager7** [comment]
> I don't think that matters, it's still a single gene object (cardinality 1 for the row).

Yes, now that I look at the other column headings I agree it would make more sense to have 'Gene' since all the sub-headings for 'Gene' are singular ('Name', 'Product', etc.)

**Comment by jseager7** [comment]
Forgot to do this when I was making the other changes to the organism table, but it's done now. The 'Reference Genome ID' &rarr; 'ID' change was already done as part of #1730.
