### ISSUE TITLE
Deletion of same gene on multiple strains

### ISSUE THREAD

**Issue by barnabynorman** [pombase/canto#1692]
An earlier ticket asked me not to grey out the "Deletion" button for creating alleles, which I completed a while back, however the logic in the backend does not appear to work. When I create the same knock-out with a different strain it is ignored.

Is this something that can be achieved?

**Comment by kimrutherford** [comment]
I think I've fixed this.  There were two problems.

First, the code Perl code that detects duplicate genotypes was ignoring the strain.  So when the second deletion was sent to the server it wasn't being stored because the code thought it existed already.

Second there was no message in the client to show that there was a duplicate.

@barnabynorman could you check that it's fixed for you?

**Comment by barnabynorman** [comment]
@kimrutherford its weird, I tested it this morning and it did not work, but when I checked it now it did??
