### ISSUE TITLE
Add ORCID to the name/email confirmation page

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#17]
Add an optional field to the session acceptance page for ORCID.  Store the ORCID with each annotation made by that user.

Original comment by: kimrutherford

**Comment by ValWood** [comment]
I moved this up. I think we need to discuss fairly soon as we are  promoting CC more and mention on MOD perspective article.

We have also had a request to be able to review sessions from OMP (which is slightly, if tangentially related).

I am thinking that we might need to provide 2 things:

1. Ability to link ORCIDs to  'user accounts' so that sessions and/or annotations can be retrieved/attributed

2. Ability for users or collaborators to  see session in 'review mode' based on PMID search

Do we envisage any problems with either of these?

**Comment by kimrutherford** [comment]
> Ability to link ORCIDs to 'user accounts'

We can add another field to the confirmation page but then there's the usual problem of dealing with inconsistencies: if the user pastes in an ORCID but the name or email doesn't match we need to prompt and ask what to do.  I 

Also need to handle adding an ORCID for an existing user.  That's easy enough.

Related: #593,  #603

> so that sessions and/or annotations can be retrieved/attributed

When you say "retrieved" what do you mean?

> Ability for users or collaborators to see session in 'review mode' based on PMID search

Is that the same as: #481 ?

**Comment by kimrutherford** [comment]
The schema change to add orcid is ready to go.  I won't do it now because there's always a chance it will go wrong.  I'll do it at the start of my next work day so I have time to fix any problems.  This is just a database change so far.

**Comment by mah11** [comment]
I have opened #1166  for the PMID search -> read-only view item (it never should have appeared on this ticket).

**Comment by ValWood** [comment]
So, I think we need to
1. Display  ORCID field here. I can solicit ORCIDs from existing users and plug them in

2. Add a field for the user to add  their ORCID  on the page where they confirm their name and e-mail

 Then how do we proceed. I want to contact ORCID soon.
We would need to be able to link to all of the review sessions  of a user based on ORCID. Should I ask if this is possible and if this  was enabled  would it be better  a) by individual publication (I think this would be better  because specific papers will be associated with different grants),  or b) a landing page listing all the papers to which a user has contributed annotation ?

Or, I could  just  ORC and see what  they recommend.

I'm looking at this
http://orcid.org/organizations/integrators/integration-chart

**Comment by kimrutherford** [comment]
> Display ORCID field here.

Where's here?


> Add a field for the user to add their ORCID on the page where they confirm their name and e-mail

That's done in the test Canto.  Could you have a look?

For the moment this is just the most basic thing we can do: a field for pasting the ORCID.

I think what we should do is add a button that redirects to orcid.org to authenticate the user and then automatically adds the ORCID, name and email (if available) to the field on the confirmation page.  I think it should work like it does on this page:
  http://europepmc.org/orcid/import

**Comment by ValWood** [comment]
I'm not sure what I mean't by "display ORCID field here". I guess I mean in the user details?

**Comment by kimrutherford** [comment]
> Add a field for the user to add their ORCID on the page where they confirm their name and e-mail

That's in the main Canto now.

**Comment by ValWood** [comment]
Where would we (or users) go to add their ORCID?

**Comment by kimrutherford** [comment]
> Where would we (or users) go to add their ORCID?

Currently the only place to do it is when you confirm your name and email at the start of a session.  Perhaps we should add a page you can send out to existing users?

**Comment by ValWood** [comment]
I think we should do this for existing ones.

Should I add  a new ticket?

**Comment by kimrutherford** [comment]
> Should I add a new ticket?

Just added: #1269

**Comment by kimrutherford** [comment]
> Add a field for the user to add their ORCID on the page where they confirm their name and e-mail

That wasn't working consistently but I've fixed that.

I've also fixed it so that if you send a session email out then the ORCID field in the name/email confirm page will be filled in automatically.

**Comment by ValWood** [comment]
- [ ]  We need some text explaining what people are allowing when they sign up...

**Comment by kimrutherford** [comment]
> Add a field for the user to add their ORCID on the page where they confirm their name and e-mail

That wasn't working consistently but it's fixed now.

I've also fixed it so that if you send a session email out then the ORCID field in the name/email confirm page will be filled in automatically.

This is still in the test Canto only.  Unfortunately the test Canto is offline while I try to fix #1271 so you can't try it.  I'll try to get the test Canto back up today.

**Comment by kimrutherford** [comment]
>  I'll try to get the test Canto back up today.

It's back, but I haven't been able to fix #1271.  I'm still working on it.

**Comment by ValWood** [comment]
Is this done? Should we close?
We can open new tickets with the "apicuron" tag for anything we need to do with ORCIDs
