### ISSUE TITLE
bookmarked canto session disappeared

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1725]
I'm getting page not found for the session I was doing.
http://canto.phi-base.org/curs/8bf2259e22c37d46

Is there any way to gt this back?

**Comment by kimrutherford** [comment]
We have a backup of that session that can be restored.  I'll talk with James about how to do that when he's back.

**Comment by ValWood** [comment]
OK there is no hurry. I noticed it had disappeared before christmas and it would be good if I didn't  need to redo what I got so far. f I do it's not a huge deal. It would be better if the  data was only flushed from the test version. I'm trying to curate real papers fully to see if there are any sticking points so I may as well do this in the live version so the paper is 'done'

**Comment by jseager7** [comment]
Unfortunately I can't find anything matching that curation session ID in the Canto data directory. The last backup I have of the data directory is from 12 December 2018, and that doesn't seem to contain the session ID either, so I'm not sure what's happened to the session. I've checked the list of publications for PMID 20601497 (which @CuzickA suggested), but nothing matches that PMID in the production or demo version of the tool.

I'm not aware of the data on the main PHI-Canto server ever being wiped since you started this curation session, and I've deliberately avoided touching the data directory since I started managing the servers, but @CuzickA seems to think there was a decision to wipe the main PHI-Canto server at some point in the past in order to rebuild it, and she understood that the session would have to be redone as a consequence. Maybe there's been a misunderstanding?

@kimrutherford If you have any ideas about what might have happened to the session, I'd be happy to investigate further, but if it's not a huge deal for @ValWood to re-enter the session, then that may be the only answer &ndash; I'm sorry for the inconvenience. Ideally we should have set up a regular remote backup process to preserve the curation data &ndash; by that I mean some way to offload the data onto a more local backup &ndash; especially since (as far as I know) we don't have any way to import the data into PHI-base yet, and I'm not confident in using the server as our only data store.

**Comment by ValWood** [comment]
Don't worry, I'm being lazy. I can re do it when I get back around to testing if @kimrutherford  has no ideas. The data entry probably didn't take too long once I got my head around the biology.

**Comment by kimrutherford** [comment]
> @kimrutherford If you have any ideas about what might have happened to the session, 

I think Barnaby reset the server database at some point and the existing sessions were deleted.

We have a copy of the SQLite file for Val's session that we can plug back in once the server is stable.  The data isn't lost.

**Comment by jseager7** [comment]
Ok, that's good to know. In that case we can do as Kim suggests and try to patch the session back in to the server database. I guess I should test the process on my local Canto version first. @ValWood does this need to be done soon? Is it important that the curation session is finished sooner rather than later?

**Comment by ValWood** [comment]
This isn't needed immediately. I was hoping to use this session as a starting point when  @CuzickA  and I speak and try to figure a way forward with the GO terms etc.

We have not got a date set for that meeting.

**Comment by jseager7** [comment]
We've restored the session now, and it should be registered under your name in the _Paper lookup_. I haven't checked the session in detail, since I don't want to risk interfering with your curated data. I'm closing this issue for now, but feel free to re-open if you notice anything odd with the restored session.
