### ISSUE TITLE
log in capability to demo tool

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1728]
I do not seem to have access rights to the demo tool.

I quickly wanted to check something, so  I used "live" 
I wanted to delete the session afterwards, but I can't because I can't log in here either (although I can edit), 
http://canto.phi-base.org/curs/aea55d2e999e3330 needs to be deleted.

Could somebody send me my username/password for live and the demo.

Thanks

Val

**Comment by kimrutherford** [comment]
> Could somebody send me my username/password for live and the demo.

You might not have one yet.

@jseager7 you'll need to run something like:

```
./script/canto_add.pl --person "Val Wood" vw253@cam.ac.uk some_password some_orcid admin
```

You'll need to replace "some_password" and "some_orcid" with what Val sends you by email.

**Comment by jseager7** [comment]
Ok, I've added Val as an admin user on both Canto instances. The live server didn't work as expected because Val already existed as a user, so I had to change her permissions with the admin interface instead. @ValWood feel free to close this issue if you're able to log in.

**Comment by jseager7** [comment]
Actually, on second thought, I'll just close this and you can re-open it if you can't login to either server.

**Comment by ValWood** [comment]
I can log in to the demo, but not the live version.

Note that there isn't much differentiation between the demo and live.  Can the demo be  labelled as "Demo' more clearly?

**Comment by jseager7** [comment]
> I can log in to the demo, but not the live version.

That might be to do with the fact you already existed as a user on the live version (due to curating). I'll try and find out what's going on.

> Can the demo be labelled as "Demo' more clearly?

I think this is a good idea. I could do something similar to PomBase and add the 'demo' background, plus some extra text in the header:

![1728-phicanto-demo](https://user-images.githubusercontent.com/37659591/51536439-7e2c8600-1e43-11e9-9bfe-8b7d85b57a78.PNG)

However I'm currently not sure how to display that background. @kimrutherford I've found a file called `demo_style.css` that seems to be related:

https://github.com/pombase/canto/blob/3dc42e377dc0b068bfc021c5920ea18569a9c7ec/root/static/css/demo_style.css#L1-L3

Is there something I can configure to get Canto to include this stylesheet?

**Comment by jseager7** [comment]
I think I've found the reason why you can't login, but I probably need assistance from @kimrutherford to fix the problem safely. I'll update this issue once it's fixed, hopefully by tomorrow.

**Comment by kimrutherford** [comment]
> Is there something I can configure to get Canto to include this stylesheet?

Try putting this in your canto_deploy.yaml:

```
extra_css: /static/css/demo_style.css
```

which will load `demo_style.css` as well as the usual style files.

**Comment by jseager7** [comment]
> Try putting this in your canto_deploy.yaml

This worked, thanks. Hopefully the background should make the demo website conspicuous enough, but I can change the summary page title too, if necessary.

**Comment by jseager7** [comment]
I think the login is fixed now &ndash; thanks to advice from @kimrutherford I managed to fix the problem through the admin interface, which was much faster. @ValWood I'll leave this open for now in case you have any other problems logging in.

**Comment by jseager7** [comment]
I'm closing this now since I'm assuming there aren't any problems.
