### ISSUE TITLE
Single organism mode: shows strain and organism on gene confirm page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1763]
The Organism and Strains columns should hidden in single organism mode:

![single-user-confirm-bug-1](https://user-images.githubusercontent.com/90474/52328177-84318200-2a53-11e9-9448-e1b924818021.png)

**Comment by kimrutherford** [comment]
I forgot to set `instance_organism` in the config.  The display is correct in single organism mode.

**Comment by jseager7** [comment]
The 'strain' column still displays in single organism mode, but I don't think this needs to be there for PomBase:

![single-org-strain-column](https://user-images.githubusercontent.com/37659591/52407347-f5ab1800-2ac7-11e9-9d68-e450870bc85b.PNG)

Long-term, I'm not sure if strains should be limited to multi-organism mode, because it's possible that future users in single-organism mode might be studying different strains of the same organism? Also, there's no guarantee that users in multi-organism mode would be interested in studying different strains; it seems to be mostly of interest to PHI-base. Maybe the strain system should be configurable in the same way that the gene service is.

**Comment by kimrutherford** [comment]
> Long-term, I'm not sure if strains should be limited to multi-organism mode, because it's possible
> that future users in single-organism mode might be studying different strains of the same organism?

I think that's a possibility.  So you're right that it might make sense to make strain support independent from multi organism mode.

**Comment by kimrutherford** [comment]
> The 'strain' column still displays in single organism mode, but I don't think this needs to be there
> for PomBase:

Thanks, I've checked in a fix for that.

**Comment by jseager7** [comment]
Seems this issue is fixed in the latest version, so I'm closing this now.

![1763-fixed-confirm-table](https://user-images.githubusercontent.com/37659591/52640288-0f849a80-2ece-11e9-9b7f-dfb9c06a38cb.PNG)
