### ISSUE TITLE
Metagenotype annotations have 'gene' feature type

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1768]
While working on a fix for #1760, I noticed that metagenotype annotations have a `featureType` of 'gene'; I expected this to be set to 'metagenotype'. I'm not sure where this value is initially set &ndash; I haven't had time to investigate yet.

@kimrutherford could you try to replicate this on your Canto version? I'm not sure if it's a configuration or schema issue on my side.

### Steps to reproduce

1. Edit a _Pathogen-host interaction phenotype_ on the summary page (or elsewhere),
2. Set a debugger breakpoint inside `function featureChooserControlHelper` or the controller for the `featureChooser` directive,
3. Inspect the value for `$scope.featureType`; it should equal 'gene'.

**Comment by kimrutherford** [comment]
> could you try to replicate this on your Canto version?

I'm seeing the same problem.  I haven't worked out the cause yet.

**Comment by kimrutherford** [comment]
This a bit weird but I think it's OK.  `$scope.featureType` comes from the config rather than the annotation.  It seems like the feature-chooser controller is called even if it's not shown in the dialog and `$scope.featureType` defaults to gene.  After the changes in https://github.com/pombase/canto/pull/1769 it all seems OK: `$scope.featureType` is "metagenotype" at the right time.

**Comment by jseager7** [comment]
Since #1760 has a working solution now, I guess this counts as fixed. Closing.
