### ISSUE TITLE
Unhelpful extension message for small ontologies (i.e. dropdown menu)

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1778]
In the extension edit dialog, we should have a better message in the case where the terms are in a dropdown rather than an autocomplete.

"(Start typing a description)" doesn't make sense here:

![relation-dropdown-message-1](https://user-images.githubusercontent.com/90474/52689087-d9bedf00-2fbd-11e9-85d6-c07886166a64.png)

**Comment by ValWood** [comment]
@jseager7  could you look at this one at some point? No hurry

**Comment by jseager7** [comment]
@kimrutherford I've taken a look at this, but it seems it might be difficult to hide that extension message on a contextual basis, since the template that stores the message ([extension_relation_edit.html](https://github.com/pombase/canto/blob/100e7cf22043530564b9fe555845d43b8049e4a3/root/static/ng_templates/extension_relation_edit.html#L16)) doesn't seem to have access to the number of terms that are found: that information is only available to a child directive (`termNameComplete`).

I tried pushing the message down into the template for `termNameComplete` &ndash; so it only shows when the autocomplete appears as an `<input>` element &ndash; but unfortunately that makes the message appear everywhere the term complete does, which isn't appropriate:

![image](https://user-images.githubusercontent.com/37659591/65420846-10819100-ddfa-11e9-9ff1-ed93f1f43fd7.png)

Here's some other possible solutions, from easiest to hardest:

* Change the placeholder text to cover both possibilities: "(Type or choose a term)"

* Change the default placeholder text in the `<input>` to hint that the user should start typing a term in the text box.

* Add a callback binding on `termNameComplete` that can be used to inform the enclosing controller whether an `<input>` or `<select>` is being displayed; the enclosing template can then display its message accordingly.

**Comment by jseager7** [comment]
I'm removing the PHI-Canto label, since this doesn't apply only to PHI-Canto.

**Comment by ValWood** [comment]
Couls the message just say

**Comment by jseager7** [comment]
For now, I've decided to put the message before the placeholder for the text box:

![image](https://user-images.githubusercontent.com/37659591/65428370-30ba4b80-de0c-11e9-8ecd-d6a2c895201d.png)

There was some debate about whether to put 'Start typing a term' instead of 'Start typing'. @kimrutherford thought that 'term' was too technical, but the placeholder text for the drop-down mode uses 'Choose a term':

![image](https://user-images.githubusercontent.com/37659591/65428556-81ca3f80-de0c-11e9-92ab-9ca38657bc88.png)

So maybe it would be better to go with 'Start typing a term' as an autocomplete placeholder, for the sake of consistency? @ValWood do you have any preference?

**Comment by kimrutherford** [comment]
> but the placeholder text in the drop-down mode uses 'Choose a term'

Good point.  So maybe "Start typing a term *name*" would be consistent?

**Comment by ValWood** [comment]
Yes go with 
 "Start typing a term name"

if anyone can improve we can open a new ticket later.
