### ISSUE TITLE
new genes are not displayed unless page reloaded

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1790]
if you go into the genotype management page and add a new gene, then the new gene is not displayed unless you reload the page

**Comment by jseager7** [comment]
@kimrutherford **TL;DR:** This is because `GenotypeGeneListCtrl` depends on `organismSelectorCtrl` to reload the list of genes, and `organismSelectorCtrl` isn't loaded in single organism mode.

In order to support the selection of multiple organisms for PHI-Canto, we made the decision to have genes as a property of the organism, but `organismSelectorCtrl` is in charge of reloading the list of organisms; `GenotypeGeneListCtrl` simply gets the genes from the last organism selected by the organism selector:

```js
$scope.selectedOrganismGenes = function () {
  return $scope.getSelectedOrganism().genes;
};
```
`organismSelectorCtrl` is configured to watch the value of the last added gene (from the 'Add another gene&nbsp;...' link), and reload the list of organisms when it detects a change:
```js
$scope.$watch('lastAddedGene', function () {
  if ($scope.lastAddedGene) {
    reloadOrganisms(
      $scope.data.selectedOrganism,
      $scope.genotypeType,
      $scope.lastAddedGene
    );
  }
});
```
Unfortunately, `organismSelectorCtrl` is never loaded in single organism mode, thanks to an `ng-if` restricting it to multi-organism mode:
```html
  <organism-selector
    ng-if="multiOrganismMode"
    label="Organism"
    organism-selected="organismUpdated(organism)"
    genotype-type="genotypeType"
    last-added-gene="lastAddedGene">
  </organism-selector>
```
**So a quick fix to this is changing the `ng-if` to `ng-show`**, so the organism selector can still make its logic available without being visible, but this definitely isn't a clean solution. I'd much rather some other higher-level component had the responsibility of holding the list of genes that should be displayed (such as `genotypeGenesPanel` or even `genotypeManage`). The organism selector could notify about when the organism changes using some event service instead (since the chain of callback bindings might get annoyingly long otherwise).

**Comment by kimrutherford** [comment]
Thanks.  That fix makes sense and works for me.

Antonia, I've re-release PomBase Canto so the bug should be fixed.
