### ISSUE TITLE
annotation extension config 

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1808]
when I'm logged in I can add a gene as an extension to
 decreased intragenic meiotic recombination (FYPO:0003179

but when I'm not logged in I don't get this option

**Comment by mah11** [comment]
OK, that means Canto is handling the configuration correctly - we've made the "gene" option admin-only for the recombination FYPO terms.

IIRC, the reason was that we were worried about people plugging in reporter genes instead of "recombination near this" genes. If we've stopped worrying about that, it'd be easy to change the config.

**Comment by Antonialock** [comment]
yeah they should be able to 'do the right thing' - if they struggle and it becomes annoying we can always revert

**Comment by mah11** [comment]
ok, config changed

**Comment by Antonialock** [comment]
cheers
