### ISSUE TITLE
Internal: change LoadUtil::get_organism() to lookup by taxon ID

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1819]
If we change the name (but not the taxon ID) of an organism in the TSV organisms file and load it a second time, we get two organisms with the same taxon ID and different scientific names.  Not good.

This came up in a discussion with PHI-base where organism names sometimes need to be updated.

Need to change LoadUtil::get_organism() to treat the taxon ID not the name as the primary key.

**Comment by jseager7** [comment]
Ideally, when the scientific name for any taxon ID in the strain list is changed, Canto should amend the scientific name everywhere in the database, since this gives users a way to amend scientific names after adding them (for example, when we want to switch from an anamorph name to a teleomorph name or vice versa).

**Comment by kimrutherford** [comment]
> Need to change LoadUtil::get_organism() to treat the taxon ID not the name as the primary key.

I decided to just change the canto_load.pl script because it was less risky.  Now if you change the species name / scientific name or the common name columns it will update the existing organism rather than creating a new one.

@jseager7 is that the change you were thinking of?  The organism name is stored in just one place so changing it should change the display in all of Canto.

**Comment by jseager7** [comment]
Yes, that sounds right. Out of curiosity, what happens if the file has two rows with identical taxon IDs? For example, if the user mistypes the taxon ID when they're adding an organism.

**Comment by kimrutherford** [comment]
> Out of curiosity, what happens if the file has two rows with identical taxon IDs?

The second row will overwrite the first row.

**Comment by jseager7** [comment]
Okay. I was wondering if it would be better to warn when that's happened (if the script doesn't already) to avoid subtle bugs occurring, but we could always handle those checks further back in the pipeline &ndash; on our config repository, for example. It's probably not worth failing the script on duplicate taxon IDs since it doesn't cause any database inconsistency problems.

**Comment by kimrutherford** [comment]
I've changed the load script so that it warns about duplicate taxon IDs.
