### ISSUE TITLE
Allow combining single-allele genotypes from different organisms

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1826]
From #1818:

> Every now and then there are multi-allele genotypes that combine genes/alleles of different species.

Canto will need to know which organism to attach to the new multi-organism genotype.
eg. was a fly gene inserted into cerevisiae or vice versa?

Let's chat about this next time.

**Comment by kimrutherford** [comment]
I think this has a lot of overlap with #826.  Am I understanding that correctly?

**Comment by vmt25** [comment]
> From #1818:
> 
> > Every now and then there are multi-allele genotypes that combine genes/alleles of different species.
> 
> Canto will need to know which organism to attach to the new multi-organism genotype.
> eg. was a fly gene inserted into cerevisiae or vice versa?
The host organism is always Drosophila melanogaster.

> Let's chat about this next time.
Sounds good

**Comment by vmt25** [comment]
> I think this has a lot of overlap with #826. Am I understanding that correctly?
It is related but different.
Anyways, at a first glance it seems to have been fixed by the original #1818 ticket - I managed to make a phenotype annotation to a mixed species genotype (https://curation.pombase.org/flybase-test/curs/33dac4236dd1bfdb/feature/genotype/view/14)
(apologies - working on Kim's test sessions and pretending to be him)


The way FlyBase handles interspecies complementation is by phenotypic genetic interactions
e.g.: a Dmel mutant gives phenotype A, which is suppressed by a mouse/cerevisiae ortholog transgene

This kind of relational genetic interactions are complicated and should be discussed and left for later discussion/ticket

FlyBase also includes intra-species complementation which, from reading #826, seems to be the same as PHI-Base's complementation annotation.
Again, this should prob be left for later discussion/ticket.

**Comment by kimrutherford** [comment]
> I managed to make a phenotype annotation to a mixed species genotype

At the moment it's not always going do the right thing.  The organism referenced by the new multi-allele genotype won't be consistent.

**Comment by kimrutherford** [comment]
We decided the solution is to set the organism of all genotypes to Dmel while loading.  Then we don't have to worry about mixing organisms.

**Comment by kimrutherford** [comment]
> We decided the solution is to set the organisms of all genotypes to Dmel while loading. Then we don't
> have to worry about mixing organisms.

That's done now.  The load script ("canto_add.pl") now has a taxon ID argument to set the organism of all genotypes.
