### ISSUE TITLE
Add a quick option to remove genes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1841]
From #1840:

> Also a quicker option to remove genes but it needs to be very clear that you are removing it
> (including all annotations to it)

**Comment by jseager7** [comment]
Maybe this could follow a similar solution to https://github.com/pombase/canto/issues/1830#issuecomment-484318386, where a 'Delete genes' link on the Genotype Management page could display a modal with a checklist of genes &ndash; then multiple can be selected and deleted in one go, with a warning shown if any of the selected genes have annotations.

Another option is to add a 'delete' icon (like a cross) to each row of the gene picker. However, users might be more likely to click that by accident, or might not need to remove genes often enough to warrant making it that easy to remove a gene.

(I'm assuming this change relates to the Genotype Management page.)

**Comment by ValWood** [comment]
There. is already an option to delete genes vis checking checkboxes. Am I missing something?

**Comment by ValWood** [comment]
Adding  "low priority' until I know what it is.

**Comment by ValWood** [comment]
but you can always delete any unwanted genes at the end. 
I'm going to close this as I don't think it is necessary to be able to delete genes from the genotype management. I don't think we really need to do this for unused genes. I tend to leave genes that were mentioned I the paper , they are still valid and they might be used by other annotation. types. 

Adding the wrong gene is an edge case because normally you would spot that earlier.

Closing unless it is re-reported as an issue.
