### ISSUE TITLE
Unable to use 'copy and edit' annotation in PHI-Canto

### ISSUE THREAD

**Issue by CuzickA** [pombase/canto#1856]
I am trying to copy and edit a pathogen phenotype and encountered the following error message

![image](https://user-images.githubusercontent.com/11753634/57375346-19e4c680-7195-11e9-87ee-8bd7aaa9b4ec.png)

I tried to edit the 'term name' and the 'comment'

**Comment by kimrutherford** [comment]
Hi. Unfortunately, I can't reproduce the problem here.

@jseager7 could you send me a copy of your data directory and config files? Firefox Send (https://send.firefox.com/) might be a good way to do that.

Cheers.

**Comment by kimrutherford** [comment]
Hi Alayne.  James sent me a copy of the database files for your Canto and I can now produce the problem locally.  I don't have a fix yet but I'll work on it tomorrow.

**Comment by kimrutherford** [comment]
Hi.  This is happening because pathogen_phenotype and host_phenotype have the same underlying namespace/ontology (single_organism_phenotype) and the annotation edit code couldn't cope.  I think I've tracked down the problem and I've committed a fix.

@jseager7 could you give it a go next time you're in the office?  Cheers.

**Comment by CuzickA** [comment]
Thanks for looking into this @kimrutherford

**Comment by jseager7** [comment]
Thanks for the reminder about this. It's already fixed, I just forgot to close the issue.
