### ISSUE TITLE
additional "allele types"

### ISSUE THREAD

**Issue by CuzickA** [pombase/canto#1862]
New alleles types required for curating https://github.com/PHI-base/curation/issues/22
currently select 'other' and then add
1. 'transformant'
2. 'genomic deletion including X' (where X is the gene name)
3. 'presence unknown'

In the future the 'transformant' alleles may be migrated over to a new type of complementation allele

Moving this info over to this tracker from https://github.com/PHI-base/curation/issues/5 as suggested by @ValWood

**Comment by ValWood** [comment]
1.

This is the situation where the avirulant  strain has a putative effector from a virulent strain expressed.

Its kind of a complementation but this would make pHI-cant very complicated if we  needed to be able to include complementation in a phenotype, and a  multigene phenotype.

A pragmatic solution is an allele type "transformant" for transfection of  a variant from a closely related strain (which is often equivalent to mutating a couple of residues).

So it would be useful to add a class of allele to PHI-Canto  "transformant"

with the prompt "Strain-gene"

**Comment by ValWood** [comment]
2. will be handled by FlyBase options. We will follow that.

3. We will continue to use "other" for this for the time being

**Comment by jseager7** [comment]
@ValWood So will this work similarly to what happens when you make a physical interaction annoation, where you pick an interacting gene (see below) &ndash; except in this case you want to be able to pick a gene from another strain?

Also, would the strains always be from the same organism as the gene initially selected for the allele, or might there be cases where the _strain gene_ is from a different organism?

@kimrutherford Will adding a new allele type require database changes?

- - -

![image](https://user-images.githubusercontent.com/37659591/59434860-43bc8900-8de4-11e9-8965-47cf3c8d7698.png)

**Comment by ValWood** [comment]
No this is in a different place.
I'm assuming it is configurable somewhere. When we create an allele there are a number of allele "tyes" to choose from:

![allele types](https://user-images.githubusercontent.com/7359272/59438635-cbf25c80-8deb-11e9-823f-7e50c1d17157.jpg)

We want additional "types" to be available for PHI-Canto. There should not be much to change except the  menu item, and a text prompt how to consistently describe the "type".

**Comment by jseager7** [comment]
> No this is in a different place.

Sorry, I realised where it should go at the time, I just used an image of the annotation type because it seemed similar to what you were describing.

It looks like the allele types are stored in `canto.yaml`. Here's an example of the fields that are configurable:

```yaml
  - name: nonsense mutation
    export_type: nonsense_mutation
    show_description: true
    description_required: true
    allow_expression_change: true
    expression_required: true
    allele_name_required: false
    placeholder: 'e.g. aa123->stop, aa1299->amber'
```
So for the transformant the `name` and the `export_type` is obvious enough, but I might need you to tell me the settings you want for the other options &ndash; e.g. if you want a description required, expression required, and so on.

Does that cover what you need?

**Comment by ValWood** [comment]
Yes that's the spot.
So  tomorrow @CuzickA  and I can  provide   the descriptions.  I  think we discussed already so they may be in tickets on the curation tracker somewhere...

**Comment by ValWood** [comment]
Val to add configs

**Comment by ValWood** [comment]
name: transformant
    export_type: transformant
    show_description: true
    description_required: true
    allow_expression_change: true
    expression_required: true
    allele_name_required: false
    placeholder: 'add strain-gene of transformed gene e.g. (sn100-Tox1A1)'

**Comment by ValWood** [comment]
FOr now we contrained this ti smae species. This means people will need to get in touch for a different organims. This will probably be done with the complementation iption longer term, but for now we can do the within species examples, AND importantly use this in multi species genotypes (which is not possible with complementations).

We are hoping that complementation by an exogenous species can be restricted to single-species phenotypes then this will all be Ok

**Comment by jseager7** [comment]
Okay, I'll test this config on my local copy first, and if that works then I'll deploy it on both servers.

**Comment by jseager7** [comment]
@ValWood Just one more question: where do you want this new allele type to appear in the list? Currently it's at the bottom, but I think it makes more sense for the allele type 'other' to be the last in the list.

Here's how the list looks:

![image](https://user-images.githubusercontent.com/37659591/65422168-a1a63700-ddfd-11e9-9895-b459806a6de2.png)

**Comment by ValWood** [comment]
yes one above "other' please

**Comment by jseager7** [comment]
The transformant allele type is enabled on both servers now. Feel free to re-open this issue (or open a new issue) if you notice any problems. Closing.

**Comment by jseager7** [comment]
Actually, reopening, since this issue mentions more allele types than transformant.

**Comment by ValWood** [comment]
'genomic deletion including X' (where X is the gene name)

is going to be tricky. I  don't think FlyBAse will help because they preload genotypes, they are not  creating them.

We want to attach the genotype to the gene of interest,  but in some cases the extent of the deletion is not reported.

Perhaps we can do this:
name: genomic deletion including X' (where X is the gene name)
export_type:  genomic_deletion_including_X
show_description: true
description_required: true
allow_expression_change: false
expression_required: false
allele_name_required: false
placeholder: 'genomic deletion including X' (where X is the gene name)'

(is it possible to interpret X as the gene in question in the menu and  text prompt?)

**Comment by jseager7** [comment]
I don't think it's possible to use placeholders like that in our configuration. What might be more tractable is to name the allele type generically, like 'genomic deletion including gene', and then add the gene name in the description of the allele?

**Comment by ValWood** [comment]
OK so it isn't possible to make X a variable and insert the gene name? or does this refer to something else?

If the former, we will need to think of more appropriate wording.

**Comment by jseager7** [comment]
> so it isn't possible to make X a variable and insert the gene name?

It's not directly possible with the configuration format we're currently using. YAML (the file format we use for our config files) doesn't really support using variables from outside of the config file.

Having said that, I might be misunderstanding what you need here. Do you want an allele name that is dynamic, in the sense that you can pick any gene in the curation session to replace the placeholder (variable) when you create the allele? Or were you planning to template 'genomic deletion including [gene]' for every relevant gene in advance (meaning, having them already instantiated as allele types in the config file)?

It might be possible to load the allele name with a placeholder denoting the type of value to be substituted, like this:

```yaml
- name: genomic deletion including {{gene_name}}
  export_type: genomic_deletion_including_{{gene_name}}
  show_description: true
  description_required: true
  allow_expression_change: false
  expression_required: false
  allele_name_required: false
  placeholder: genomic deletion including {{gene_name}}
```

But Canto would still need new logic to substitute in the gene name when the allele is created, and this solution feels a bit brittle to me.

@kimrutherford I'm guessing Canto currently has no way to easily support dynamic allele names?

**Comment by ValWood** [comment]
I was thinking only for the gene for which the allele was being created.

So maybe we can think of slightly better text instead.
what we are trying to convery is "genomic deletion including this gene"

**Comment by jseager7** [comment]
In the latest meeting we decided that 'genomic deletion including gene' could be handled (for now) with the 'Other' allele type plus a comment. It's already been decided that the 'presence unknown' allele type will be handled by the 'Other' allele type, so I don't think there's anything left to do on this issue.

Closing now, feel free to re-open if anything else comes up.
