### ISSUE TITLE
Add a link to the genotypes page from here:

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1896]
![access to genotypes page](https://user-images.githubusercontent.com/7359272/58383703-cadec400-7fd1-11e9-85c7-42425063a024.jpg)

I often want to add a genotype from the gene page. 

In fact if I am curating a complicated paper with lots of genotypes I often need to go to the gene page view to see only the ones I have already added for a specific gene.

To do this I need to go back tot he summary and then to the genotype page. I think it would be useful to have a link to 
"genotype management"  under the genotypes list (empty here), so you can go directly to add more.

It doesn't seem a lot, but it  could add many  extra clicks  per session...

**Comment by kimrutherford** [comment]
The "Multi allele phenotype" link goes to the genotype management page.  But I agree that that's not the best place for it.

**Comment by ValWood** [comment]
So I'm suggesting a direct  link under
"genotypes for cut14 in this session"

**Comment by kimrutherford** [comment]
OK, I've moved the link and renamed it to "Genotype management".

**Comment by jseager7** [comment]
@kimrutherford You might want to restrict this link to not show in pathogen-host mode for now, since that mode should never navigate to the standard `genotype_manage` view. This can be fixed as long as we can get data back on the organism that corresponds to the gene. I'm happy to look at fixing it, since I fixed the other bugs we had related to this problem previously (on the genotype edit view and so on).

**Comment by kimrutherford** [comment]
> You might want to restrict this link to not show in pathogen-host mode for now

Thanks.  Good point.

I've disabled it in pathogen-host mode but I like your suggestion of making a link to the pathogen and host genotype management pages depending on which gene page we're on.  That's low priority though as it's just a shortcut.

**Comment by jseager7** [comment]
This is more complicated than I expected, since it looks like `gene_page.mhtml` is a Mason template. All the previous pages where I fixed this problem were AngularJS templates. The way I see it, I'd either have to wrap the Genotype Management link in an AngularJS component (so I can re-use the existing logic), or I'd have to re-implement the solution in Perl &ndash; neither of which are particularly appealing.

I guess the 'best' option would be to convert the whole page to AngularJS, but that's surely going to be a lot more work than the other two options. If it's something that's going to need doing anyway, I'd be happy to try at some point.

**Comment by kimrutherford** [comment]
> I'd either have to wrap the Genotype Management link in an AngularJS component

That's not too much of a pain.  I recently did it for `finished_publication.mhtml` and there changes were mostly just:
```
 $no_annotation_reason => undef
 </%args>

-<div id="curs-pub-finished">
+<div ng-controller="FinishedPublicationPageCtrl" id="curs-pub-finished">
 <p>
 Thank you for your contribution<% $contrib_destination %>.
 You curated <% $gene_count %> <% $gene_count == 1 ? 'gene' : 'genes' %> for
```
and
```
+var finishedPublicationPageCtrl =
+    function ($scope, $uibModal, CursSettings) {
...
+    };
+  };
+  
+canto.controller('FinishedPublicationPageCtrl',
+                 ['$scope', '$uibModal', 'CursSettings', finishedPublicationPageCtrl]);
```

Once there's a controller you can do any Angular stuff you like in the template HTML.

**Comment by kimrutherford** [comment]
I've just looked at this again and realised that the gene page already has a controller so ignore what I said about that.  :-)

I think the best plan (although it's a bit of work) is to create directive to show genotype management links and replace these lines:

https://github.com/pombase/canto/blob/ab361bc0674e4eeae1de125dc635182c3b12aa9f/root/curs/front_gene_section.mhtml#L62-L76

then we could re-use the directive in the gene page.

**Comment by ValWood** [comment]
What is required from curators here? I'm not sure...

**Comment by kimrutherford** [comment]
> What is required from curators here? I'm not sure...

I don't think there's anything to discuss.

@jseager7 it's not high priority but could you add this to your list to issues to work on?

**Comment by jseager7** [comment]
I've made an attempt at this. I ended up trying a slightly different solution, where instead of having a list of links, I've added directive that bundles the back button with a forward button that links to Genotype management:

![image](https://user-images.githubusercontent.com/37659591/64346983-10585780-cfeb-11e9-9668-4bc11e2c9ecf.png)

This is more consistent with how the navigation on the Genotype management page displays. The directive takes a binding called 'role' that it uses to decide which genotype page to link to (pathogen, host, or normal). This means that if you're on a host gene, you get linked to host genotype management, and so on. In single and multi organism mode you go to the standard Genotype management page. I did this because I wasn't sure if there was much point linking to the 'opposite' genotype page in pathogen-host mode (linking from host management to pathogen management and vice versa).

This solution works fine for the gene page, since we can get the organism's role using the following code:

```pl
$gene->organism_details()->{pathogen_or_host}
```
Unfortunately, when I try to do the equivalent thing on the genotype page:

```pl
$genotype->genotype_type()
```

I get the following error:

`[error] Couldn't render component "curs/genotype_page.mhtml" - error was "Can't call method "lookup_by_taxonid" on an undefined value at lib/Canto/CursDB/Genotype.pm line 390.`

And this is seemingly because I'm not supplying a config argument that the subroutine needs:

```pl
sub genotype_type
{
  my $self = shift;
  my $config = shift;

  my $genotype_organism = $self->organism();

  my $org_lookup = Canto::Track::get_adaptor($config, 'organism');
  my $organism_details = $org_lookup->lookup_by_taxonid($genotype_organism->taxonid());

  if ($organism_details->{pathogen_or_host} eq 'unknown') {
    return "normal"
  } else {
    return $organism_details->{pathogen_or_host};
  }
}
```

@kimrutherford The question is, how should I go about supplying a value for the `$config` argument for this subroutine?

**Comment by kimrutherford** [comment]
> Unfortunately, when I try to do the equivalent thing on the genotype page:
> $genotype->genotype_type()

Is that in genotype_page.mhtml?  If so the Config is available via the Catalyst context object "$c" which is available in the .mhtml files.  So you should be able to called genotype_type() like:

    $genotype->genotype_type($c->config())

Does that help?

**Comment by jseager7** [comment]
> Does that help?

Yes, that's what I needed, thanks. I've amended the PR with a commit that implements the changes to the genotype page.
