### ISSUE TITLE
Write a script to remove unused strains

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#1899]

**Comment by kimrutherford** [comment]
I've added a script to remove unused strains.  I've tested locally but I suggest doing a data directory backup before trying this.  The script doesn't have any arguments.

`./etc/remove_unused_strains.pl`

Please let me know if you have problems.

**Comment by ValWood** [comment]
When you say "remove unused strains" where does it remove them from? 

Is this the single allele strains that are not used to construct multi allele genotypes? or just the ones that are not used at all.

(it's just that if we know the strain exists it is useful to store them because they will likely be used at some point, and should really be used somewhere to record the phenotype  for a multi-allele phenotype comparison)

**Comment by kimrutherford** [comment]
The script removes strains that were loaded from the CSV file but that aren't used in any sessions.  This is to clean up the PHI-Canto database before loading the list of strains from PHI-base.

**Comment by ValWood** [comment]
got it.
