### ISSUE TITLE
Canto URLs have spurious forward slashes

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1907]
I think this problem's been around for a while now, but it might be getting worse. On both the PHI-base servers, Canto has two extra forward slashes after the domain name on its homepage URL. Other links have one extra forward slash.

`https://canto.phi-base.org///curs/13842afb0a578560`

(Note that I just made up the curation session ID here.)

The bug doesn't cause any adverse effects as far as I can tell, it just looks odd. Pombase's Canto is affected too, only not on the homepage for some reason:

`https://curation.pombase.org/demo//curs/fe878952f8154adb`

**Comment by kimrutherford** [comment]
Could you attach your Apache configuration?

**Comment by jseager7** [comment]
Which configuration files specifically? Do you want everything in the `sites-enabled` directory?

**Comment by kimrutherford** [comment]
> Which configuration files specifically?

I'm not sure.  :-)

Could you send an archive of the whole Apache conf directory?  Maybe using send.firefox.com?

**Comment by jseager7** [comment]
> Could you send an archive of the whole Apache conf directory?

Okay, I've done that.

**Comment by kimrutherford** [comment]
Thanks.

The problem is probably this line:
`RequestHeader set X-Request-Base /`

The example in the docs don't have a slash at the end:
https://metacpan.org/pod/Catalyst::TraitFor::Request::ProxyBase

The docs also recommend a full URI so maybe try:
`RequestHeader set X-Request-Base https://canto.phi-base.org`

**Comment by jseager7** [comment]
Okay, that change gets rid of one extra space, thanks. Unfortunately, we still have one more space that appears on the summary page on all versions of Canto, for example:

```
https://demo-canto.phi-base.org//curs/df72946dce1db734
```
Note that this is _only_ on the summary page. All the other pages that I've checked seem to be fine.

**Comment by kimrutherford** [comment]
Hi James.  I can't get to that page: https://demo-canto.phi-base.org/curs/df72946dce1db734

I get "Page not found: curs/df72946dce1db734"

**Comment by jseager7** [comment]
Oh, sorry, I just made that link up. Here's an actual session:

https://demo-canto.phi-base.org//curs/dfd6363574e65f68

**Comment by kimrutherford** [comment]
I can't see any links with a double slash on that page?

**Comment by jseager7** [comment]
Does the URL for that page have a double slash (meaning the one in your browser address bar)? The bug might be browser-specific, which would be weird.

**Comment by jseager7** [comment]
I've just checked this on another browser on another device (Safari on iOS), and the URL in the address bar when I'm on the summary page still shows one extra slash after the domain name.

**Comment by jseager7** [comment]
I guess I should also clarify that I'm entering the curation session using the Paper Lookup form on the front page.

**Comment by kimrutherford** [comment]
Ah, got it.  I get the same thing in my local dev Canto.  It's because of:
https://github.com/pombase/canto/blob/f67b743987c16248c8614fc17549c4ad71e331f9/root/head.mhtml#L30

The "uri_for()" method uses the "X-Request-Base" to construct URLs.  I think that a bunch of things will break if we change this.  (I just tried removing the trailing in application_root and Canto failed quickly).  We can chip away at the issues though.

If you'd like to try you could change that line to:
```javascript
var application_root = '<% $c->uri_for('/') =~ s|/$||r  %>';
```

The `=~ s|/$||r `  line noise removes any trailing slash.

I tried this instead of the line noise but it didn't do what I hoped:
```javascript
var application_root = '<% $c->uri_for('') %>';
```

(The single quotes within single quotes look wrong but the Mason `<% ... %>` bit is processed first)

**Comment by jseager7** [comment]
I tried making that change on my local copy, but for some reason it seems to prevent the annotation tables loading on the summary page. Neither the web console nor the server console show any obvious errors.  😕

**Comment by kimrutherford** [comment]
I've made a pull request that fixes that problem.  I've also fixed all the other places where I think there is an assumption that application_root end in "/".

https://github.com/pombase/canto/pull/1921

I suspect there are other places to fix so I don't think we should merge without some thorough testing.

**Comment by kimrutherford** [comment]
I've merged the pull request.  Does it fix the extra slash?

**Comment by jseager7** [comment]
Yes, that's fixed the issue, thanks. Closing now.
