### ISSUE TITLE
add ability to add or edit the comment to curators in approval phase

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1917]
I always have to reopen the session to amend the comment, would be nice to be able to do this in approval mode (we use it to record changes to sessions)

**Comment by ValWood** [comment]
Yes this would be useful. There is a ticket about this somewhere though so it is a duplicate.

I would also like to see the spacing preserved so it is easy to see individual comments (currently they all run together). I'll add this to the existing ticket.

**Comment by ValWood** [comment]
https://github.com/pombase/canto/issues/635
let's keep this ticket. It's clearer what we need. I presume this is quick so I won't make it low priority because it is useful.

**Comment by kimrutherford** [comment]
I've added an "Edit ..." link for admin users.  Could you give it a test?

**Comment by kimrutherford** [comment]
I've changed the link on the publication page so that if you're logged in as admin you'll see:
![edit-message-for-curators-1](https://user-images.githubusercontent.com/90474/58932019-0f2e4900-87b6-11e9-8df9-92bcc5db2571.png)
![edit-message-for-curators-2](https://user-images.githubusercontent.com/90474/58932025-17868400-87b6-11e9-9b1a-c43b32998827.png)

**Comment by ValWood** [comment]
The comment I was referring to  last night, that I can no longer locate appeared in a box here when I first viewed the submission. I think it was a red box? This comment seems to disappear, but could be preserved in the comment box perhaps?

![takashi comment](https://user-images.githubusercontent.com/7359272/58945129-30be0f00-877b-11e9-8fc4-dba95f119a6d.jpg)

**Comment by kimrutherford** [comment]
> The comment I was referring to last night, that I can no longer locate appeared in a box here when I first
> viewed the submission. I think it was a red box? This comment seems to disappear, but could be
> preserved in the comment box perhaps?

I don't know of a red box.  Do you want to be able to view the message to curators when doing session approval?

**Comment by ValWood** [comment]
I can no longer see the message in question. It is the message that the user adds if they submit the session without making any annotation. I'll try to recreate the issue myself once I finish this session.

**Comment by kimrutherford** [comment]
I've fix it so that the "Edit message to curators" link is visible in approval mode so you'll be able to view it that way.

**Comment by kimrutherford** [comment]
> I would also like to see the spacing preserved so it is easy to see individual comments (currently they
> all run together).

I think that's fixed now.

**Comment by ValWood** [comment]
So maybe I imagined this and the message appeared as a standard message to curators.Anyway this has disappeared so I think it mught be a casualty of the "curator feedback changes"

I just made one of the  comments in question in a test session:

![test](https://user-images.githubusercontent.com/7359272/58969860-47cb2400-87b0-11e9-910f-a5d65535bd29.jpg)


in the 'other field' where people need to type to say why they did not curate.I think this must have previusly gone in the comments fild and I probably saw it here:

Message sent to the curators:

when I opened the session.

anyway this text no longer appears here, so I think existing text maybe disappeared?

We don't crucially need  the old comments if we lost them, but we should  make sure new ones are  accessible  for future...

**Comment by kimrutherford** [comment]
> So maybe I imagined this and the message appeared as a standard message to curators.Anyway this 
> has disappeared so I think it mught be a casualty of the "curator feedback changes"

Ah, I didn't realise you were thinking about the message for when they choose "Other".  That's stored separately.  Or at least it should have been but the code to do that was broken.  It looks like it has never worked properly.  It was storing just the text "Other" and not storing the actual message.

It should be better now so that the user will see something like this on the "finish" page:

![no-genes-other-reason-fix-1](https://user-images.githubusercontent.com/90474/58991398-447d7a00-883c-11e9-9d57-694972de45e0.png)

And in approval you should see this:

![no-genes-other-reason-fix-2](https://user-images.githubusercontent.com/90474/58991410-4e9f7880-883c-11e9-9543-83d9cde46ea0.png)

**Comment by ValWood** [comment]
Yes, I think I saw it like that in the session in question. But I can no longer see it...(it disappeared)

**Comment by ValWood** [comment]
I'm calling this a bug. It isn't major but I think the messages disappear. let me know if you want to discuss...

**Comment by kimrutherford** [comment]
After the fix it works for me.  Can you let me know if you see it in another session?

**Comment by ValWood** [comment]
OK will open a new ticket if I see it next time.
