### ISSUE TITLE
Use 'Enter' and 'Esc' keys to go quicker between menu pages while doing annotations?

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#1931]
(Topic for discussion)
Would it be possible to use 'Enter' and 'Esc' keys to go quicker between menu pages while doing annotations?

This akin to the saving document 'menu':

![Screenshot 2019-06-11 at 11 23 31](https://user-images.githubusercontent.com/33721108/59264631-6e1f1280-8c3b-11e9-99a2-c75be4defcdd.png)

This would make things faster, especialy when one does not want to pick a lower ontology term or add qualifiers.

**Comment by ValWood** [comment]
This sounds like a plan. Note that also, for other curation types  if you check "advanced mode"
"quick add" links appear next to gene names.
At present we do not have a "quick add " option for phenotypes (because genotypes need to be created first). I think we could have these  if genotypes exist, especially in advanced mode).

Will discuss further on PomBase side and add to this ticket.

**Comment by vmt25** [comment]
Closing because not a priority - Keyboard shortcuts do most of the job
