### ISSUE TITLE
Split genotype tables into haploid and diploid sections

### ISSUE THREAD

**Issue by mah11** [pombase/canto#1941]
Right now, genotypes get sorted into three tables on the genotype management page. But there are actually four, not three, kinds of genotype:

- haploid single locus
- haploid multi-locus
- diploid single locus
- diploid multi-locus

I think it would be good to have one table for each of these. It does not make sense to group haploid and diploid multi-locus genotypes (as it's doing now), especially if we continue to have separate tables for single-locus haploids and diploids. (It would be equally logically consistent to lump everything, but way too confusing to use.)

Aside: Both single-locus tables should offer the "combine selected" option, and both haploid genotype tables should offer the "create diploid" option (per #2012).

**Comment by jseager7** [comment]
> (It would be equally logically consistent to lump everything, but way too confusing to use.)

Not sure if this has been discussed already, but one idea that @kimrutherford and myself were considering was to have one table for all these genotypes, but having subheadings in the table to distinguish haploids, diploids, etc. It was simpler to get the table displayed without doing this, which (I think) is why we now have multiple tables, but this is how it could've looked otherwise:

![combined-genotype-table](https://user-images.githubusercontent.com/37659591/59348597-6b8ded00-8d0f-11e9-8332-f9162f5e2db7.PNG)

I think it should be possible to repeat the column headings for each section as well, if that would make things clearer for long tables.

**Comment by ValWood** [comment]
I slightly prefer to keep to two tables unless there any reasons not to.
Aesthetically better because the 4 tables will be multiple shapes and sizes.
In this case we might need an explicitly "haploid" header row too.

However, because PomBase use diploids so infrequently  PHIBase and FlyBase might have stronger preferences.

I'm sure there are existing tickets somewhere about this issue that should be linked to this one.

**Comment by mah11** [comment]
I could live with two tables or four, but the three it's got now really is silly.

**Comment by kimrutherford** [comment]
> It does not make sense to group haploid and diploid multi-locus genotypes

If there is a multi-locus genotype that's a haploid+diploid, which table should it go in if we split the multi-locus table?

**Comment by mah11** [comment]
> If there is a multi-locus genotype that's a haploid+diploid, which table should it go in if we split the multi-locus table?

I guess I'd put it with diploids, on the assumption that you'd only build it that way if the organism was diploid except for a locus or two of interest. It's a bit arbitrary, but probably not too bad, since I also have the impression that genotypes like that will be rare.

I've never thought I would use the diploid-creation system for the cases where an extra copy of one gene is added to a haploid yeastie.

**Comment by ValWood** [comment]
related
https://github.com/pombase/canto/issues/1932

**Comment by ValWood** [comment]
@jseager7  I thought there was an older ticket  with the table merge mock up?
Did I imagine this? I can't find it...

**Comment by jseager7** [comment]
@ValWood I'm not sure. I don't remember creating a mockup of this in particular, but I did previously have the idea of representing every genotype as its own 'panel' rather than as rows in a table. I mentioned that in this comment: https://github.com/pombase/canto/issues/1520#issuecomment-400609875

The idea was mainly to reduce the use of screen width, but nobody voiced any support for that option at the time &ndash; probably because everyone still prefers to use tables.

![image](https://user-images.githubusercontent.com/37659591/59420347-a56cfb00-8dc4-11e9-8fb9-1a21714f7dd2.png)

This solution does have the advantage that it can cope better with having multiple different types of genotype, since all the panels are independent (so it doesn't matter if one panel has a field or column that the others don't have), but I admit it's a pretty drastic user interface change.

**Comment by ValWood** [comment]
James, I assigned this tentatively to you to start with. Kim can step in to help if necessary
Does that sound OK?

**Comment by jseager7** [comment]
Sure, I can take a look when I have time. Just to confirm, is the intended solution to keep the existing split between single-locus and multi-locus genotypes (two tables total), but sort the diploid alleles below the haploid alleles in each table and add subheadings to the tables above the rows where the diploid alleles begin? I think this is similar to the mockup in https://github.com/pombase/canto/issues/1941#issuecomment-501236756, just with an extra subheading to mark the haploid section of the table.

Also, out of curiosity, does PHI-Canto have a need for diploid curation yet?

**Comment by ValWood** [comment]
I imagined that PHI-Canto would need to specify diploids at some point. If not @kimrutherford  can look at this instead. I will assign to both of you then it can be whoerver gets to it first.

Your summary is accurate.

**Comment by jseager7** [comment]
The changes to the multi-locus genotype table are now ready as well:

![image](https://user-images.githubusercontent.com/37659591/113005847-bbe87000-916c-11eb-93cd-e0456ca266b0.png)

It currently classifies genotypes that mix haploid and diploid as haploid, but that problem is covered by my comment above.

**Comment by kimrutherford** [comment]
Thanks very much James.  Let me know when you'd like me to do some testing.

**Comment by ValWood** [comment]
The diploid header probably isn't totally necessary, but, because diploid alleles are much rarer you won't see it so often, and it does make the alleles very easy to locate so let's keep it.

We did discuss whether it should be possible to combine haploid and diploid. Some species do have chromosomes that are largely diploid but where the corresponding locus is absent in the homolog. So, I guess we do not want to restrict the combination completely even though we may not require it. However, it is better to classify as diploid if a diploid allele is present.

@mah11  does this make sense to you?

**Comment by jseager7** [comment]
> However, it is better to classify as diploid if a diploid allele is present.

I agree that this makes more sense than classifying as haploid. The logic used to classify the genotypes should be easy enough to amend.

**Comment by jseager7** [comment]
I've fixed the classification of genotypes with mixed haploid and diploid alleles. Now a multi-locus genotype is classified as diploid if it has at least one diploid allele.

![image](https://user-images.githubusercontent.com/37659591/113130520-125cb980-9214-11eb-904f-5846fb58ca73.png)

This should be ready for testing now, so I'll open a pull request.

**Comment by mah11** [comment]
> > However, it is better to classify as diploid if a diploid allele is present.
> 
> I agree that this makes more sense than classifying as haploid. The logic used to classify the genotypes should be easy enough to amend.

I think this will be OK as long as curators remember to use haploid genotypes for cases where an additional copy of just one gene (or a few) is present in a genotype that's otherwise haploid. Certainly a genotype with just one hemizygous locus of interest (or a few loci) should be treated as diploid.

I have no preference regarding the Alleles/Strain/Annotations subheaders.

**Comment by jseager7** [comment]
@ValWood @mah11 Are there cases in Canto where a genotype can contain two copies of the same gene at different loci? Kim Rutherford suggested the case of cdc1+[WT level], cdc1+[Overexpression] as an example of a multi-allele genotype that should be classified as single locus, but maybe this isn't a good example because a gene at the same locus presumably can't be both over-expressed and normally expressed at the same time.

The currently proposed haploid/diploid split treats the above case as a multi-locus genotype, which is maybe only accurate by accident. I wondered about cases where a gene is subject to simultaneous insertion and substitution of amino acids as a more accurate example of multiple alleles at a single locus, but this is already covered by existing compound allele types – e.g. amino acid insertion and substitution – so it wouldn't make sense to have multiple genotypes with the individual mutations: surely the mutations are part of the same genotype (or the same allele). Considering Canto technically creates genotypes instead of alleles, does that imply a genotype containing two alleles of the same gene (or at least the same gene name) is always multi-locus?

**Comment by jseager7** [comment]
Ignore the previous comment: I misunderstood how Canto was meant to be treating multiple alleles on the same gene.

**Comment by ValWood** [comment]
A very reasonable question though as this is a  hack biologically, but convenient.
