### ISSUE TITLE
Canto doesn't update terms immediately after reloading finishes

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1942]
I was running a manual reload of PHI-Canto's ontologies today, and I noticed that even after the loading script had 'finished' (in that control was passed back to the terminal), certain changes to the ontology terms weren't showing in Canto. For example, terms that had their names changed were still showing their old names in the annotation tables, and the term suggestion when selecting terms was still showing the old term names too.

After about 5 to 10 minutes, the changes actually reached the user interface, but I think this might have necessitated reloading without cache in the case of the annotation tables. Is this known behaviour? Is it an issue related to browser caching, or something else?

**Comment by kimrutherford** [comment]
In order to make Canto a bit more responsive, most of the APIs set the HTTP header `cache-control: max-age=100`.

That's done here:
https://github.com/pombase/canto/blob/78fbfa53a15faf1e98f42bf11f23207df807afcc/lib/Canto/Controller/Service.pm#L297-L298

As the comment says, it's a bit dodgy.  As you've found, the underlying data can change in that 100 seconds and the application in the browser won't know.  We could make that max-age a configuration setting if you'd prefer.  I should have done that in the first place.

**Comment by jseager7** [comment]
I think as long as we know roughly how long it takes before updates propagate to the server we can account for that when reloading.

I'm guessing this is only going to be a problem for @CuzickA, because for other users they're only likely to want to see new terms after they make a term request, in which case Canto's delay due to the caching probably isn't going to be the limiting factor &ndash; considering it takes about 30 minutes to reload the ontology list.

If we're ever able to bring the ontology loading down to under three minutes or so, then it might make sense to have the caching duration configurable. All this is assuming there aren't other disadvantages to the cache duration which haven't occurred to me (or that I haven't understood).
