### ISSUE TITLE
background duplicated when combining backgrounds of diploids

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#1947]
here I am combining two diploids as checked
![Screenshot 2019-06-13 at 08 59 04](https://user-images.githubusercontent.com/12727506/59414566-a4829c00-8db9-11e9-9a01-6a865b35602a.png)

but end up with a duplicated background

![Screenshot 2019-06-13 at 08 59 16](https://user-images.githubusercontent.com/12727506/59414592-b19f8b00-8db9-11e9-9657-c2bb19bb188e.png)

maybe simplest thing is to not keep the background?

**Comment by kimrutherford** [comment]
> maybe simplest thing is to not keep the background?

I think I was going to ask about that but forgot.  It's a quick fix to not keep the background.

**Comment by kimrutherford** [comment]
Val and Midori what's your opinion of what to do with the background when merging genotypes?

**Comment by ValWood** [comment]
I guess we should suppress the redundancy?

If the starting alleles had this background then it would be correct to keep it...

**Comment by kimrutherford** [comment]
> I guess we should suppress the redundancy?

Which redundancy?

**Comment by mah11** [comment]
If the diploid single loci to be combined all have the same background, it would be safe (and convenient) to use one copy of it as the multi-locus diploid background. But it might be more consistent to omit background from multi-locus diploids in all cases, since we can't keep everything if the single-locus backgrounds differ (as Antonia's example illustrates).

When we release diploid-ing to the community, we'll have to see if there are howls of anguish about having to add backgrounds to multi-locus diploids as a separate step. If not, we could leave it indefinitely.

**Comment by ValWood** [comment]
h+/h- ade6-M20  ade6-216 h+/h- pat1-114/pat1-114

->  h+/h- ade6-M20  ade6-216 pat1-114/pat1-114

would not be incorrect if they hadn't done any further mucking around

**Comment by mah11** [comment]
Yebbut, that's not what the screenshot has. The cds1∆ / cds1∆ single locus has h+/h- ade6-M20 ade6-216 (should that be ade6-M20/ade6-216?), but the chk1∆/chk1∆ single locus background is **h-/h-** pat1-114/pat1-114.

It may also be a stretch generally to assume they hadn't done any further mucking around.

**Comment by kimrutherford** [comment]
> If the diploid single loci to be combined all have the same background, it would be safe
> (and convenient) to use one copy of it as the multi-locus diploid background.

I rolled my sleeves up to fix that but found that it's already implemented.

We should make a decision about what to do if the backgrounds are different.  It's easy to change the code to not combine the backgrounds if they differ.

**Comment by ValWood** [comment]
This  is the current behaviour so closing...
