### ISSUE TITLE
"penetrance" for PHI-Canto

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#1954]
Enable penetrance extensions  for all non-population single organism phenotype terms

**Comment by ValWood** [comment]
Check the PomBAse config file to see where penetrance and expressivity are valid/invalid

**Comment by kimrutherford** [comment]
> non-population single organism phenotype terms

Do you have the term IDs?

**Comment by ValWood** [comment]
We will need to look at which terms are valid. Possibly penetrance was excluded from the pathogen host interaction phneotypes, but it is relevant here. This is none urgent, we will try to locate the terms when I next work with Alayne.

**Comment by ValWood** [comment]
To test this we need to add penetrance to the config file for the PHIPO terms equivalent to these 2 PomBase terms to test

cell phenotype
FYPO:0000002	is_a|has_part	has_penetrance	FYPO_EXT:1000002|%	penetrance	proportion of the population that shows the phenotype (can be quantitative or qualitative)	0,1	user

and

sterile
FYPO:0000280	is_a	has_penetrance	FYPO_EXT:1000002|%	penetrance		0,1	user
(if there is an equivalent term)

(Penetrance is not applicable to population phenotypes)

For the pathogen-host interaction phenotypes I think we can configure

is_a: PHIPO:0000402 ! individual organism phenotype
seems like a good candidate for configuration. 

James could you add these at some point and we can test?

Thanks
Val

**Comment by jseager7** [comment]
Here's the proposed configuration for these terms:

### Cell phenotype (PHIPO:0000034)

domain ID | subset relation | extension relation | range ID | Canto display text | Help text | cardinality | role
-- | -- | -- | -- | -- | -- | -- | --
PHIPO:0000034 | is_a\|has_part | has_penetrance | FYPO_EXT:1000002\|% | penetrance | proportion of the population that shows the phenotype (can be quantitative or qualitative) | 0,1 | user

### Sterile (no term)

domain ID | subset relation | extension relation | range ID | Canto display text | Help text | cardinality | role
-- | -- | -- | -- | -- | -- | -- | --
PHIPO:XXXXXXX | is_a | has_penetrance | FYPO_EXT:1000002\|% | penetrance | proportion of the population that shows the phenotype (can be quantitative or qualitative) | 0,1 | user

We currently don't have a term in PHIPO for sterile / sterility, so @CuzickA will have to create one or adapt the existing FYPO term.

### Pathogen-host interaction phenotypes

@ValWood I'm not really sure how to understand the following:

> For the pathogen-host interaction phenotypes I think we can configure
> is_a: PHIPO:0000402 ! individual organism phenotype

I'm presuming this means enabling _has_penetrance_ on all children of the term 'individual organism phenotype', but this term isn't a child of 'pathogen host interaction phenotype' (PHIPO:0000001); rather, it's a child of 'single species phenotype' (PHIPO:0000002). Presumably that means no terms from 'individual organism phenotype' will show up when making pathogen-host interaction phenotypes. Is this what you meant?

I've shown the extension configuration below, anyway. I'm also not sure if the subset relation should be _is_a_ or _is_a|has_part_ in this case.

domain ID | subset relation | extension relation | range ID | Canto display text | Help text | cardinality | role
-- | -- | -- | -- | -- | -- | -- | --
PHIPO:0000402 | is_a | has_penetrance | FYPO_EXT:1000002\|% | penetrance | proportion of the population that shows the phenotype (can be quantitative or qualitative) | 0,1 | user

**Comment by ValWood** [comment]
That's all fine. I don't yet know where the pthogen-host interaction branch can be configured. We would need to look at the terms to see if they make sense. My immediate feeling is that penetrance is not appropriate for many of these. However it is appropriate for cell level phenotypes. Don't worry about sterile. If it was there we could add but we will not add until required.

@CuzickA  may remember the pathogene -host interaction phenotype where this came up.

**Comment by jseager7** [comment]
Okay, in that case I'll enable the above configuration on both Canto servers.

**Comment by jseager7** [comment]
@ValWood something else I forgot to ask: our current extension config has the _has_penetrance_ extension enabled on _population phenotype_ (PHIPO:0000509). Your earlier comment said that "penetrance is not applicable to population phenotypes", so should I remove the extension from this term?

**Comment by ValWood** [comment]
For us (PomBase), population phenotypes are those that can *only* be observed if you  are looking at the population. Penetrance is how many individuals within a population have a particular phenotype, so we think that if you can only see the phenotype by looking at the population, you can't say anything about penetrance.

For PomBase, w think  it's better to create at the level of the individual organism if we can.   This probably applies to you too. So if plants have 'short stature'  you would observe this at the level of the individual and then say the % of the population it applied to.

There may be phenotypes which are population level for us but not for you, and it is possible you may want penetrance on some population terms, so w won't rule it out.

But for now I think it is better  not to allow, so that we can add in the appropriate places as required

Expressivity, (now severity) is allowed on population terms.

**Comment by jseager7** [comment]
Okay, thanks for clarifying. PHI-Canto has both penetrance and expressivity / severity enabled on population phenotypes, so I'll leave that as it is.

**Comment by ValWood** [comment]
Apologies,  I wasn't clear. I think we  should exclude penetrance from population phenotypes and only add to specific branches/terms if it is found to be required.

**Comment by jseager7** [comment]
Okay, I've amended our configuration to exclude penetrance from population phenotypes now.

**Comment by jseager7** [comment]
The new extension config is active on the demo server now, and it should be active on the production server once the ontologies reload overnight. There's just one problem so far, which is that certain terms show the 'penetrance' extension twice, probably because the domains for both has_penetrance_ extensions overlap:

![image](https://user-images.githubusercontent.com/37659591/64349817-8068dc80-cfef-11e9-881a-01b4cab15d58.png)

I seem to remember there's some way to take a union or intersection of term hierarchies in the extension config (I think we need a union here?) only problem is the _individual organism phenotype_ and _cell phenotype_ domains aren't using the same subset relation (_individual organism phenotype_ isn't using _has_part_), so applying the extension to a union should mean that _has_part_ starts applying to _individual organism phenotype_ too. Is there any way around this?

**Comment by ValWood** [comment]
we can probably close and open new tickets if this needs tweaking

**Comment by jseager7** [comment]
I'm reopening this since @CuzickA wants to have penetrance enabled for all pathogen-host interaction phenotypes, in addition to individual organism phenotypes. I'm also not sure we need 'cell phenotype' as a separate extension row, since as far as I know, we're not using the 'has_part' relation in our logical definitions (yet). That would make the new extension as follows:

domain ID | subset relation | extension relation | range ID | Canto display text | Help text | cardinality | role
-- | -- | -- | -- | -- | -- | -- | --
PHIPO:0000001&is_a(PHIPO:0000402) | is_a | has_penetrance | FYPO_EXT:1000002\|% | penetrance | proportion of the population that shows the phenotype (can be quantitative or qualitative) | 0,1 | user

@kimrutherford I'm assuming `term&is_a(term)` is the correct syntax for a union of terms?

**Comment by kimrutherford** [comment]
> @kimrutherford I'm assuming term&is_a(term) is the correct syntax for a union of terms?

Unfortunately it's not possible to configure something like that on one line.  I think you can get what you need by having two config line, one for PHIPO:0000001 and one for PHIPO:0000402.

**Comment by jseager7** [comment]
> I think you can get what you need by having two config line, one for PHIPO:0000001 and one for PHIPO:0000402.

That's fine. I'll test this on the demo server now.

**Comment by jseager7** [comment]
This should be working on both servers now. Closing.
