### ISSUE TITLE
Annotation confirmation sometimes doesn't show evidence

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1968]
I've noticed that sometimes when confirming a metagenotype annotation (in the _Create annotation_ workflow), the cell for 'Evidence' is empty, even though experimental evidence has been selected. For example, I chose the evidence code 'Asexual sporulation assay', but it doesn't display:

![phi_annotation_no_evidence](https://user-images.githubusercontent.com/37659591/60438072-bc567e80-9c07-11e9-823b-c7266ebf131b.PNG)

However, the data is still saved correctly, and it displays in annotation tables once you finalise the annotation:

![phi_annotation_actual_evidence](https://user-images.githubusercontent.com/37659591/60438147-ea3bc300-9c07-11e9-81d8-51bc99499f86.PNG)

I've tried this with at least one different evidence code, and the same bug still happens.

**Comment by kimrutherford** [comment]
I've fixed that.  Unfortunately the small table under "You have made the following annotation" currently is different code to the main tables and gets the evidence from the config in a slightly different way.

The missing evidence was because the evidence code you picked wasn't in the main "evidence_types" configuration: https://github.com/pombase/canto/blob/fa2ad9a93a49295188a70a2c30f5642db935a7d1/canto.yaml#L1440-L1442

I've changed the code and now that isn't a problem.

The change is in the main branch.  Could you check that it works for you now?

**Comment by jseager7** [comment]
I've checked on `master` commit fa2ad9a93a49295188a70a2c30f5642db935a7d1, and the bug doesn't occur anymore with the same evidence code. Thanks. Closing now.
