### ISSUE TITLE
Don't suggest conditions that are already on the annotation

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1969]
I've noticed that Canto suggests experimental conditions even if those same conditions are already on a phenotype annotation. For example, I had the experimental condition 'high temperature' on an annotation, but Canto still suggests it, which doesn't seem very useful:

![redundant_condition_suggestion](https://user-images.githubusercontent.com/37659591/60438533-c9c03880-9c08-11e9-818e-fe4651ea15b6.PNG)

Filtering out conditions that are already on the annotation would leave us with more space to suggest conditions that the user might actually want to select. Not sure how easy this is to implement, though.

**Comment by ValWood** [comment]
It would be neat if the conditions you have used disappear. However, it's really low priority because it doesn't really cause any issues.  The conditiosn presented are just all the conditions that you already used in that session. Once you have selected a condition, you just ignore is and the list never gets very long so it isn't really a hindrance.

Adding low priority.

**Comment by ValWood** [comment]
It would need to be very quick to justify in the short term

**Comment by jseager7** [comment]
I'm going to close this, since it's not likely to become a problem in the foreseeable future, and it's not going to be quick to implement either.
