### ISSUE TITLE
Show lists of more features on admin pages

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#1976]
(Requested by @martin2urban)

Currently the admin pages can display a list of genes from every curation session &ndash; Martin was wondering if we can also offer summaries of other features, such as genotypes, and metagenotypes.

![image](https://user-images.githubusercontent.com/37659591/60672704-f0cb7400-9e6d-11e9-84ef-0d1fe64d1fbf.png)

@kimrutherford If this is likely to be a lot of work, we could look at performing these aggregations on the JSON export from Canto.

**Comment by kimrutherford** [comment]
> Martin was wondering if we can also offer summaries of other features, such as genotypes, and
> metagenotypes.

The list of genes is easy because it's just showing the rows from the `gene` table in the TrackDB.  When a gene/protein is retrieved from UniProt we keep a local copy of the details as a cache.

The genotypes and metagenotypes are only in the sessions so making a single table is more work and potentially slow.

> we could look at performing these aggregations on the JSON export from Canto.

Or do the querying in the main PHI-base database once the JSON file is loaded.

**Comment by ValWood** [comment]
I am wondering what the use case for a list of genes is in the admin interface, PHI base seems to be the logical place to query this. 

Maybe @martin2urban  wants to be able to access the genes which are "curated" in publications?
Is this something users might want to be able to do? in which case PHI-base might be a better place to enable this query. FOr Pombase this would list would just be a list of all published genes and we can get this list from PomBase. For genotypes I'm not sure how we would use the list (it would be very long- @kimrutherford  how many genotypes do we have).

Otherwise as Kim suggests, parsing from the Json might be sufficient. 

I'm not objecting, just wondering what the use case is so the best solution can be implemented.

**Comment by jseager7** [comment]
> Or do the querying in the main PHI-base database once the JSON file is loaded.

I think the reason Martin wants more summaries of data is to help with migrating PHI-base's schema to being compatible with PHI-Canto &ndash; we currently can't really load PHI-Canto curation sessions into PHI-base. I think he wants to be able to check the data that's been exported in more legible format than the JSON file.

It sounds like this is sort of out-of-scope for Canto though; we'll probably able to do this aggregation in PHI-base, and I'm sure I can script something to perform the necessary aggregation on the JSON output in the short term. I just wondered if any other curators would find more feature summaries useful, but it doesn't sound like that's the case.

**Comment by martin2urban** [comment]
I agree, more information might be good for admins/curators in the future, but I will close the ticket for now.

**Comment by ValWood** [comment]
Yes OK, if we think these will be generally useful we can add them later, but it does sound a bit out of scope for your current use case. Probably better ways to do this...
