### ISSUE TITLE
find a way to locate extant entry for an obsolete ID

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2017]
There does not seem to be a way.
I will find out, @jseager7  will provide some examples for me.

@jseager7  has automated the location of the entry in UniPark but there is no paper trail to the replacement ID

**Comment by jseager7** [comment]
@ValWood here's an example of an obsolete entry from Gibberella zeae / Fusarium graminearum (see below for a list of other entries):

[I1RA15](https://www.uniprot.org/uniprot/I1RA15) (I1RA15_GIBZE)

This particular entry was obsoleted due to its proteome becoming redundant. An explanation of UniProt's proteome redundancy process is available here:

https://www.uniprot.org/help/proteome_redundancy

The protein sequence can be looked up in UniParc by just searching for the obsolete accession ID:

https://www.uniprot.org/uniparc/?query=I1RA15

You can also check the history for any obsolete entry, which preserves some other information about gene names and so on, up until the point the entry was deleted:

https://www.uniprot.org/uniprot/I1RA15?version=*

Once you get to UniParc, the only two ways I know to locate a corresponding UniProt ID are either to BLAST the sequence, or look up the gene name and the taxon ID in UniProt: for example, given the obsolete identifier [Q59PD2](https://www.uniprot.org/uniprot/Q59PD2), and its corresponding UniParc ID [UPI000042BF9C](https://www.uniprot.org/uniparc/UPI000042BF9C), you can get the last taxon identifier and the gene name from the XML format of the UniParc ID:

```xml
<dbReference type="UniProtKB/TrEMBL" id="Q59PD2" version_i="1" active="N" version="1" created="2005-04-26" last="2016-11-30">
<property type="NCBI_taxonomy_id" value="237561"/>
<property type="protein_name" value="Uncharacterized protein"/>
<property type="gene_name" value="SPA2"/>
</dbReference>
```

You can then construct a query to lookup the gene name and the taxon ID in UniProt, as follows:

https://www.uniprot.org/uniprot/?query=taxonomy:237561+gene:SPA2&sort=score

In this case, we get just one result, which is ideal, but this normally doesn't happen. The biggest disadvantage of this query style is that you can't run them in bulk, and trying to run the queries individually with no delay is likely to get you blocked from UniProt (if you had accession identifiers, you could do a bulk lookup, but the point is we don't).

Just to be thorough, you can align this active entry with its obsolete sequence to check if they're similar: in this case, the sequences align fully:



Whether or not this truly means that the entries correspond to the same gene, I don't know.

- - -

If you want to investigate further, here's a list of various obsolete identifiers for multiple organisms:

A0A075P597
B5S9S0
A0A0G2UVN6
I1RRX7
Q5A755
Q4PCH0
A6SSN8
K8Z7I4

**Comment by jseager7** [comment]
I'm closing this in favour of https://github.com/PHI-base/curation/issues/52.
