### ISSUE TITLE
"Add note ..." link missing in single allele table row menu

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2031]
The links to existing notes are also missing.

https://curation.pombase.org/flybase-test/curs/7e6b097ab9f9fca5/genotype_manage

**Comment by kimrutherford** [comment]
Hi Vitor.

It turns out this there was a simple fix for this: log in as admin (flybase-admin@pombase.org) to see the notes and links.

I made notes admin-only because that was the easiest way to hide the notes from PomBase community curators.  I'll talk to Val and co. to check that that makes sense.

**Comment by vmt25** [comment]
At a first glance that is absolutely fine

**Comment by kimrutherford** [comment]
This issue has a "discuss" tag because of this:

> I made notes admin-only because that was the easiest way to hide the notes from PomBase
> community curators. I'll talk to Val and co. to check that that makes sense.

but I now think it's less of a problem.  In the current implementation the notes only show up if they are configured.  Val, will you be using genotype notes for PomBase Canto?  If not we can change the code so that you don't have to be in "Advanced mode" to edit and view notes.

**Comment by ValWood** [comment]
I'm not sure but I  think we have discussed for some purposes?

**Comment by kimrutherford** [comment]
> I'm not sure but I think we have discussed for some purposes?

I think so, but I couldn't remember for sure.  I'll leave this issue open with the discuss label for now.

**Comment by vmt25** [comment]
Can be closed from FlyBase's standpoint

**Comment by ValWood** [comment]
@kimrutherford Is this the same as an "allele comment"? or a "genotype comment" or neither?

**Comment by kimrutherford** [comment]
It's the same as "allele comment".  It's just named differently in FlyCanto.  We can close this as our problems with allele notes are covered by other issues.
