### ISSUE TITLE
pathogen gene appearing in host gene list

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2034]
I am adding a pathogen gene
A0A0K6FU48_9AGAM
but it is appearing in the host gene list. Why is that?
I can't see any way to change this.

**Comment by ValWood** [comment]
/curs/baeff7a059e5f6c4/

**Comment by jseager7** [comment]
I've just checked, and for some reason _Rhizoctonia solani_ [456999] is classified as a host organism in the PHI-Canto configuration files.

@CuzickA @martin2urban Is this a classification error? Would _Rhizoctonia solani_ normally be regarded as a pathogen?

**Comment by jseager7** [comment]
Note though that there currently isn't any way to change the 'role' of an organism from pathogen to host (or the other way round) in PHI-Canto's interface. This might be a case where an organism that is normally a pathogen is taking the role of a host for the experiment. We were holding off on implementing role reassignment until problems like this actually occurred.

Implementing this will probably require schema changes to the curation session databases, since currently the host / pathogen roles are statically defined in the configuration files.

**Comment by ValWood** [comment]
It should be classified as a pathogen. Could you switch?
I'll put this one on hold and try another one.

**Comment by jseager7** [comment]
I've switched the organism to be classified as a pathogen. The change will take effect once the organism lists are reloaded. I'm not sure if I can do the reload while Canto is running, but if I can then I'll do it as soon as possible.

**Comment by ValWood** [comment]
No hurry for me, I got into another paper now.

**Comment by jseager7** [comment]
This should be fixed now: _Rhizoctonia solani_ is recognised as a pathogen on my test session. Closing.
