### ISSUE TITLE
Small bug in gene "deselector"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2041]
If I have used a gene or organims in an annotation it should not be possible to 'deselect'.

this is probably the case, but here, I have used rice in a metagenotype annotation,  However, the red x is present so I could theoretically delete it (I did not try this).

![bug X](https://user-images.githubusercontent.com/7359272/65896928-13562600-e3a6-11e9-81b5-c95057b87a28.jpg)

(an unimportant aside but these x's aren't very aesthetically pleasing)

**Comment by jseager7** [comment]
I've checked this now, and fortunately Canto just errors if you try to delete an organism that was in a metagenotype. Unfortunately, the error message is vague and unhelpful:

![image](https://user-images.githubusercontent.com/37659591/65956595-a349ad80-e442-11e9-83cc-3322f1983ffb.png)

Even more unfortunate is the fact that Canto still fails to delete the organism even if it's no longer associated with a metagenotype (because the metagenotype got deleted). Seems like Canto behaves as if there are still genotypes linked to the organism. You can see a more helpful error message if you try to delete a strain.

![image](https://user-images.githubusercontent.com/37659591/65956660-cd9b6b00-e442-11e9-8513-c33c3c2c89b1.png)

Regardless, none of this is intended functionality. The Delete button needs to be greyed out once the organism is linked to a metagenotype, and Canto shouldn't behave like an organism is still linked to a genotype / metagenotype when it isn't.

**Comment by ValWood** [comment]
The second message might refer to the fact that there is still a single organism genotype, even if the metagenotype got deleted?

**Comment by jseager7** [comment]
> The second message might refer to the fact that there is still a single organism genotype, even if the metagenotype got deleted?

Normally it would, but in my test session, I didn't even have a single organism genotype at the time. 

It might be because Canto has to create a dummy genotype when creating a metagenotype for a host with no alleles &ndash; maybe Canto forgets to clean this dummy genotype up properly when the metagenotype is deleted.

**Comment by kimrutherford** [comment]
I've assigned this to myself.  If it becomes a common problem please increase the priority.

**Comment by kimrutherford** [comment]
I've had a go at fixing this.  The delete button should now be correctly greyed out if a wild type genotype for the host is part of a metagenotype.  And you should now be able to remove the host once all the metagenotypes that refer to it are removed.

James I had to fix the internals so that the wildtype genotypes are removed when they aren't used any more.  This clean up code only runs when a metagenotype is deleted so the delete host button may be greyed out until you add and then remove a metagenotype that includes the wild type genotype for the organism.

**Comment by jseager7** [comment]
@kimrutherford Unfortunately the fix left out the `ng-click` on the new buttons, so the host organism won't delete under any circumstances. The code needs this added back in:
```
ng-click="removeHost(o.taxonid)"
```
Do we need to bump Canto's version number when merging changes to AngularJS templates? If not, I'll push this straight to `master`.

**Comment by kimrutherford** [comment]
> I've opened a small pull request to fix that.

Cheers!
