### ISSUE TITLE
Do we need to show synonyms here?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2054]
![synonyms](https://user-images.githubusercontent.com/7359272/66131250-fe1e0900-e5ea-11e9-81f1-ab046a1a1a7c.jpg)

1. 
I don't think the synonyms will ever be useful.

Presumably the author will know they have the right thing from the gene name and product (and if the gene name is not assigned  the systematic ID will be there instead)

**Comment by ValWood** [comment]
i.e this column is either blank, or less informative than the gene name?

Would get rid of some clutter on this v. messy page.

**Comment by jseager7** [comment]
I'm not aware of any reason why the synonyms _need_ to be there, but I'd like to hear from the rest of the PHI-base team. @CuzickA @martin2urban is there any particular reason to display gene synonyms on the PHI-Canto confirmation page?

**Comment by ValWood** [comment]
These were probably included because we have them in PomBAse canto. However this is because we allow people to add names OR synonyms then disambiguate them, so in this table the name they added (gene or synonym) is bolded. For PHIbase  as the gene is retrieved via the UniProt accession synonym is not really needed for annotation.

**Comment by CuzickA** [comment]
It may be useful when a gene has been given 2 different names i.e. discovered by 2 different groups. I don't think we currently have any examples of this curated into PHI-Canto at the moment but it is possible we will in the future.

**Comment by ValWood** [comment]
We also have this situation, but the authors always know which gene is meant so it has never been a problem. We don't  need to represent every name, we only need enough info that people know they are curating the correct gene. Obviously in PHI-BAse, you would display all the names for end-users.

**Comment by jseager7** [comment]
Even if different labs have different naming conventions for genes, that may not cause confusion in Canto since the users will have to look up their gene in UniProt first regardless, which means they should be able to resolve synonyms before they reach Canto.

Maybe a better fix to this problem is to allow users to pick their own alias (or 'preferred name') for each gene in the session. There's no issue open about this at the moment, but there is one for doing the same thing for organisms (to resolve the problem about anamorph / teleomorph names). We can probably afford to hold off on implementing either until we're sure they'll be useful for users &ndash; either way, I think gene aliases will be more useful than organism aliases.

**Comment by ValWood** [comment]
We should avoid gene alias's if possible. PHI-base will need to maintain these but it isn't something that we planned to do in Canto. We *might* be able to add something later as a new annotation type , but this would be much, much longer term.
Authors should  be able to cope with annotating using the primary name- and we should make sure names are added to uniprot  so they will be retrievable from a central source.

**Comment by jseager7** [comment]
@ValWood I've just checked PomBase's version of Canto and I've noticed that the synonym column is displayed there too (but it might usually be empty). Do you want it hidden in both versions?

![image](https://user-images.githubusercontent.com/37659591/67004809-042ae400-f0d9-11e9-843a-ac2df0c465df.png)

**Comment by ValWood** [comment]
Yes it isn't an issue but it can be hidden if there are no synonyms at all.

**Comment by jseager7** [comment]
I've removed the synonyms column in pathogen-host mode. If we ever need synonyms in future it would probably be better to show them by clicking on the gene name or something.

The gene table that is used in the PomBase version is managed using Perl, so I'm not sure how to hide the synonyms column in that case. This issue was about pathogen-host mode anyway, so it counts as fixed.

Closing now.

**Comment by ValWood** [comment]
Yes for PomBase the situation is slightly different as we don't disambiguate  from UniProt, and sometimes we have the same name used twice once as a primary ID and once as a synonym. For pombe we disambiguate at the entry point, but then we don't display subsequently.
