### ISSUE TITLE
Gene  names review interface. Workflow issues

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2055]
![synonyms](https://user-images.githubusercontent.com/7359272/66131495-6e2c8f00-e5eb-11e9-808c-68310de5618e.jpg)

I don't think it is clear here why the button is greyed out when you have not picked a strain. How would you know?

**Comment by ValWood** [comment]
it would be better if
a) The stain selector bars were next to the table rows not embedded in the table (perhaps?)
b)  There was some visual indicator that the strain had not  been selected and this was why you could not proceed

c) Unrelated but what is the gubbins in brackets after the species name
e.g. [5599] I don't think we need to display this do we? We only need "organism name" here

**Comment by jseager7** [comment]
> I don't think it is clear here why the button is greyed out when you have not picked a strain. How would you know?

Some text appears when you hover over the button, but I agree this is very obscure;

![image](https://user-images.githubusercontent.com/37659591/66132175-923ca000-e5ec-11e9-95a0-1d21677928e7.png)

It would be better to have a notice permanently visible above the button telling you what still needs to be done, which is hidden when you've added all the strains, or whatever.

- - -

> what is the gubbins in brackets after the species name

That's the NCBI Taxonomy ID. I guess this could be useful to show in the case where we've remapped a strain level identifier to the species level, e.g. [229533] &rarr; [5518], but I agree it's a bit superfluous and could be provided as a label when you hover over the species name.

**Comment by jseager7** [comment]
> it would be better if the strain selector bars were next to the table rows not embedded in the table (perhaps)

We'd have to ensure this doesn't make it look like the strain selector relates only to one gene row. See the mockup below:

![image](https://user-images.githubusercontent.com/37659591/66132728-6cfc6180-e5ed-11e9-9ad6-4daa71695c0d.png)

Do you think that still makes it obvious that the strain pertains to the whole organism, and not the gene?

Also note that we're likely to run into width issues if we put the strain selector to the side, since the placeholder text is already very long. The table won't wrap, so I expect one of three things will happen:

* the other columns will be crushed down to an unhelpfully narrow width;

* the strain selector will overflow the cell and the table, escaping to the right; or

* the table will extend beyond the side of the screen.

**Comment by ValWood** [comment]
OK, I was thinking more that the pulldown  (action) would be outside the table, but the strain (data) would appear in the table.

But, as you say it might cause problems if the strain list is wide, so ignore this suggestion.

I like your  "You must specify all strains before continueing" option

**Comment by ValWood** [comment]
I think the table will look less cluttered if we can implement 
https://github.com/pombase/canto/issues/2054

**Comment by jseager7** [comment]
@ValWood @CuzickA would you support removing the common name and the NCBI taxonomy ID from organism column on the confirmation page? I think the common name is unlikely to be needed, but the taxon ID might be more important for reasons mentioned above (in case of remapping from subspecies to species).

We should also think about formatting the scientific name in italics (instead of bold) so that it matches the way we display scientific names elsewhere in Canto.

Before: 

![image](https://user-images.githubusercontent.com/37659591/69647201-f74aca00-1060-11ea-9b3b-8f6441d285d1.png)

After:

![image](https://user-images.githubusercontent.com/37659591/69647275-15182f00-1061-11ea-8618-af4fad2fd104.png)

**Comment by jseager7** [comment]
Another thing we could do to reduce the clutter on the page is to simplify the label for the strain selector. I don't think we need to mention "for this organism" in the label. Either we should say the name of the organism to make it extremely clear which organism you're adding strains for, or we should leave the text out.

![image](https://user-images.githubusercontent.com/37659591/69647840-1dbd3500-1062-11ea-8749-43c02e802b79.png)

**Comment by ValWood** [comment]
Agree!

**Comment by CuzickA** [comment]
I also agree with both suggestions above. 
I assume the common name and ncbi taxon id are still visible to curators on the previous page when selecting host species from the drop down? If so, I think its fine to just show species name as above.

**Comment by jseager7** [comment]
> I assume the common name and ncbi taxon id are still visible to curators on the previous page when selecting host species from the drop down?

Yes, they are. Here's proof:

![image](https://user-images.githubusercontent.com/37659591/69718568-98d82700-1106-11ea-896f-a409d3e12ef3.png)

I still think it might be a good idea to show the taxon identifiers when they've been remapped from subspecies to strain level, because the taxonomic rank isn't obvious on the UniProt page for an entry. All you get is the lineage, and even that isn't shown in full:

![image](https://user-images.githubusercontent.com/37659591/69718897-5105cf80-1107-11ea-964e-64b5a6a694f8.png)

We could get around this problem with thorough guidance to curators about how to select their UniProt IDs.

If confusion about taxon IDs becomes a problem in future, we could always show the taxon IDs on the next page, but make them more discreet:

![image](https://user-images.githubusercontent.com/37659591/69719147-ca9dbd80-1107-11ea-8b30-342f37dc96f4.png)

**Comment by jseager7** [comment]
This should be deployed to the PHI-Canto servers sometime tomorrow.
