### ISSUE TITLE
I was able to make a duplicate allele

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2058]
![duplicate](https://user-images.githubusercontent.com/7359272/66132337-cca63d00-e5ec-11e9-9b01-f41caafdf5fe.jpg)

**Comment by mah11** [comment]
That's a genotype.

What steps did you take to create the duplicate?

**Comment by ValWood** [comment]
I assume that I selected the  2 single gene genotypes and combined them.

**Comment by mah11** [comment]
Erm, I just clicked on the screenshot ... in the big image I could see that the actual problem is that there's a second version of the lem2-BBM allele that has "lem1" in the name.

<img width="630" alt="allele_typo" src="https://user-images.githubusercontent.com/5196259/66252306-017fd480-e752-11e9-9a27-5e77232aaebe.png">

So this isn't a bug.

**Comment by ValWood** [comment]
Fixed thanks
