### ISSUE TITLE
Improve message on management page for hosts with no genotypes

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2059]
Currently it says "No genotypes in this session. Try adding one." for hosts with no genes but there is no way to add a genotype:

![canto-host-no-genotypes-1](https://user-images.githubusercontent.com/90474/66280081-8e24c100-e911-11e9-8085-1228b95d22c3.png)

**Comment by jseager7** [comment]
I noticed this a few days ago, thanks for opening an issue about it. I'll take a look.

**Comment by jseager7** [comment]
@kimrutherford I've fixed the 'no genotypes' message, but while doing that I realised that a message that I previously set to display when the organism had no genes wasn't working, because it hadn't been updated to match the change where we partitioned the genes in the controller to `allGenes` and `visibleGenes`. Here's the fixed version:

```html
<p class="curs-genotype-no-gene-notice"
   ng-if="data.selectedOrganism && data.visibleGenes.length === 0">
  No genes have been added for this organism.
</p>
```
With that fixed, the page looks like this:
![image](https://user-images.githubusercontent.com/37659591/66474669-a7507d80-ea89-11e9-93e9-24320cc3619e.png)
However, I don't think it's necessary to have two messages that say the same thing. Would you prefer that I kept the message on the right (in the genotype column) and removed the message in the gene column? For example:
![image](https://user-images.githubusercontent.com/37659591/66474856-0d3d0500-ea8a-11e9-8e52-11a70761719c.png)
Alternatively, I could shorten the message in the gene column to something less verbose:
![image](https://user-images.githubusercontent.com/37659591/66474997-55f4be00-ea8a-11e9-8d32-3e460b174b2e.png)

**Comment by jseager7** [comment]
There's also another potential solution, which is to replace the link to 'Delete or edit genes and organisms' with a link that adds another gene for the selected organism (like what happens in single organism mode). Then we can relabel that link to 'Add another gene' (or 'Add a gene') so it's more obvious what to do when there aren't any genes:

![image](https://user-images.githubusercontent.com/37659591/66476283-17143780-ea8d-11e9-8e41-1ff53345748d.png)

I think the reason I gave up on doing this in the past is because the code that fetches a new gene reloaded the page (or used to), but the link's existence could also be due to a hacky solution to get around the problem of how to let users add another organism. Personally I've never been too happy with the way the current link works, because it's so disruptive to the workflow to move the user back to the edit_genes page.

**Comment by kimrutherford** [comment]
> There's also another potential solution, which is to replace the link to 'Delete or edit genes
> and organisms' with a link that opens a modal to add another gene for the selected organism
> (like what happens in single organism mode).

I think that makes sense as it's always possible to "Delete or edit genes and organisms" link on the summary page.  You're right that it's disruptive to the workflow on the genotypes page.

**Comment by ValWood** [comment]
Yes, to add genes later it shouldn't be necessary to go back. We do add genes at various points later on.

We should however be able to confirm better that we have the correct gene. I have been meaning to mention this. We don't see the product etc when we add genes later (for example if required for extensions, we do not go back to the add genes page), so we are not always so sure that we have the right gene...

**Comment by jseager7** [comment]
I've decided that an easier fix for this is just to disable the Host genotype management link until the user has added at least one host gene. There's no point in allowing the user to go to the page if they can't do anything. There's a pull request open at #2155 to do this.
