### ISSUE TITLE
Allow users to specify alias names for genes

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2060]
Related: #2054 

@CuzickA has requested the ability to specify an alias (effectively a user-defined synonym) for each gene in a curation session. This is useful for curators who aren't the original authors of the publication, since sometimes the gene name retrieved from UniProt doesn't match what's in the original paper. PHI-base in particular gives primacy to the data as it is presented in the paper.

I imagine this would work similarly to the custom names for genotypes and/or alleles, in that the feature (in this case, the gene) preserves a link to its original UniProt ID (accession) &ndash; and therefore its UniProt gene name, synonyms, etc. &ndash; but the name that is shown throughout Canto is the user-defined name. For PHI-base, we will also need the JSON export to provide the user-defined name in addition to, or instead of, the gene name of the UniProt accession.

**Comment by CuzickA** [comment]
Eg paper PMID: 28720735 authors use gene name pksP whereas Uniprot uses alb1 which is displayed in PHI-Canto.

![image](https://user-images.githubusercontent.com/11753634/66312412-7dbc1880-e908-11e9-93f6-df7ee431a81e.png)

**Comment by kimrutherford** [comment]
We need to decide what the user interface should be for this.

**Comment by ValWood** [comment]
This is a bit out of scope. See also 
https://github.com/pombase/canto/issues/2054#issuecomment-539173875

Canto should use the primary name.
We should let UniProt be the reference for the names- Authors will be aware of alternative names. If authors think that Uniprot are using the wrong primary name we should let UniProt know.

We can discuss if necessary on the next call, but this seems like "mission creep".

**Comment by CuzickA** [comment]
I can see it makes sense to use the UniProt name in Canto, but how should the alleles be made for this example should they be 'deltaalb1' or 'deltapksP' to follow the paper?
![image](https://user-images.githubusercontent.com/11753634/66380232-e9f15780-e9ae-11e9-8a5b-21a43d550126.png)

This may be a bit misleading to look at as the metagenotype uses the genotype name rather than the uniprot gene name 'alb1'
![image](https://user-images.githubusercontent.com/11753634/66380316-173e0580-e9af-11e9-8952-6ce130504ff9.png)

On the annotation summary page its not clear that 'alb1' and 'pks9' are same gene
![image](https://user-images.githubusercontent.com/11753634/66380469-6be18080-e9af-11e9-9b5d-e4cc2cf9c764.png)

I guess the solution would be to make all the alleles named as 'alb1'. If we agree on this then we will need to add it to the help documentation. If the paper author is curating the paper I'm sure they would easily be able to cope with using the UniProt gene name but it is not quite so easy for other curators who are not so familiar with the paper/expt.

As mentioned in the related ticket #2054 we will need to group synonyms for the PHI-base display results.

**Comment by kimrutherford** [comment]
>  you can also add an allele synonym but I can't find where to do this?

You can add allele synonyms in the allele edit dialog if you are logged in as admin.

**Comment by ValWood** [comment]
Thanks, I probably wasn't logged in.

@CuzickA  if you want to discuss this further to clarify, add to next agenda.

v

**Comment by mah11** [comment]
> [where to add allele synonyms] Is it the field "short geneotype name" ...?

NO. That field is, as its label implies, a name for a genotype (which may have one or more alleles specified), not for anything connected to one allele.

The ticket about the label for that field is #1321. No action has been taken because we have neither resolved the confusion that arose in the ticket over details connected to alleles versus details connected to genotypes, nor decided what (if any) field label would be any better.

**Comment by CuzickA** [comment]
Ok thanks so
1) in this case the allele names need to follow the UniProt name 'alb1'
2) I have added 'pksPdelta' to the allele synonym, accessed in admin mode via edit option for the allele
![image](https://user-images.githubusercontent.com/11753634/66472352-f21bc680-ea84-11e9-9b87-192f1ec1d881.png)
3) This allele synonym is only displayed on the pathogen genotype page (but not in the metagenotype or annotation summary page). Is this what we want?
![image](https://user-images.githubusercontent.com/11753634/66472562-6a828780-ea85-11e9-94ad-3594f8409d34.png)

**Comment by jseager7** [comment]
> This allele synonym is only displayed on the pathogen genotype page (but not in the metagenotype or annotation summary page). Is this what we want?

We could display it in the other tables, if that's what you want. The reason it doesn't display in the genotype tables on the Metagenotype Management page is because those two components don't actually share any code (which I still haven't got round to fixing).

One concern I have with this is that when we have multi-allele genotypes displayed in the other tables (the table of metagenotypes and the table of annotations), then the distinction between alleles won't be clear if we just append the synonyms to each allele. It could make a genotype of two alleles look like it's got four alleles. We don't have this problem with the genotype tables because each allele is on its own row, but that's not the case for the other tables I've mentioned. We might have to come up with a different layout.

We could get around this problem if we could designate one allele synonym as the 'preferred synonym' for display in Canto (which ensures there's only ever one name shown per allele), and that's basically what this issue was about in the first place.

**Comment by CuzickA** [comment]
I agree with the problem of it looking like a multi-allele genotype. I wondered that with the above display and then realised by hovering over the blue text it pops up that its a synonym.

@ValWood Do you think the allele synonym needs displaying in the metagenotype and summary pages or is it sufficient to display it in the pathogen genotypes?

**Comment by ValWood** [comment]
I wouldn't worry about having the allele name based on the primary name for deletions in the multi gene and meta genotypes. The users will know that this is the primary name. If they disagree with the assigned primary name we will ask UniProt to change it.

(Although you can probably add a synonym to the multi -allele phenotype too).

If this isn;t resolved please add to the next call for discussion.

**Comment by jseager7** [comment]
We've decided that this can be handled by changing the allele names to match what is in the publication (in the case that the name doesn't match what's in UniProt). Deletions can still be renamed by using the 'Other genotype...' option instead of the quick 'Deletion' button.

This doesn't fix the complication of how to parse the gene name out of the allele name (for displaying the gene name in PHI-base), but hopefully the allele naming conventions will be consistent enough that we can develop rules for parsing the gene name in all cases. This is not really Canto's problem anyway.

Since no changes are needed, I'm closing this issue. We can use the PHI-base/curation tracker to keep track of whether this problem develops further with other papers.
