### ISSUE TITLE
organism/strain column

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2072]
I notice metagenotype table now has

Magnaporthe oryzae (strain: Guy11)

We should

- [x] 1 change the column heading to 

species (strain)
and
chance the table text to
Magnaporthe oryzae (Guy11)

All users will be used to seeing species name (strain in parentheses)  in this context so we don't need to be explicit

- [x] 2. The  pathogen and host-only tables should follow the same convention

**Comment by ValWood** [comment]
- [ ] "Unknown strain used"
throughout change text to just "unknown strain"

**Comment by jseager7** [comment]
Related: #2037

**Comment by jseager7** [comment]
> "Unknown strain used" throughout change text to just "unknown strain"

@kimrutherford would we need changes in the database to amend the strain names for existing genotypes that have been created using the 'Unknown strain used' option? It's one of the default options in the strain picker:

![image](https://user-images.githubusercontent.com/37659591/67204628-d65ddc00-f405-11e9-869b-3c578c9e3489.png)

**Comment by jseager7** [comment]
@ValWood The changes to the metagenotype table are ready now. As part of the changes I've also implemented abbreviations for the genus, and I've removed the bold styling on the species names, since I wasn't sure if the visual emphasis was necessary. Which style do you prefer? (see images below)

![image](https://user-images.githubusercontent.com/37659591/67205065-d1e5f300-f406-11e9-99f7-5483d7356120.png)

![image](https://user-images.githubusercontent.com/37659591/67205108-e75b1d00-f406-11e9-964e-c4534303b276.png)

**Comment by ValWood** [comment]
I think the table will look less busy generally if it isn't bold maybe? We can always change it later, but let's try "not bold".

Looks good, this will be much better combined.
