### ISSUE TITLE
Allele notes aren't deleted when an allele is deleted

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2078]
Required for #2067 

I've noticed on the `phi-canto-testing` branch that if you delete an allele with a note on it, that same note will re-appear automatically when the allele is created again. Not sure if this is intentional or desirable.

**Comment by kimrutherford** [comment]
Could it be that the allele from the single allele genotype you deleted was part of a multi-allele genotype?  If you delete the single allele genotype and then add an identical allele and genotype, it will reuse the allele from the multi-allele genotype because it's still in the database.

If that's the case then I think that explains the behaviour.  If not I'll dig deeper.

**Comment by jseager7** [comment]
> Could it be that the allele from the single allele genotype you deleted was part of a multi-allele genotype?

I can't reproduce this bug when deleting a single allele genotype when it's the only genotype in the session, so yes, that's probably the cause.

So this isn't a bug, but I wonder if the note being re-created will be what the users expect to happen. It seems a bit counter-intuitive that deleting something doesn't actually delete it. This behaviour doesn't seem to happen with the Background field: for example, if you make a multi-allele genotype with a background on one of its alleles, then delete and recreate the constituent single allele genotype, it doesn't cause the background to be restored to the new single allele genotype.

**Comment by kimrutherford** [comment]
> This behaviour doesn't seem to happen with the Background field

That makes sense because the background is part of the genotype.  The notes are part of the alleles.

An easy-ish fix would be to have a confirmation dialog when the user attempts to delete a single allele genotype where the allele has some notes attached.  If they confirm we should delete the notes too.

**Comment by jseager7** [comment]
I'm fine with that easy-ish fix, since I think this is a low priority issue as it is. I'll tag the issue as such; we can afford to defer this until it proves confusing for curators anyway.

**Comment by ValWood** [comment]
I can't think of a use case where , if we deleted an allele we would want to retain the allele note?
@mah11 
@CuzickA 
Do you think we can just remove the note too?

**Comment by kimrutherford** [comment]
> Do you think we can just remove the note too?

Do you use notes on alleles for PomBase or PHI-Canto?

**Comment by ValWood** [comment]
I don't remember ever using allele note although it is possible. Could you check if we have used it yet?

**Comment by ValWood** [comment]
I possibly used it once or twice?

**Comment by kimrutherford** [comment]
> Could you check if we have used it yet?

There are none for PomBase because the old version of the code used for pombe Canto doesn't support allele notes.

@jseager7 could you run this for PHI-Canto to see if there are any allele notes?:
```sh
canto/script/canto_docker ./script/canto_curs_map.pl 'my $rs = $curs_schema->resultset("AlleleNote"); print $curs->curs_key(), " ", $rs->count(), "\n" if $rs->count() > 0'
```

**Comment by CuzickA** [comment]
I may have used allele notes a couple of times.

I think the allele note should be deleted at the same time that the allele is deleted.

**Comment by mah11** [comment]
> Do you use notes on alleles for PomBase ...?

I don't think I've entered any in the Canto interface (I keep forgetting the link is there), but there's a [Chado ticket](https://github.com/pombase/pombase-chado/issues/753) to load some that I've collected.

**Comment by jseager7** [comment]
> jseager7 could you run this for PHI-Canto to see if there are any allele notes?

@kimrutherford I don't get anything printed on the production server when running this script, so we probably haven't used any allele notes.

**Comment by kimrutherford** [comment]
> I don't get anything printed on the production server when running this script, so we probably haven't used any allele notes.

Thanks for checking.

**Comment by ValWood** [comment]
What is the decision here?

**Comment by jseager7** [comment]
I think the decision is to have a dialog appear when the user attempts to delete a single allele genotype with notes attached, asking the user to confirm whether they also want to delete the notes. Nobody objected to this plan.

Although I'm not sure what happens if the user declines. There seem to be two options:

* the single allele genotype is deleted but the notes stay, to be reused when the same allele is created again; or
* the allele isn't deleted, meaning the prompt cancels deleting the allele.

@kimrutherford Can you confirm which of these options you meant?

**Comment by ValWood** [comment]
I'm a little confused here.
Is this correct:
If an allele is added with a 'note' and the allele is then used in other multi-allele genotypes, the note  is transferred to the allele in the multi allele genotypes.

If the single allele genotype is subsequently deleted clearly the note disappears because the allele disappears.
However, if you recreate the allele, the note 'reappears' because it is attached to the allele in the multi-alle genotype.

This behaviour seems OK to me, because even if you delete a single allele genotype from a specific session, it presumably remains in the database because it is part of multi allele phenotypes. If a note is attached to any instance of the allele (single or multi) it should still be relevant. 

This is a  U-turn on what I said previously.
I still think it would be useful to see actual examples, but if it is used as I expect I can't think of any reason why an 'old' note would not be relevant to a resurrected allele  (in this case we would need to trace to the origins and delete).

**Comment by ValWood** [comment]
Action
-[ ] provide list of existing allele notes (I think I have now   used quite a bit)

**Comment by jseager7** [comment]
> If an allele is added with a 'note' and the allele is then used in other multi-allele genotypes, the note is transferred to the allele in the multi allele genotypes.

As understand it, it's not that the note is transferred, but that the single-allele genotype and multi-allele genotype both reference the same underlying allele in the database.

Canto's user interface kind of obscures what's actually happening at the database level because it doesn't allow alleles to exist independently of genotypes. The fact that you can see the allele notes in single allele genotypes but not in multi-allele genotypes doesn't help: it creates the impression that notes are an exclusive property of a single-allele genotype that won't be referenced by a multi-allele genotype. I'd argue that users being able to delete single-allele genotypes even when they exist in a multi-allele genotype only adds to the impression that single-allele genotypes and multi-allele genotypes aren't intimately connected.

That's my main issue with this feature: it's surprising for the user that the note seems to resurrect itself after recreating the allele, so the user might mistake it for a bug – even if the functionality is desirable – because it's not obvious what's going on.

Is there any particular reason why we don't show the allele notes in multi-allele genotypes? Even adding the 'new notes' label might be enough to indicate to the user that the notes are 'inherited' by the multi-allele genotypes.

**Comment by jseager7** [comment]
More generally, my point is that users aren't going to expect data to come back once they've deleted it unless they use an undo feature, so this is purely a usability issue. Canto's behaviour here might be useful in practice (in terms of saving time) but I definitely don't think it's conventional.

If the allele could be seen independently of the genotype then I doubt users would get confused by this, but that's a big change to solve a minor problem so I'm not suggesting we do that. Indicating that notes are still preserved in the multi-allele genotype might be easier, but either way this issue should stay low priority for being so situational.

**Comment by ValWood** [comment]
>Is there any particular reason why we don't show the allele notes in multi-allele genotypes?

I agree the allele note should probably stay with the allele wherever it is used.
We need to check the existing notes first to see if they really only apply to the allele in some specific context. I just don't really know what type of info they have at present.
Once we know how they are used we can see if they are a) useful and b) how they should be propagated

**Comment by kimrutherford** [comment]
> I'd argue that users being able to delete single-allele genotypes even when they exist in a multi-allele genotype only adds to the impression that single-allele genotypes and multi-allele genotypes aren't intimately connected.

I agree.  It's a weird interface.

> > If an allele is added with a 'note' and the allele is then used in other multi-allele genotypes, the note is transferred to the allele in the multi allele genotypes.
>
> As understand it, it's not that the note is transferred, but that the single-allele genotype and multi-allele genotype both reference the same underlying allele in the database.

Yep!

If the allele from a single allele genotype is used in a multi allele genotype (by combining two single allele genotypes), there is only one instance of that allele in the database and one copy of the note.  That's the case no matter how many genotypes that allele appears in.

> Can you confirm which of these options you meant?

I'm not sure.  :-)

I think my suggestion of a dialog box isn't going to make things less confusing so I withdraw that idea.

I think I'm now in favour of not worrying about this because not many users use notes and many users don't delete single allele genotypes before submitting the session.  I also suspect that, in particular, not too many users will add a note to an allele, then delete the single allele genotype then later recreate the same single allele genotype.

**Comment by jseager7** [comment]
> I think I'm now in favour of not worrying about this because not many users use notes and many users don't delete single allele genotypes before submitting the session.

In that case I'd be fine with closing this until real users start reporting it as a problem.

**Comment by jseager7** [comment]
Okay, I'll close this now.
