### ISSUE TITLE
Difficult to annotate 'physical interaction' with same gene names from different species

### ISSUE THREAD

**Issue by CuzickA** [pombase/canto#2080]
For PMID:30584105
I have 3 'NIS1' genes from different species.  (For genotypes these are clearer as pre-fixed with abbrev. species names).
![image](https://user-images.githubusercontent.com/11753634/67094122-09f0fa00-f1ab-11e9-94c4-f177241d29a0.png)

I want to annotate 'physical interaction' between CoNIS1 and BAK1, it is difficult to choose the correct NIS1 here
![image](https://user-images.githubusercontent.com/11753634/67094663-2a6d8400-f1ac-11e9-86d7-4354db49c7d6.png)

The summary then provides below (I would have to cross-ref the pathogen taxon id or click on the gene name to figure out which species NIS1 has been selected here).
![image](https://user-images.githubusercontent.com/11753634/67094814-702a4c80-f1ac-11e9-8424-3c838ab61ea2.png)

I also noticed this looked a bit odd... having 'choose genetic interaction type' for the physical interaction menu

![image](https://user-images.githubusercontent.com/11753634/67094770-5e48a980-f1ac-11e9-8520-a4078cf8725b.png)

**Comment by ValWood** [comment]
I don't think the physical interaction interface has been updated to deal with  strains yet.

I don't know why the label here is "genetic interaction type" it isn't like that in PomBase (or at least last time I looked).

**Comment by kimrutherford** [comment]
> it is difficult to choose the correct NIS1 here

I think this is the same problem as: #2101

**Comment by kimrutherford** [comment]
> I don't know why the label here is "genetic interaction type" it isn't like that in PomBase

Probably the PHI-Canto configuration needs a tweak.

**Comment by jseager7** [comment]
> Probably the PHI-Canto configuration needs a tweak.

I've checked the configuration file, and there's no references to 'genetic interaction' anywhere in the file. No references to 'genetic' even. I'll check the code that renders the drop-down and see if I can notice any problems.

**Comment by kimrutherford** [comment]
Thanks James.  I should have actually had a look at the code before commenting.  I had hard coded that string.  I've changed it to "Choose interaction type ..."

**Comment by jseager7** [comment]
I think this issue has been partly obsoleted by the changes in the `master` branch, because it looks like 'physical interaction' doesn't use genes anymore, it uses genotypes:

![image](https://user-images.githubusercontent.com/37659591/68769721-b98b8180-061c-11ea-969f-cadd319677f5.png)

That fixes the problem of not being able to distinguish genes, but the problem now is you can't select a second organism as the partner in the interaction. It sounds like for pathogen-host mode we want an option to select an 'Interacting organism' as well as an 'Interacting genotype'.

**Comment by ValWood** [comment]
that seems like a  bug. 
Physical interaction should still use genes

**Comment by kimrutherford** [comment]
> Physical interaction should still use genes

Ah.  I didn't think this through.  All of the interaction code now uses genotypes rather than genes.  I'll need to go back to the drawing board.

**Comment by ValWood** [comment]
physical interactions should stay the same as it was.

**Comment by kimrutherford** [comment]
> physical interactions should stay the same as it was.

Because I misunderstood, I've replaced all of the gene to gene interaction code with the genotype to genotype interaction code.  So unfortunately it's not a simple case of changing configuration for the physical interactions.  I'll need to put the gene-gene interaction code back without interfering with the genotype-genotype interaction code and enable it only for physical interactions.  That's going to take some time.

**Comment by ValWood** [comment]
yes sorry, I never thought about this!

**Comment by kimrutherford** [comment]
I think we can close this now.  In the new style annotation edit dialog the organism is selected first then only the genes for that organism are shown.
