### ISSUE TITLE
metagenotype management

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2084]
<img width="1071" alt="Screenshot 2019-10-23 at 07 51 16" src="https://user-images.githubusercontent.com/7359272/67365892-674dc800-f56a-11e9-89b1-aaeb99bf6a9d.png">

It would be lovely if these could be displayed  as "single row tables"
(i.e like the first table) if possible.

I will keep suggesting small nudges to improve the display.

1.  In the metagenotype table we could combine the allele/ expression columns so they appear as in the annotation tables
single column  allele [expresion] 
2. Here the strains have a name and a synonym.  When the strains are selected in the pulldown, both should be visible. However once selected, I think we only need to see the strain abbreviation? (Ws and Nd here)
3. Are we planning to tuck the "add more pathogen genotypes" so it is smaller and tucketed just under the table (tis option should not be required a lot at this point. Also It can say, simple "Add more..."

These changes will allow a few more tables to resolve more pleasingly/take up a little less space

**Comment by ValWood** [comment]
when 2 is implemented, add CS as an abbreviation for "chinese spring"
PMID:22241993

**Comment by jseager7** [comment]
> In the metagenotype table we could combine the allele/ expression columns so they appear as in the annotation tables

This is yet another inconsistency that stems from the fact that these genotype tables don't share any code with the tables on the Genotype Management page (see #1714). I'm hoping to fix this eventually but it could involve a lot of work.

> Here the strains have a name and a synonym. When the strains are selected in the pulldown, both should be visible. However once selected, I think we only need to see the strain abbreviation? (Ws and Nd here)

This might be tricky to achieve, at least until Canto supports strain synonyms at the database / config level &ndash; in fact, this might even require an extra field to store the abbreviations too. Part of the reason we even see these multiple names is because the strain names were loaded from UniProt: once we change to PHI-base's list of strains, we might only see the long name; presumably we'd have to add any abbreviations manually, unless PHI-base's naming already follows the same convention.

> Are we planning to tuck the "add more pathogen genotypes" so it is smaller and tucked just under the table...

I was planning to do this, but I think @CuzickA conversely suggested that the link wasn't obvious enough as it is. I'm not sure if moving the link below the tables will help this (unless the link actually turns out to be more obvious when it's closer to the other navigation links).

**Comment by ValWood** [comment]
> I was planning to do this, but I think @CuzickA conversely suggested that the link wasn't obvious enough as it is. 

personally, I think it is non-obvious because it's in a strange place.

Can we put the strain format discussion on a call.  We should move to a standard name, short (dislplay name (optional), synonym format.
What status is the strain table at right now? I know you were tidying it. 
Have you asked @CuzickA  and @martin2urban  which strins can merge.  We don't need to lose any names in PHIBase if we create a synonyms column which might allow this to move forward.
Once we have the tided form in a config it will be relatively easy for us to add new synonyms and short names.

**Comment by ValWood** [comment]
> I was planning to do this, but I think @CuzickA conversely suggested that the link wasn't obvious enough as it is. 

personally, I think it is non-obvious because it's in a strange place.

For me, part of the problem is that you need to look at the table to see if a strain is missing, so the logical place for a link is at the bottom of the table, not above it.

I don't want this instruction to be the first thing I see if I have done all my single allele genotypes. When I first saw this instruction I had to think about  what I needed to do before I realised I could ignore it.....Its really oddly places between the organism and the genotype table. I just find it confusing.

The main instruction at this point should be to combine genotypes to make a multi-species genotype. And then  "oh, you forgot one, you can still add it here"

**Comment by jseager7** [comment]
> What status is the strain table at right now? I know you were tidying it.

I'm doing one final cleanup of our host strain list, then after that's done it should be ready to either be loaded into Canto as-is, or joined with strain data from UniProt (so we can add synonyms and so on).

> Have you asked CuzickA and martin2urban which strains can merge.

They haven't done a formal review of the strain list yet. It would make sense for them to do that after I'm done checking the host strain list, or after I've compiled a list of all the potential merges / renames.

> For me, part of the problem is that you need to look at the table to see if a strain is missing, so the logical place for a link is at the bottom of the table, not above it.

Now I agree with this. I guess it's no less likely that curators would miss the link if it was at the bottom of the table versus the top, and like you say, we should have instructions on how to combine genotypes near the top, not how to add genotypes in the first place. Anyway, in the case where the user hasn't added enough genotypes, the link will be more conspicuous anyway because it will be shifted up the page. I'll bundle this change with pull request #2082, since that hasn't been merged yet.

**Comment by jseager7** [comment]
> In the metagenotype table could combine the allele/ expression columns so they appear as in the annotation tables: single column allele [expression]

Those columns are merged now, so the table looks more like it does on Genotype Management:

![image](https://user-images.githubusercontent.com/37659591/68760970-fa7a9a80-060a-11ea-8b0d-097a657a5ab9.png)

**Comment by jseager7** [comment]
I've moved the second suggestion about displaying strain abbreviations to its own issue at #2110, because it's not going to be quick to fix. Since I think everything else in this issue is finished, I'm going to close it now.

**Comment by ValWood** [comment]
It still looks like this to me?

<img width="974" alt="Screenshot 2019-11-14 at 14 27 35" src="https://user-images.githubusercontent.com/7359272/68865591-fde55300-06ea-11ea-8a7e-125aa2dfd68e.png">

**Comment by jseager7** [comment]
Sorry, that's because I had to revert the production server to an earlier commit because of a database upgrade issue. I'll leave this open again until that's fixed so I don't forget.

**Comment by jseager7** [comment]
Production server is back to normal, so I'm closing this again.
