### ISSUE TITLE
How should we be capturing 'disease"

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2099]
This is currently asdded as an extension to virulence /pathogenicity causing  pathogen-host interaction phenotypes.
However, this means captuing the same thing over again.
It seems that we should capture this as a different annotation type ...

I think we have discussed this before, but I can't remember the outcome @CuzickA ?

@jseager7  could this be added to the next agenda?

**Comment by jseager7** [comment]
The plan was to automatically fill the disease names based on a curated list, and only have the user supply a disease if it differs from the expected disease. See https://github.com/pombase/canto/issues/1975.

I'm not sure if we ever decided exactly _how_ the user would supply the disease name in the case where it differs from the expected disease.

As for the repetition of disease names, it's kind of inevitable if we associate the disease with a particular interaction, because some interactions will cause disease and some won't &ndash; we could maybe avoid that if we view phenotype outcomes like 'abolished pathogenicity' to imply 'no disease', meaning the phenotype can be used to infer disease presence or absence. That could be tricky to implement though.

**Comment by jseager7** [comment]
Note also that because of changes in #1975, the disease annotation extension is currently disabled on the PHI-Canto servers (well it _should_ be disabled, anyway). Feel free to let me know if you ever need it re-enabled so data doesn't get left out. I could restrict it to admin as a 'middle-ground' solution.

**Comment by jseager7** [comment]
I've re-enabled the disease annotation extension following some further discussion. The plan is to use that for now, until either the disease ontology is ready, or until we can decide on a way to capture diseases as a separate annotation type.

@ValWood If it's annoying have to record the same disease repeatedly, one option might be record the disease only once for each (host, pathogen, tissue type) triple &ndash; then later on in the pipeline we could use some basic inference rules to apply that same disease to every interaction that matches the triple. If there's no recorded disease for a triple, then we don't do anything. 

Unfortunately, the above approach could run into problems if you happen to curate two or more diseases for a triple: then we have no way of knowing which is the 'ordinary' disease and which is the unusual one, meaning we don't know which disease should apply to the other un-annotated phenotypes. I can't really think of any solution to this when using annotation extensions, besides just filling in all the disease annotations manually when you can't automatically populate them.

**Comment by jseager7** [comment]
It's possible that the disease that manifests could also depend on experimental conditions, like which chemical substances are present in the environment. That could complicate things further.

**Comment by ValWood** [comment]
Let's see how we go. I'm sure there is a better more consistent way to do annotate/infer disease. Hopefully it will become clearer later.
It doesn't bother me to capture multiple times  (but I won't be doing the bulk of the curartion) ....and I guess it's only for terms which are disease symptoms.

**Comment by jseager7** [comment]
Closed in favour of #2390.
