### ISSUE TITLE
changes to extension config

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2185]
Because GO-CAM prefers

MF part of 
or
BP occurs_at CC

instead of
CC exists_during BP

we need to change the config files to 
i) allow occurs at on MF
(I think we will omit on just BP as it might clutter the annotations too much, so we will only make these lings when we have  MF part of BP, we  can revisit if this is too restrictive)

I think we also need to restrict what is allowed in "occurs_during" to phases and responses, but I will double check this when I finish the updates.

**Comment by mah11** [comment]
fine and dandy if we want to do this bit anyway:

> allow occurs at on MF

... but it's not yet accepted as a substitute for CC exists_during BP, because they don't mean quite the same thing (see https://github.com/pombase/curation/issues/2558#issuecomment-566969093 and quite a few of the comments on the relevant GO annotation ticket, https://github.com/geneontology/go-annotation/issues/2677).

> restrict what is allowed in "occurs_during" 

the relation is happens_during

**Comment by ValWood** [comment]
Hmm, I see. I have come across some that don't make sense./

For example
SPBC19G7.05c.1 | mating projection tip [exists_during] cell morphogenesis involved in conjugation with cellular fusion
or

GO:0005739 | mitochondrion | 750
during conjugation with cellular fusion

and we can't say things are involved_in these processes.

However, it probably isn't sustainable to list every process that occurs at the same time some  localization is observed. I don't think this is really what we are trying to capture. I think we are trying to indicate the phase i=of lifecycle stage that the localization is observed which will cover lots of  processes.

But, the problem is that there isn't an extant way to describe  "conjugation"   temporally...any ideas?

**Comment by mah11** [comment]
> t probably isn't sustainable to list every process that occurs at the same time some localization is observed. I don't think this is really what we are trying to capture.

I agree with this, but I don't think that necessarily means that we would *never* want to indicate that a localization temporally coincides with a process. Once in a while, it would be nice to specify that gene product X is seen in location Y when process Z is taking place, even though we don't have enough data to say X is involved in Z. The idea is that the "found in/at Y during Z" might give researchers a hint that it would be interesting to do the experiments that would let us say either "X is involved in Z" or "it's a coincidence". I would prefer to forgo that clue provision rather than leap straight to changing existing annotations without additional data. 

> I think we are trying to indicate the phase or lifecycle stage that the localization is observed which will cover lots of processes.

Yes, we are, but I suspect phases+responses will only cover *almost* everything.

> But, the problem is that there isn't an extant way to describe "conjugation" temporally...any ideas?

I have yet to be convinced that there's anything wrong with saying "during conjugation" for these.

**Comment by ValWood** [comment]
Yes I agree, it is often useful in the absence of other information.

For the ones where it makes sense I have changes to  MF occurs_at"
But I will keep the ones where there is not enough info to say this.

There seemed to be enough objection to rethink this .

**Comment by mah11** [comment]
any further mucking about is probably superseded by the "existence overlaps" plan a la https://github.com/pombase/pombase-chado/issues/841
