### ISSUE TITLE
user interface: populate gene names when known from a previous session (curation streamlining and speed increase))

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#219]
This isn't urgent as it wont usually affect users so much,
but it would be nice if a paper has been annotated previously, that the names appeared in the gene names box (at present I usually just add a single "random" name, as when I get to the session, most of the names will be there....

Original comment by: ValWood

**Comment by ValWood** [comment]
Action
If any genes are already associated with a session in Chado (via artemis or biogris), prepopulate the session

**Comment by ValWood** [comment]
This is part of  future ML work, to identify named entities and prepopulate Cano, so I added "next grant" lable

**Comment by ValWood** [comment]
sources of "known genes"
1. Publication keywords (will need to ignore if it has a synonym match, unless can be resolved by bioGRID)
2. Structure (should be able to map exactly using uniprot ID)
3. Previous (legacy) annotation - precise using the  systematic ID

**Comment by kimrutherford** [comment]
> Structure (should be able to map exactly using uniprot ID)

This needs a little bit of work first.  The genes and PMIDs from PDB aren't loaded into Chado at the moment because there isn't a clean way to store things like method, resolution and chain.  The PDB details are in this file:
https://curation.pombase.org/dumps/latest_build/pombe-embl/external_data/protein_structure/systematic_id_to_pdbe_mapping.tsv
(`pombe-embl/external_data/protein_structure/systematic_id_to_pdbe_mapping.tsv` in SVN)
Those details are processed when Chado is processed to make the website.
So first step is to load at least the gene to PMID mapping from PDB into Chado.
I've made a separate issue about this:
  - pombase/pombase-chado#1148

**Comment by kimrutherford** [comment]
I have a prototype of this running on my desktop.

![image](https://github.com/pombase/canto/assets/90474/f65c77ee-4d00-42cf-9e3e-8e3a2e7554a2)

Unfortunately it dumps you straight into the Canto front page without asking for more genes.  Fixing that will take a bit of thought.  Canto only prompts for genes when you first enter a session because there are no genes yet.  When the session it's hard-wired to go to the front page.  There's probably a workaround for that.

![image](https://github.com/pombase/canto/assets/90474/b1294f76-bad1-424e-a056-63c7193dc903)

**Comment by ValWood** [comment]
This will be great. I can't test because the login required is orcid sandbox, and I don't have a password for this and the passed recovery doesn't work.
I would go ahead and add it. It won't be a problem even if the wrong gene is occasionally added.

**Comment by kimrutherford** [comment]
> I would go ahead and add it.

I will do but first I'll try to arrange for Canto to go to the edit genes pages when there are existing genes, rather than to the front page.

**Comment by kimrutherford** [comment]
> I will do but first I'll try to arrange for Canto to go to the edit genes pages when there are existing genes, rather than to the front page.

Val, could you suggest improvements for the message here?  It only appears once, the first time you get to this page.

```
Warning: this session has been populated with PMID:35101096 genes known from other sources.
Use the "Add more genes from PMID:35101096" link to add missing genes 
```

![image](https://github.com/pombase/canto/assets/90474/22840809-7fce-46b0-a85a-262d830a2f89)

**Comment by kimrutherford** [comment]
I've updated the test Canto with this change.  PMID:35101096 is an example if you'd like to try it.

**Comment by ValWood** [comment]
I agree "Note"
perhaps
Note: this session has been populated with genes from PMID:35101096 abstract, keywords and other sources. Use the "Add more genes" link to add missing genes. You can also add, or remove, genes at any time during curation.

**Comment by ValWood** [comment]
tested, wonderful

**Comment by kimrutherford** [comment]
Should we say "UniProt keywords" in the message?

**Comment by ValWood** [comment]
These aren't UniProt Keywords they're PubMed

**Comment by kimrutherford** [comment]
Yes, sorry.  Should we say "PubMed keywords"?

**Comment by ValWood** [comment]
OK, that might be helpful (and encourage people to add them!)

**Comment by kimrutherford** [comment]
OK, done.  And I've released this change in the main Canto.

Should we close this issue?

**Comment by ValWood** [comment]
OK I will announce

**Comment by ValWood** [comment]
I just tried https://www.pombase.org/reference/PMID:27538348
and I didn't see any genes populated (I expected minimally to see those curated by BioGrid)

**Comment by kimrutherford** [comment]
Action: include BioGRID genes/publications

**Comment by kimrutherford** [comment]
> Action: include BioGRID genes/publications

That's done, but not in time for the load.

I'll check it worked OK on Thursday morning.

**Comment by kimrutherford** [comment]
> That's done, but not in time for the load.
>
> I'll check it worked OK on Thursday morning.

I've just restarted the load after a failure so this will be done by the morning after all.

(Mondo has new release with an exciting new relation "has material basis in germline mutation in" which caused problems.  It's [all fixed now](https://github.com/pombase/pombase-chado/commit/66c101c53ed5d379640a65e3d0ee7988417aa283))

**Comment by kimrutherford** [comment]
> Action: include BioGRID genes/publications

Done!

Example from the test Canto for PMID:27538348:

![image](https://github.com/pombase/canto/assets/90474/5d76b84e-9036-4b71-88dd-e37dbe38dd5f)

**Comment by ValWood** [comment]
nice!
