### ISSUE TITLE
gene list on summary page - order alphanumerically, ignoring case 

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2195]
I would prefer the gene list on the summary page to be ordered alphanumerically, ignoring case.

((I am assuming this is easy but it is also not a priority at all... and one will get used to it with time.)

**Comment by kimrutherford** [comment]
> I would prefer the gene list on the summary page to be ordered alphanumerically, ignoring case.

This might need to be a option because I think it makes sense to not ignore case for PomBase.  I think pombe gene names are always lowercase and systematic IDs (uniquenames) are always uppercase.  That's convenient because unnamed genes are displayed using the systematic ID and will be grouped together first in gene list.  Val, Midori, what are your thoughts?

> I am assuming this is easy but it is also not a priority at all... and one will get used to it with time

If it doesn't need to be an option, it's a one line change to ignore the case.

**Comment by ValWood** [comment]
This doesn't really affect PomBase because all our assigned genes are lower case and all our unassigned genes are upper (SPAC). The effects will be minimal, SPACs will appear integrated into  the list rather than at the bottom- but we hardly ever have SPACs in Canto anyway. I don't think it will really affect PHI-base either, alphabetical will probably be better here too.

So, personally I have no objection to this change. If @mah11   and @CuzickA agree, go ahead and alphabetize by default.

**Comment by jseager7** [comment]
If this is just for the summary page and not the genotype management page, then this won't affect PHI-Canto at all because we use a different component to display the gene list.

However, our list doesn't sort case-insensitive, so it's worth considering if we want to fix this:

![image](https://user-images.githubusercontent.com/37659591/73445908-ae124180-4353-11ea-9160-500311a4e9a0.png)

**Comment by mah11** [comment]
I like the current behavior for pombe Canto, but if the sorting changes I'd get used to it soon enough. No strong feelings, really.

**Comment by kimrutherford** [comment]
OK, thanks everyone.  I've changed the order to be case-insensitive.  If this becomes an annoyance for PomBase we can make it an option.
