### ISSUE TITLE
Add  assayed_using to PHIPO protein localization terms

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2210]
with "PHIPO 0000238"
assayed using  options would be "proteins"

LAter it would be good to restrict to pathogen or host proteins for specific terms...

**Comment by jseager7** [comment]
Here's the draft configuration:

domain ID | subset relation | extension relation | range ID | Canto display text | Help text | cardinality | role
-- | -- | -- | -- | -- | -- | -- | --
PHIPO:0000238 | is_a | assayed_using | GeneID | assayed protein |   | 0,1 | user



For PHI-Canto I think our Gene IDs and Protein IDs are equivalent since we're using UniProt accession numbers, right? Is there any need to specify ProteinID for the range ID in the config?

**Comment by ValWood** [comment]
Oh,I think this should have cardinality 0,2
I forget what the  2 numbers are for
@mah11 ?

**Comment by ValWood** [comment]
Ignore. comment. This is localization. I thought I was commenting in the interactions ticket.

**Comment by ValWood** [comment]
> For PHI-Canto I think our Gene IDs and Protein IDs are equivalent since we're using UniProt accession numbers, right? 

Yes

> Is there any need to specify ProteinID for the range ID in the config?

I think in the first instance any Protein ID in the session should be available in the pull down.

**Comment by jseager7** [comment]
> I think in the first instance any Protein ID in the session should be available in the pull down.

I meant whether we should prefer ProteinID over GeneID for extensions like this, but it doesn't sound like there's any difference (yet).

Would it ever be useful to have different display modes when ProteinID is specified, for example giving the protein name instead of the gene name? I'm guessing this would just make it harder to pick the correct option.

As for restricting the extension values, there was some discussion about restricting the list to only genes/proteins from a specific organism in issue #2101, but nothing about restricting by pathogen/host role.

If we want different options for filtering the extension, then we'll probably need new special range IDs for that purpose; something like TaxonGeneID, PathogenGeneID and HostGeneID, plus the same with proteins.

**Comment by ValWood** [comment]
> Would it ever be useful to have different display modes when ProteinID is specified, for example giving the protein name instead of the gene name? I'm guessing this would just make it harder to pick the correct option.

We don't worry about this. In these cases we are just using the ID as a proxy so we know which gene/transcript/protein we are referring to. Then we infer from the context of the term if the extension is a gene/mRNA /protein. This hasn't caused a problem for users. I'm not sure if we document this clearly though...

**Comment by mah11** [comment]
There's nothing in user-facing documentation about the "ProteinID|TranscriptID|GeneID" stuff because users never see it. The distinction is made only in the configuration files; we store it there so that if we ever want to make gene vs. RNA vs. protein distinction in our website displays (mainly pombase.org, perhaps also pombe Canto) we will have the necessary data available. It's a future possibility, though, not a medium-term plan.

**Comment by kimrutherford** [comment]
> I meant whether we should prefer ProteinID over GeneID for extensions like this, but it doesn't
> sound like there's any difference (yet).

Yep, they are synonyms at the moment.

**Comment by jseager7** [comment]
Sorry about the delay on this, I lost track of the issue. The config has been updated now, so the extension should enable by tomorrow after the ontologies reload. Closing.
