### ISSUE TITLE
Issues converting Aberration data from Canto into proformae

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2213]
Aberrations from Canto are converted into genes/alleles
1. aberrations are added as genes and alleles - see attached files
a) the converter complaints about it (there is an error report)
b) adds 4 question marks to the gene name
c) phenotype notes are added to GA7a field

Action:
a) add aberration proforma instead of allele proforma
b) add phenotype notes to ! A17. field
c) for two aberrations, curators should fill the interaction section of the notes, which should be transferred to the ! A19b. field

**Comment by vmt25** [comment]
Here is example: the error log and record
(Record as .txt, because GiHub does not support the .phen extension)

[vt1898.phen.txt](https://github.com/pombase/canto/files/4134811/vt1898.phen.txt)


[error_log.txt](https://github.com/pombase/canto/files/4134796/error_log.txt)

**Comment by gm119** [comment]
can you also add the exported json file you used to make the vt record - it'll help a lot with debugging if I can run the script over the  json

**Comment by vmt25** [comment]
Here it goes - there are a few more papers there. Let me knwo if you want it cropped.
(again, adding .txt extension because jsons are not supported)

[canto_exported_10012020.json.txt](https://github.com/pombase/canto/files/4134893/canto_exported_10012020.json.txt)

**Comment by gm119** [comment]
thanks.
your example only has a case for the A17 field - so I'll need an example which is designed to show ' for two aberrations, curators should fill the interaction section of the notes, which should be transferred to the ! A19b. field'

If its handy, could you also say which type of note should go into each field, I've got these different types of notes mapped for when the genotype involves alleles:

	'phenotype' => 'GA7a',
	'genetic_interaction' => 'GA28c',
	'xenogenetic_interaction' => 'GA29c',
	'rescue_complementation' => 'GA22',
	'internal_note' => 'GA14',

could you provide a similar mapping for when the genotype consists solely of FBab, I've started it off below but put ?? where I wasn't sure what you wanted:

	'phenotype' => 'A17',
	'genetic_interaction' => '??',
	'xenogenetic_interaction' => '??',
	'rescue_complementation' => '??',
	'internal_note' => 'A15',

**Comment by vmt25** [comment]
Here is my take on the mapping of text fields. The xenogenetic interaction and rescue/complementation fields should not be used and I suggest having a Peeves error message.


'phenotype' => 'A17'
'genetic_interaction' => 'A19b', plus by Peeves: 'There is a genetic interaction description for <aberration X>. These should be added for interactions only involving aberrations. For interactions involving aberrations and alleles, please move the descriptions to the corresponding fields of the alleles.'
'xenogenetic_interaction' => Error message by Peeves: '<aberration symbol>: Can't add a xenogenetic interaction description to an aberration.'
'rescue_complementation' => Error message by Peeves: '<aberration symbol>: Can't add a rescue/complementation description to an aberration.'
'internal_note' => 'A15'

**Comment by vmt25** [comment]
And here is the test export json with two interacting aberrations (.txt extension)
[test.json.txt](https://github.com/pombase/canto/files/4149464/test.json.txt)

**Comment by vmt25** [comment]
And here is the converted proforma file (.txt extension)

[vt1.edit.txt](https://github.com/pombase/canto/files/4149472/vt1.edit.txt)


Let me know if you need more complicated stuff.

**Comment by gm119** [comment]
have added code to cope with aberration notes.
I have added code that copes with:

		'phenotype' => 'A17',
		'genetic_interaction' => 'A19b',
		'internal_note' => 'A15',

for 'xenogenetic_interaction' and 'rescue_complementation':

I don't think I can add Peeves messages for the above two -  there is no way for Peeves to know   that data in a particular proforma field came from a 'xenogenetic_interaction' or 'genetic_interaction' slot in the json, so any error messages would have to be in the json output converter script which can see the json info.

Since these are likely to be rare errors, for these two fields any filled in notes in aberrations will still appear in the error log file as they should never be filled in, so curators will have to paste any genuine notes in by hand.

for 'genetic_interaction' => 'A19b', again, I don't think I can make a Peeves message, any error warnings would have to be done in the json output. I wasn't sure why you wanted an error message here, since this is a free text field - so you could put in a correct free text line that just describes aberration interactions AND an incorrect line that is allele/aberration and there is no way to easily determine what is correct/incorrect since its free text.

So I think this is one where curators just need to keep to the rules (you can only attach notes to single entity genotypes in FlyBase Canto which hopefully will act as a reminder that this is supposed to just be about interacting aberrations)
