### ISSUE TITLE
Add a GeneService

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2229]
We should add a GeneService (or GeneListService) so we can remove the form submission here:

https://github.com/pombase/canto/blob/34cf038bd1b173107696f907665569766e1c6334/root/static/js/canto-modules.js#L9245

**Comment by jseager7** [comment]
We can actually already use `Curs.list('gene')` to get the genes, but `Curs.delete` doesn't seem to be supported for genes. I tried this:
```js
Curs.delete('gene', 3)
```
But the URL it generated returned a 404 error, presumably because there's no corresponding path handler in `Curs.pm`.
```
https://canto.phi-base.org/curs/c18ce0f43f9600c9/ws/gene/delete/3
```
Maybe it would make more sense to add a subroutine to `ServiceUtils.pm` (in the style of existing subroutines like `delete_genotype`) that deletes a gene if it has no alleles. Then we can just extend `Curs.pm` with the relevant webservice endpoint. For example:

```pl
sub ws_delete_gene : Chained('top') PathPart('ws/gene/delete')
{
  my ($self, $c, $gene_id) = @_;

  my $st = $c->stash();
  my $schema = $st->{schema};

  my $service_utils = Canto::Curs::ServiceUtils->new(
    curs_schema => $schema,
    config => $c->config()
  );

  $st->{json_data} = $service_utils->delete_gene($gene_id);

  $c->forward('View::JSON');
}

**Comment by kimrutherford** [comment]
Hi James.  Thanks for investigating.

Adding a subroutine to ServiceUtils makes sense.  The current deletion code in _edit_genes_helper() is rather dodgy because it doesn't handling checking for genes that have allele/genotypes.  Ideally we should put those checks in the new code and replace this mess:
https://github.com/pombase/canto/blob/d0826bbfa1393c3b71b83a6168ef721c9dd42f49/lib/Canto/Controller/Curs.pm#L584-L605

**Comment by ValWood** [comment]
I am not sure what this is so I ha ve assigned as "medium priority" @kimrutherford  you can increase  or decrease

**Comment by kimrutherford** [comment]
I'm going to close this because I don't think I'll ever get around to it.
