### ISSUE TITLE
Fix strain loader to handle strain abbreviations and synonyms

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2235]
Depends on #2232 and #2231

We'll need to decide how to represent abbreviations and synonyms in the strain input file.

**Comment by kimrutherford** [comment]
> We'll need to decide how to represent abbreviations and synonyms in the strain input file.

I think we just need to add a new column to handle abbreviations.  I'm not sure about the synonyms.  We could mash them into a column too which is easy but a bit nasty:
```
746128,Aspergillus fumigatus,A1160P, some_abbreviation, "synonym 1, syn 2, another 1"
```

@jseager7: any thoughts on this?

**Comment by kimrutherford** [comment]
We also should think about what to do when a strain file is reloaded after editing.  Should existing synonyms be removed and replaced with the ones in the input file?  Or should the synonyms in the file be added to the synonym list of existing strains (if any).

**Comment by kimrutherford** [comment]
> I think we just need to add a new column to handle abbreviations.

That seems uncontroversial and easy to change so I've added that code to the #2238 PR.

**Comment by jseager7** [comment]
> I'm not sure about the synonyms. We could mash them into a column too which is easy but a bit nasty:

That's the approach I've taken with the spreadsheet I've been using to clean up the strain list (storing synonyms as a comma-separated list).

It is a bit messy, but I don't think it's too bad. I think it keeps the strain list more usable if we can store it in tabular format (as opposed to something like YAML).

I don't think I've seen any examples of synonyms that have commas in them so far – they seem safer than semicolons, which I think sometimes occur in _M. musculus_ strains.

**Comment by kimrutherford** [comment]
OK, thanks James.  I'll implement that tomorrow.

**Comment by jseager7** [comment]
> We also should think about what to do when a strain file is reloaded after editing.

I think it's going to be simpler if the synonyms are always replaced when a strain is loaded. Changing the loading process to append-only is probably going to make it harder to edit and remove synonyms when necessary.

Although, we might need some handling for what happens when a strain that's in use is removed, because genotypes aren't allowed to exist without strains. Could the loader simply refuse to update if a strain goes missing?

Having said that, what happens if someone tries to load a partial strain file (that is, loads one file containing strain _A_ and then loads another file containing strain _B_)? Does the new strain file get appended to the `strain` table, or do they replace the existing strains, like with the ontology loading?

**Comment by kimrutherford** [comment]
> Does the new strain file get appended to the strain table, or do they replace the existing strains,
> like with the ontology loading?

That's what happens currently - the strains are appended.
