### ISSUE TITLE
make json input file with Triage status and Curation priority info in

### ISSUE THREAD

**Issue by gm119** [pombase/canto#2249]
FlyBase wants to be able to add 'Triage status' and 'Curation priority' info via the json input file (as triaging of the publication has already been done external to Canto).

I need to provide a test json input file with this information added under publications, with an appropriate key for each type of data

**Comment by vmt25** [comment]
It also requires the creation of cv terms for the range of values for the priority score as strings.

Creation of cv terms with 'canto_add.pl'

Values are 0-9, in 0.5 increments:
0
0.5
1
1.5
2
2.5
...

@vmt25 will do this for testing - and will add this to the configuration pipeline

**Comment by vmt25** [comment]
As discussed today, I'm adding high priority for this issue.
Big thanks,
V

**Comment by gm119** [comment]
I've implemented this in the json with the labels "curation_priority" and "triage_status", which are currently sitting directly under each PMID like so:


"PMID:nnnnnnn" : {

         "alleles" : {
             blah
          }

         "curation_priority" : 6,

        "genes" : [
             blah
        ],
        "triage_status" : "TRAINING"
  }





curation_priority is an integer
triage_status is a string

am attaching a test file with 3 PMIDS worth of data (as new_canto_input_with_status.json.txt - had to add .txt to get it to upload
[new_canto_input_with_status.json.txt](https://github.com/pombase/canto/files/4402249/new_canto_input_with_status.json.txt)
)

**Comment by kimrutherford** [comment]
I've changed the JSON loader to store the status and priority.  We'll need to add the statuses and priorities to the Canto DB.  They're stored as cvtems a bit like Chado.  Here are the command lines I used on my local test database so I could load your example JSON file:
```
./script/canto_add.pl --cvterm "Canto publication triage status" TRAINING
```
```
./script/canto_add.pl --cvterm "Canto curation priorities" 6
```

The first argument after "--cvterm" is the CV name and the second is the cvterm name.

If you can send me a list of the statuses I'll add them all to the main Fly-Canto.  I'll add the priorities from 0 to 9 in 0.5 steps.

**Comment by kimrutherford** [comment]
> If you can send me a list of the statuses I'll add them all to the main Fly-Canto. I'll add the
> priorities from 0 to 9 in 0.5 steps.

I've added the priorities and I've removed the two PomBase priorities (low and high):
https://curation.pombase.org/flybase/view/object/cv/9?model=track

> If you can send me a list of the statuses I'll add them all to the main Fly-Canto.

At the same time I'll remove any statuses that you don't need.  Here is the current list is Fly-Canto: https://curation.pombase.org/flybase/view/object/cv/8?model=track

**Comment by gm119** [comment]
1. re priorities, I implemented this as integers (as discussion with Vitor indicated that this would be simpler for Canto) - sorry that this info wasn't already on this ticket.
Values can be any integer between 0 and 36 (wide-range is to separate out papers well).

For the input file, what format would you like the list of priorities to be - do you want full input json, or is tsv with PMID<tab>priority sufficient ?

2. statuses

@vmt25 will have to comment on what of the existing statuses can be removed, and also what the text description for the new statuses should be (to go in 'Definition' in Canto), but here is the list of new statuses so you have them to be doing on with:

DISEASE
LOW_PRIORITY
PHENO
PHENO_ANAT
PHENO_CHEM
PHENO_DATASET
TRAINING

Again, what is your preferred format for input ?

3. @vmt25 - do you have handy a list of all the FBrfs+PMIDs that are currently in the Fly-Canto so I can easily make these lists ?

**Comment by kimrutherford** [comment]
> Values can be any integer between 0 and 36 (wide-range is to separate out papers well).

OK, I'll make that change.

> For the input file, what format would you like the list of priorities to be - do you want full
> input json, or is tsv with PMIDpriority sufficient ?

> Again, what is your preferred format for input ?

Is that to update the publication that are already loaded?  For that just a three column TSV would be good with PMID, status and priority.

**Comment by gm119** [comment]
> Is that to update the publication that are already loaded? For that just a three column TSV would be good with PMID, status and priority.

yep, I did mean to update the already-loaded publications, sorry for lack of clarity. 

Will make three column TSV as you suggested for these once have the list of already-loaded pubs from @vmt25

**Comment by kimrutherford** [comment]
> > Values can be any integer between 0 and 36 (wide-range is to separate out papers well).
>
> OK, I'll make that change.

I've added those.

**Comment by kimrutherford** [comment]
> @vmt25 - do you have handy a list of all the FBrfs+PMIDs that are currently in the Fly-Canto so
> I can easily make these lists ?

Canto doesn't have the FBrfs but here are the PMIDs in case it helps: [flybase-pubs.txt](https://github.com/pombase/canto/files/4643550/flybase-pubs.txt)

**Comment by gm119** [comment]
thanks ! the PMIDs do help - will set off on making your these lists, should get them done today

**Comment by gm119** [comment]
attaching three column tsv file containing status and priority info for the pMIDS in flybase-pubs.txt (except for 119583 which does not exist as pmid in FlyBase files - and I think I made by accident when testing canto a couple of weeks ago !)

[status_and_priority_for_already_in.txt](https://github.com/pombase/canto/files/4643706/status_and_priority_for_already_in.txt)

**Comment by vmt25** [comment]
> @vmt25 will have to comment on what of the existing statuses can be removed, and also what the text description for the new statuses should be (to go in 'Definition' in Canto), but here is the list of new statuses so you have them to be doing on with:


I was playing with this, and making some progress, just before my leave, but not there yet and my memory is not great, so apologies if this does not make sense.

Not totally sure about what to be deleted, because a) there seem to be some dependencies on the publications statuses in the admin page publication tree and b) I'm not sure whether all types seen must exist as cv terms or only the top ones. could @kimrutherford comment?

It is also possible simply not display some types we do not need/use without having to remoev terms from the database. 

Please see the terms not needed at the bottom. My plan for the admin page was to remove/not add/not display them and simply stick with the sub-tree under 'Curatable' for all the statuses we want to implement - and remove Curatable!
I was getting there but fighting with a basic lack of skill, some syntax issues and keeping track of all changes needed in canto_deploy.yaml, where these cvs can be added.



Not used:
Structure publications 
Phenotype screen publications
Curatable low priority publications
Community curatable publications
Publications with a community session
Uncuratable publications and 'child' publications
Community curated publications
Publications without corresponding author
Sessions with term requests
All community sessions
Community sessions never sent
Community sessions not started and never sent

Not sure:
Sessions without a curator
un-triaged publications (not sure if needed due to some dependencies?)

**Comment by kimrutherford** [comment]
> a) there seem to be some dependencies on the publications statuses in the admin page publication tree

We can remove any reports on the admin page that mention statuses that you don't use.  And it wouldn't be a problem because the reports will just give zero results if a status doesn't exist.

> b) I'm not sure whether all types seen must exist as cv terms or only the top ones.

Sorry I don't understand that one.

> It is also possible simply not display some types we do not need/use without having
> to remoev terms from the database.

Everything following the "Reports" heading on the main admin page is completely configurable.  The configuration is here: https://github.com/pombase/canto/blob/037064d7a9d91eb6cc714b008c78de0b1ec06a76/canto.yaml#L1240 
and it can be complete overridden in the canto_deploy.yaml

And it's also possible to configure new reports based on your status codes and priorities.

I'm happy to have a Skype chat about this anytime.  Sorry that it's not documented.

> Not used:

Some of the things in your list aren't status related.  For example "Curatable low priority publications" shows a table of low priority publications.

The current possible statuses are here:
https://curation.pombase.org/flybase/view/object/cv/8?model=track

Today I spotted a place in the code where the "Curatable" status was hard-coded.  I've just modified that code to make Curatable optional.  So now we should be able to completely replace the current statuses with your list.

**Comment by kimrutherford** [comment]
> attaching three column tsv file containing status and priority info for the pMIDS in flybase-pubs.txt 

Thanks Gillian.

I've updated the existing publications:
https://curation.pombase.org/flybase/view/list/all_publications?model=track

Please let me know if you spot any problems.

**Comment by gm119** [comment]
I had a quick look and it looks good to me - this should really help prioritize curation - thanks !

**Comment by vmt25** [comment]
Yes

> I've updated the existing publications:
> https://curation.pombase.org/flybase/view/list/all_publications?model=track
> 
> Please let me know if you spot any problems.

Looks great, thanks

**Comment by vmt25** [comment]
This seems to be done. Closing ticket
