### ISSUE TITLE
naming unnamed alleles?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2256]
In canto I'm checkin a paper which says
The Rho1 thermo-sensitive mutant Rho1-596 carries a missense mu- tation causing a Cys17-to-Arg substitution in the GTP-binding domain; Rho1.C17R almost disappeared from cell extracts upon mild heat shock (Viana et al., 2013).

nut the rho1-596 allele appeared as 'unknown'

so I added synonym rho1.C17R
and C17R

but in Pombase it already  seems to be called C17R?
https://www.pombase.org/genotype/596-C17R-amino_acid_mutation-expression-wild_type_product_level

**Comment by mah11** [comment]
No, the URLs for genotype pages are built from the name(s), description(s), and expression of the allele(s) in the genotype. So the 'C17R' in that URL is the description; the name is just '596' (which is atrocious and since I've found the session I'm about to fix it).

There's no problem with Canto.

**Comment by ValWood** [comment]
Right.  Got it.
