### ISSUE TITLE
generic Canto bug/ retrieves on names

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2270]
I accidentally searched on cdc2 instead of the gene name.
This shouldn't work right, we need people to use Unirpto IDS? (in fact, it only seems to retrieve cerevisie pombe names).

The reason this isn't practical is that  it will retrieve (presumably every  protein with a particular name), so best to disable it.

@RLovering

(If there has been any  other discussion please add here)

**Comment by kimrutherford** [comment]
> I accidentally searched on cdc2 instead of the gene name.
> This shouldn't work right, we need people to use Unirpto IDS?  (in fact, it only seems to retrieve cerevisie pombe names).

I've tracked this down and I think I've fixed the problem.  Probably were using gene names that had been used before in the UniProt Canto.  The lookup code was checking for the name the local cache in Canto's database first before querying UniProt because it's faster.  I've changed it so that it only looks up UniProt IDs in the local cache.

Let me know if you see the problem again.

**Comment by ValWood** [comment]
I thought I would just confirm and got '0' genes added ,  this lead me to check what happens if I add a  list with a garbage ID

TO do this i was using this test session
https://curation.pombase.org/uniprot/curs/a606c5a2c39fa9b3/edit_genes
I could delete one entry
Q8Z9U1 

but not

O16850
P15436

(this could be a none issue if these were added by name originally, it might not be possible to remove them, but purging the sessions will remove the problem)

So, probably all OK.

**Comment by kimrutherford** [comment]
> So, probably all OK.

Thanks for checking.  I'll close this.
