### ISSUE TITLE
New range needed for 'involved in biological process' extension

### ISSUE THREAD

**Issue by CuzickA** [pombase/canto#2276]
Problem found with
GO:0045087 innate immune response
GO:0052200 response to host defenses

Type in text and it does not appear in list

![image](https://user-images.githubusercontent.com/11753634/80470700-4495d500-893a-11ea-98f1-e864980bece0.png)

Look up GO term id in QuickGO and enter this in box and term is found
![image](https://user-images.githubusercontent.com/11753634/80471032-bd952c80-893a-11ea-835c-c265419f99bf.png)
Is is possible to select this term for the AE BUT there is no option to drill further down to child terms.

@jseager7 this bug seems similar to the problem we had with some of the BTO terms only loading with term ids.

**Comment by jseager7** [comment]
I think this might be a problem with the molecular function annotation extension configuration. We use PomBase's configuration now though, so I can't change it myself. The relevant row is as follows:

domain ID | subset relation | extension relation | range ID | Canto display text | Help text | cardinality | role
-- | -- | -- | -- | -- | -- | -- | --
GO:0003674 | is_a | part_of | GO:0009987\|GO:0051641 | involved in biological process |   | 0,1 | user

@mah11 is this happening because 'innate immune response' (GO:0045087) and 'response to host defenses' (GO:0052200) are not children of the range terms 'cellular process' (GO:0009987) or 'cellular localization' (GO:0051641)?

**Comment by mah11** [comment]
@jseager7 
> is this happening because 'innate immune response' (GO:0045087) and 'response to host defenses' (GO:0052200) are not children of the range terms 'cellular process' (GO:0009987) or 'cellular localization' (GO:0051641)?

Most likely, yes. This may be a case where the PHI-base configuration has to diverge from PomBase's -- we can use the "cellular" range terms because fission yeast is unicellular and therefore doesn't do anything that falls outside those branches of GO. For PHI-base you my want to make any GO biological process available in the MF-part_of-BP configuration (if not, I'm not in a position to advise what to exclude).

**Comment by ValWood** [comment]
Yes you will need some additional configuration.
It would be nice if you could somehow keep the core set, and add a supplementary set.
We can discuss how this might work.

It seems a shame to maintain totally independently.

**Comment by jseager7** [comment]
> It would be nice if you could somehow keep the core set, and add a supplementary set.
We can discuss how this might work.

TSV is a fairly easy format to work with, so we can probably keep an additional table of PHI-base specific config in our config repository (although that's private so maybe a public repository would be a better place), then have some logic somewhere, either on the PHI-Canto server or using GitHub's build systems, that will combine and/or override the extensions in the PomBase configuration.

Best case, we could extend Canto so that it can load multiple extension config files in a hierarchy where each higher config file overrides the last, but that's probably not worth doing if we're the only ones who need it – unless we anticipate that almost every new version of Canto will want to use the same general set of GO extensions that you use for PomBase.

**Comment by jseager7** [comment]
@kimrutherford For the time being I can probably fix this with some hacky shell scripting on our server, just by substituting the relevant line in GO_MF_A_E_config with the correct values, but please let me know if you have any better ideas.

**Comment by ValWood** [comment]
PomBase config  should be generally applicable (I think?). It's only that we haven't concerned ourselves with making extension configurations for terms outside our area of interest.

It would be good to do this in the way that new users can take advantage. The generic GO  Canto would probably use the additions.

It probably wouldn't harm to add everything to our config. ...we would not be affected if we didn't  use the terms.

However, some like "occurs" in 'cell-type" we would not want to see on cell level processes.

We need to discuss a way to generalise as much as possible.

**Comment by ValWood** [comment]
If this is not resolved before we can discuss on the next call.

**Comment by kimrutherford** [comment]
> It would be nice if you could somehow keep the core set, and add a supplementary set.

No changes are needed to Canto to get that to work.  We'd need to pull out pombe specific config into a separate config file for each annotation type, then load the "core" config and the pombe config. PHI-Canto would load the core and the PHI-base specific config.

**Comment by jseager7** [comment]
> No changes are needed to Canto to get that to work. We'd need to pull out pombe specific config into a separate config file for each annotation type, then load the "core" config and the pombe config.

Based on what Val was saying here:

> The generic GO Canto would probably use the additions required by PHI-Base

It sounds like the situation could be more complicated, in that PomBase would need to override a general rule that's already set with a more specific rule.

**Comment by ValWood** [comment]
That's correct. We can discuss how best to do this ....I'm not sure...

**Comment by jseager7** [comment]
If we have to use an override method, and assuming we don't want to change the subset relation, then one option is to treat the first three columns of the extension config table as unique key that identifies a particular extension. For example, the following rows would be uniquely identified (due to the differences in their 'extension relation' name):

domain ID | subset relation | extension relation | range ID
-- | -- | -- | --
GO:0003674 | is_a | **happens_during** | GO:0022403\|GO:0033554\|GO:0072690
GO:0003674 | is_a | **has_qualifier** | PBHQ:002\|PBHQ:004
GO:0003674 | is_a | **occurs_in** | GO:0110165

Then, if you wanted to override a specific extension, you would add another extension table with a row whose first three columns match a row in the core table, but with a different range ID:

domain ID | subset relation | extension relation | range ID
-- | -- | -- | --
GO:0003674 | is_a | occurs_in | **GO:0045177**

And Canto could then override the values from the core table with the values in the supplementary table.

Of course, this won't work if you need to change the 'subset relation' (e.g. from is_a to part_of). If we can guarantee that no two extensions will have the same domain ID and the same extension relation name, then we can use those two values as the unique key, and that will allow us to override the subset relation as well, if we have to.

**Comment by kimrutherford** [comment]
I think it will be OK if the "core" config file only has rules that work for all databases.  If a rule needs to be overridden then it shouldn't be in the core file.

If that is too awkward we could also put specific configuration earlier in the configuration file - the first match is used and any others are ignored.

**Comment by jseager7** [comment]
> If that is too awkward we could also put specific configuration earlier in the configuration file - the first match is used and any others are ignored.

I didn't realise that was the case, but that seems easier. So if we specified the extension config files as below, that would lead to the extended config overriding the core config?

```yaml
extension_conf_files:
  - /import_export/extended_extensions.tsv
  - /import_export/core_extensions.tsv
```

How is the matching performed? Is it just based on domain ID? I feel like I've asked this before.

**Comment by kimrutherford** [comment]
> How is the matching performed? Is it just based on domain ID? I feel like I've asked this before.

The first configuration where the domain matches is used.  The downside of this approach is that it can be hard to debug.  We'd need to take care that the order of lines in the configuration was correct.

**Comment by jseager7** [comment]
So in situations where you're only trying to override one extension relation (out of multiple) on a domain ID, does the first extension config override all subsequent configs?

For example, if the first loaded config file had this:

domain ID | subset relation | extension relation | range ID
-- | -- | -- | --
GO:0003674 | is_a | occurs_in | **GO:0045177**

And the second file had this:

domain ID | subset relation | extension relation | range ID
-- | -- | -- | --
GO:0003674 | is_a | happens_during | GO:0022403\|GO:0033554\|GO:0072690
GO:0003674 | is_a | has_qualifier** | PBHQ:002\|PBHQ:004
GO:0003674 | is_a | occurs_in | **GO:0110165**

(With the intention that you only wanted row 1 of the first file to override row 3 of the second file)

Would the override only enable the rows in the first extension file, therefore effectively ignoring all three rows in the second file?

**Comment by kimrutherford** [comment]
> the first match is used and any others are ignored.

> The first configuration where the domain matches is used.

Sorry, I shouldn't comment late at night after my brain has turned off for the day.  This isn't true at all. Canto needs to display all matching configuration because there is often more than one extension type for a term, as in your example.

**Comment by jseager7** [comment]
> Canto needs to display all matching configuration because there is often more than one extension type for a term, as in your example.

So without implementing some new system, we can't include any rule in the core extension config unless it's exactly the same for all versions of Canto that use the core config?

**Comment by kimrutherford** [comment]
> So without implementing some new system, we can't include any rule in the core extension
> config unless it's exactly the same for all versions of Canto that use the core config?

Yep, that's my suggestion.  I get the impression that a lot (maybe the majority?) of extension configuration will be the same for everyone.

At some point we talked about adding a taxon column so that extensions could be taxon constrained. I think that would help.

**Comment by ValWood** [comment]
@jseager7  is this sorted by the other ticket?

**Comment by jseager7** [comment]
@ValWood No, the other ticket was about a missing domain term on the extension (the extension not being available for a term), whereas this issue is about missing _range_ terms (the extension is available but some terms are not suggested). Specifically, PHI-Canto can't see GO:0045087 'innate immune response' and GO:0052200 'response to host defenses' in the 'involved in biological process' extension.

I was opting to fix the other issue first because it's blocking the GAF submission, and because it's possible – but tedious – to work around this issue by entering the GO term ID manually.

I'm not sure if the terms in 'innate immune response' and 'response to host defenses' would be hidden from the term suggestion list by taxon restrictions in PomBase. If not, it might not be appropriate to amend PomBase's config with these new range terms.

**Comment by ValWood** [comment]
You can go ahead and add. These terms have taxon constraints.

**Comment by jseager7** [comment]
These terms have been added to PomBase's configuration now. They're already enabled on the demo server (see below for images), and should be enabled on the main server by tomorrow. Closing now.

#### Innate immune response
![image](https://user-images.githubusercontent.com/37659591/97858515-2d73dd80-1cf7-11eb-94c4-0336e275eaf0.png)
#### Response to host defenses
![image](https://user-images.githubusercontent.com/37659591/97858553-38c70900-1cf7-11eb-99c5-2711216ca0b1.png)
