### ISSUE TITLE
Create 'session on hold' status

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2281]
For curation sessions that are on hold because e.g.
a) it is waiting some information/clarification from authors regarding e.g. an allele identity
b) waiting for some curation policy decision.

So this would be different from 'curation paused'.
'Curation paused' would be more applicable to 'I am in the middle of this and had to stop to have a break or because the working day is over'
'Curation on hold' would be applicable to sessions needing exterior input.

P.S. I assume this would need some changes to the Admin publication list configuration on canto_deploy.yaml

**Comment by ValWood** [comment]
"curation paused'  is really only a  only a 'security blanket' to make community curators feel 'safe' that they have left their work is saved. You can in fact leave a session and  come back any time without using the pause button. Everything will still be there. So in effect that pause button is a  meaningless dummy button.


If we have things which need to be resolved we would flag them in the comment  (or term suggestion box), so that when we return to a session we know exactly what we still need to do. 

Do you need this   so that  you can easily separate sessions that you can currently continue from 'waiting' ?
If so  now that you know that "curation paused' isn't really doing anything, you could use that button for waiting  temporarily.

I guess it would be a useful status, but it might be a bit complicated. Our users probably would not need it because that are not dealing with lots of sessions simultaneously.
It seems that you would need
CURATION IN PROGRESS_AWAITING _FEEDBACK
We could use it in approval, but this would then be an additional approval status
IN_APPROVAL_AWAITING_FEEDBACK 

Note also, that there is also  this list  of outstanding term requests in the admin interface 
https://curation.pombase.org/pombe/view/list/sessions_with_term_requests?model=track
maybe this could be extended to include more outstanding query types?

My ,main concern is that we would  like to overhaul the admin interface at some point  (there are 39 open tickets),  many relating to session management
For example
https://github.com/pombase/canto/issues/980
https://github.com/pombase/canto/issues/284

This Admin interface overhaul  has  never got to the top of the list, because we usually have more pressing things to do. It could be slicker, but it works./

Maybe it would be better to concentrate on the non-admin options for now and then get together as a group in a  few months to spec out how we could improve the admin part for all of us? I'm worried that we might be requesting partially overlapping changes, or changes which will be negated by future revisions, but to be honest I can't remember what is in there now!

**Comment by ValWood** [comment]
Maybe the way to do this is to introduce more "suggestion" options like term suggestion, or in session flags for when things are pending, and then use these to  automatically assign to the 'sub status"

Approval_in_progress_awaiting_feedback
or
Curation_in_progress_awaiting feedback.

Another consideration- just because you are waiting for feedback on one question does not mean that you cannot proceed with the rest of the session. So I guess what you want to  indicate that the session cannot be finalised until you have that info, but you have done everything that you can?

We would submit a session which is complete, but requires an additional change which needs fixing, because the fix can be done in approval.
Do you use the approval options? If so does "approval in progress" work?

I think we would need to know more about your workflow to work out a  general solution.

**Comment by vmt25** [comment]
> "curation paused' is really only a only a 'security blanket' to make community curators feel 'safe' that they have left their work is saved.

> Do you need this so that you can easily separate sessions that you can currently continue from 'waiting' ?
> If so now that you know that "curation paused' isn't really doing anything, you could use that button for waiting temporarily.
The purpose is exactly that of clearly marking 'waiting' sessions. We are aware that 'curation paused' does not really do anything and could use it for this purpose.

> Another consideration- just because you are waiting for feedback on one question does not mean that you cannot proceed with the rest of the session. So I guess what you want to indicate that the session cannot be finalised until you have that info, but you have done everything that you can?

Actually, that is what we do. We do all the curation possible, sometimes annotating data to 'placeholder' alleles for which we don't have a clear id (also the reason why I made #2282, for the creation of temporary/placeholder alleles in a standardized manner so that we FB phenotype curators cannot create alleles at will). So, yes, this would be an indication of "session cannot be finalised until you have that info,"


> We would submit a session which is complete, but requires an additional change which needs fixing, because the fix can be done in approval.
> Do you use the approval options? If so does "approval in progress" work?

We are using the approval process a) because that is the way to export the sessions into FlyBase and b) it is being helpful in the training of a new curator, as a way to mark that all has been checked. But we don't really need it, so could use it for this purpose.

The 'curation on hold' is more a wish that a need, so that there is a status more clearly defined as 'waiting for stuff' rather than the 'coming back to this tomorrow' feel of 'curation paused' because records with stuff waiting are not ready for submission/release on the website. Also, curation paused does not let you see what already is on record, which is not helpful.

The 'waiting approval' maybe works better because you can see the annotations while the session is on that status, but I'll have to explore its capabilities. Again, the name is not exactly right, because it is not always a matter of changing an allele id, it can be pretty substantial work.

Anyways, we could make our internal policy to use either 'curation paused' or 'approval in progress' for the 'on hold' purpose.

**Comment by kimrutherford** [comment]
On the call we talked about adding the "Edit message to curators" link to the "Curation paused" page.  That would be a quick fix to allow the curator to make a note about why the session was paused.  The link would only be visible if the user is logged in as admin.

**Comment by vmt25** [comment]
It would be useful that this 'message for curators' is different from the one added within session, in that it is only associated to the paused status:
a) only shows up in the paused menu
b) is temporary and disappear when curation is resumed/submitted

**Comment by vmt25** [comment]
Context for the sake of the reader: Using the 'curation paused' status, in combination with the message, would fulfill the aim of this issue.

**Comment by kimrutherford** [comment]
Hi Vitor.

I have implemented this, hopefully how you wanted it.  There is now an "Add message" button on the "Curation paused" page.  This message will persist on that page and in the database until you un-pause the curation.  Let me know if it worked how you planned.

![paused-message-1](https://user-images.githubusercontent.com/90474/100180137-6b51d380-2f3c-11eb-9844-9d8530689fbc.png)
![paused-message-2](https://user-images.githubusercontent.com/90474/100180147-6f7df100-2f3c-11eb-9930-4ce94457c9a8.png)
![paused-message-3](https://user-images.githubusercontent.com/90474/100180150-73117800-2f3c-11eb-9a13-54fdbad92fcb.png)

**Comment by vmt25** [comment]
Hi Kim,

Yes, that works exactly how we discussed it. Thanks.

Closing ticket
