### ISSUE TITLE
Create .phen records for approved Fly-Canto sessions that do not have any CV annotations

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2285]
Make “canto_json_output_parser.pl” create records for all papers lacking controlled vocabulary annotations.

There are two examples in canto-flybase-export-20-05-06.json (now archived) for PMID:29931724 and PMID:3112771.

The json output for this kind of publications always has on the metadata section:
a) "annotation_status" : "APPROVED"
b) and an extra "no_annotation_reason" : ' line with a reason for the absence of annotations, which can be either:
	(i) a predefined value from a list by PomBase e.g. 'Review' or'Experimental data, not of available types'
	(ii)  or ‘Other’, which prompts free text input from the curator, which can be something like “only found pheno_chem data”, “no pheno data to capture”, “only negative phenotype data captured as free text descriptions.” , etc

If no data is added - either CVs or notes/free text - the json
file will only show the gene/allele and metadata sections -
e.g. FBrf0240885 / PMID:29931724

If notes/free text are added, the json will shows the notes under
the associated allele
(cannot find any test export file with that example - apologies)

**Comment by vmt25** [comment]
To discuss:
a) include the reason for absence of annotations as internal notes?
b) if so, configure the pre-set reasons for FlyBase purposes (on canto_deploy.yaml)?

**Comment by vmt25** [comment]
Hi Gillian, 

Thi problem still occurs.

Also, I had another check at this and I can confirm that the curator has to click the 'No experimental results to add?:' box to submit records with no annotations, regardless of the presence of notes (phenotype/interactions/rescues free text or internal notes).

If you want to play around, the attached zip file has two export jsons with 'empty' sessions, with the extra "no_annotation_reason" : ' line.

canto-flybase-export-20-07-02.json is last week's automated file and has 2 empty sessions (for "PMID:30666901" and "PMID:30426565") from Arzu, without iany text/nternal notes.

test-negative_08072020.json is a mock export json and has just one session (for "PMID:16116079") without CV annotations, but with a phenotyoe free text.

Of importance, sessions withouth anything  (annotations or text) only show the metadata part, whereas sessions with text/notes show the genes and alleles.

Thanks

[no–annotations-Canto.zip](https://github.com/pombase/canto/files/4891436/no.annotations-Canto.zip)

**Comment by gm119** [comment]
I believe that I have fixed this issue, and new code is updated on svn in time for tomorrow


a. Now a curation record is made when there are no annotations and no notes/free text.
The 'no_annotation_reason' is used to generate an internal note and/or triage flag as follows, depending on its value:
no_annotation_reason = 'No phenotypic data' -> internal note: phen curation: No phenotypic data in paper.

no_annotation_reason = 'Only pheno_chem data' -> internal note: phen curation: only pheno_chem data in paper. PLUS P40: pheno_chem added

no_annotation_reason = anything else - text added as is to internal note

b. The code was already coping with the case where only notes/free text are added (but no CV annotations) and making a curation record, but now it also uses 'no_annotation_reason' to generate an internal note and/or triage flag as described in a. above.

I think it would be good if the canto interface to encode the:
'No phenotypic data' 
'Only pheno_chem data'
options as predefined values rather than having to be filled in as free text each time under 'Other:' by the curator - @vmt25 is that a yaml config file thing ?

Plus it would be good to settle on a standard phrase for the 'no annotation reason' for te case where there are no annotations but there is a note/free text added under allele(s) - in that case I think I'd get the code just to ignore the no annotation reason (no need for internal note). We could use the 'only negative phenotype data captured as free text descriptions.', but I bet there would be the odd case where its not all negative phenotype data, so maybe just 'No CV annotations possible' or something ?

**Comment by vmt25** [comment]
Cool!

> I think it would be good if the canto interface to encode the:
> 'No phenotypic data'
> 'Only pheno_chem data'
> options as predefined values rather than having to be filled in as free text each time under 'Other:' by the curator - @vmt25 is that a yaml config file thing ?

Yes, it is.
I just have to add an extra bit to the canto-deploy.yaml file and ask Kim to reload Canto.

**Comment by vmt25** [comment]
> I just have to add an extra bit to the canto-deploy.yaml file and ask Kim to reload Canto.

This bit is done on the canto_deploy.yaml file in the repository.

This ticket can be closed.
