### ISSUE TITLE
Show background in metagenotype annotation table

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2295]
In  PHI-Canto metagenotype annotations, background is not visible.

See for example

<img width="1124" alt="Screenshot 2020-06-08 at 10 20 59" src="https://user-images.githubusercontent.com/7359272/84014403-2b893680-a972-11ea-87ed-f313b6b55851.png">

these are not the same genotype but they appear to be.

can we remember why we did not include the background?

sometimes we will have host @ pathogen  background  so 2 separate columns might be too much. 

Could the multigenotype background be added into the respective  genotype column?

**Comment by jseager7** [comment]
> can we remember why we did not include the background?

I can't remember, but I presume it was because the table rows already had a lot of information in them. I can look at adding the background for each genotype to their respective columns.

**Comment by jseager7** [comment]
Here's a mockup of how this could look:

![image](https://user-images.githubusercontent.com/37659591/84016697-8b351100-a975-11ea-9df3-04e778f51dbf.png)

Note that the 'bkg' abbreviation for 'background' has been used elsewhere in Canto, which is why I chose it here, but we could have any label for the background name.

**Comment by ValWood** [comment]
> I can't remember, but I presume it was because the table rows already had a lot of information in them.

We thought that must be why.
I think it would make sense  to add as per your mock-up
bkg is fine.
