### ISSUE TITLE
Add 'compared to control genotype' extension

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2296]
We have decided that we need an additional extension option.

We really need in some cases  to have some way to link an annotation to the control in the gene for gene experiments.

We decided that it would be better to introduce a mechanism to do this more generally using an annotation extension.

 The extension option would be 
"compared to control genotype" and the options in the pull down would be all of the genotypes in the session.

We can chat about this on the next call.

**Comment by ValWood** [comment]
Note that this will probably be a configuration option required by most  species that use Canto for curation.  The only reason we never need it for  fission yeast phenotype is that  we always use the same strain.

**Comment by jseager7** [comment]
Is this needed for PHI-Canto only?

**Comment by jseager7** [comment]
Sorry, ignore that – I didn't read your comments properly. What I should've asked instead is whether PHI-Canto prompted the need for this annotation extension.

**Comment by ValWood** [comment]
>whether PHI-Canto prompted the need for this annotation extension.

yes, other users so far haven't required it. I'm not sure what Flybase do

**Comment by jseager7** [comment]
Extensions are never part of Canto's core configuration, and we don't currently have any shared extension config except the ad-hoc sharing of GO extensions between PHI-base and PomBase.

So, presuming the original comment refers to phenotype annotations, we can enable this extension 
on PHI-Canto as soon as we have a way to link an annotation to a genotype (presuming that's not possible already; I know it's currently possible for genes). Any other users of Canto can opt-in to the extension when they're ready.

**Comment by mah11** [comment]
Note: this is veering towards the notion of "dependent phenotypes" that [OMP](https://microbialphenotypes.org/) uses - see PMID:25433798: "Finally, OMP employs the qualifier “altered_relative_to” for dependent phenotype terms, which denote a difference in phenotype between organisms of two different genotypes or the same genotype assessed in two different environments."

**Comment by jseager7** [comment]
> Note: this is veering towards the notion of "dependent phenotypes" that OMP uses

That would imply we'd need to be relating one phenotype annotation to another phenotype annotation, rather than to a genotype. @ValWood is there always an annotation capturing the wild-type control phenotype? If so, I think reusing what OMP has (or at least following their example) would make more sense.

**Comment by mah11** [comment]
I guess I should add a caveat: it's been ages since I looked at OMP's stuff in detail; I brought it up because I remembered the general point that they came up with a way to make a reference explicit (as opposed to the implicit "reference lab strains = normal" that we can get away with for S. pombe). I therefore don't have a good idea how readily their system could be adapted for use with Canto.

**Comment by jseager7** [comment]
Nevertheless, I think long-term for PHIPO it's likely that we'll need some way to indicate relations between phenotype annotations, because it might help us decompose some of our very complex phenotypes (e.g. involving mutual interaction between pathogen and host) into two phenotypes linked by some causal relation. I expect this would also help us align PHIPO to uPheno's phenotype reconciliation effort. So I think it would be useful to explore how other ontologies are handling this.

**Comment by jseager7** [comment]
@kimrutherford Do annotations have a unique identifier in Canto? I can't see one in the export format. We'd probably need this to provide a range ID for the annotation extension.

**Comment by ValWood** [comment]
I think we can use > “altered_relative_to” 
but we still want to specify the genotype and not the phenotype (I'm assuming that is what OMP do?)

We will have already made the phenotype annotation for the control, but not linked them.

We need to record the starting genotypes because this is a gain or or loss of phenotype mutant related to a starting particular genotype. It's the starting genotype we want to capture in the instances so we know what was being compared to. The starting phenotype can be derived from this information.

We don't want to over complicate it or the users won't be able to curate. It is true that computationally it won't be trivial  to connect but the end-user only really needs the genotype to figure this out.

**Comment by kimrutherford** [comment]
> Do annotations have a unique identifier in Canto? I can't see one in the export format.
> We'd probably need this to provide a range ID for the annotation extension.

There is an internal integer ID for annotation, but no systematic unique ID that we could use in this case.

**Comment by kimrutherford** [comment]
> I'm not sure what Flybase do

It hasn't come up in the chats we've had with them.

**Comment by jseager7** [comment]
We've decided we need to add a new annotation extension for this. The extension will relate a pathogen-host interaction phenotype annotation to the metagenotype representing its control case.

@kimrutherford In order to add this, I'll need a new range ID on the extension config for metagenotypes, analogous to what we already for genes (GeneID).

**Comment by kimrutherford** [comment]
> The extension will relate a pathogen-host interaction phenotype annotation to the
> metagenotype representing its control case.

Ah, I thought the extension needs to have a genotype as it's range.  Val could you confirm?

**Comment by ValWood** [comment]
Yes it's the genotype in the extension.

**Comment by jseager7** [comment]
> Yes it's the genotype in the extension.

@ValWood In the last call I thought we discussed something about relating a pair of genes (presumably pathogen and host) as a control for a pathogen-host phenotype annotation. Linking a pair of genes implies linking a metagenotype, since otherwise we'd only be linking the pathogen gene or the host gene separately. Was this discussion referring to a different annotation extension to the one mentioned here?

**Comment by ValWood** [comment]
Yes more specifically its a metagenotype.

**Comment by kimrutherford** [comment]
The code changes are done so we can try this out now.

**Comment by jseager7** [comment]
I've enabled this on the PHI-Canto test server and it seems to work fine. See below for an example:

![image](https://user-images.githubusercontent.com/37659591/86016116-51a67180-ba1a-11ea-88b6-068b88b7808d.png)

I've noticed that metagenotype display name tends to be long enough to get truncated, but you can still hover over the ellipsis to see the full name:

![image](https://user-images.githubusercontent.com/37659591/86016830-34be6e00-ba1b-11ea-90ec-3daea2682704.png)

The extension configuration is shown below, in case anyone wants to revise the text or cardinality:

domain ID | subset relation | extension relation | range ID | Canto display text | Help text | cardinality | role
-- | -- | -- | -- | -- | -- | -- | --
PHIPO:0000001 | is_a | compared_to_control | MetagenotypeID | compared to control genotype |   | 0,1 | user

- - -

@kimrutherford I've noticed that it's possible to relate a metagenotype to itself, which probably isn't necessary or sensible. We should think about filtering out the metagenotype of the annotation from the list. 

This might be difficult to fix in the general case, but assuming a feature never needs to be related to itself, then we can probably just exclude the instance of the feature from the list that gets returned. For example, if an annotation on gene _ABC1_ could be extended with a GeneID, then the code would filter out _ABC1_ from the gene list, but if the extension was for a GenotypeID, nothing would be filtered out.

**Comment by jseager7** [comment]
This is enabled on the production server now, so I'm going to close this issue. We can open new issues for any problems that show up.
