### ISSUE TITLE
Display of extension options in the copy/edit menu

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2339]
Not obvious how to add extensions in copy edit menu
I have seen this situation quite a few times now:

<img width="961" alt="Canto open ticket" src="https://user-images.githubusercontent.com/7359272/89635675-3f341900-d89f-11ea-8c94-962bc281ef42.png">

People are mainly using the "copy edit" for annotation, but the annotation extensions become very non-obvious in the copy edit window.

At some point we must've decided not to show them, but we should probably reconsider this. 
I have been discussing the same with @CuzickA for PHIPO, they will definitely want to display the extension options by default.

I guess the problem will be that some extensions require more than a simple box, so perhaps an option would be to show the most used by default and a link to others.....

The use of extensions would definitely improve if they were more accessible  from the copy/edit menu

**Comment by ValWood** [comment]
Dan has done a couple of papers, and he knows  he can  say which protein are affected but he can't see how, so we  are doing something wrong.

**Comment by jseager7** [comment]
We could show links to each extension in the popup window, meaning the names of the extensions would become links. In the case of extensions that have already been set, the values can just be shown next to the name (as is currently the case), so this should be fairly efficient on space. Here's a mockup:

![image](https://user-images.githubusercontent.com/37659591/92394017-af40f380-f118-11ea-81cb-e1afeaae91fa.png)

In the example above, three of the extensions haven't been set. To add an extension, the user would click the name of the extension. The same method would work for extensions that have already been set (if the cardinality of an extension permits adding another value, otherwise the link would be disabled).

For reference, here's a summary of the maximum number of extensions per term in each of the extension files used by PomBase and PHI-base. This number would equal the number of links we would show in the list. Even if we show all the extensions, the list shouldn't be too long in any case except PSI-MOD. However, I can't see where in Canto the PSI-MOD extensions are used, if at all.

Extension file | Max. extensions
--- | ---
FYPO_A_E_config | 4
GO_BP_A_E_config | 3
GO_CC_A_E_config | 3
GO_MF_A_E_config | 5
phipo_extensions | 6
PSI-MOD_A_E_config | 11

**Comment by ValWood** [comment]
I like that. It's an efficient use of space.

**Comment by jseager7** [comment]
Also, we'd have to decide how to display annotation extensions that allow multiple values (cardinality > 1).

**Option 1**: display the values inline, separated by a comma or some other character. This is the most space efficient, but could get difficult to read if the extension values are complex.

![image](https://user-images.githubusercontent.com/37659591/92396214-90446080-f11c-11ea-9beb-223728e0b239.png)

**Option 2**: display each value on its own line, with indenting for the sake of readability. This is arguably clearer for complex values, but uses more vertical space:

![image](https://user-images.githubusercontent.com/37659591/92396383-d8638300-f11c-11ea-88aa-3437b7ba6fba.png)

**Option 3**: repeat the extension name for every value. This is system that Canto currently uses (but doesn't put each extension on its own line like below). I think this has the clearer meaning when compared to Option 2, with no extra use of space. However, it could add a lot of visual noise to the list.

![image](https://user-images.githubusercontent.com/37659591/92396568-1eb8e200-f11d-11ea-9349-bf48af8890c9.png)

**Comment by ValWood** [comment]
I would vote for comma separated, same line where possible

**Comment by CuzickA** [comment]
Hi @jseager7 I like your mock up of the AEs above and I agree with Val on option 1 for multiple values.

**Comment by jseager7** [comment]
Thanks for the feedback. I'll work on adding this to Canto.

**Comment by jseager7** [comment]
I've discussed this with @kimrutherford, and it seems like implementing what I initially suggested is going to be complicated and difficult.

We agreed that part of the problem could be fixed by making the extension edit button more obvious, which should help a lot when an annotation has no extensions to begin with.

For example, here's how an empty extension section of the pop-up currently looks:

![image](https://user-images.githubusercontent.com/37659591/98807673-e9798a80-2412-11eb-9e8d-4173d2c408a9.png)

The Edit button could be made a lot more obvious with additional styling. Here's a mockup, with the Edit as Text admin-only action also presented as a button:

![image](https://user-images.githubusercontent.com/37659591/98807905-41b08c80-2413-11eb-9749-9790361750ae.png)

Here's how the proposed solution looks when extensions are added:

![image](https://user-images.githubusercontent.com/37659591/98808562-3dd13a00-2414-11eb-80f0-ef62f38426d6.png)

I think this should help make it clearer how to add annotation extensions when in the pop-up-based workflow. It might not help much if the user doesn't understand what annotation extensions are (in which case they won't think to click the button), but hopefully the user should normally go through the step-based workflow first, which should introduce them to the concept of extensions.

I haven't necessarily given up on my original idea – since I think providing links to extensions up-front still has the usability benefit of being more time-efficient, and probably makes the purpose of extensions more obvious – but as an interim solution, this is much easier to achieve. There's no reason why we couldn't combine my initial solution with this one in future.

@ValWood are you happy with the above solution?

**Comment by ValWood** [comment]
@jseager7  sorry for the delay on this, I will comment later, but we probably won't do this for now...

**Comment by ValWood** [comment]
I'm going to close this.
I will evaluate when people don't add extensions (either not at all, or sporadically), then I will ask which workflow they are using (full, or copy edit).

Once I have more information we can think about appropriate solutions.
