### ISSUE TITLE
Redundant call to extensionConfFilter in ontologyWorkflowCtrl?

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2341]
It looks like during the ontology workflow, `extensionConfFilter` is called twice, but one of these calls seems to override the other. The first call is in `ontologyWorkflowCtrl`, in `$scope.updateMatchingConfig`:

https://github.com/pombase/canto/blob/bc4f9192cc6fbd55c5ad4f2c17bdfbcb8815ae7f/root/static/js/canto-modules.js#L3038-L3049

And the second is in the `extensionBuilder` directive, again in `$scope.updateMatchingConfig`:

https://github.com/pombase/canto/blob/bc4f9192cc6fbd55c5ad4f2c17bdfbcb8815ae7f/root/static/js/canto-modules.js#L2614-L2627

If I specify a new argument in the first function, it has no effect on the list of extensions shown during the ontology workflow. Specifying the argument in the second function works as expected.

Out of curiosity, I tried seeing what would happen if I deleted `$scope.updateMatchingConfig` from `ontologyWorkflowCtrl`, and the 'Proceed' button on the evidence code page never enabled. So I guess the code does something, but it's not clear what.

@kimrutherford Do you know what the purpose is for these two separate calls?

- - -

Note that the only other place `extensionConfFilter` is used is in `annotationEditDialogCtrl`, but that use case doesn't have this problem; there's only a single call to the function.

**Comment by kimrutherford** [comment]
> Do you know what the purpose is for these two separate calls?

It's been a while since I looked at this but I think the first call is setting `$scope.matchingExtensionConfigs` so that `ontologyWorkflowCtrl` knows if the extension page should be shown during the workflow.  If there are no matching extension configs, that page is skipped.

The second call is in the `extensionBuilder` controller and is used to actually show the extension options.  It would probably make more sense to pass the matching extensions into `extensionBuilder` (perhaps with a service as you mention in #2335) but it's not that smart at the moment.

I hope that helps.  We should probably have a Skype chat about this and #2335.

**Comment by ValWood** [comment]
Is this a non issue? can we close?

**Comment by jseager7** [comment]
> Is this a non issue?

It's a very minor issue, and I think the problem it aimed to solve has been fixed by #2004. I'll close this issue for now.
