### ISSUE TITLE
Changes to PHI-Canto metagenotype extension workflow

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2345]
We discussed making some changes to the metagenotype annotation extension which will make curation much easier for the users.

Currently,  2 of the options  for extensions are: 
1) "gene for gene" (incompatible or compatible)
and 
2) infective ability (various)

When gene-for-gene is selected, the user  still needs to select 2 infective ability terms, one for the pathogen and one for the host ( and only some combinations are valid for each  gene-for-gene type selected(compatible or incompatible)

For non- gene-for-gene  annotation, a subset of infective ability terms are allowed (but the user sees all of the options).

This means that the user is always faced with  a lot of extensions terms to select from, many of which are nominally similar but subtly different, and many of which are often not relevant for the specific annotation.  It takes quite a lot of time even for an expert curator to make the correct selection.

We would therefore like to change this as follows, we hope this is possible.

1. There would be only one  extension type to cover  gene for gene and infective ability (called infective ability)
2. the first action of the pop-up would force the user to select "gene for gene" or "non-gene for gene"
3. Depending on the selection the user would be presented with the appropriate terms in the pull-down.

4. for gene for gene we would like to precompose the possible combinations which would prevent lots of thinking about  the selections

5. non gene for gene would see only the reduced applicable set

This is  a quick sketch of how it might work:

![WhatsApp Image 2020-09-07 at 12 53 41](https://user-images.githubusercontent.com/7359272/92385287-882ef580-f109-11ea-9780-93ab49c426d7.jpeg)

@CuzickA  (could you also tag K-H-K) @kehammond
Does this align with what we discussed.

@CuzickA  will discuss with @jseager7 and we can chat further about this on the next  PHI-base call

**Comment by ValWood** [comment]
I found this on my desktop, starting point for allowed combinations (this is probably most of them @CuzickA  could you check?

compatible interaction, pathogenic ability present, host resistance absent (disease)
compatible interaction, gain of pathogenicity, host resistance absent (disease)
compatible interaction,  pathogenic ability present, loss of host resistance (disease)
incompatible interaction, pathogenic ability present, gain of host resistance  (no disease)
incompatible interaction, pathogenic ability present,   host resistance present  (no disease)
incompatible interaction, pathogenic ability absent,  gain of host resistance  (no disease) 
incompatible interaction, pathogenic ability absent,  host resistance  absent (no disease)
incompatible interaction, pathogenic ability absent,   host resistance present  (no disease)
incompatible interaction,  gain of pathogenicity,  gain of host resistance
incompatible interaction,  loss of pathogenicity, host resistance absent

**Comment by CuzickA** [comment]
> I found this on my desktop, starting point for allowed combinations (this is probably most of them @CuzickA could you check?
> 
> compatible interaction, pathogenic ability present, host resistance absent (disease)
> compatible interaction, gain of pathogenicity, host resistance absent (disease)
> compatible interaction, pathogenic ability present, loss of host resistance (disease)
> incompatible interaction, pathogenic ability present, gain of host resistance (no disease)
> incompatible interaction, pathogenic ability present, host resistance present (no disease)
> incompatible interaction, pathogenic ability absent, gain of host resistance (no disease)
> incompatible interaction, pathogenic ability absent, host resistance absent (no disease)
> incompatible interaction, pathogenic ability absent, host resistance present (no disease)
> incompatible interaction, gain of pathogenicity, gain of host resistance
> incompatible interaction,  loss of pathogenicity, host resistance absent

@ValWood this looks a good list to start with. We can always add to it if required.

Do I need to make these compound terms as new phipo terms or will they be created some other way?
Are we joining three terms together or going for a 2-step approach where compatible/incompatible is selected first and then the pathogen/host infective ability combination is selected?

**Comment by ValWood** [comment]
I think this post composition should be "behind  the scenes". Something to discuss on Monday...

**Comment by jseager7** [comment]
We've currently decided to move the gene-for-gene annotations into their own annotation type, for two main reasons: 

* so it's more obvious to the curator which annotation type to choose when they're curating gene-for-gene experiments, and

* so we have better control over which terms and annotation extensions to suggest.

However, there are a number of things that need changing to allow this to solve the problem.

### Unresolved issues

* **Canto's configuration can't restrict annotation extensions by annotation type**. The domain of an extension can be limited to a specific ontology term in the extension's _own_ configuration file, but this level of control isn't possible in Canto's main configuration file. If we allowed the configuration file to configure available extensions by annotation type, we'd have to decide which configuration takes priority over the other.

  * **Proposed solution:** add an `exclude_extensions` property to the `available_annotation_type_list` object, that specifies a list of annotation extensions to exclude from the annotation type. The extensions could be identified by their relation name in the extension TSV file. I think exclusion is a better choice than inclusion, since we commonly want to include extensions by default. I'm not keen on scattering the configuration for extensions, but I feel like the canto_deploy file is the best place for this.

* **Canto's annotation type configuration can't restrict by ontology subsets**, only by the ontology namespace. We don't want to change the namespace for this new annotation type (it would still be 'pathogen-host interaction phenotype'), but we _may_ want to restrict the terms that are available to a subset of PHIPO (crossing multiple hierarchies).

  * **Proposed solution:** add a `subsets` property to the `available_annotation_type_list` object, that specifies a list of subset names to include. We'll need to decide which of the `namespace` and `subsets` properties take priority over the other when deciding which terms to include; this will matter if we have subsets that are used across namespaces.

* **Choosing an unambiguous name for the non-gene-for-gene annotation link**. Unfortunately, gene-for-gene phenotypes are a subset of pathogen-host interaction phenotypes, so we'll have to make sure curators aren't confused about when to use a pathogen-host interaction phenotype annotation.

  * **Proposed solution:** we could take a wait-and-see approach, and wait until it's clear that curators are struggling with this; it may be more of a problem for professional curators (not so much community curators), since they're not as familiar with the experiments.
  
  * Note that we'd probably want to exclude the gene-for-gene subset from the pathogen-host interaction phenotype term suggestions, since curators won't have the annotation extensions they need to complete the annotation in this mode. Alternatively, we could have the interface point the curator to the correct curation type if they select the 'wrong' term.

**Comment by jseager7** [comment]
@ValWood @CuzickA I've discussed this with @kimrutherford, and we think the easiest solution is to add a new annotation type for metagenotypes – tentatively called 'gene-for-gene phenotype' – and add an extension that is only shown for that annotation type; the new extension will contain the precomposed list of options that Val compiled above.

I'd appreciate your feedback on the following actions, or at least your opinion on whether or not we should do them:

- **Remove the 'gene-for-gene interaction' extension**, since it will be made redundant by the precomposed list.

- **Create a supplementary ontology to store the precomposed terms**; we could follow FYPO's convention and use PHIPO_EXT as the term prefix.

- **Give the new extension a different name from 'infective ability'** (since we're planning to use the relation name to disambiguate which extension should be assigned to each annotation type). Perhaps we can pick something more specific now that the extension deals with more specific information (namely host resistance genes and pathogen effectors).

**Comment by CuzickA** [comment]
This sounds like a good way to move forward.

Before the changes are made, can we make sure we don't lose the current data in the 'gene-for-gene interaction' extension and 'infective ability' extension as it has taken a long time to add into the sessions. Is there a way of pulling out the current terms used to make sure we have them covered in the new compound terms.

In the supplementary ontology of precomposed terms, we may still need to display the definition of each of the three individual component terms so that the curator understands which to use. Alternatively we could rewrite the definitions for these compound terms.

Perhaps the new extension could be called 'gene-for-gene interaction' instead of 'infective ability'.

**Comment by jseager7** [comment]
> Before the changes are made, can we make sure we don't lose the current data in the 'gene-for-gene interaction' extension and 'infective ability' extension...

When I said 'remove' I meant that the 'gene-for-gene interaction' extension would no longer be available for selection (similar to what we did with the disease_caused extension a while ago). All of the existing annotation extensions would be preserved.

> Is there a way of pulling out the current terms used to make sure we have them covered in the new compound terms.

I can do this if we decide to go ahead with the proposed solution. If you want to amend the existing annotations to use the new extension, then I think it would be better to disable the old extensions after all the relevant annotations are migrated to the new extension.

> In the supplementary ontology of precomposed terms, we may still need to display the definition of each of the three individual component terms

I don't think it's going to be easy to embed all three definitions into one term definition. As far as I know, Canto doesn't support line breaks in term definitions, so you might have no way to cleanly separate the three definitions with formatting. Maybe you could abridge the definitions of the constituent terms to form the definition for the precomposed term (meaning, to form only a single paragraph)?

> Perhaps the new extension could be called 'gene-for-gene interaction' instead of 'infective ability'.

That sounds fine to me.

**Comment by ValWood** [comment]
> we think the easiest solution is to add a new annotation type for metagenotypes

I think this will be much easier for curators...

**Comment by CuzickA** [comment]
> Create a supplementary ontology to store the precomposed terms; we could follow FYPO's convention and use PHIPO_EXT as the term prefix.

It would be good to discuss this at the next group meeting. 

Would PHIPO_EXT be a new ontology set up like PHI-ECO and PHI-DO for loading into the new AE 'gene-for-gene'?
Or is it possible to add these terms within PHIPO using a different namespace , or subset rule to load into the new AE?

**Comment by jseager7** [comment]
> It would be good to discuss this at the next group meeting.

I've added it to the agenda.

> Would PHIPO_EXT be a new ontology set up like PHI-ECO and PHI-DO for loading into the new AE 'gene-for-gene'?
Or is it possible to add these terms within PHIPO using a different namespace , or subset rule to load into the new AE?

I'd much prefer to put these terms in their own ontology, because the precomposed terms are so domain specific (and so highly composed) that I'd prefer not to put them in anything except a supplementary ontology exclusively for that purpose.

We can put the ontology on our config repository, and we shouldn't need to edit it very often, so it shouldn't add much maintenance burden.

**Comment by CuzickA** [comment]
@jseager7 If we put these terms into their own ontology it may be difficult for me to edit as I've had difficulty in the past with Protege swapping between different ontologies and I need to prioritise PHIPO. Could we get this set up so that you could add these new terms for PHIPO_EXT via a spreadsheet like with PHI-ECO?

**Comment by jseager7** [comment]
> Could we get this set up so that you could add these new terms for PHIPO_EXT via a spreadsheet like with PHI-ECO?

Sure, that was my plan anyway (although I forgot to say that above).

**Comment by CuzickA** [comment]
> > Could we get this set up so that you could add these new terms for PHIPO_EXT via a spreadsheet like with PHI-ECO?
> 
> Sure, that was my plan anyway (although I forgot to say that above).

Great!

**Comment by CuzickA** [comment]
Do you think the individual components of the proposed compound terms should also be in this ontology instead of PHIPO? 

When you have a chance could you give me a template table for these new terms and I'll try to start adding them and thinking up some new definitions. 

Thanks

**Comment by jseager7** [comment]
> Do you think the individual components of the proposed compound terms should also be in this ontology instead of PHIPO?

I'm not sure. If the component terms could still be useful in isolation (even if they might not be useful in PHI-Canto), then it might make sense to keep them in PHIPO.

We don't really need the component terms in PHIPO_EXT unless we're planning to logically define the compound terms with reference to their components. Even then, we could probably import the necessary PHIPO terms for the sake of the logical definitions (assuming we keep the terms in PHIPO).

Just to note, I don't think including or excluding logical definitions will affect Canto either way.

**Comment by jseager7** [comment]
> Is there a way of pulling out the current terms used to make sure we have them covered in the new compound terms?

@CuzickA Here's a list of all of the infective_ability term names used on annotations with a gene_for_gene_interaction extension. If you need more information, please let me know.

- functional host resistance gene absent
- functional host resistance gene present
- functional pathogen effector absent
- functional pathogen effector present
- gain of functional host resistance gene
- gain of functional pathogen effector
- loss of functional host resistance gene
- loss of functional pathogen effector
- unaffected pathogenicity

**Comment by CuzickA** [comment]
@jseager7 

Thanks for the template table.

Please could you identify the 'gene-for-gene' curation session with AE 'unaffected pathogenicity'. This term should not have been used and it looks like I missed correcting last time. Thanks.

**Comment by jseager7** [comment]
There are 5 annotations in the curation session for [PMID:100900](https://canto.phi-base.org/curs/583b15b394a3a9e5). This is a test session that I think is populated with example data for gene-for-gene experiments. That's the only session that matches the query.

**Comment by CuzickA** [comment]
Thats fine. Thanks for double checking @jseager7

**Comment by jseager7** [comment]
The new gene-for-gene interaction extension is now available on the demo server. 

![image](https://user-images.githubusercontent.com/37659591/98940605-244af380-24e3-11eb-86d0-d7b2cf475a95.png)

Note that the full extension text is not shown in the annotation extension column, because it's too long and gets truncated, but you can expand the text by clicking the ellipsis:

![image](https://user-images.githubusercontent.com/37659591/98940927-ae935780-24e3-11eb-9ff6-b6720d0f6aa0.png)

I also had to rename the old 'gene for gene interaction' extension to **'interaction compatibility'**, otherwise their names would have clashed:

![image](https://user-images.githubusercontent.com/37659591/98941031-dedaf600-24e3-11eb-8210-fda19d46ec05.png)

- - -

I haven't applied this change to the main server yet, because I'm not sure what will happen to the existing 'gene for gene interaction' extensions. @kimrutherford Is there any way to change the relation name for an extension such that Canto will update existing annotations?

**Comment by kimrutherford** [comment]
> I need to change every extension with the relation name gene_for_gene_interaction to interaction_compatibility, and I'm not sure if Canto has any way to do this automatically.

There is no automatic way.  If it's a one-off we can write a short script or a gnarly one-liner to fix every session.

> I'm also not sure what happens if you load two extensions with the same relation name, which is what will end up happening if the old extension isn't renamed.

Sorry, I don't understand that bit.

**Comment by jseager7** [comment]
> Sorry, I don't understand that bit.

Our current extension configuration has an extension called gene_for_gene_interaction:

domain ID | subset relation | extension relation | range ID
-- | -- | -- | --
PHIPO:0000001 | is_a | gene_for_gene_interaction | PHIPO:0001188

The range is PHIPO:0001188, which is simply a grouping term for the following terms:

- [compatible interaction](http://purl.obolibrary.org/obo/PHIPO_0001189)
- [incompatible interaction](http://purl.obolibrary.org/obo/PHIPO_0001190)

In the new (proposed) extension configuration, the gene_for_gene_interaction extension will instead by populated with terms from our extension ontology, PHIPO_EXT:

domain ID | subset relation | extension relation | range ID
-- | -- | -- | --
PHIPO:0000001 | is_a | gene_for_gene_interaction | PHIPO_EXT:0000001

While the old gene_for_gene_interaction relation is renamed to interaction_compatibility:

domain ID | subset relation | extension relation | range ID
-- | -- | -- | --
PHIPO:0000001 | is_a | interaction_compatibility | PHIPO:0001188

However, if the old gene_for_gene_interaction extensions aren't renamed, it could be pretty confusing to tell these extensions apart in curation sessions.

My previous comment about '[loading] two extensions with the same relation name' isn't entirely accurate, since we won't be loading two extensions with the relation name 'gene_for_gene_interaction' in the new config (one will already be renamed to 'interaction_compatibility' in the extension config file).

The problem is more the fact you could add the new gene_for_gene_interaction extension to an existing annotation that already has the old gene_for_gene_interaction extension on it, effectively ending up with two different extensions with the same name on one annotation. I'm not sure how much this will matter in practice, since (I presume) Alayne is planning to replace all the old gene_for_gene_interaction extensions with values from the new extension, so as long as they're switched in one go, we shouldn't end up with duplicated extension relation names. Changing the old extension to a unique name might still help avoid any confusion, though.

**Comment by jseager7** [comment]
I've spoken to Alayne and she has no problems with leaving the old and new extensions with the same name, so there's not really any point updating the relation names in annotations automatically.

@CuzickA @ValWood The new gene-for-gene extension is active on the main server now. If you're happy with this solution after trying it, feel free to close this issue.

**Comment by jseager7** [comment]
> feel free to close this issue.

Actually, ignore that, because I haven't added the new annotation type yet.

**Comment by jseager7** [comment]
I've also now realised that the existing gene-for-gene annotations are technically the wrong annotation type. Alayne is planning to replace the old gene-for-gene extensions with this new precomposed extension, but we also need to switch the annotation type for the gene-for-gene annotations: currently, they're classified as pathogen-host interaction phenotypes, but if the gene-for-gene curation is handled with a different annotation type (gene-for-gene phenotype), then we have to transfer these old annotations to the new annotation type.

Canto doesn't support transferring annotations from one type to another, and allowing this would open up all kinds of problems about which annotations are valid for transfer. Maybe it would be better to just write a script to fix this specific problem.

**Comment by jseager7** [comment]
> Actually, ignore that, because I haven't added the new annotation type yet.

The gene-for-gene phenotype annotation type is now available on the main server. You can find it either in the Quick Links list on the summary page, or on the Metagenotype Management page.

Note that the new gene-for-gene extension is not restricted to the gene-for-gene annotation type yet; that needs issue https://github.com/pombase/canto/issues/2004 to be completed first.

![image](https://user-images.githubusercontent.com/37659591/99393480-4bd00080-28d5-11eb-908b-e3d126cf5d3f.png)

- - -

![image](https://user-images.githubusercontent.com/37659591/99393521-5f7b6700-28d5-11eb-8dc5-ebb26570ce0b.png)

**Comment by jseager7** [comment]
@kimrutherford Now that we've decided to rename all instances of the old 'gene_for_gene_interaction' extension, here's the criteria required to decide which extensions should be renamed:

1. The relation name must be `gene_for_gene_interaction`; **and**
2. **Either** of the following must be true:
   - The range term ID or range display name must be one of the following:
     - PHIPO:0001189 'compatible interaction'
     - PHIPO:0001190 'incompatible interaction'
   - The range term ID must be prefixed with `PHIPO:` and not `PHIPO_EXT:`.

When the above criteria are true, change the relation name from `gene_for_gene_interaction` to `interaction_compatibility`.

Note that according to Alayne, **the new extension has already been used on the production server:** there are at least two instances of the _new_ 'gene_for_gene_interaction' extension in a test session, and one in a real session. So unless you'd rather have those extensions temporarily removed, it will be necessary to check the range values for the extensions.

**Comment by kimrutherford** [comment]
Hi James.

I'm wondering/worried about any extensions containing gene_for_gene_interaction relations that are part of extension that has two parts ORed together with "|"

Here's an example with "|":

   - infects_tissue leaf , infective_ability reduced virulence , compared_to_control_genotype pmk1-AS(aaQ104G)[Not assayed] Magnaporthe oryzae / wild type Oryza sativa (Mokoto) | causes_disease leaf spot

If there are some cases with an OR and a gene_for_gene_interaction relation we'll need to decide what to do about them.  If not, no problem.

Could you run the unfinished version of the relation rename script on a copy of the main PHI-Canto?:
https://github.com/pombase/canto/blob/1018ad763e480e66ddfbbe210bbe98bf99c3c772/etc/rename-ext-relation-example.pl

Currently it makes no changes.  It just checks for gene_for_gene_interaction relations in ORed extensions and reports them.  If there is no output that's good.

Cheers.

**Comment by jseager7** [comment]
> Could you run the unfinished version of the relation rename script on a copy of the main PHI-Canto?

@kimrutherford I've run `rename-ext-relation-example.pl` on the main server and there's no output from the script, so there shouldn't be any instances of the old extension as part of an or-group. Personally, I'm not aware of us using the or-group feature anywhere in PHI-Canto at the moment.

**Comment by kimrutherford** [comment]
Thanks.  I've updated `rename-ext-relation-example.pl` to change the extension relation names. Since I don't have a copy of the main PHI-Canto database I can't guarantee it works but I did try with other relation names and range IDs.  I suggest trying the script on a test database first.

It all goes well the only output should be the IDs of the sessions that were changed.  If you run it a second time there should be no output as there should be no relevant extensions to rename.

**Comment by jseager7** [comment]
@kimrutherford I've run this on a local copy of the production server's database, and initially got this error:

```
missing "logs" directory - exiting
```
After making a 'logs' directory in the canto_space folder, the error went away and the script worked correctly, replacing 95 annotations across 5 sessions. After running the script a second time there was no output, as expected.

The exact command was as follows:

```
 ./canto/script/canto_docker /canto/etc/rename-ext-relation-example.pl gene_for_gene_interaction interaction_compatibility
```

**Comment by jseager7** [comment]
I've also confirmed that the fix has worked in the curation sessions and the JSON export. See below:

![image](https://user-images.githubusercontent.com/37659591/100087661-f6e93880-2e46-11eb-98cc-800de9f2cde3.png)

```json
  {
    "rangeDisplayName" : "compatible interaction",
    "rangeType" : "Ontology",
    "rangeValue" : "PHIPO:0001189",
    "relation" : "interaction_compatibility"
  },
```

**Comment by kimrutherford** [comment]
> missing "logs" directory - exiting

Sorry I forgot to mention that.  I'm working on improving the logging from Canto and that was a consequence.

What is the next step for this issue?

**Comment by jseager7** [comment]
> What is the next step for this issue?

I don't think any more code changes are needed. All the remaining work is manual: change existing annotations to use the gene-for-gene extensions; transfer gene-for-gene annotations to the 'gene-for-gene phenotype' annotation type, using the annotation type transfer script; and finally, restrict the gene-for-gene extensions to the 'gene-for-gene phenotype' annotation type using the new column in the annotation extension configuration file.

It might be worth leaving this issue open until the changes are all applied on the PHI-Canto servers, just so we can keep discussion in one place, but I don't mind if it's closed.

**Comment by jseager7** [comment]
@kimrutherford Sorry, I wasn't thinking straight when I said that nothing else was needed. I confused the extension relation renaming script with the other script that we'll (presumably) need to migrate all of these gene-for-gene annotations to the gene-for-gene phenotype annotation type – currently they're classified as 'pathogen-host interaction phenotypes'.

Basically, we need a script to transfer all annotations of one annotation type to another type. The relevant issue is at https://github.com/pombase/canto/issues/2366. I think previously we might've discussed adding an option to `canto_admin.pl` to take care of this, but the logic might be so specific that maybe a throwaway script would be better.

**Comment by jseager7** [comment]
The following actions have been completed now:

- transferred all existing gene-for-gene annotations to the new 'gene-for-gene phenotype' annotation type;

- restricted annotation extensions by annotation type, so for example, 'gene-for-gene interaction' is only enabled for gene-for-gene phenotypes and 'extent of infectivity' is only enabled for pathogen-host interaction phenotypes;

- disabled the 'interaction compatibility' extension, since the extension is redundant now that we have the new gene-for-gene annotation extension.

@ValWood I think that covers everything that was needed for this issue. Feel free to close this issue if you don't need any further changes.

**Comment by ValWood** [comment]
SInce @CuzickA  has remapped successfully, I think this si safe to close...
