### ISSUE TITLE
UniProt lookup failing in PHI-Canto demo server

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2358]
In the PHI-Canto demo (https://demo-canto.phi-base.org/) UniProt accession lookup is failing. 

Reported by @Antonialock:

----

I could add the example gene Q00909 to the session, but not any other genes. I get this error: (with a comforting message at the end :) )

Internal error
Caught exception in Canto::Controller::Curs->gene_upload " not well-formed (invalid token) at line 1, column 0, byte 0 at /usr/lib/x86_64-linux-gnu/perl5/5.24/XML/Parser.pm line 187. XML::Simple called at lib/Canto/UniProt/UniProtUtil.pm line 73."
There has been an internal error. The problem has been logged and will be investigated.

**Comment by kimrutherford** [comment]
I think this is because the UniProt batch lookup API has changed a bit.  I've fixed the Canto code to match.

@jseager7 Could you check this fix works for you?

**Comment by jseager7** [comment]
Strangely enough, this error didn't occur on the production server or the test server when I tried to replicate the bug there. I don't think I've updated the test server since the fix was pushed, so maybe UniProtKB have fixed the problem at their end. Whatever the reason, there are no errors when adding a gene that isn't the example gene. Closing now.
