### ISSUE TITLE
Small text change in PHI-canto prompts

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2393]
Please add "effector-mediated modulation of host process by symbiont" as the first suggested  GO  process term in the GO term prompts. Descendants of this term will be the most frequent process annotations for pathogen-host curation (I still struggle to find it in GO myself), and people really need to come in at the top and still down at the moment because the terms are patchy.

**Comment by jseager7** [comment]
@ValWood Do you want this term to replace the existing specific term suggestion 'pyrimidine metabolic process or alpha-glucoside transport', or do you want the term appended to the suggestions?

**Comment by ValWood** [comment]
I think this should be visible by default as a high-level term, It's the entry point for all PHI GO annotation. I would swap "cell cycle" out as it is rarely required at present in this field of research.

@CuzickA do you agree?

**Comment by CuzickA** [comment]
Yes, this sounds like a good idea

**Comment by jseager7** [comment]
@ValWood @CuzickA I think I've misunderstood something here. In the configuration file, there are two fields used for term suggestions: `broad_term_suggestions` and `specific_term_examples`. I thought 'effector-mediated modulation of host process by symbiont' was meant to be a _specific term example_, since it's an example of an actual term that appears in GO (GO:0140418).

However, the discussion above implies that this term is meant to be visible by default, and that only applies to _broad term suggestions_. It also sounds like the requested term is meant to replace 'cell cycle', which is a broad term suggestion.

If we want to follow convention, the broad term suggestion (visible by default) should be something like 'effector', and 'effector-mediated modulation of host process by symbiont' should be a specific term example (hidden by default). Taking this approach would amend the text as follows (presuming we want to keep 'transport' as a suggestion):

> Start typing a biological process in the search box (type at least 2 characters). If you do not find the term you are looking for with your initial search, begin with a broad term (effector, transport)

Is this acceptable, or would you prefer to have the full term visible from the start?

**Comment by jseager7** [comment]
Just to be absolutely clear, here's the current configuration for biological process, with my initial change applied:

* broad term suggestions
  * cell cycle
  * transport
* specific term examples
  * effector-mediated modulation of host process by symbiont
  * pyrimidine metabolic process or alpha-glucoside transport

**Comment by ValWood** [comment]
I'm suggesting
broad term suggestions
effector-mediated modulation of host process by symbiont
transport

(it seems that the broad term suggestions are just "substrings" but they are in fact "high level terms")

This is the term that will be most useful for users to locate the correct term in the pathogen-host branch. 
My main aim is to prevent people getting bogged down in the "response to" terms and going down the wrong branch early on. We might change this later, and add others once the GO is cleaned up a bit.


<img width="539" alt="Screenshot 2021-01-27 at 09 53 21" src="https://user-images.githubusercontent.com/7359272/105974301-ac25b000-6085-11eb-930b-700815af29cd.png">

**Comment by jseager7** [comment]
> (it seems that the broad term suggestions are just "substrings" but they are in fact "high level terms")

Ah, okay. Thanks for the clarification. I'll reconfigure the term to be a broad suggestion.

The new configuration will be as follows:
```yaml
    broad_term_suggestions: "effector-mediated modulation of host process by symbiont, transport"
    specific_term_examples: "pyrimidine metabolic process or alpha-glucoside transport"
```

**Comment by jseager7** [comment]
The change is applied now. Here's the new help text:

![image](https://user-images.githubusercontent.com/37659591/106138555-30e6fb80-6164-11eb-8893-4a6bdfa71ba9.png)
