### ISSUE TITLE
Wild type protein and RNA level configuration

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2400]
Please add
Mouseover Text: Used to capture qualitative descriptions about the level (e.g. increase, decrease etc) timing (e.g. cell cycle phase) and location (tissue) of the RNA transcribed from a gene.

Canto text (on create annotation page, a little help text)

Choose a wild-type RNA level term
Qualitative descriptions of presence, absence, increase, decrease, etc. of the RNA expression in a single species.
Note: if you need to capture changes in RNA level observed in a mutant in a single-species use the single-species  “RNA level” phenotypes, or for changes in RNA level in a pathogen-host interaction use  "pathogen-host interaction phenotypes.

We need the additional note for PHI-Canto because WT phenotypes are often captured as controls. We might be able to improve this over time. But @CuzickA  and Chris, our tester were confused by this, as it is a new annotation type in PHI-Canto.

Also need to have the tissue ontology available for extensions in PHi-Canto  for this annotation type.

**Comment by jseager7** [comment]
> Mouseover Text: Used to capture qualitative descriptions about the level (e.g. increase, decrease etc) timing (e.g. cell cycle phase) and location (tissue) of the RNA transcribed from a gene.

@ValWood What part of the interface should this mouse-over text apply to? Could you attach an image?

**Comment by jseager7** [comment]
> Canto text (on create annotation page, a little help text)

Do we need corresponding text for the Protein level annotation type? There's no help text there at the moment.

**Comment by jseager7** [comment]
> Also need to have the tissue ontology available for extensions in PHi-Canto for this annotation type.

Just to confirm, do we only want the tissue type extension on the RNA level annotation type, or on Protein level as well?

- - -

Finally, do you want the 'RNA level' and 'Protein level' extensions to be renamed to Wild-type RNA level' and 'Wild-type protein level'?

**Comment by jseager7** [comment]
The existing configuration for the tissue type annotation extension is shown below. I'm presuming for RNA and Protein annotations that we don't want to say 'host tissue infected', but what should we call it otherwise?

domain ID | subset relation | extension relation | range ID | Canto display text
-- | -- | -- | -- | --
PHIPO:0000001 | is_a | infects_tissue | BTO:0000000 | host tissue infected

**Comment by ValWood** [comment]
@ValWood What part of the interface should this mouse-over text apply to? Could you attach an image?
![Uploading Screenshot 2021-01-27 at 15.32.07.png…]()

**Comment by ValWood** [comment]
We also need corresponding mouse over and help for "Wild-type protein level"

**Comment by ValWood** [comment]
> Just to confirm, do we only want the tissue type extension on the RNA level annotation type, or on Protein level as well?

Yes please


> Finally, do you want the 'RNA level' and 'Protein level' extensions to be renamed to Wild-type RNA level' and 'Wild-type protein level'?

Yes please, I think this is in another ticket too

**Comment by ValWood** [comment]
domain ID | subset relation | extension relation | range ID | Canto display text
-- | -- | -- | -- | --
PHIPO:0000001 | is_a | occurs_in | BTO:0000000 | expressed in tissue ?

actually this will also need restricting to host genes which will be a bit more work.
So don't rush with this one because we  aren't using it much, and we can add manually in free text

**Comment by jseager7** [comment]
Sounds like the tooltip help text is related to the changes in issue #2397. I've had a look at the code and it should be easy to change. I'll try amending the tooltip on the help text to match the text above.

@ValWood Is the text below sufficient for a tooltip for the Protein level annotation type?

"Used to capture qualitative descriptions about the level (e.g. increase, decrease etc) timing (e.g. cell cycle phase) and location (tissue) of the protein produced from a gene."

- - -

> actually this will also need restricting to host genes which will be a bit more work.

I think in order to do this we'd need additional feature types in the annotation type configuration, for example `host_gene` and `pathogen_gene` instead of simply `gene`.

> So don't rush with this one because we aren't using it much, and we can add manually in free text

Apart from the organism role restrictions, the other changes should be easy to implement, so I don't mind applying them now.

**Comment by mah11** [comment]
@jseager7 The latest from #2397 is that I'll revise the text for all curation type tooltips, so please don't rush ahead with the text above (it needs editing for punctuation).

**Comment by jseager7** [comment]
Okay, sure. I'll wait until everything is settled before changing the tooltips.

**Comment by jseager7** [comment]
Forgot to reply to this issue sooner. The tooltip text changes have been applied now, and I've enabled the tissue type extensions on the RNA level and protein level annotation types. I've also amended the help text on the 'Create annotation' pages for both annotation types.

@ValWood Here's the help text for the 'Create annotation' page for the wild type protein level annotation type.

> Qualitative descriptions of presence, absence, increase, decrease, etc. of the protein translated from a gene. Note: if you need to capture changes in protein level observed in a mutant in a single species, please use the single-species 'protein level' phenotypes, or for changes in protein level in a pathogen-host interaction, please use the pathogen-host interaction 'level of pathogen protein' or 'level of host protein' phenotypes.

If the text looks okay, then I think everything in this issue is done and it can be closed.

**Comment by ValWood** [comment]
I think that looks OK!
