### ISSUE TITLE
Host genotypes overlay  pathogen genotypes in metagenotype management if both alleles are long

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2409]
An additional consequence  of wide pathogen and host genotype columns is this bug:

<img width="1322" alt="overlay" src="https://user-images.githubusercontent.com/7359272/107125343-53ce8980-68a1-11eb-8a46-42ebbd29cc2e.png">

might be alleviated by
https://github.com/pombase/canto/issues/2408

**Comment by jseager7** [comment]
That looks pretty awful. I'm surprised that the host column doesn't wrap under the pathogen one when it runs out of space, since something similar to this happens on the genotype management page. Forcing that would at least stop the tables overlapping.

I'm sure there's been discussion in the past about how to handle very long allele / genotype names like the example above. I think breaking lines on commas was vetoed due to the potential of mistaking line-wrapped single allele genotypes for multi-allele genotypes. I think that the genotype table on the Genotype Management page truncates long allele names and expands them only on request; this fix might not apply here because we're not sharing code between the Genotype Management and Metagenotype Management pages (see https://github.com/pombase/canto/issues/1714), which is something that I knew would cause us problems eventually; I just never got around to fixing it.
