### ISSUE TITLE
WT product vs WT product level

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2412]
In this ticket
https://github.com/pombase/canto/issues/1536
we changed "WT product level" to "WT product"

This isn't so bad in  Pombase-Canto, because it is clearer from out header bars what the thing in brackets is:

<img width="285" alt="Screenshot 2021-02-06 at 18 01 14" src="https://user-images.githubusercontent.com/7359272/107126040-529f5b80-68a5-11eb-8b5f-dad464270c79.png">

but that isn't the case in PHI-Canto

<img width="474" alt="Screenshot 2021-02-06 at 18 02 22" src="https://user-images.githubusercontent.com/7359272/107126064-8a0e0800-68a5-11eb-8e31-e4963a8bd1c1.png">

and becomes very confusing if the  allele is WT level of a mutant allele. I don't think users will easily understand this:

<img width="668" alt="WT level" src="https://user-images.githubusercontent.com/7359272/107126008-1c61dc00-68a5-11eb-9f8f-30c1419e889a.png">

**Comment by jseager7** [comment]
@ValWood Just to confirm, do you want the text to be reverted to 'wild type product level'?

Unfortunately this change has been applied globally, so I can't revert it without also affecting PomBase's Canto.

@kimrutherford It looks like commit 553bb8a3dee8ef5fa974bd5428522fd65bcf6371 might have to be amended to allow a special case for pathogen-host mode; either that, or the expression display names will have to be made configurable.

**Comment by ValWood** [comment]
If we had a short string, I would prefer "WT level" or even "WT EXP. level"

WT product on its own isn't clearly related to product level.

@mah11 
@CuzickA

**Comment by CuzickA** [comment]
> If we had a short string, I would prefer "WT level" or even "WT EXP. level"
> 
> WT product on its own isn't clearly related to product level.
> 


I agree

**Comment by ValWood** [comment]
Any objections to "WT EXP. level"?
@mah11  any better suggestions here?

**Comment by mah11** [comment]
> Any objections to "WT EXP. level"?

I don't particularly like it, because it's not really all that obvious that "exp." stands for "expression". But the only thing I feel strongly about is that if we do include "exp." it MUST NOT be upper case.

I also don't mind the length of "WT product level", but that's probably because I don't use PHI-Canto.

Of the shorter suggestions I prefer "WT level" without the "exp.". I agree that "WT product" is inscrutable.

**Comment by CuzickA** [comment]
I also prefer "WT level".

**Comment by jseager7** [comment]
> But the only thing I feel strongly about is that if we do include "exp." it MUST NOT be upper case.

Agreed.

> it's not really all that obvious that "exp." stands for "expression".

I was hoping we could add a tooltip to the 'WT exp. level' text that would explain the meaning was 'wild type expression level'. Unfortunately, the genotype name is already a link, and (in my opinion) it wouldn't be conventional to put an expansion of an abbreviation on a link (usually a tooltip there explains the _purpose_ of a link).

Maybe part of the problem is that the curator has no easy way to guess at the meaning of 'WT exp. level' because we don't call it that when the curator selects the expression – instead it's called 'Wild type product level' during allele creation:

![image](https://user-images.githubusercontent.com/37659591/111457488-27175880-8710-11eb-8173-dd1339746659.png)

**Comment by ValWood** [comment]
I think "WT level" is fine. I just made a mistake changing to "WT product" in the 'short version', it should have been "WT level " originally. If you just make this change this can close.

**Comment by jseager7** [comment]
Sorry about the delay on this. I must've thought there was still something that needed discussing. I've made the change now, so the wild type product level expression will be abbreviated to 'WT level'. Here's an example from the genotype table:

![image](https://user-images.githubusercontent.com/37659591/114853521-c6953d00-9ddb-11eb-886f-1035a39fd504.png)

As usual, this change probably won't affect PomBase's Canto immediately because it's not on the latest version of the code.
