### ISSUE TITLE
fix to FBcv obo file for 3 terms that failed

### ISSUE THREAD

**Issue by gm119** [pombase/canto#2413]
Hi @kimrutherford am attaching a 'fixed' flybase_controlled_vocabulary.obo file with the correct namespace added to the three terms that Arzu found previously were resulting in error messages:

FBcv:0007504 abnormal body weight
FBcv:0007505 increased body weight
FBcv:0007506 decreased body weight

So could you load this fixed file into FlyBase Canto so that the errors go away (!)
(I'm attaching the file rather than pointing you to the purl as although Clare has fixed the 'master' ontology (DPO) the 'official' FBcv file won't get updated until our next release, so I added the 3 namespace lines manually as per her suggestion !)

[fixed_flybase_controlled_vocabulary.txt](https://github.com/pombase/canto/files/5943126/fixed_flybase_controlled_vocabulary.txt)

(I had to change  the filename to .txt to attach it to the ticket, sorry)

**Comment by kimrutherford** [comment]
I've loaded that OBO file now.  Please let me know if it fixes the problem.

**Comment by kimrutherford** [comment]
Hi Arzu.  Is this issue fixed for you now?

@arzuozturk

**Comment by arzuozturk** [comment]
Hi Kim,

Sorry about my late response. I think the problem was solved. I wanted to double check it but I can't access Canto:

This Canto server is temporarily offline. We apologise for the inconvenience.

We are working to fix this problem and the server will return shortly.

Could you please take a look into this?

Thanks.

**Comment by kimrutherford** [comment]
Hi Arzu.  I'm very sorry sorry about that.  Canto is back online now.  Our main server needed a reboot this morning but Fly-Canto didn't automatically restart.  And I forgot to check that it was OK.

I'll fix the configuration so that Fly-Canto restarts on its own next time we need to reboot (which is very rare).

**Comment by arzuozturk** [comment]
Hi Kim,

Thanks for bringing back Canto and fixing this. I've just checked, the 3 terms do not give errors any more. 

Best,

**Comment by kimrutherford** [comment]
Great.  I'll close this issue.
