### ISSUE TITLE
Allow  interacting taxon on MF and CC GO terms

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2418]
(After https://github.com/pombase/canto/issues/2335)

I think currently we are only asked for taxon on GO processes when they apply to multi-species terms.

We also need to be able to specify the host or pathogen taxon when annotating component and function terms.

It will not be as easy as for "BP"  easy to know automatically whether the function is single species or multi-species, so in the short term we would need to allow taxon information to be added for all MF and CC terms. 

I would make the taxon extensions admin only because this is a bit opaque.

Later think we can be cleverer, by utilizing the annotation extension information to figure out if a taxon field is required for an annotation. We can think about this later. This isn't super-urgent because the specification of dual taxon in the taxon field is not currently mandatory for GO multi-species annotations.

**Comment by jseager7** [comment]
Adding the extensions for the molecular function and cellular component annotation types is easy, especially considering the extensions will be admin-only, so that can be enabled sooner if you want.

If there are particular extensions that can be used to infer whether or not the taxon extensions should be shown, it would be helpful to list them here.

**Comment by ValWood** [comment]
I'm afraid that it is only possible to restrict easily for the process terms but I will have a think...

**Comment by jseager7** [comment]
@ValWood It's now possible to restrict the **with_symbiont_species** and **with_host_species** extensions so that they only show when the gene belongs to a host or a pathogen, respectively. The issue covering that (#2335) was marked as a prerequisite to this issue, so I guess I can move ahead with this now.

Assuming we still want the (admin-only) option to specify symbiont and host taxon IDs for all cellular_component and molecular_function terms, the table below shows the proposed extension configuration. GO:0003674 is molecular_function and GO:0005575 is cellular_component.

Is this correct?

domain ID|extension relation|range ID|Canto display text|role|feature type
---|---|---|---|---|---
GO:0003674|with_symbiont_species|PathogenTaxonID|with symbiont species|admin|host_gene
GO:0003674|with_host_species|HostTaxonID|with host species|admin|pathogen_gene
GO:0005575|with_symbiont_species|PathogenTaxonID|with symbiont species|admin|host_gene
GO:0005575|with_host_species|HostTaxonID|with host species|admin|pathogen_gene
GO:0044419|with_symbiont_species|PathogenTaxonID|with symbiont species|user|host_gene
GO:0044419|with_host_species|HostTaxonID|with host species|user|pathogen_gene

**Comment by ValWood** [comment]
Great,  that looks right. Can be tweaked if not.

**Comment by jseager7** [comment]
The change is applied in our configuration repository, and I'll update the server later today. It should be active tomorrow once the ontologies reload.
