### ISSUE TITLE
quick links sometimes not visible

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2420]
<img width="860" alt="Screenshot 2021-02-17 at 08 47 50" src="https://user-images.githubusercontent.com/7359272/108178850-d3a7ef80-70fc-11eb-9aec-e11815c95305.png">

although they appear on reloading.
Reported by @JackyVH , I have seen it too. In the cases I  have seen it the bullets appeared, but not the links.

**Comment by kimrutherford** [comment]
My best guess is that there a temporary network glitch that briefly prevents Canto from contacting the server.  The default state is for advanced mode to be off.  Canto asks the server if you have previously turned advanced mode on so if there's a glitch advanced mode (and the quick links) will stay turned off.

Do you notice this happening more when the WiFi is playing up?

**Comment by ValWood** [comment]
I think it could be. My wifi plays up quite a lot.

Should we close?

**Comment by kimrutherford** [comment]
It's a problem that could be fixed by changing the implementation to avoid contacting the server.  But it's a couple of hours work so maybe not worth it?

**Comment by ValWood** [comment]
Nah, it never really bothers me, we can just reload.

**Comment by JackyVH** [comment]
My WiFi seems Ok but it could be that. As it is so easy to click on advance mode to recover the links that it’s not really worth investigating further
Jacky

Sent from my iPhone

On 19 Feb 2021, at 09:31, Val Wood <notifications@github.com> wrote:

﻿

I think it could be. My wifi plays up quite a lot.

Should we close?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpombase%2Fcanto%2Fissues%2F2420%23issuecomment-781954524&data=04%7C01%7C%7C6b0e610e94e844474ed008d8d4b92efd%7C4eed7807ebad415aa7a99170947f4eae%7C0%7C0%7C637493239103987853%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ByL4pf2LncOzsSQiWbdr0Dpfk2WJWFpZlZOTjI4xUfY%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADKVK2C2RLIFTYOAUSQFTPLS7YVYJANCNFSM4XX6CU5Q&data=04%7C01%7C%7C6b0e610e94e844474ed008d8d4b92efd%7C4eed7807ebad415aa7a99170947f4eae%7C0%7C0%7C637493239103997846%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bttwXImn76IEvlqloPz3b32fbUWTXLG4eggGzX02lq0%3D&reserved=0>.

The Francis Crick Institute Limited is a registered charity in England and Wales no. 1140062 and a company registered in England and Wales no. 06885462, with its registered office at 1 Midland Road London NW1 1AT

**Comment by ValWood** [comment]
For me it works if I reload the page when it happens.
