### ISSUE TITLE
Show "Add another gene" not "Delete or edit genes and organisms" on genotype management page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2434]
The test Canto has the wrong link on the genotype management page.  This needs to be fixed in the main code branch.  The pombe Canto instance doesn't have this bug because it's using the old code.

**Comment by kimrutherford** [comment]
Now fixed.

**Comment by mah11** [comment]
I'm reopening this (instead of a new ticket), because this bit turns out not to be true:

> The pombe Canto instance doesn't have this bug because it's using the old code.

IOW, I do indeed see "Delete or edit genes and organisms" on the genotype management page in pombe Canto. Seems to be new since I last added genes to a session from this page, so very recent but I don't remember well enough to be more precise.

**Comment by kimrutherford** [comment]
Ah, sorry.  The code was correct but the configuration wasn't.  Fixed now.
