### ISSUE TITLE
Genotype background not shown in metagenotype picker 

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2435]
We noticed  whilst doing  a copy edit and adding background 
that the "background did not display in the  dropdown for PHI-Canto (I think it does for PomBase Canto?)

**Comment by ValWood** [comment]
![Screenshot 2021-03-09 at 18 05 44](https://user-images.githubusercontent.com/7359272/111140691-8ba0af00-857a-11eb-8e10-b6ac0b1468bb.png)

**Comment by ValWood** [comment]
![Uploading Screenshot 2021-03-15 at 10.37.49.png…]()

**Comment by jseager7** [comment]
You're right that it's inconsistent that the background isn't shown, because it appears in the genotype picker for single-species phenotypes: 

![image](https://user-images.githubusercontent.com/37659591/111141919-fc949680-857b-11eb-9080-1e88d7c5e597.png)

I'm a bit concerned about what might happen to the width of the metagenotype picker if we show the background as well, but as long as the background text isn't very long it shouldn't add too much width.

I think at some point I should really look at an alternative display mode for metagenotypes in pulldown menus, like having the pathogen and host parts of the metagenotype on individual lines, while still having some visual distinction between individual metagenotypes.

**Comment by jseager7** [comment]
I've got a proof of concept for showing the genotype background in metagenotype names. Here's how it looks with the new code:

![image](https://user-images.githubusercontent.com/37659591/111165403-e516d700-8596-11eb-98d2-5422e45c35e2.png)

The background is shown after the strain in the new system, whereas before I think the background was shown first. I can change that if needed.

I just need to fix one small problem with the new system before it's ready to merge.

**Comment by ValWood** [comment]
Looks good. We need it so go ahead. If length is an issue that's a problem that would need to be addressed separately. It should only be an issue if we can't read the full row.
