### ISSUE TITLE
genotype chooser

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2445]
This has changed recently (I think?)

It isn't quite as clear now that some alleles are hidden because there is no clear  demarkation of the bottom of the panel.
In this view some of my alleles are hidden, and for a while I thought the alleles I had added recently were not appearing. 

<img width="345" alt="Screen Shot 2021-03-26 at 15 04 38" src="https://user-images.githubusercontent.com/7359272/112657802-ac0a1c80-8e4a-11eb-8e08-16a530871b58.png">

**Comment by kimrutherford** [comment]
Was that on your old laptop?

It's a bit hard to debug because it's OK on my machine.

Firefox:
![genotype-select-firefox-1](https://user-images.githubusercontent.com/90474/112767030-f66ce280-9070-11eb-9eef-3b63d3a9469a.png)

Chrome:
![genotype-select-chrome-1](https://user-images.githubusercontent.com/90474/112767039-fff64a80-9070-11eb-9ccd-2e82d4313b8e.png)

**Comment by ValWood** [comment]
yes! ignore...
