### ISSUE TITLE
recent canto change, restart approval

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2463]
There is something a bit odd about this:

<img width="1274" alt="canto ticket" src="https://user-images.githubusercontent.com/7359272/116877111-68f35400-ac15-11eb-9745-6ea8b05e5196.png">

I *think* the restart approval button appears even if a session is not in approval. I recently used this to access a paper that was not yet submitted (I think), and now it is in approval, even though the authors did not yet curate it/submit it.

I tried again with one of my own sessions, and this is also now in approval.
I think I prefer to only be able to review, (or edit, but not necessarily in approval) from here?

**Comment by mah11** [comment]
Yeah, I agree, this is kinda weird. I checked papers with a few different statuses, and it's using the same text and options for everything I tried except papers that have no session at all.

"Restart approval" makes sense only for papers with approved sessions (and not for sessions currently undergoing approval, still in progress, or created but nothing else done yet). I don't know if we care about the distinction between "currently being curated" and "has been curated" for the text.

Tangent: The link for "Admin only: publication page." is broken. It tries to go to `https://curation.pombase.org/......`, which of course isn't a thing. I think if we get that working, we wouldn't need a button for approval on the pombe "home" page.

**Comment by kimrutherford** [comment]
It's not very recent.  It looks like it was changed in Jan last year: #2186

@jseager7 could you have a look at this?  Let me know if you'd like to chat about it.

**Comment by ValWood** [comment]
I don't think it came into PomBase Canto until recently though...

**Comment by jseager7** [comment]
> I don't think it came into PomBase Canto until recently though...

I think that's because PomBase's version of Canto is so far behind the latest version of the code (as stored on GitHub). Not sure though.

**Comment by kimrutherford** [comment]
> I think that's because PomBase's version of Canto is so far behind the latest version of the code (as stored on GitHub).

That will be it.  I had forgotten.

**Comment by jseager7** [comment]
This bug is my fault: I never added checks for the session state when I added the button. I'm not sure why the admin link is broken, but I'll take a look.

@kimrutherford Which session states should I be checking for? Based on [Midori's comment](https://github.com/pombase/canto/issues/2463#issuecomment-831896054) above, it sounds like I should be checking for `APPROVED` and `EXPORTED`, or maybe just `APPROVED`. Here's a list of the states from `State.pm`, for reference:

```perl
use constant {
  # user needs to confirm name and email address
  SESSION_CREATED => "SESSION_CREATED",
  # no genes in database, user needs to upload some
  SESSION_ACCEPTED => "SESSION_ACCEPTED",
  # session can be used for curation
  CURATION_IN_PROGRESS => "CURATION_IN_PROGRESS",
  # session has been paused by the user
  CURATION_PAUSED => "CURATION_PAUSED",
  # user has indicated that they are finished
  NEEDS_APPROVAL => "NEEDS_APPROVAL",
  # sessions is being checked by a curator
  APPROVAL_IN_PROGRESS => "APPROVAL_IN_PROGRESS",
  # session has been checked by a curator
  APPROVED => "APPROVED",
  # session has been exported to JSON
  EXPORTED => "EXPORTED",
};
```

**Comment by kimrutherford** [comment]
> Which session states should I be checking for?

I think just APPROVED for now.  Thanks for looking into this.

> I'm not sure why the admin link is broken, but I'll take a look.

I think that one was my fault.  Let me know if you'd like me to look into it.

**Comment by jseager7** [comment]
> I think that one was my fault. Let me know if you'd like me to look into it.

@kimrutherford I just fixed the admin publication link in commit eb960c6, but thanks for the offer. Sorry if that makes it awkward to merge into the `pombase-release` branch.

I will need your help with fixing the 'Restart approval' button though, because currently the data retrieved from the API (`/tools/pubmed_id_lookup`) doesn't include the session state for the curation sessions, just an array of strings containing the session ID. It looks like the API is still designed to handle the possibility of multiple curation sessions per publication. Maybe the API could provide an additional property containing the state for the first session in the list, which should, in theory, be the only session there. Alternatively the API could return a list of session objects with an `id` property and a `state` property, but that could be disruptive if this API is used all over the place.

**Comment by jseager7** [comment]
> The API isn't used anywhere else so I implemented this. It now returns something like:

Thanks. I'll work on updating the front-end code to use this.

**Comment by jseager7** [comment]
This is now fixed on the latest version of the code (and in PHI-Canto). The 'Restart approval' button should only show when the session has been approved (but not after it's been exported). The publication page link should be working correctly too.
