### ISSUE TITLE
 PMID:32680850 labeled as exported but not showing in this week's export json

### ISSUE THREAD

**Issue by vmt25** [pombase/canto#2465]
Hi Kim, 

PMID:32680850 appears as exported but is not present in this week's export json. 
I am almost sure I did it this week (around export time yesterday) but also checked last week's json and it is not there.

The curation session is: https://curation.pombase.org/flybase/curs/f096d2a8cdaffb3e

Is this a bug or did I unintentionally export the session?

**Comment by kimrutherford** [comment]
Hi Vitor.

I've checked the exported files against the Canto database and only PMID:32680850 is missing for the JSON export files.  So perhaps the session was put into the exported state by accident?

**Comment by vmt25** [comment]
Hi Kim,

Thanks for looking into it.
Hmmm, I went through the motions of sumissionfor another publications and there is no way to export through the web browser, so I cannot have export it by accident.

Do you have time stamps for the submission and approval of the session?

Cheers,
Vitor

**Comment by kimrutherford** [comment]
> Hmmm, I went through the motions of sumission for another publications and there is no way to export through the web browser, so I cannot have export it by accident.

Thanks for checking.  That's very good evidence that it's a bug rather than user error.  :-)

> Do you have time stamps for the submission and approval of the session?

The time stamps are at the bottom of this page in the admin interface:
  https://curation.pombase.org/flybase/view/object/curs/2278?model=track

I've had a good look at the code and it's definitely possible that things could go wrong if you approve a session while the export is running.  I think you suggested that might have happened?

The quick fix is to do the exporting at a time when no approving is happening, like 3am.

I'll work on a real fix for the bug as well.  The problem happens because first the sessions are exported, then it goes back and marks them as exported.  That implementation was easiest at the time.  The export code is 8 years old and hasn't been used much so I'm not surprised it's a bit buggy.  It shouldn't be too hard to fix.

**Comment by vmt25** [comment]
> > Hmmm, I went through the motions of sumission for another publications and there is no way to export through the web browser, so I cannot have export it by accident.
> 
> Thanks for checking. That's very good evidence that it's a bug rather than user error. :-)
> 
> > Do you have time stamps for the submission and approval of the session?
> 
> The time stamps are at the bottom of this page in the admin interface:
> https://curation.pombase.org/flybase/view/object/curs/2278?model=track

Silly me, of course. I should have remembered (but I usually don’t go to the bottom of that page)

> I've had a good look at the code and it's definitely possible that things could go wrong if you approve a session while the export is running. I think you suggested that might have happened?

Yes, I thought of it because I remember that I was running to finish one session on time for the export.

> The quick fix is to do the exporting at a time when no approving is happening, like 3am.

I don’t think it needs a quick fix because it was just the one record and both Arzu and me keep good logs of what we curate, because we need to check the conversion to our flat text files.

Export around 12am UK time is fine and is what we count on anyways.

> I'll work on a real fix for the bug as well. The problem happens because first the sessions are exported, then it goes back and marks them as exported. That implementation was easiest at the time. The export code is 8 years old and hasn't been used much so I'm not surprised it's a bit buggy. It shouldn't be too hard to fix.

Many thanks for doing this and apologies for always coming to you with a new problem.

**Comment by kimrutherford** [comment]
Hi Vitor.

Thanks for the discussion about this bug last week.  It's fixed now.

**Comment by vmt25** [comment]
Huge thanks for fixing it!
