### ISSUE TITLE
Canto error

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2475]
I got an unusual error this morning accessing a publication:

<img width="614" alt="Screenshot 2021-06-15 at 10 24 53" src="https://user-images.githubusercontent.com/7359272/122059607-b7833900-cde4-11eb-96c6-f686309f1d55.png">

It went away when I reloaded

**Comment by kimrutherford** [comment]
Thanks for the screenshot.  I think the publication was probably one that was submitted for approval without any annotation.  We probably haven't seen the error before because it's a uncommon case: the session had to be in approval with no annotation, and then you logged in.

I've fixed the bug and had a look (and fixed) a few other places in the code where a similar problem could happen.
