### ISSUE TITLE
Add direct link from PHI-Canto to PHI-base 5 homepage

### ISSUE THREAD

**Issue by martin2urban** [pombase/canto#2491]
PHI5 UI (phi5.phi-base.org) displays PHI-Canto data (https://canto.phi-base.org/).
Please put a direct link to PHI5 UI  on the PHI-Canto web site.

**Comment by jseager7** [comment]
The PomBase Canto start screen has this extra text, which is configurable for each Canto instance:

![image](https://user-images.githubusercontent.com/37659591/134877224-abc6650d-ee6f-4860-8328-ab351f044acb.png)

I've tested modifying this on my local version of PHI-Canto and it seems to do what we need:

![image](https://user-images.githubusercontent.com/37659591/134880234-5b3f6e94-11c7-43d8-ba1a-900bd102ccbd.png)

As the text suggests, I've chosen to link to the Curation page on the PHI-base 5 website instead of the homepage, to be more in keeping with the PomBase text, but I can easily change this to link to the homepage if needed.

I've omitted the text about work being visible in other databases because I don't think PHI-base 5 currently integrates with any other databases. This can be amended in future if that changes.

@martin2urban are you happy with the above changes?

**Comment by martin2urban** [comment]
@jseager7 : Good solution. I am happy with where the link is going. However, would like to suggest to shorten the text to:

![Capture](https://user-images.githubusercontent.com/2812591/134883319-67d57028-60df-4cbe-9b49-2a11cdfc01ad.PNG)

**Comment by jseager7** [comment]
@martin2urban Okay, here's how the text appears now:

![image](https://user-images.githubusercontent.com/37659591/134884453-36be27fc-6422-4ee7-88f6-d23818da92da.png)

Note that the link still links to the Curation page instead of the PHI-base 5 homepage. I'll close this issue once the change is applied on the PHI-Canto servers.

**Comment by jseager7** [comment]
This link to PHI-base 5 has been applied on both the production and demo server now.

For the record, I added an MHTML template in `root/phi_base_docs` called `phibase_instance_front.mhtml` that was adapted from `pombase_instance_front.mhtml` in `root/docs` (see https://github.com/pombase/canto/commit/9ab55527cfaf8df1b05a34caea83eb848fe41c00).

After that the only thing that was needed was to point our configuration at this template file using `canto_deploy.yaml`:

```yaml
instance_front_mhtml: /phi_base_docs/phibase_instance_front.mhtml
```
