### ISSUE TITLE
annotating binding sites

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2499]
I know that it must be possible to capture these, because I see done  it here:
<img width="1141" alt="? binding site" src="https://user-images.githubusercontent.com/7359272/142724176-f96c07db-233a-4190-933d-271f8650d1a3.png">

but when I did the same here, it did not appear
<img width="851" alt="? binding site 2" src="https://user-images.githubusercontent.com/7359272/142724199-7a5bbba7-7bdc-4e21-948a-beaa5d7b839b.png">

it appears:
binding site 243261
(no hyphen)

**Comment by kimrutherford** [comment]
It's a dash symbol "–" rather than a hyphen "-".  The loading code isn't clever enough to fix that automatically.

**Comment by ValWood** [comment]
I don't have 'dash' on my keyboard...any idea how to create one?

**Comment by ValWood** [comment]
OK, got it, option plus hyphen

**Comment by kimrutherford** [comment]
Sorry I wasn't clear.  It was a dash symbol in the session but it needs to be just a normal hypen - just a minus sign.

**Comment by ValWood** [comment]
How weird, I had to google how to do a dash so I don't know how I managed that. I'll change it back!

**Comment by kimrutherford** [comment]
>  I had to google how to do a dash so I don't know how I managed that.

Could be a copy and paste from a paper?

**Comment by mah11** [comment]
> Could be a copy and paste from a paper?

That's how they usually sneak in. I've "corrected" a bunch of copy/pasted en dashes in allele descriptions from the Canto log.

> a normal hyphen - just a minus sign

And now for a bit of the pedantry I never can resist: Actually, a minus sign is _not_ a hyphen. In full-fledged mathematical character sets, there's a distinct `minus` symbol; otherwise, minus is closer to the en dash than anything else. The hyphen gets used for minus when the "better" options aren't available, e.g. in ASCII. Oh, and en dash is correct (when available) for number ranges, which is why I put "corrected" in snark-quotes above.

**Comment by kimrutherford** [comment]
I was going on what Unicode calls it: https://en.wikipedia.org/wiki/Hyphen-minus
