### ISSUE TITLE
Add header for multi-locus genotype table

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2538]
We need a header on the multi-locus table that also mentions interactions.  Could you have me improve this?:

### Multi-locus genotype annotations and interactions

**Comment by ValWood** [comment]
It needs to specify "Genetic Interactions"

**Comment by kimrutherford** [comment]
Now I've looked at this I worry that having "genetics interactions" in the title will confuse things because the interactions are displayed in a separate table:

![multi-locus-table-1](https://user-images.githubusercontent.com/90474/156094746-514be2ec-ecf5-4d75-9c10-a76b47044a64.png)

**Comment by ValWood** [comment]
Good point. This might be a bonkes suggestion , but how would it work  if
a) the Multi locus genotype annotations and genetic interactions headed was bold.
b) the genetic interactions table was intended so that it appeared to be a 'sub table of the multii-gene phenotypes
c) the genetics interactions 'table header' was not bold and was positioned to the left of the table

**Comment by kimrutherford** [comment]
That could work but it will take a bit of time to implement - I need to shuffle the code around a bit.

**Comment by ValWood** [comment]
This would also need to accommodate the legacy interactions.

**Comment by ValWood** [comment]
OK. I think that will work.

There is something that hasn't been thrashed out. Often  (although this mainly applied to legacy publications) the GIs are made already by BIoGrid. However these wont be connected to alleles and phenotypes. 
 We will make the new annotations and do these connections. However we won't be able to delete the existing GIs because they aren't ours, so there will be some rerdundancy. I guess any PMID which has both new and legacy, we just don't display the legacy (they should be redundant anyway).

In some cases (like big synthetic lethal screens), we would not add phenotypes (although populating alleles will be easy because they  are likely to be deletion).

**Comment by kimrutherford** [comment]
I was thinking that the easiest plan is to keep the existing gene-gene interactions in a section called something like "Legacy gene-gene interactions" and maybe only allow deletion.  Biogrid interactions could be shown in a section like "Existing legacy gene interactions".  The advantage of this plan is that the code already exists for displaying these gene-gene interactions (just need to disable editing) so we'd only have to worry about new genetic interactions for the new system.

**Comment by ValWood** [comment]
OK!
