### ISSUE TITLE
inconsistencies between the dates of papers in Canto

### ISSUE THREAD

**Issue by arzuozturk** [pombase/canto#2542]
Hi Kim,

Sometime ago you provided changes for FlyBase’s publication table column config in canto_deploy.yaml, namely to include the date of publication.

Currently there are some inconsistencies between the dates of papers in Canto. Some of them are like "Jun 2006", some are like "30 Apr 2015" and some are like "20 05 2016". These are messing up the table sorting.

![Screenshot 2022-03-02 at 10 27 30](https://user-images.githubusercontent.com/66944690/156344313-bb4dbaa5-f973-4afb-8a8f-ce5ed0331fd0.png)

• Can they be modified to the same format?
• If possible can the format be year/month/day (to help sorting)? If it is too complicated, can we just have the year or year+month?

Thanks.
Arzu & Vitor (@vmt25)

**Comment by kimrutherford** [comment]
Hi.

The inconsistencies are coming from PubMed.  I'll try to change the code to fix the dates when the publication data gets downloaded.

**Comment by ValWood** [comment]
These could be examples of the "publications with 2  PMIDs" that we an others have encountered.

**Comment by kimrutherford** [comment]
> These could be examples of the "publications with 2 PMIDs" that we an others have encountered.

It doesn't look like it in this case.  I think the publications will be curated by FlyBase before they get to Canto.

> If possible can the format be year/month/day (to help sorting)

That is the easiest fix.  Is this format OK?: "2021 Jun 24"

Val, do you have any objection to changing the publication date format?

**Comment by ValWood** [comment]
Whatever is easiest...

**Comment by arzuozturk** [comment]
Thank you so much for looking into this, Kim.

Would it be possible to have the format as "2021 06 24" instead of "2021 Jun 24"? If not, "2021 Jun 24" works for us.

**Comment by kimrutherford** [comment]
> Would it be possible to have the format as "2021 06 24" instead of "2021 Jun 24"?

Yep, no problem.  I have most of the necessary changes ready to go.  I'll be able to finish it off tomorrow.

**Comment by kimrutherford** [comment]
I've changed the code that retrieves the publication details from PubMed so that the dates are standardised as "YYYY MM DD" when stored in the Canto database.  New publications that you add will get this standard date format.

To fix the dates that are already stored in your Canto database you'll need to run this command:
```
   ./script/pubmed_util.pl --update-field publication_date
```

This command only needs to be run once but it could take a while and Canto will be unavailable during that time.  For the PomBase Canto database it take 10-15 minutes.  If it succeeds it will display something like:
```
updated publication_date in 13589 publications
```

As usual because this command is directly editing your Canto database I recommend making a full backup before running the command.

Please let me know if this works OK for you.

**Comment by vmt25** [comment]
I'll try it later today.
Huge thanks.

**Comment by vmt25** [comment]
Hi, 

got the following:

root@flybase-vm:/data/export/canto-space# sudo ./canto/script/canto_docker ./script/pubmed_util.pl --update-field publication_date
Unknown option: update-field
./script/pubmed_util.pl: needs one argument:
  --add-missing-fields (or -f): access pubmed to add missing title, abstract,
          authors, etc. to publications in the publications table (pub)

I assume this because our version needs an update/gitpull.
like I said on another ticket, I cannot test canto on my local instance because of a problem my virtual machine/VirtualBox. Will try and fix it.

**Comment by vmt25** [comment]
thanks

**Comment by kimrutherford** [comment]
Hi Vitor.  Have you had a chance to try out these changes?

**Comment by vmt25** [comment]
Hi Kim, not yet, apologies. I'm not managing to get my virtual machine up and running yet.

**Comment by vmt25** [comment]
Hi,
Finally managed to get my head around this - fixing my VM and testing this change.

@kimrutherford your command worked and the dates seem to be OK.
Many thanks and apologies for the delay in testing/implementing.

**Comment by kimrutherford** [comment]
Hi Vitor.  No problem.  I'm happy to hear that it worked.

I'll close this.  Please re-open if there are any problems.
