### ISSUE TITLE
Inconsistent condition auto-complete

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2643]
I think this is a bug when autocompleting the condition synonym,

First in the video:  if I select with the cursor and click enter, the term that is added is the synonym

Second in the video: If I click with the mouse, the synonym is replaced by the main term name.

https://user-images.githubusercontent.com/22526102/192758025-d7e8a211-e5c6-4d6b-8e2d-d30618790839.mov

In the first case, you end up with the name in red:

![Screenshot 2022-09-28 at 11 38 01](https://user-images.githubusercontent.com/22526102/192758707-05620f40-cdfc-4260-812a-95eb35312d87.png)

**Comment by kimrutherford** [comment]
> I think this is a bug when auto-completing the condition synonym,

I'm surprised we never noticed before!

It's a bug in the Javascript library we use for making the conditions buttons and the conditions autocomplete.  I can't see a way to fix it while still showing the synonyms in the autocomplete menu.  We've had quite a few problems with this JS library but we haven't found a good alternative.

**Comment by ValWood** [comment]
That's a new bug I'm sure...

**Comment by kimrutherford** [comment]
> That's a new bug I'm sure...

It's unlikely to be new since that code hasn't changed in close to 10 years.  How often do you use condition synonyms?

**Comment by ValWood** [comment]
right maybe I usually know the primary names....

**Comment by kimrutherford** [comment]
Hi @manulera

I've done a hacky fix since I couldn't work out how to fix this in a non-hacky way.  :-)

I've changed the text in autocomplete list slightly to make this hacky fix possible.  Instead of "38 degrees Celsius (synonym)" it now says "high temperature (38 degrees Celsius)":

![image](https://user-images.githubusercontent.com/90474/224929252-18698bac-e6d5-4589-9f8f-22b786aa8110.png)

If you press return, that text appears in the condition box:

![image](https://user-images.githubusercontent.com/90474/224929410-24e9a3e9-f273-4581-b273-f858247d9910.png)

But in the final annotation (after clicking "OK") the synonym in brackets will be removed and it's stored correctly in the database:

![image](https://user-images.githubusercontent.com/90474/224929487-45117032-3ef1-485e-852d-c925cb6b06c8.png)

It's all a big hack but hopefully it will solve the problem.

Could you test the fix when you have time?  Thanks.

**Comment by ValWood** [comment]
@manulere @ValWood 
Needs testing

**Comment by manulera** [comment]
hi @kimrutherford. This works well! It can be closed. 

Sorry, this totally slipped under my radar!
