### ISSUE TITLE
Disable "Legacy genetic interaction" creation?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2649]
I think we talked about this: should we disable the creation of "legacy genetic interactions"?  Currently it's still possible.

Maybe we need some documentation about what the legacy genetic interactions are before going live?

**Comment by ValWood** [comment]
We decided:

Remove  ability to create 'legacy genetic interactions' from  gene and summary
Remove ability to "copy and edit"
Keep ability to delete (Admin only- also because we do not make all of the GI annotations, some are pre-existing from BIOGRID- actually that is another point. How will we hide the biogrid style interactions that we cannot delete if we have made new style interactions?)

**Comment by kimrutherford** [comment]
> How will we hide the biogrid style interactions that we cannot delete if we have made new style interactions?

Could you explain that a bit more?

**Comment by kimrutherford** [comment]
> should we disable the creation of "legacy genetic interactions"?

Done!  I've updated the main Canto instance with the fix.  Let me know if you see any problems.

**Comment by ValWood** [comment]
Yay, have a beer. I'm just about to approve 2 sessions ;)

**Comment by ValWood** [comment]
close?

**Comment by kimrutherford** [comment]
Do you think we should mention it in the documentation?
