### ISSUE TITLE
Database error message when deleting genotype

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2700]
You can test this in the example curs https://curation.pombase.org/test/curs/4666975359de04dd

* GO to genotype management
* Try to delete pkl1+[Overexpression]
* Error message is shown

I guess the problem here is that there is no annotation linked to the genotype (and therefore the interface allows you to click delete), but the genotype belongs in a genetic interaction, so it can't be deleted.

**Comment by kimrutherford** [comment]
> I guess the problem here is that there is no annotation linked to the genotype (and therefore the interface allows you to click delete), but the genotype belongs in a genetic interaction, so it can't be deleted.

Yep, that was the problem.  I've changed things so that the delete menu item is disabled if the genotype is part of an interaction.  With a help pop-up explaining the problem.

![interaction-delete-disable-1](https://user-images.githubusercontent.com/90474/222636049-54e5f1d6-a7c9-4906-b137-b4197f6fa16a.png)
(The screenshot didn't capture my mouse pointer)
