### ISSUE TITLE
Can't create certain diploids

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2701]
Hi @kimrutherford I noticed that certain types of diploids cannot be created. For example, if I want to combine a knockdown allele and an overexpression wild type allele I can't do so. See this example starting from the test server on PMID:1

![Screenshot 2023-03-02 at 16 57 38](https://user-images.githubusercontent.com/22526102/222498587-864b3a88-049e-49f7-856c-2f31c379034c.png)

This is definetely an edge case, but it can be confusing that having picked cdc2 knockdown then you see this window:

![Screenshot 2023-03-02 at 16 58 37](https://user-images.githubusercontent.com/22526102/222498824-6799afa7-15b8-4582-9dc7-5cecd003111b.png)

Even for combining wild type product level with knockdown (more realistic scenario), you can only do it if you pick the knockdown and click the create diploid, but not if you start from the wild type.

**Comment by kimrutherford** [comment]
Thanks Manu.  There was a display bug and a Javascript bug.  The display bug was that it was not showing the expression level so it wasn't possible to see the difference between `cdc2+[Knockdown]` and `cdc2+[WT level]` in the dialog box.  The Javascript bug caused the `cdc2+[Knockdown]` to be missing from the dropdown if you started from `cdc2+[WT level]`.  I think I've fixed those problem.

I've also removed the `cdc2+[WT level] / wild type` option from the dialog because I think it's the same as `homozygous cdc2+[WT level]`?  Please let me know if I've got that right.

![image](https://user-images.githubusercontent.com/90474/222608211-3ea4dd14-3cc7-489e-9d2a-ff8ecc5bd073.png)
![image](https://user-images.githubusercontent.com/90474/222608037-a98adafa-f3aa-400b-aa03-8f80f183ef4a.png)

**Comment by manulera** [comment]
> I've also removed the cdc2+[WT level] / wild type option from the dialog because I think it's the same as homozygous cdc2+[WT level]? Please let me know if I've got that right.

Yes, that's right!

I checked in the canto test server and it looks good. Thanks!

**Comment by kimrutherford** [comment]
Thanks for testing.
