### ISSUE TITLE
Error in FlyCanto using "Add another gene" function

### ISSUE THREAD

**Issue by kimrutherford** [pombase/canto#2709]
From @arzuozturk:

I attempted to add two genes: Crei\ChR2 (FBgn0086497) and Crei\ChR1::Crei\ChR2::Vcar\ChR1::Vcar\ChR2 (FBgn0287205) (used both the gene symbol and FBgn to show that none is working in the screenshot below) to PMID:36688373 in Canto using "Add another gene" link and received the error message below.

![image](https://user-images.githubusercontent.com/90474/225549882-04944dbb-77a8-4ddc-b3da-9649d19fd01c.png)

Vaguely remembering my failed attempt of adding Scer\GAL4 to some other papers before, I tried to add one non-Drosophila gene (Hsap\SLC6A1) and one Drosophila gene (Rpt1). The latter was successful while the former failed. (I am not sure how relevant this information is but I wanted to let you know.)

Could you think of a reason why this might be happening?

CC: @gm119

**Comment by kimrutherford** [comment]
Hi.  I think I've worked this out.

Canto has two modes, single organism and multi-organism.  I think your Canto is probably in single organism mode and the single organism is melanogaster.  There is not a big difference between the two modes, except that there are a few places where Canto will display the organism of each gene (example below) in multi-organism mode.  After a bit of discussion, Vitor and I thought that displaying the organism name wasn't needed because FlyBase gene names have the organism as a prefix.

The other effect of single organism mode is that gene lookups will be organism specific, so in your case if you look up a gene it will only find melanogaster genes.  So that is probably the reason for the error you're getting.

The quick fix is to switch to multi-organism mode by commenting out or removing these two lines from the configuration (`canto_deploy.yaml`) and then restart Canto:

```yaml
instance_organism:
  taxonid: 7227
```

That change should fix some of the problem, but not all.  You should then be able to use `FBgn` identifiers but unfortunately due to a bug in Canto, gene names that include a backslash (like `Dbor\Adh`) won't work.  That should be an easy bug to fix but you would then need to deploy an updated version of Canto.  I'm happy to do the fix if re-deploying is worth the effort for you.

I hope that helps.

![image](https://user-images.githubusercontent.com/90474/225841735-2fe86c83-7a75-471c-85e7-5ece17298708.png)

**Comment by arzuozturk** [comment]
Hi Kim,

Thanks for responding so fast and looking into this.

If @gm119 also agrees, I think a "switch to multi-organism mode" should be enough for now. We can write this down so that phen curators would use FBgn identifiers instead of gene symbols to avoid the "\" problem.

Have a nice weekend!
Arzu

**Comment by arzuozturk** [comment]
Thanks @gm119. 
Yes, I can do the commenting out and restart following the SOP. (Hopefully I won't break the whole Canto :))

**Comment by arzuozturk** [comment]
this looks more complicated than I imagined. I will look at it on Monday with a fresh brain :)

**Comment by kimrutherford** [comment]
Please let me know if I can help or if there are any problems after changing the configuration.

**Comment by arzuozturk** [comment]
Hi Kim,

I hope you and your family are well.

I finally gave it a go and it looks like I broke FlyBase Canto :((( I am so sorry about this and I would really appreciate if you could help me.

![Screenshot 2023-06-15 at 21 44 26](https://github.com/pombase/canto/assets/66944690/3bd2a2bd-b7a4-444e-81c4-cca44e05f4af)

My biggest mistake was to do the changes (commenting out two rows you suggested) on master instead of testing!!! It was very stupid of me and I won't ever do that again :(((((

Here is what happened:
- I edited the canto_deploy.yaml in Github and committed the change.
- Then I did git pull and restarted Canto. At this point FlyBase Canto was working but I was still unable to add non Drosophila genes that is when I realised that I did the git pull while I was in canto-space/canto folder when the [SOP](https://docs.google.com/document/d/1e0u6oRVn8BPY8rvA5iv4B7_Rt63WngkMIeUprRWi-DY/edit) was telling me to do the git pull once inside the canto-space directory. I am not sure how significant this is but when I did this on my terminal it said "... From: https://github.com/pombase/canto ...". After realising this, I did another git pull while in canto-space directory this time it said: "... From: github.com:FlyBase/canto-config ..." and I restarted Canto. But then FlyBase Canto became unaccessible.
- Lastly, thinking that maybe the commenting out was the problem, I undid the commenting out on Github, committed the change, did a git pull and restarted Canto but this didn't help.

I copied my terminal, thinking that that might help to solve the problem. Here it is:
[FlyBase_Canto_problem_230615.txt](https://github.com/pombase/canto/files/11763227/FlyBase_Canto_problem_230615.txt)

I am very sorry about this.
Many thanks in advance.
Arzu

**Comment by arzuozturk** [comment]
Thank you so much! I am available now or all day tomorrow. Please let me know whenever suits you the best.

**Comment by ValWood** [comment]
Arzu don't panic, it will be fine! Kim will sort it.

**Comment by kimrutherford** [comment]
Hi Arzu.  Did you see my email?  I can chat anytime this morning.

**Comment by arzuozturk** [comment]
Hi Kim, I can talk in 2 minutes. Would that work for you?

**Comment by arzuozturk** [comment]
Thanks so much for your help this morning, Kim!

I just realised that the canto-test has the version number 1695. We reverted the master canto to v1692 this morning. Do you think we should change it to v1695? Would there be some changes between v1692 and v1692 that might be important/necessary?

**Comment by kimrutherford** [comment]
> Thanks so much for your help this morning, Kim!

Happy to help!

I had a look at the changes between v1692 and v1695.  There are no important changes.  Most there were small fixes for features that aren't used in FlyCanto.

**Comment by arzuozturk** [comment]
FYI: I just commented out the two lines in canto_deploy.yaml on Canto-test, did a git pull and it is working! For testing this, I changed the server back to deneb. When the server update issue is resolved, I can implement this change on Canto as well.

**Comment by kimrutherford** [comment]
Hi @arzuozturk 

Can we close this issue?  I'm happy to help if there are still problems.

**Comment by arzuozturk** [comment]
Hi Kim,
Sure, we can close it. Thanks :)
