### ISSUE TITLE
Bug in allele autocomplete for wee1

### ISSUE THREAD

**Issue by manulera** [pombase/canto#2751]
Hi @kimrutherford,

Somehow auto-complete allele names does not work for the gene wee1, but it worked for others. Below the url that gave an error:

https://curation.pombase.org/pombe/curs/bd553a3d6f928456/ws/allele/list/SPCC18B5.03/wee1?u=1689948033287

![Screenshot 2023-07-21 at 16 04 28](https://github.com/pombase/canto/assets/22526102/c51df274-1fd1-4371-8b54-e74a0697669a)

**Comment by kimrutherford** [comment]
Thanks Manu.

There were two problems: a bug in Canto and some remaining nonsense_mutation alleles in Canto/Chado.

The bug was that the autocomplete code couldn't cope with nonsense mutations alleles from Chado, in this case "wee1-112(opal)".  The autocomplete code was incorrectly assuming that every allele type from Chado would have corresponding configuration.  I've fixed the code and re-deployed Canto so the autocomplete should work again now.

Below is a list of the remaining nonsense_mutation alleles.

[nonsense_mutations.tsv.txt](https://github.com/pombase/canto/files/12136106/nonsense_mutations.tsv.txt)

|allele              |session           |
|--------------------|------------------|
|cut2\-R267\-\>stop\(R267\-\>stop\)|16ad711046a3f839  |
|nup184\-1\(Q960\-\>stop\)|3b211355644f4b72  |
|cut12\-1\(R536\*\)  |acd1a2d2ddcf29cc  |
|rad23\-1\(Q232\*\)  |1db37277d7f4d8d8  |
|hhp2\-W214\-\>stop\(W214\-\>stop\)|4d3b0d5a0015df91  |
|apm1\-1\(W343\*\)   |c6d09a7812ec9301  |
|tsn1\-Y227stop\(V211\*\)|1aa134ff4369c6d4  |
|tht1\-D543\*\(D543\-\>stop\)|5eae8ab56540b745  |
|pds5\-G755V\-STOP\(AA755\-\>Stop\)|b2ae716b0ad7c3cb  |
|pds5\-K686\-STOP\(AA686\-\>stop\)|b2ae716b0ad7c3cb  |
|wee1\-112\(opal\)   |91da8e4c4e7b6d48  |
|pan2\-Q69Stop\(Q69\-\>STOP\)|ac98af394a19cfe7  |
|pst1\-1\(W1305\*\)  |11f8c49a46c7964f  |
|dot2\-439\(E33\*\)  |1ebe4a1548de4aff  |
|elf1\-21\(Q863\*\)  |afd6568b8a2d599f  |
|dri1\-W46X\(aa46\-\>stop\)|297469ade6812e26  |
|dsc2\-V160\*\(V160\*\)|bea1c1e13005750d  |
|sre1\-Q802\*\(Q802\*\)|bea1c1e13005750d  |
|pli1\-Y108\-\>stop\(Y108\-\>stop\)|396866ab84f69995  |
|pli1\-Q196\-\>stop\(Q196\-\>stop\)|396866ab84f69995  |
|pli1\-Q8\-\>stop\(Q8\-\>stop\)|396866ab84f69995  |
|psc3\-303\(S931\-\>stop\)|396866ab84f69995  |
|erh1\-Q46\-\>stop\(Q46\-\>stop\)|396866ab84f69995  |
|sck1\-Q112\-\>stop\(Q112\-\>stop\)|396866ab84f69995  |
|ppe1\-E35\-\>stop\(E35\-\>stop\)|396866ab84f69995  |
|ekc1\-W636\-\>stop\(W636\-\>stop\)|396866ab84f69995  |
|mcl1\-1\(W109\*\)   |3d88b1b5a61259cf  |
|spo3\-KC51\(W427\*\)|56a166785d462f8d  |
|caf4\-Q470stop\(Q470stop\)|e8e4518f9c7db116  |
|caf4\-R530stop\(R530stop\)|e8e4518f9c7db116  |
|fis1\-E128stop\(E128stop\)|e8e4518f9c7db116  |
|dnm1\-G148stop\(G148stop\)|e8e4518f9c7db116  |
|slr9\-1\(R162\-\>stop\)|94b54d8b1a931fb9  |
|atg7\-m1\(W227\*\)  |393d0a5aae35d3ac  |
|lcf1\-W376\-\>stop\(W367\*\)|3afd4a567ba06463  |
|tsn1\-S204stop\(L188\*\)|729e6559539b7379  |
|ssu72\-Gln57Stop\(aa57\-\>stop\)|af39cc71da933c2d  |
|ctf1 Tyr260Stop\(aa260stop\)|af39cc71da933c2d  |
|sgf11\-Q64\-\>stop\(Q64\-\>stop\)|865ebc50ec806a07  |
|tor1\-g2\(R1071\*\) |9a10046246e64418  |
|sst6\-Q207STOP\(Q207\-\>stop\)|155dba22ce11dc4f  |
|SPAC1296\.01c\-Q175STOP\(Q175\-\>stop\)|155dba22ce11dc4f  |
|bro1\-E644STOP\(E644\-\>stop\)|155dba22ce11dc4f  |
|sst4\-W170STOP\(W170\-\>stop\)|155dba22ce11dc4f  |
|sst4\-Q202STOP\(Q202\-\>stop\)|155dba22ce11dc4f  |
|tsc1\-Q688STOP\(Q688STOP\)|155dba22ce11dc4f  |
|pcs2\-N147D\(N147D\)|155dba22ce11dc4f  |
|ppk14\-R148STOP\(R148\-\>stop\)|155dba22ce11dc4f  |
|tsc2\-L636STOP\(L636STOP\)|155dba22ce11dc4f  |
|vps25\-W113STOP\(W113\-\>stop\)|155dba22ce11dc4f  |
|puf2\-Q40STOP\(Q40\-\>stop\)|155dba22ce11dc4f  |
|puf2\-Y416STOP\(Y416\-\>stop\)|155dba22ce11dc4f  |
|osh6\-S117STOP\(S117\-\>stop\)|155dba22ce11dc4f  |
|not2\-E31STOP\(E31\-\>stop\)|155dba22ce11dc4f  |
|pmr1\-W880\-\>stop\(W800\-\>stop\)|0572af570458b258  |
|pmr1\-R155\-\>stop\(R155\-\>stop\)|0572af570458b258  |
|alg10\-183\-stop\(183\-stop\)|661292025a8cdee8  |
|ufd1\-I210HRLstop\(210\-\>stop\)|16d769aa2fc305a4  |

**Comment by manulera** [comment]
Great! Thanks Kim!
