### ISSUE TITLE
allele names not updated in Canto

### ISSUE THREAD

**Issue by arzuozturk** [pombase/canto#2753]
Hi Kim,

Gillian made a massive retrofit changing the names of several alleles in Chado. We just realized that those allele names were not updated in Canto. The [Canto SOP](https://docs.google.com/document/d/1e0u6oRVn8BPY8rvA5iv4B7_Rt63WngkMIeUprRWi-DY/edit) section below suggests that weekly_routine.sh would check the genetic entities in Chado and update the data in already existing (not newly added) publications. It seems that that didn't happen. Do you know whether weekly_routine.sh has that function? If yes, why it might have failed and how can we fix it?

"**G. MANAGE PUBLICATIONS - IMPORT, DELETE**
**1. Import (and update) of publications**
The import of new publications and associated data into the Canto instance at ‘flybase-vm’ occurs automatically, every Monday at 01:00, by the 'weekly_routine.sh' script (see Section 'AUTOMATED RUN OF CANTO'S INSTANCE IN FLYBASE-VM', Step 1, namely Step 1bi2-4.). However, if you really need to, you can do it manually (e.g. the scheduled weekly import fails to run on schedule, or even when manually executed, or there is a need to bulk-import a new set of publications)
**a)** Loading publications will import some of the associated data present in Chado, which will include:
- genetic entities: genes, alleles (inc. allele synonyms) and aberrations
- internal notes: publication-level and allele-level notes
- triage status: publication type/list e.g. 'HIGH PRIORITY'
- priority score

If a publication already exists in Canto and some of the above data has changed in Chado, it will be updated."

Thanks.
Arzu

**Comment by kimrutherford** [comment]
Hi Arzu.  I've had a look at weekly_routine.sh and I don't know under which conditions the publications and alleles would or wouldn't be updated by the script.  I think it depends what the script on this line does:
```
/usr/bin/perl /data/export/support_scripts/get_fbrfs_to_add_to_canto.pl /data/export/support_scripts/modules_server.cfg > "${CURATEDPAPERLISTFILE}"
```
(line 267 of weekly_routine.sh)

But I don't know what "get_fbrfs_to_add_to_canto.pl" does.

Are there any errors in the log file (canto_weekly_update.log)?

In the Canto SOP it says something about what to do if the update has problems.  I've pasted the paragraph below.  I don't know what the scripts that are mentioned do.  They aren't in the canto-space Git repository so I can't have a look.

Do you know who wrote those scripts? 
("get_fbrfs_to_add_to_canto.pl" and "get_fbrfs_to_add_to_canto_by_release.pl")

------------------------
Canto SOP:
If something went wrong with the weekend update (that is run by the weekly_routine.sh script) and the new thin-curated publications that meet the cut-off for phen curation didn’t get added automatically,  use the support_scripts/get_fbrfs_to_add_to_canto_by_release.pl script (the weekend weekly_routine.sh script expects the records to still be in /staging/records, so if they have already been archived, you will need to use this special script to get the correct list of FBrfs, you cannot use get_fbrfs_to_add_to_canto.pl).

**Comment by gm119** [comment]
> Do you know who wrote those scripts?
("get_fbrfs_to_add_to_canto.pl" and "get_fbrfs_to_add_to_canto_by_release.pl")

that would be me ! These scripts just identify which new publications should be added to canto. They don't talk to canto, they just make a list of reference ids (FBrfs) that had their genetic entities newly curated the previous week. This list is then used by the canto_json_input_maker.pl script to make input json that is used to add the genetic entity data from those newly curated publications into canto.

We think that weekly_routine.sh is working fine.

The issue that Arzu had this week was for a publication that had already been loaded into Canto.

It is PMID:37163553 and one of the alleles loaded into it is FBal0128123. This had the symbol tum[dsRNA.UAS.cBa] at the time it was loaded into Canto.

FBal0128123 was recently renamed in FlyBase to tum[RNAi.UAS.cBa], but it is still displayed as tum[dsRNA.UAS.cBa] in Canto. (this resulted in an out-of-date symbol in the curation records made from the exported json file, because my script that proesses the exported json is using symbols from that file rather than ids - it is not a big deal as the QC we do on the curation records reports such an error, so Arzu can make the necessary changes before database loading).

We had the impression that  Canto gets the latest symbols for each id (e.g. FBal0128123) by talking direct to chado, so we thought that the symbol would be updated in Canto automatically whenever the connection to the specific database is updated each week (I think this is what we thought "If a publication already exists in Canto and some of the above data has changed in Chado, it will be updated" means). 

I guess we might have been wrong about the above - perhaps symbols are only updated from an underlying chado cb each time Canto is restarted ? or maybe not at all ?

Its not a big deal if Canto doesn't automatically update symbols when there are changes in chado, since the errors are reported by QC checks as mentioned above (plus I could in theory change the script that makes curation records from the exported json to do a symbol vs id validity check in it and use the latest, current symbol), but it would be good to know what if anything is supposed to happen automatically so we can update the SOP to make it clearer.

Hope that makes sense !

**Comment by kimrutherford** [comment]
> We had the impression that Canto automatically gets the latest symbols for each id (e.g. FBal0128123) already loaded in it by talking direct to chado,

Thanks, I understand now.  Canto doesn't read any allele information from Chado, it only reads it from the JSON input files.  So if the allele information changes in the JSON file and you re-load the JSON, the Canto database will be updated with the change.

It's safe to re-load the JSON for a publication if gene or allele details change.

It looks like this is the issue where we discussed allele symbol changes: https://github.com/pombase/canto/issues/2248#issuecomment-737591565

**Comment by gm119** [comment]
thanks, that all makes sense. So I think the simplest thing to do is for me to modify the script that turns the exported json into curation records, so that it checks chado to see whether the symbol in the json for the corresponding FBid is still valid, and if not, uses the updated symbol from chado, instead of the symbol in the json.

I'll close this ticket and make myself one on the FlyBase system to do this
