### ISSUE TITLE
bug: new notes

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2761]
There is sometimes a field "new notes". I never saw this before.
When it is present I click on it but the fiekld is empty
e.g.

https://curation.pombase.org/pombe/curs/7097a362b55929af/genotype_manage
<img width="1156" alt="Screenshot 2023-08-29 at 14 35 01" src="https://github.com/pombase/canto/assets/7359272/3efaba25-c495-4c9a-89c2-a0df2f42da09">
<img width="998" alt="Screenshot 2023-08-29 at 14 37 42" src="https://github.com/pombase/canto/assets/7359272/55352d01-6147-451d-80b2-733c66819ec7">

**Comment by kimrutherford** [comment]
Sorry, it wasn't configured correctly.  I made some changes to the way notes/comments were handled because FlyBase needed more that one type of note.  After the change I forgot to add the correct config for pombe Canto to show the existing notes/comments.

The FlyBase changes were for this issue, 3 years ago:
  
  - pombase/canto#2015

It's fixed now so you can see the notes/comments again:

![image](https://github.com/pombase/canto/assets/90474/325ffa19-aeff-4b03-b457-1332b92748a2)
