### ISSUE TITLE
Often cannot locate porcess terms for extentions even with exact string

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2826]
For example:

<img width="755" alt="Screenshot 2024-04-23 at 12 46 48" src="https://github.com/pombase/canto/assets/7359272/cbff5ce5-f950-42db-a29e-6b2f996aab83">

<img width="1033" alt="Screenshot 2024-04-23 at 12 45 56" src="https://github.com/pombase/canto/assets/7359272/a7dafa96-6dba-4998-af0b-632fbc2922e3">

<img width="645" alt="Screenshot 2024-04-23 at 11 47 07" src="https://github.com/pombase/canto/assets/7359272/d5568f01-2fc7-42c1-afa5-d8836839eb45">

@PCarme   have you seen this other then for extensions?

**Comment by kimrutherford** [comment]
I can't see any obvious reason for that.  Seems like a bug.  I'll investigate when I'm back at work later.

**Comment by kimrutherford** [comment]
I think part of the problem is that the "in biological process" extension is restricted to `GO:0009987` (cellular process) only.

That explains why "protein catabolic process" and "anaphase-promoting complex-dependent catabolic process".

Should I change the configuration to include all of / more of biological_process?

I can't understand why "RNA capping" isn't found as it's a descendent of "cellular process".  I'm still trying to work that out.

**Comment by ValWood** [comment]
Yes use biological process.
Some of these should be cellular, and most irrelevant terms should not be blocked by taxon constraints.

**Comment by kimrutherford** [comment]
> Yes use biological process.
> Some of these should be cellular, and most irrelevant terms should not be blocked by taxon constraints.

OK, I'll change that now.  Canto will be updated will the new configuration in an hour or two.

 > I can't understand why "RNA capping" isn't found as it's a descendent of "cellular process". I'm still trying to work that out.

I was misreading the ancestry graph.  RNA capping" is a "part_of" descendent of "cellular process" but not an "is_a" descendent, which explains things.  Changing to allow any BP term in the extension will fix that.

**Comment by ValWood** [comment]
CC @Pcarme
