### ISSUE TITLE
lactate as an extension

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#2834]
error log has
warning in 9d56e0cfc18f0d09: can't find term with ID: CHEBI:24996
warning in 9d56e0cfc18f0d09: can't find term with ID: CHEBI:24996

but we can't work out why because lactate is in the extension options.
Does it need to be added to some config? I can't remember

**Comment by ValWood** [comment]
CC @PCarme

**Comment by kimrutherford** [comment]
Hi Val.

The message is because that term isn't in Chado.  It's not in the mini ontology: `pombe-embl/mini-ontologies/chebi.obo`

I've just added it.  The warning should be gone in the morning.

**Comment by ValWood** [comment]
So how was it recognized, this part confuses me? I thought things only showed up in the autocomplete if they were already in the mini-ontology?

**Comment by kimrutherford** [comment]
> I thought things only showed up in the autocomplete if they were already in the mini-ontology?

Yep, good point.  Which extension were you auto-completing?

**Comment by kimrutherford** [comment]
> Which extension were you auto-completing?

It's OK, I found it in the session:  increased_in_presence_of lactate

**Comment by kimrutherford** [comment]
It turns out that it comes from loading the GO OBO file.  I think this has confused us before.  We load all the terms in the GO OBO file because that's simpler.  But it means we get some bonus terms in Canto.

The GO files we load into Canto and Chado are different.  For Chado we load the standard `go-basic.obo` from the snapshot: http://purl.obolibrary.org/obo/go/snapshot/go-basic.obo

For Canto we process `go-plus.owl` from the snapshot to generate a taxon restricted OBO file.  Unfortunately that has extra terms and I've never got around to investigating how we can remove them.  The lactate ChEBI term is in `go-plus.owl` because it's used in the logical definition of  `lactate metabolic process (GO:0006089)`

**Comment by kimrutherford** [comment]
> Cant we just automatically include anything which comes via GO?

The GO OBO file we load into Chado doesn't have the ChEBI terms needed for logical definitions.  We load `go-basic.obo` which doesn't have the logical definitions.

The taxon restricted OBO we load into Canto is generated from `go-plus.owl` by OWLTools and includes the logical definitions and the terms (like ChEBI term) that are needed for the logical definitions.
