### ISSUE TITLE
subsets: Make some subsets visible for browsing, but don't allow their selection for annotation

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#461]
Some grouping terms are defined in GO as a grouping_term should not to be used for annotation (for example nuclear part?)

We will also use the same subsets for phenotype terms where the terms should not be used for direct annotation. In these cases the "proceed" button should not be visible and a message should say

"This term should not be used for direct annotations, please select a child term"

Original comment by: ValWood

**Comment by ValWood** [comment]
Once ontology subsets  tickets are done, we can also proceed with
https://github.com/pombase/curation/issues/49
Noting this  here because I have an enquiry whether we will  be migrating to DO. It is still planned but it was a bit off my radar but we can think about it again now ontology_subsets is nearer to the top of the list.

Or maybe we should do this another way?....I'll comment on the curation tracker ticket....we should discuss.

**Comment by kimrutherford** [comment]
> "Genes should not be annotated directly to this term. Please select a child term ."

The current Canto ignores any terms in those do_not_annotate subsets.  If you type the name of a term in those subsets it won't autocomplete.  That was done for #1084

Would you rather autocomplete, then show that message?

**Comment by ValWood** [comment]
We'll go through ontology subsets with Midori  and Antonia when I get back. We can then decide what is required for what with respect to annotation, consistency checking and anything else. I won't be able to comment sensibly until I get back. I'm in end of term mode today.....at best I might manage to annotate a paper....
