### ISSUE TITLE
user interface: paper/session list for non-admin user?

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#603]
When we did some curation yesterday, Ryoko tried to get to her list of assigned papers to pick one. WHen she first logged in, she followed a couple of links and wound up on her "people" page (unfortunately I didn't make a note of her exact actions, but I think she saw the whole "people" list, minus passwords, at one point). After she'd curated one paper, though, she couldn't find a link to get back to her list, and things behaved differently even after she logged out and then back in. (Again, sorry for lack of specifics.)

On a sort of related note, I've noticed that the pombe page (http://curation.pombase.org/pombe), it fills in some links under the "your curation sessions" heading -- but that list seems to be sessions I've visited recently, not necessarily ones assigned to me (and certainly not all the sessions from my "people" entry). This is kind of confusing.

Do we want ordinary users to be able to see a list like what we see for any of the "people" links -- the papers they're curating (or have curated, or are corresponding author for), and/or a list of their sessions?

If so, 

a) Where can we put a convenient link? Edit the existing "your curation sessions" area? or ?

b) Do we want to include all the details that we show to ourselves, i.e. logged-in admin users? I suspect not but haven't fully thought it through.

The rest of the curators may want to chat about this before we implement anything; I just wanted to get it down somewhere before I forgot any more details.

Original comment by: mah11

**Comment by ValWood** [comment]
One option
List papers by

Session created
Sessionn accepted
Approved
Etc

**Comment by mah11** [comment]
We have ideas for two different things, one for admin and one for the paper lists on the main pombe Canto page. I'll move the one about the admin "people" pages to a separate ticket, which I hope will make the remainder of this one simpler :)

We want to improve the list of PMIDs one sees on curation.pombase.org/pombe/. For community users who typically don't log in, Canto should be able to use their email address to retrieve the correct sessions (especially when they come from having submitted a session, a la #616). Or maybe it'll only work in the #616 situation and for logged-in users. We can sort that out somewhere along the line.

Anyway, whenever Canto can tell who's looking, have a heading and two lists of PMIDs that link to sessions, with subheadings:

"Your papers in Canto"
- "Curation in progress" - lump session_created, session_accepted, curation_in_progress, curation_paused
- "Curation completed" - lump needs_approval, approval_in_progress, approved

(Shout if I've missed any session statuses, or if the wordings need improvement.)

Think about whether the "completed" list should be expandable/collapsible. Not as high a priority, because we curators are the only people who have very many. I think we think the "in progress" list should always be expanded ..?

**Comment by kimrutherford** [comment]
I've added an email search box on the front page.  I haven't split the search results into sub-heading yet.  It's in the test Canto if you'd like to test it:
  https://curation.pombase.org/test/

**Comment by ValWood** [comment]
woks so far.....

**Comment by kimrutherford** [comment]
The publications list is now divided into active and in-active sessions.  Currently there is a limit (100) on the number of sessions/publications shown.

Another quick fix would be to add an extra link for admin users that goes straight to the relevant Person page in the admin interface.  Does that sound useful?

**Comment by ValWood** [comment]
In test, I only see a single list 'publications curated'.
I created a new session, it didn't seem to appear?
v

**Comment by mah11** [comment]
> Another quick fix would be to add an extra link for admin users that goes straight to the relevant Person page in the admin interface. Does that sound useful?

Do you mean add the link to the home page, as part of the email search results? If so, yes, very useful.

**Comment by kimrutherford** [comment]
> In test, I only see a single list 'publications curated'.

Sorry, forgot to re-release it.

> I created a new session, it didn't seem to appear?

For now it only shows the first 100 so perhaps it fell off the end?

**Comment by ValWood** [comment]
reverse list ;)

**Comment by kimrutherford** [comment]
> reverse list ;)

Most recent at the top?  Good plan, I'll do that.

**Comment by ValWood** [comment]
Midori doesn't like reverse lists...but  I think she'll agree here ;)

**Comment by kimrutherford** [comment]
> reverse list ;)

Done.

**Comment by kimrutherford** [comment]
> Another quick fix would be to add an extra link for admin users that goes straight to the relevant
> Person page in the admin interface.

Done too.

**Comment by kimrutherford** [comment]
Is there anything that needs doing here?

**Comment by mah11** [comment]
Probably not ... close it, and we'll open new tickets if we think of anything else.
