### ISSUE TITLE
distinguish "disruption" type allele

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#681]
At present we annotate disruptions as other, and partial deletions as deletions (I think?)

We would like another classifier for these "disruption"
syntax
yfg1::ymg1+  (where ymg = your marker gene) 

Maybe we should also have a "partial deletion" allele type for when we *know* that the deletion is not complete (but we do not know the absolute range of bases, but they are loosely called deletion as say 80% of the deletion is delted)....I think there are quite a few like this, and longer term it will be useful to have a way to distinguish them from a complete deletant

Original comment by: ValWood

**Comment by ValWood** [comment]
I'm going to make a new ticket for this later...moving to curation tracker for now

**Comment by kimrutherford** [comment]
Can this be closed?  Did you make a curation tracker issue?

**Comment by kimrutherford** [comment]
These allele name are causing problems for Mark.  Can we fix them for V55?

**Comment by mah11** [comment]
I'm not sure why Val suggested moving this to the curation tracker -- there's a Canto request at the heart of it, and not a huge one at that: add "disruption" to the allele type options.

What sort of allele names are causing problems for Mark? If it's the "yfg1::ura4+" thing, he's gotta deal with it because that's the decades-old standard nomenclature for gene disruptions in yeasts. If he means something else, we'll need a list of which names need fixing (and can open a curation ticket for them).

**Comment by kimrutherford** [comment]
Mark says:
>   The issue is with them ending in ":".
>   Colons and semi colons an be in the middle of the names, but at the end
>   causes an issue and so gets flagged up by the healthchecks in ensembl and
>   ensembl genomes

The two that Mark noticed were:
>    SPBC1A4.03c:allele-9  Sma::
>    SPBC1A4.03c:allele-8  Xba::

both from session 6f1818d4183cd160

**Comment by mah11** [comment]
> SPBC1A4.03c:allele-9 Sma::
> SPBC1A4.03c:allele-8 Xba::

Oh, *those*. They're special. They've annoyed us before; I remember looking at the paper last time they made something choke. The authors really did use those names ... and *they're not even disruptions!!!* They're just truncations (aka partial deletions), and therefore unrelated to the issue of adding "disruption" as an allele type in Chado, Canto, etc. 

I am now making the executive decision to delete the sodding colons, so the names will load for v55. So there.

**Comment by kimrutherford** [comment]
> I am now making the executive decision to delete the sodding colons, so the names will load for v55. So there.

Excellent!

**Comment by kimrutherford** [comment]
> there's a Canto request at the heart of it, and not a huge one at that: add "disruption" to the allele type options.

I'll need to do that before closing this issue.

Is a disruption allele much like a deletion?  Should disruption alleles get an automatic name like deletions do?  If so, what should it be?

Is a description needed or required on those alleles?

I assume (as with deletions) it doesn't make sense to allow an expression?

**Comment by mah11** [comment]
> Is a disruption allele much like a deletion?

In a disruption, another gene -- almost always a selectable marker -- is plunked into the gene of interest (hereafter yfg1). Sometimes some of the yfg1 sequence is deleted, but not all (otherwise we'd call it a deletion). Usually stuffing in the extraneous sequence results in no Yfg1 product being made, so disruptions most often give null phenotypes. But of course there are occasionally exceptions, 'cos this is biology and it's complicated.

> Should disruption alleles get an automatic name like deletions do?

It might be easier not to. If we were to auto-generate names, I think the interface would have to collect the identity of the disrupting gene (i.e. the selectable marker that gets stuffed in, e.g. ura4+). Then the name would be in the "yfg1::ura4+" format.

> Is a description needed or required on those alleles?

It will certainly be a good thing to have. I think the "yfg1" part and the disrupting marker (e.g. "ura4+") will always be known, so we can demand them. The insertion site and whether any yfg1 sequence is deleted should be known, too, but may be a pain to determine, so probably should be optional.

> I assume (as with deletions) it doesn't make sense to allow an expression?

Hmm. Expression is *almost* always null for disruptions, but yes, you guessed it, there are rare exceptions. I recall curating one a while back (tho of course I can't remember which paper :P ). So I guess we'd better leave the ability to support the exceptions ...

**Comment by ValWood** [comment]
I only moved to the curation tracker as I was hoping we  could standardize other 'others'  and include in the drop down at the same time (before I went on hol, but did not get around to it).

Here is the ticket:
https://github.com/pombase/curation/issues/657
its no problem if the disruption  one is done earlier, we can address the others later.

**Comment by ValWood** [comment]
note that there will still be some work to do on the curation side for disruptions, fixing the "non-standard" ones
SPBC530.14c:allele-2    | dsk1+::ura4
 SPBC4F6.06:allele-3     | kinl::LEU2

Questions...
should markers should always be lower case?
should markers always have "+" appended? (otherwise we will have the same allele listed in 2 ways)
should the wt gene allele omit the "+"

(I think the convention is to always have lower case in alleles and only have + on the marker, but there are anomalies in the  file in the dropbox which need fixing)

**Comment by mah11** [comment]
> should markers should always be lower case?

Not necessarily. Not all markers are pombe genes. In the example above, LEU2 is an S. cerevisiae gene, for which upper case is correct (I suspect the disruption description should be kin1::LEU2, but the "LEU2" part is fine). Other markers, such as KanMX, also get used, although more often where the target gene is also deleted, so we would call those deletions.

> should markers always have "+" appended?

Again, not necessarily, because it's so often omitted from S.c. gene names, and because other markers would never have the "+". If the marker is a pombe gene, it should have the "+", but we may have to maintain that manually.

> should the wt gene allele omit the "+"

If it's a pombe gene, no (so the first example should be dsk1::ura4+), but these days it's seldom included for S.c. wt alleles.

**Comment by ValWood** [comment]
> should the wt gene allele omit the "+"

In the majority of cases this is not included in the allele description for a disruption. I think we could standardize on exclusion (as that is how the bulk have been done so far).

**Comment by mah11** [comment]
If by "the wt gene allele" you mean the selectable marker that's inserted, it should have the "+" if it's a pombe gene.

**Comment by mah11** [comment]
The gene being disrupted shouldn't get the "+" because disrupting it makes it not wild type. 

    </bleedin' obvious>

**Comment by kimrutherford** [comment]
I've added a disruption allele type.  Currently the allele name is required, the description and expression are optional. Let me know if I need to tweak that.

**Comment by ValWood** [comment]
</bleedin' obvious>

did you fix the anomalies? I'm sure there were some, but I could not see any in the current file? Maybe there was only one...

**Comment by ValWood** [comment]
I think the description can be optional but we should have some text  to appear under the allele description box suggesting a recommended format e.g.

cdc2+::marker,  cdc2+::marker(nt343)

**Comment by mah11** [comment]
Comments on the description content and format should go on the curation ticket (https://github.com/pombase/curation/issues/664). The disrupted gene should NOT have the "+" because it is not wild type if it is disrupted.

**Comment by kimrutherford** [comment]
> did you fix the anomalies? I

I wasn't me.  There are none now so it should be fine in the next release.

@markmcdowall

**Comment by ValWood** [comment]
I think we are done on this ticket. If there is anything else we should put it in a new ticket. There will be new tickets spawned from the curation tracker ticket eventually.
