### ISSUE TITLE
Add a page of ontology versions

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#792]
It would also be nice if the curators could see at a glance when the last update happened. We should have a database table that has the ontology name and the date/time of last update. That table should be viewable in Canto.

Original comment by: kimrutherford

**Comment by kimrutherford** [comment]
Note to self: see Git branch tickets/ticket-792.

**Comment by kimrutherford** [comment]
This was easy to do at the same time as #1022.

It was easier to store the date the ontology was last updated, rather than the version.

It's only in the test tool for now.  If you follow the "CVs" link on the admin page:
   http://curation.pombase.org/test/track

there's now an extra column "load date".
