### ISSUE TITLE
mothball "search for an existing genotype"

### ISSUE THREAD

**Issue by pombase-admin** [pombase/canto#820]
from this page:
http://curation.pombase.org/test/curs/9e6eec24910dcadf/genotype_manage
you have the option to either look for an existing genotype, or to add a new genotype

I think these 2 options should be streamlined into one option.

In this scenario, you'd 
1. click the link to "Find an existing genotype ..." (reworded to something more fitting)
2. tick the genes applicable to your genotype
3a. if the genotype exists you select it from the table of "Matches"
3b. if the genotype does not exist there is also the option of "adding a new genotype" (using the ticked genes)

the "adding a new genotype" link will give you a popup to specify the alleles of the genotypes (using the genes you have ticked). i.e. one popup for all the genes already selected
This would feel a lot neater than having to go "back" and clicking the other link to add a new genotype, and then re-select the genes.

problem: sometimes you might want to add multiple alleles of one gene. We can't think of a way around this other than to let you duplicate the gene in the pop-up (inelegant?) or to link to the other interface for these special cases (confusing? clunky?). Can you think of a way around this? Or another better solution? 

Original comment by: Antonialock

**Comment by ValWood** [comment]
We had a long chat about this.
It turns out a) that none of us is using it and 
b) it isn't currently working properly
i) if you search on cdc2 and wee1, you get all alleles  of cdc2 and wee1 alone and (cdc2+wee1 + other)
ii) also we don't really like that it works as a filter, rather than a search
iii) you get a bit stuck here if you don't find the allele you want.
iv) it brings the allele but you don't get the expression options.

Taking all of this into account, we think it would be better for now to remove this option (because it isn't working for the expression part), and we don't think that it really saves much time. Once you have added an allele for a session, you can reuse it. It could hep a bit for consistency.

We think that if we do want to do this we will deal with it in a different way later, in the same part of the interface where you "add a genotype"

**Comment by ValWood** [comment]
Putting at high priority because if anyone does use it they expression will be ignored

**Comment by kimrutherford** [comment]
I've removed the "Find an existing genotype ..." link.  Is that all that was needed here?

(Not released in the main Canto yet, should be in test)

**Comment by ValWood** [comment]
yep, that's it
