### ISSUE TITLE
existing terms  for allele not showing

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#909]
In this session
curs/8570af08389340e2
I went to add a new phenotype for mto-delta. Non of the existing annotations for this allele show up, even though there are lots (this could be because the existing annotations were made in the old canto?)

Val

**Comment by mah11** [comment]
Try again now -- network access here just got a lot better, and I can now see lots of phenotype annotations in that session.

Everything from old Canto should show up in new Canto because all of the old annotations would be in the Canto database all along.

**Comment by ValWood** [comment]
I see them now, but there are 2 versions of the genotype mto1delta. The 
old annotations are attathed to one version, and the 3 annotation I made 
today are attached to the other version????


On 20/07/2015 15:20, Midori Harris wrote:
>
> Try again now -- network access here just got a lot better, and I can 
> now see lots of phenotype annotations in that session.
>
> Everything from old Canto should show up in new Canto because all of 
> the old annotations would be in the Canto database all along.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pombase/canto/issues/909#issuecomment-122900234>.
>


-- 
Cambridge University
PomBase http://www.pombase.org/
Cambridge Systems Biology Centre http://www.sysbiol.cam.ac.uk/Investigators/val-wood

**Comment by mah11** [comment]
That's really weird. If you click on through as though you were going to edit the genotypes, you can see that the new one is missing its description and expression. I'll put the "bug" label on this ticket so Kim can investigate how it snuck in that way.

In the meantime, you should be able to use the "edit" link for the annotation to move the newer ones to the old mto1delta.

**Comment by kimrutherford** [comment]
> In the meantime, you should be able to use the "edit" link for the annotation to move
> the newer ones to the old mto1delta.

Good advice.

I think you're right that the network problems were causing the annotation not to show.

When Val added the new mto1delta genotype Canto should have said "Using existing genotype with the same alleles" and then carried on.  Unfortunately the code for comparing the new allele to the existing ones got it wrong.  The existing mto1delta had it's description field set to "deletion" (which is a bit bogus) and the new mto1delta had no description.  The code was been too strict and decided that since one had a description and the other didn't, they must be different alleles/genotypes so it made a new one.

I'll fix the code to be cleverer.  And I'll remove the description "deletion" from deletions because it's redundant.  I the that description come from the database upgrade code.  I have suspicion that there will be some wild type alleles with the description "wild type" for the same reason.  I'll fix those too. 

Val: could you move the annotations and delete one of the alleles?

**Comment by kimrutherford** [comment]
I'll also fix the annotation display so that if the annotation hasn't loaded it says so to avoid confusion if the are network problems in future.

**Comment by ValWood** [comment]
yep, will do

**Comment by ValWood** [comment]
Val: could you move the annotations and delete one of the alleles?
Done, all mto1delta nw use the same allele
v

**Comment by kimrutherford** [comment]
> Done, all mto1delta nw use the same allele

Thanks I've tidied up the descriptions for the delete and wild type alleles so this won't happen again.
