### ISSUE TITLE
normal mitotic spindle polar microtubule

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#911]
I want a term to indicate that the nuclear spindle microtubules are normal (the astral ones are absent)

Will this term cover it?

standard def
PMID:15772152

**Comment by mah11** [comment]
I think that would be fine ... BUT this is on the wrong tracker, and I don't see a simple way to move tickets between trackers (because to GitHub "canto" and "fypo" are different projects).

Apparently the ability to move issues has been requested, and there's a third-party thingummy that we (read:Kim) could deploy in the meantime.

https://github.com/holman/ama/issues/413
https://github.com/google/github-issue-mover
