### ISSUE TITLE
Can't add an extension post-creating the annotation

### ISSUE THREAD

**Issue by Antonialock** [pombase/canto#912]
I created an annotation without an extension
I then realized I wanted to add an extension to a term
I clicked edit, but there was no box to add an extension
It is also not possible to add an extension if you hit "duplicate"

If you add an extension at the point of making an annotation it is then editable.

the session is d800c02f9eed68d9
It was initially community curated - I don't have this problem in sessions that were not community curated first 

looks like not the same problem but related to https://github.com/pombase/canto/issues/910 ? 
(I don't know how to link issues)

see screenshot

![screen shot 2015-07-21 at 16 06 20](https://cloud.githubusercontent.com/assets/12727506/8804222/04127360-2fc3-11e5-9d74-37e7ea3f5b42.png)

**Comment by mah11** [comment]
This is exactly the same issue as #910, as Kim's follow-up comments show (and you did the link correctly -- if the other issue is on the same tracker all it takes is the # and the issue number).

The underlying problem is essentially Canto acting as though it's the community curator, not the admin-status curator, doing the edit.

**Comment by Antonialock** [comment]
ah ok, thought it seemed slightly different :-) I'll close this tehn
