### ISSUE TITLE
allele description for amino acid deletion appearing oddly

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#913]
like so:
cdc12-â24-36(24-36)[Endogenous]

I think I have seen this in other sessions too?

pombe/curs/186e8e06649ff2d7

**Comment by ValWood** [comment]
It doesn't look exactly like this int he session (this is what appeared with a cut and paste)

I think what is usually 'aa' is â

**Comment by mah11** [comment]
This usually arises from copying and pasting special (non-ASCII) characters. In this case it looks like Kathy pasted the delta symbol instead of typing "delta" -- the Greek delta triangle appears in the non-hyperlinked genotype details, but something in Canto's innards needs ASCII to be able to make the hyperlinked stuff in the genotype column look as intended.

I can fix it in the session if you want.

**Comment by ValWood** [comment]
I can do it as I go through, Im checking that session and I have additional phenotypes.
I'll probably wait until I can edit extensions before proceeding.....

**Comment by kimrutherford** [comment]
> In this case it looks like Kathy pasted the delta symbol instead of typing "delta"

Yep, that's my guess.  Handling funky symbols is a bit of a pain in the general case.  I'll fix the display code to cope with cut and paste things like this.

Does it make sense though to change delta symbols to the string "delta" as a special case?  These name end up in Ensembl and in output files.

**Comment by kimrutherford** [comment]
> In this case it looks like Kathy pasted the delta symbol instead of typing "delta"

Yep, that's my guess.  Handling funky symbols is a bit of a pain in the general case.  I'll fix the display code to cope with cut and paste things like this.

Does it make sense though to change delta symbols to the string "delta" as a special case?  These name end up in Ensembl and in output files.

**Comment by ValWood** [comment]
I'm not sure of the exact question 
what ends up in the output files "delta string" or "delta symbol"
In the tool  I think we should convert to delta symbol if possible?

**Comment by mah11** [comment]
> Does it make sense though to change delta symbols to the string "delta" as a special case?

I'm not sure, because I don't know what the code will do for the display. We want to be able to type the string "delta" and have Canto display the delta symbol. That happens now, and is working fine. I'm pretty sure Mark has done something on the ensembl or pombase drupal end that does the equivalent conversion for  I really really don't want to do anything with any special characters that would break the current behaviour for either the PomBase web site or Canto.

If, but *only* if, a pasted-in delta symbol could be converted to "delta" *and* displayed as a delta symbol in Canto, then yes, do it.

**Comment by ValWood** [comment]
So in the session I am working on 
Kathys allele gets interpreted as 
cdc12-∆24-36(24-36) - Endogenous - cdc12  in the genotype details
BUT
cdc12-â24-36(24-36)[Endogenous]
in the annotations.....

So I think at some level Canto must be able to interpret it correctly?
If this is the case, do i need to fix anything?

**Comment by kimrutherford** [comment]
> If, but only if, a pasted-in delta symbol could be converted to "delta" and displayed as
> a delta symbol in Canto, then yes, do it

Yep, that's what I was thinking.  Mostly so that the deltas are stored in a consistent way rather than some as a delta character and some as the text "delta".

**Comment by mah11** [comment]
That should be OK then (and I guess that way Val wouldn't have to change anything in the session in question?). What will the annotation table show?

**Comment by ValWood** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/7359272/8823871/64b42470-3068-11e5-9777-9f211af27a54.jpg)

**Comment by ValWood** [comment]
so above in the genotype details box it shows correctly, I guess this just needs to propagate to the annotation table too?

**Comment by kimrutherford** [comment]
> So I think at some level Canto must be able to interpret it correctly?

The display code works (shows a delta symbol) in the case where the allele name has the text "delta" like "cdc2delta" in the database.  But it's screwing up where the allele name in the database has a delta character, like "cdc2∆".  I'm going to make it consistently store the delta as text so that everything.

I'll fix up the current annotation to be consistent soon.  For now go ahead with the session.  I can fix it when you're done.  Although I suggest you stick to putting "delta" as text if you make an new deletion alleles.

> so above in the genotype details box it shows correctly, I guess this just needs to propagate to the annotation table too?

For that allele it's a "∆" in the database which is displaying OK in some places and not in others.  I'm going to change it to "delta" then it will be fine.

My fix will be to quietly store "delta" in the database if you paste in "∆".  The user shouldn't notice a difference because it will display as "∆"

**Comment by ValWood** [comment]
The problem we are going to have is making the community type delta instead of "∆"
any ideas how we can enforce this?

**Comment by mah11** [comment]
The code change Kim has just described will mean we won't have to make anyone type "delta" -- it will know to store "delta" behind the scenes if someone pastes "∆".

**Comment by kimrutherford** [comment]
> The problem we are going to have is making the community type delta instead of "∆"
any ideas how we can enforce this?

My plan is that "delta" or "∆" would be fine when you create an allele name, but "∆" will be stored as "delta" for consistency in the database.

**Comment by ValWood** [comment]
got it!

**Comment by kimrutherford** [comment]
> I think I have seen this in other sessions too?

All fix all sessions in one go.

**Comment by ValWood** [comment]
Taken the "next" label off this as its easy to fix up and it probably won't happen often. Will leave at high priority

**Comment by kimrutherford** [comment]
> it will know to store "delta" behind the scenes if someone pastes "∆".

Done!  And I've fixed already stored allele names to use the text "delta" rather than a symbol.
