### ISSUE TITLE
identical annotations?

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#946]
I can see on the sty1 page what appear to be identical annotations to
"regulation of cytoplasmic translation in response to stress"
3 IDA from AspE et al 2008
2 IMP from D-S 2005

are we missing some data from the display, or are they really the same?

**Comment by mah11** [comment]
This turns out to be a curation issue -- these are both old annotations in Artemis (the papers haven't been done in Canto yet), and there really are duplicate copies in the contig file. I'll delete the duplicates, and if there's anything else to capture we'll get it when we get round to Canto-ing them.
