### ISSUE TITLE
phaf format field description

### ISSUE THREAD

**Issue by ValWood** [pombase/canto#951]
I wondered if the name of the genotype column should be changed?
http://www.pombase.org/submit-data/phenotype-data-bulk-upload-format
to background? as that is what is in this field.

I guess it depends how the format for multi-alleles will look too?

**Comment by ValWood** [comment]
Actually its a little more confusing. I was showing this to Chris.

The phaf download file info 
http://www.pombase.org/downloads/phenotype-annotations
 says
The file is in the PomBase phenotype data bulk annotation format (PHAF). The same format can be used to submit phenotype annotations to PomBase in bulk, and is described on the Phenotype Data Bulk Upload Format page.
but the columns seem to be slightly different?

For example this says column 3 is
3	Allele description
but if i cut on column 3 i get the FYPO ID?

**Comment by ValWood** [comment]
and I think that column 4 (the allele description field), is empty?

**Comment by ValWood** [comment]
Actually the data is in the file.
Its just that the  submission phaf, and full phaf are different in format and this is not clear from the download phaf data, which leads you to the submission format:

:#Database name  Gene systematic ID      FYPO ID Allele description      Expression      Parental strain Strain name (background)        Genotype description    Gene name       Allele name     Allele synonym  Allele type     Evidence        Condition       Penetrance      Expressivity    Extension       Reference       Taxon   Date
PomBase SPAC13C5.07     FYPO:0000006                    972 h-  not available   not available   mre11   D65N            amino_acid_mutation     Electrophoretic mobility shift assay data       
                                PMID:21098122   4896    20140624

So maybe we just need a new description to cover the download format.  I remember  now that we had 2 formats  but I can't remember why....

**Comment by mah11** [comment]
The format of the downloadable file is identical to the upload PHAF, except that the downloadable one has a "database" column added at the beginning (I had forgotten that it had that addition). I'll update the web documentation to reflect that. It's a bit of a pain because having the additional column first throws off the numbering for the others, but oh well.

As for what to call the columns, right now upload 7/download 8 is "Genotype description", and the "Strain name" column has (up6/down7) "background" as a bit of explanatory text. Both actually refer to background-related information, and the current PHAF the "genotype description" column isn't really doing the job of a proper, multi-allele-friendly "genotype details" file or column. I don't have strong feelings about what the column headers are, but I do think that's a separate issue from the multi-allele file question.

We haven't decided what to do for multi-allele phenotype upload or download formats. I've become pretty well convinced that a single file won't work well enough. (It won't be pretty with single or multiple files, but trying to adapt a single file would be uglier.)

**Comment by mah11** [comment]
oh, and this must be on the wrong tracker ...

**Comment by ValWood** [comment]
OK

**Comment by ValWood** [comment]
moved to
https://github.com/pombase/pombase-chado/issues/494
